### ISSUE TITLE
No way to not automatically sync new items added to root.

### ISSUE THREAD

**Issue by sduensin** [nextcloud/desktop#10]
This is kind of a special case and I understand the logic behind the current behavior.  However, as is, selecting *anything* to selectively sync partially selects the root folder.  Anything new added to the root folder is automatically selected and synchronized to the clients.  For newly added files this makes perfect sense.  For folders, however, it can be dangerous.  Being able to ignore external storage is great but it's highly annoying to have the sync client add things on it's own and then try to run around and stop all the clients before it fills their disk.

**Comment by nshobe** [comment]
This apparently has been a known issue in the community for some time. Forum mentions go back a bit further even.

https://github.com/nextcloud/server/issues/3661

**Comment by Maxattax97** [comment]
My brother who uses my Nextcloud server was hotspotting with data, when a new (very large) folder began downloading in the background. This folder was inside the root directory, and was enabled by default in the client. I think this is a somewhat dangerous default, perhaps an setting in the UI would be best?

There are several issues related to this, and it's clear that this is a feature highly sought after.
#27 #39 #110 #30

**Comment by Apromixately** [comment]
I just ran into a similar issue. I wanted to synchronize only a subfolder which I had reduced to 1.4 MB but then Nextcloud reported it needed to download 600 MB. From what I can tell, the reason is that Nextcloud also wants to synchronize plain files in the parent folders. This sort of makes sense since there is no file-level selection of what to synchronize. Still, it's not really the behavior that I wanted. I think the root folder is a special case of this.

**Comment by Apromixately** [comment]
I think the problem mentioned by @Maxattax97 is also totally valid but a different issue. Here the problem is that new folders are automatically selected to be synchronized. Maybe the default should be "if the parent folder is selected it should be added otherwise not".

**Comment by maxxer** [comment]
Additional feedback: new folders should be automatically synced only if parent is (fully?) selected. Given this situation on the client:

```
* [ ] Folder1
* [x] Folder2 
 \ *  [x] Folder3
* [ ] Folder5
 \ *  [x] Folder6

```
IMHO:
1. if I create a new folder in *Folder2* it's synced automatically;
1. if I create a new folder in the root (or below *Folder5*) it's **not** synced automatically.

**Comment by redRolf** [comment]
I too would expect the behaviour described by @maxxer
In general, I would really like to see this feature. We have several use cases for this at our company. This feature request has been opened for 3 years, what would be needed to move this closer to being implemented?

**Comment by tomdereub** [comment]
No ! I really need this issue to be solved, it's causing many troubles in my company (25 people), by often silently syncing unwanted folders.
Any feedback about my proposal ? Would it be complicated to develop ? I'm no dev, but I would be pleased to help in another way if possible.

**Comment by Joshuasony** [comment]
Same issue here and I agree with this thread and the request of being able on client side to decide if newly added folders are being synced automatically or not. Our Company with 150 people uses Nextcloud and users have no option the deactivate the automatic sync of new folders. 

And on macos I have even another, very annoying issue: deselecting those automatically checked folders is not removing them from my harddrive. I have only found one other person that experienced this issue, but it was resolved for him when moving to a new server. https://github.com/nextcloud/desktop/issues/2468

**Comment by tomdereub** [comment]
Once more, don't stale this issue please ! I'm still hopping for a solution one day...

**Comment by Ossur** [comment]
This is also a privacy issue. Many users sync selected folders to their work computers - which often are hooked up to all sorts of surveillance and running on proprietary operating systems. Any new folders popping up there is not good enough

**Comment by tomdereub** [comment]
Up !

**Comment by a17uk** [comment]
Having the same issue, up up up, six years still hasn't been fixed

**Comment by tomdereub** [comment]
Any news about this issue ? What do you think about the solution proposed here https://github.com/nextcloud/desktop/issues/10#issuecomment-950760178 ?

**Comment by albert-a** [comment]
@tomdereub, you are thinking in the right direction. The decision to sync subfolders should be made per each folder explicitly, rather than by trying to guess what user meant by unchecking some of the subfolders.

Although, I think cluttering folders selection dialog can be confusing for the users. The majority of users probably don't need it. I think that's why "Edit Ignored Files" (aka `.sync-exclude.lst`) is implemented separately. Not everybody needs it.

IMHO, this flag should be called "Manual Sync", and should be set on specific folder by creating empty file `.sync-manual` in the folder. Optionally it could be implemented as a checkbox in the context menu when right-clicking on the folder in desktop client: ![general_settings_folder_context_menu_manual_sync](https://github.com/user-attachments/assets/90135b32-62c7-41cf-844c-9e5793394e81)

 If the flag set for the folder, then
- its subfolders should be automatically deselected for each new desktop client installation/connection.
- if the flag appears on the existing installation, it does not trigger deselecting subfolders, but simply prevents new subfolders from being automatically selected.

PS: Though not all users need this feature, it can be **extremely** useful for the others. My use case is that we have a large `Libraries` folder, each subfolder of which is a library. Each user needs a small subset of the libraries, and selects what is needed. But when the new libraries become available, they are automatically synced to all users, which is of cause not desired. I could really use this feature.

**Comment by albert-a** [comment]
Alternatively:
This feature could be implemented with `.sync-manual.lst` file which could be empty, or contain the list of subfolders that are selected by default on the new desktop client installation/connection.

**Comment by tomdereub** [comment]
@albert-a : We are now starting to use VFS sync (even if we still have performance issues at the moment, especially first sync that's very long). With VFS we don't meet this issue any more.
