### ISSUE TITLE
[feature request] prevent uploads without end to end encryption

### ISSUE THREAD

**Issue by nicosmaris** [nextcloud/desktop#1013]
This is a feature request, is there any workaround?

My setup can be found at https://github.com/nextcloud/desktop/issues/1012

Also at:

https://help.nextcloud.com/t/prevent-uploads-without-end-to-end-encryption/44936

**Comment by nicosmaris** [comment]
I will leave this open for review by the nextcloud developers but I understand the rationale of https://github.com/nextcloud/server/issues/4634#issuecomment-298649453

**Comment by brainchild0** [comment]
I would make a closely related suggestion, which might have a more frequent use case.

My understanding is that the current use case for client-side encryption is that the user creates an empty folder, marks it as encrypted for clients, then populates it from the client.  The client encrypts before uploading upon detecting that the folder is marked for encryption.

However, the desktop client, in the current design, will immediately synchronize any new content beneath a synchronized folder according to the encryption rules of the parent folder.

Thus, if a user working on a client system creates content that needs to be encrypted on the clients, but places the content in a folder that is synchronized but not encrypted, then as soon as the content is saved to the client, it is exposed to the server.

It seems that a compelling use case might be creating a new folder and content on the client, but postponing uploading until the user can resolve whether to designate the new folder as encrypted.  If so, then the effect of the synchronization would be, in a possible design improvement, that the client automatically create the empty folder on the server, marks it as encrypted, then finally uploads the encrypted content.  Otherwise, the user is faced with additional manual steps, and prone to make errors forgetfully saving data that needs to be marked for encryption in a location where it will be uploaded without client encryption as soon as it is saved.

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
