### ISSUE TITLE
Desktop client prevents system from going to sleep

### ISSUE THREAD

**Issue by HorlogeSkynet** [nextcloud/desktop#1027]
Hi over here, it _looks_ like nobody reported this odd issue, and 'cause it's occurring for some months now, maybe starting with the v2.5.0, but I'm not 100% sure.

### Expected behavior
The system should be going to sleep without any issue when told so.

### Actual behavior
Nextcloud prevents the system from going to sleep forthrightly, even when no data are being treated...

### Steps to reproduce
1. Open Nextcloud
2. Login to your account
3. (Wait for the end of synchronization)
3. Try to suspend the system

### Client configuration
Client version: v2.5.1

Operating system: GNU/Linux Debian (Buster) [64 bits]

OS language: English

Desktop environment: Cinnamon v3.8.8

Qt version used by client package: v5.11.0

Client package : Nextcloud AppImage

Installation path of client: /opt/nextcloud/Nextcloud.AppImage

### Server configuration

Nextcloud version: Latest stable

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`

> When clicking on `Suspend`, no logs are appended to the file...

2. Web server error log: Not relevant.

3. Server logfile: nextcloud log (data/nextcloud.log): Not relevant.

Finally, the occurring dialog :

![screenshot from 2019-01-16 12-58-34](https://user-images.githubusercontent.com/5331869/51313839-d97b0480-1a4e-11e9-8ff1-4a4d2e9ca488.png)

_Maybe_ related to #186 & #782... You tell me.

Bye :wave:

**Comment by 3rownz** [comment]
I noticed the same behavior had installed on windows 10 for about a month now. Thought it odd that my computer was not sleeping like usual so ran 'powercfg -requests' command in command prompt:
```
EXECUTION:
[PROCESS] \Device\HarddiskVolume6\Program Files (x86)\Nextcloud\nextcloud.exe
Uploading data to <nextcloud domain name>
```
The program was synced to the nextcloud server, but idle and not uploading any files while I ran this command.

**Comment by HorlogeSkynet** [comment]
Hi @3rownz, very interesting (and glad not to be alone !).

Is there a way to show the same information on Linux ([it seems not](https://www.reddit.com/r/linux4noobs/comments/8mqwnd/command_line_what_is_preventing_suspend/)) ?
Does the dev team have any idea now ?

Bye :wave:

**Comment by 3rownz** [comment]
Hi @HorlogeSkynet 

I have been testing a windows workaround for this issue to allow my system to override the activity that keeps it from sleeping. 

- Using the following command:
`POWERCFG -requestsoverride PROCESS nextcloud.exe SYSTEM`

- I also Went inot the power options and disbaled the allow wake timers.
'Setting > System > Power & sleep > Advanced Power Settings > change plan settings > change advanced power settings > Sleep >Allow Wake Timers'.

Im not sure which of the above setting did it, but after I did a restart, but my pc went to sleep last night.
I did a quick search for anything similar to this in a linux based OS, Im not sure but 'powertop' app might have some advaced power settings that could achieve the same result.

This still needs to be looked into by the developers, the computer not sleeping could be a big issue for some users and these workarounds are not user frindly fixes. I hope someone from the devlopment team responds to the issue, Its still open so theres hope yet. 

Im not saying something drastically is wrong with the client, this could be by design, or I might be missing something. From my little experieince it looks like there is unknown data being constantly sent to the server. The questions we should be asking are:
- Why is data constantly being sent from thre client to the server?
- What data is being sent?
- Does the data need to be sent? 
- Is it secure sending the data constantly?
- Or If my assumption is wrong and theres no data being sent, what is the app doing to keep my system awake?

**Comment by HorlogeSkynet** [comment]
Soooo, I can't reproduce this issue, (maybe ?) starting with the v2.6.0.
Important point : Cinnamon version has not changed since January (thanks to Debian stable) so I guess it's definitely about the Desktop client.

Feel free to re-open this if needed.

Bye :wave:

**Comment by nuschpl** [comment]
This is still an issue on current Ubuntu 22.04, not related to Cinnamon - when nextcloud desktop client is on system goes to sleep and immediately wakes up with 'systemd-sleep: System returned from sleep state.' immediately following 'Entering sleep state 'suspend'.
When I close Nextcloud  Desktop client sleep works like e charm. At the  time of getting into sleep it's fully synchronised with green checkmark icon. Maybe this is due to interval of checking for sync which does the attempt in the middle of preparing system to sleep - maybe it's worth to add some sleep handler script which would pause sync for 5 seconds needed to enter sleep mode ?

**Comment by nuschpl** [comment]
@HorlogeSkynet Kindly please reopen, I don't have permissions, eager to provide any debug info needed.

**Comment by HorlogeSkynet** [comment]
Hi @nuschpl, is it sill an issue with latest Nextcloud desktop and graphical environment versions on your system ?

**Comment by HorlogeSkynet** [comment]
Closing here (again) as stale, please tell me whether it's still an issue.

**Comment by jfml** [comment]
I'm afraid, I'm experiencing this as well, please tell me if I should open a new issue. 

I'm on Bazzite / Fedora 41 (KDE 6.2.5). The Appimage (Nextcloud-3.15.3-x86_64) and the Flatpak both (3.15.3) have a weird issue were it's almost constantly changing from being all synced (green checkmark) to „Waiting to start syncing“ (blue update icon) and back again, that I've been unable to fix (on both Flatpak and Appimage). 

Not sure if this is connected but my desktop doesn't go to sleep with the sync client enabled, if I close it, I can suspend normally.

I'd be happy to provide log files or test things (there seem to be a lot of logfiles to be created and deleted constantly in /home/username/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud/logs/ ) not sure if that is normal?

**Comment by nilsding** [comment]
Hi @jfml, please open a new issue about that, including as many information as possible (i.e. log files, whether you're using group folders/external storage, ...)

**Comment by jfml** [comment]
Will do, thanks! ^__^
