### ISSUE TITLE
Feature Request: Initial archive download

### ISSUE THREAD

**Issue by snussik** [nextcloud/desktop#1097]
**Feature Request:** Initial archive download

### Expected behaviour
The desktop client to have the following option:
`Initial download of the first time added folder and subfolders in archive (tar, rar, zip or so on)`
  

### Actual behaviour
Now it scans the structure and tries to sync it. But on mac it's very slow and unstable (on the release build)

**Comment by mgallien** [comment]
So I am not sure I understand your idea. Let me try:

1. You have a complex folder with many sub-folders and files on your computer
2. You setup Nextcloud to sync it to a server where the account is empty
3. The client batch upload everything in one go without checking for conflicts or duplicates with the server because server has no files.

Can you confirm ?

**Comment by snussik** [comment]
Yep. That's right.
And I think that it's more correct to use terms "target" - "source", not "computer" - "server":
if the target is empty then download gziped data and unpack.
I think that it gives a lot of profits:
1. Quicker download as you don't have multiple streams of files. 
2. No need of sync checking. As on really large sources with a huge number of small files it takes long.
