### ISSUE TITLE
Windows10 context menu integration crashes Explorer on right in navigation pane

### ISSUE THREAD

**Issue by shining-cat** [nextcloud/desktop#1108]
This is my very first bug report, I hope I'm giving all that is needed...

### Expected behaviour
Right click on an item of Windows Explorer's Navigation pane should open contextual menu

### Actual behaviour
Windows Explorer crashes then restarts

### Steps to reproduce
1. install Nextcloud client on windows 10 (bug also seen on windows8), no fancy settings
2. right clik on any item in windows explorer navigation pane (left column of explorer window)
2bis. No bug for right clicks anywhere else in windows explorer, I can see in a Nextcloud-synched folder the correct context menu related to nextcloud...
3. explorer crashes

Investigation:
disabling `OCContextMenuHandler`	from `C:\Program Files (x86)\Nextcloud\shellext\OCContextMenu_x64.dll`
via Ccleaner Tools> startup > context menu
disables all context menu entries for Nextcloud (one can not see the nextcloud shortcut entries anymore)
also bug does not happen anymore

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system: Windows10 Pro / Version 1809 / OS version 17763.316

OS language: Fench

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration
I could give more info there but it doesn't seem to be related to the server:
I have another computer on windows10 with client version  2.3.1 (build1) with only a minimal context menu integration (only "share with nextcloud") connected to the same server and there is no rght-click in navigation pane bug there...

**Comment by FlexW** [comment]
Sorry for the late answer. Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.

**Comment by joneuhauser** [comment]
I still encounter this problem in Nextcloud Client version 3.4.1, windows-10.0.19044. A right click hangs the explorer for about 20 seconds on every file, including non-Nextcloud files.

**Comment by cieldeville** [comment]
Hello there,

I wasn't sure if I should open a new issue or post it here, but considering the above gives some additional context I figured I would open it here, please correct me, if I was wrong here.

I am experiencing the same issues on Windows 10 currently.

**Expected Behaviour**
Right-clicking an item in Windows Explorer should bring up a context-dependant menu.

**Actual Behaviour**
Windows Explorer enters an unresponsive state, then crashes shortly thereafter.

**Steps to Reproduce**
1. Install NextCloud Client
2. Right-click any item (file, folder, navigation tree item on the left, etc.)
3. Explorer enters unresponsive state, then crashes

**Investigation**
Using ShellExView, a utility to enable and disable context menu extensions I selectively disabled all context-menu extensions that do not ship with Windows. Enable only the Nextcloud context menu handler produces the behaviour described above. Enabling any other extension or combination of extensions does no longer crash Windows explorer.

**Client Version**
Client Version: 3.6.4stable-Win64 (build 20221208)
Operating System: Windows 10 Home Version 21H2, Build: 19044.2364
OS Language: German
Installation Path of Client: P:\Program Files\Nextcloud

**Server Version**
Probably not related, but: 25.0.1

**Are you using the Nextcloud Server Encryption module?**
Yes

**Are you using an external user-backend?**
No

**Comment by Ballard-dev** [comment]
Still an issue on Windows 10 latest build, as of todays date, the only difference between two clients is one of them has additional context menu items already.
