### ISSUE TITLE
right-click tray icon menu cropped on vertical panel

### ISSUE THREAD

**Issue by polrus** [nextcloud/desktop#1117]
in Linux the last part of the right-click tray icon menu is cropped 
see the screenshot
https://send.firefox.com/download/1b4efb5044/#gacpRB35DPhOXehqPlS-Wg

I think the reason is that when you do a right click the menu does not contain the "apps" entry but after a second the "apps" entry is added moving the last menu entries down (behind visible range)

### Expected behaviour
Quit option should be visible

### Actual behaviour
Last menu entries (for example quit) are cut
### Steps to reproduce
1. RIght click on tray icon
2.
3.

### Client configuration
Client version:
2.5.1
Operating system:
Liunx
OS language:
Polish
Qt version used by client package (Linux only, see also Settings dialog):
5.9.4
Client package (From Nextcloud or distro) (Linux only):
Appimage
Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by luixxiul** [comment]
This is reproduced on Windows too.

![](https://user-images.githubusercontent.com/3362943/54863398-88a7c500-4d8b-11e9-88a4-769a29543238.gif)

The apps list should be cached before rendering the pop up.

**Comment by DeBukkIt** [comment]
I can confirm the error for Windows 10.

### Steps to reproduce
1. Run NextCloud
2. Close any NextCloud window
3. Right click on the tray icon in the task bar

### Expected behaviour
The context menu should know its dimensions and should not change them after it appears on the screen. In particular, parts of the context menu should not protrude beyond the edge of the screen.

### Actual behaviour
The menu item "Apps" appears in the context menu when it is already visible (a few milliseconds later). This causes the context menu to grow in the Y direction and the bottom entry ("Exit NextCloud") slips out of the visible screen.

![NextCloud_Contextmenu](https://user-images.githubusercontent.com/1151380/62960367-cc62a000-bdfa-11e9-80e0-607d0d234273.JPG)

**Comment by luixxiul** [comment]
not fixed, bumping

**Comment by godfuture** [comment]
Same here on windows:
![ContextMenuOverlapping](https://user-images.githubusercontent.com/4669278/67673172-ba17ed00-f979-11e9-9885-88c057e1781c.jpg)
For me it is very irritating that the system tray context menu changes it size right after opening.
