### ISSUE TITLE
CMake doesn’t properly install/link the client libraries on Linux (at least on Debian and Ubuntu)

### ISSUE THREAD

**Issue by Iolaum** [nextcloud/desktop#1146]
### Expected behaviour

Dependencies should be installed in proper directories where the client executable can find them.

### Actual behaviour
`libnextcloudsync.so` is put one directory below the place where the client looks for it:

### Steps to reproduce
1. Clone nextcloud/desktop repository locally to compile Following wiki instructions.
```
# Set up repo to compile
$ mkdir /src
$ cd /src
$ git clone git@github.com:nextcloud/desktop.git
# Install dependecies required
$ sudo apt install qt5-default openssl libssl-dev libzip-dev qtdeclarative5-dev qtwebengine5-dev qt5keychain-dev qttools5-dev sqlite3 libsqlite3-dev libqt5svg5-dev zlib1g-dev libkf5kjs-dev doxygen
$ cd /src/desktop
$ mkdir build
$ cd build/
# Extra step to give proper CMAKE paths
# Find the hardcoded location paths for CMAKE
$ dpkg -L $PACKAGE_DEPENDENCY
# cmake command given
$ cmake .. -DCMAKE_INSTALL_PREFIX=/opt/nextcloud-client/ -DCMAKE_BUILD_TYPE=Release -DNO_SHIBBOLETH=1 -DQTKEYCHAIN_LIBRARY=/usr/lib/x86_64-linux-gnu/libqt5keychain.so -DQTKEYCHAIN_INCLUDE_DIR=/usr/include/qt5keychain/ -DOPENSSL_ROOT_DIR=/usr/bin/ -DOPENSSL_INCLUDE_DIR=/usr/include/openssl/ -DOPENSSL_LIBRARIES=/usr/lib/x86_64-linux-gnu/
# Build
$ make -j4
```
2. I didn't want to run make install because then I wouldn't have a proper path to uninstalling `nextcloud-client` if things didn't work. Hence I did the following:

```
$ sudo apt install checkinstall
$ sudo checkinstall -D --install=no --pkgversion=2.5.2.0 --pkgrelease=Iolaum6 --pkgsource=https://github.com/nextcloud/desktop --maintainer=nikperrakis@protonmail.com --provides=nextcloud-client --pkglicense=GPL2 --pkgname=nextcloud-client --stripso=no
# Specify some extra things as asked by checkinstall
$ sudo dpkg -i nextcloud-client_2.5.2.0-Iolaum6_amd64.deb
```
This way I know I can delete all files that `nextcloud-client` will install and have a better path of going back to the official `nextcloud-client` if needed.

3. The problem is that after the installation the `/opt/nextcloud-client/bin/nextcloud` binary wouldn't run. I run:
```
$ ldd /opt/nextcloud-client/bin/nextcloud
# Big output of files
```
and show that the client couldn't find `libnextcloudsync.so`. Those files were initially at
`/opt/nextcloud-client/lib/x86_64-linux-gnu`
however the executable was looking for them at:
`/opt/nextcloud-client/lib/x86_64-linux-gnu/nextcloud`
After manually moving them to the latter directory the client was starting normally.

I think this is a problem coming from the CMAKE specifications but I couldn't pin point it.

Another interesting fact is that sync libraries that nextcloud looks for at:
`/opt/nextcloud-client/lib/x86_64-linux-gnu/nextcloud` (ie `libnextcloudsync.so` and `libocsync.so`)
on the official ppa the  are provided by a different package:
```
$ dpkg -c libnextcloudsync0_2.5.1-20181204.111806~bionic1_amd64.deb 
drwxr-xr-x root/root         0 2018-12-04 11:18 ./
drwxr-xr-x root/root         0 2018-12-04 11:18 ./etc/
drwxr-xr-x root/root         0 2018-12-04 11:18 ./etc/Nextcloud/
-rw-r--r-- root/root       418 2018-12-04 10:09 ./etc/Nextcloud/sync-exclude.lst
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/lib/
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/
-rw-r--r-- root/root   1517664 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/libnextcloudsync.so.2.5.1
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/nextcloud/
-rw-r--r-- root/root    379200 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.2.5.1
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/share/
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-12-04 11:18 ./usr/share/doc/libnextcloudsync0/
-rw-r--r-- root/root       372 2018-12-04 11:18 ./usr/share/doc/libnextcloudsync0/changelog.Debian.gz
-rw-r--r-- root/root     20404 2018-12-04 10:09 ./usr/share/doc/libnextcloudsync0/changelog.gz
-rw-r--r-- root/root       103 2018-12-04 11:18 ./usr/share/doc/libnextcloudsync0/copyright
lrwxrwxrwx root/root         0 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/libnextcloudsync.so.0 -> libnextcloudsync.so.2.5.1
lrwxrwxrwx root/root         0 2018-12-04 11:18 ./usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.0 -> libocsync.so.2.5.1
```
hence the relevant configurations is CMAKE may not be used enough to notice the problem.

### Client configuration
- Operating system:
```
$ uname -a
Linux shade 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Client information and dependencies shown from client settings dialogue: 

> Built from Git revision 9032b1 on Mar 9 2019, 16:49:49 using Qt 5.9.5, OpenSSL 1.1.0g 2 Nov 2017

- Installation path of client: `/opt/nextcloud-client/`

**Comment by elsiehupp** [comment]
I came across this same problem when I was doing a development build on a system where my production copy of Nextcloud was the Flatpak version. Basically, the CMake install script doesn’t install a fully working copy of Nextcloud Desktop. Rather, it seems to require a production copy installed via e.g. `apt` or similar in order to work.

**Comment by elsiehupp** [comment]
@FlexW you seem fairly familiar with the CMake scripts—do you have any idea what’s going wrong here? Thanks!

**Comment by FlexW** [comment]
@elsiehupp I'm not sure about the original question, because I'm not familiar with apt and it tools, but I think I have an answer for your question:

On a Linux system when a executable file gets executed and uses shared libraries (like in the case of the desktop client), the linker looks in predefined directories for the libraries. These directories are normally: `/lib`, `/lib64`, `/usr/lib`, `/usr/lib64` and maybe some others. Only shared libraries in these directories are used.

Now, if you do a development build of the desktop client and want to execute the desktop client from the build directory or from a custom install directory, the desktop client searches for the shared libraries not in the build directory but in the predefined directories I mentioned above. Thats a problem because your libraries are in custom directories that the linker can not find. In Linux there are two possibilites I'm aware of to work around this problem (and I think these are the only ones). The first possibility is to start the application with a `LD_LIBRARY_PATH` pointed to the directory where your shared libraries are. For example:
```
LD_LIBRARY_PATH=/path/to/where/libnextcloudsync.so/is:/path/to/where/libnextcloud_csync.so/is ./nextcloud
```
The other possibility would be to patch the rpath of the executable to point it to the correct location, but that would be a bit to tedious for development. I'm also a little bit annoyed of setting LD_LIBRARY_PATH anytime I start the client, but if you have a good shell (like fish ;)) it's very fast to type/autocomplete. Maybe it is possible with CMake to patch the rpath of the executable to the libraries in the build directory and when one executes make install cmake removes the rpath again from the executable (to use then system libraries), but I have never seen this.

If you want to learn more about linking on Linux, I can recommend you this awesome book https://man7.org/tlpi/

**Comment by Iolaum** [comment]
It's been a while since I worked and reported on this. However after re-reading my post the idea was not to:

    Now, if you do a development build of the desktop client and want to execute the desktop client from the build directory or from a custom install directory,

I wanted to do a build from source, following the provided instructions. I would then install the resulting package properly and it would be the only desktop client installed and used. (This is why I was creating a deb package that I would then install.)

Hence LD_LIBRARY_PATH shouldn't have been needed in my case because there would be only one location for the nextcloud libraries present on the system. 

Not sure if that distinction applies to other developers who also encountered/reproduced this issue.

**Comment by FlexW** [comment]
@lolaum You are right. LD_LIBRARY_PATH does not play a role. When I try to install the Nextcloud client from source, I get the following directory structure, which is correct in my opinion. This is on ArchLinux.  CMake picks the library directory from the `CMAKE_INSTALL_LIBDIR` variable. You could have a look in the official deb package, and see how they do it. Maybe there needs to be done something special to set the variable correct on Debian/Ubuntu.

```
├── bin
│   ├── nextcloud
│   └── nextcloudcmd
├── etc
│   └── Nextcloud
│       └── sync-exclude.lst
├── include
│   └── nextcloudsync
│       ├── creds
│       │   ├── abstractcredentials.h
│       │   └── httpcredentials.h
│       └── mirall
│           ├── account.h
│           ├── configfile.h
│           ├── networkjobs.h
│           ├── progressdispatcher.h
│           ├── syncengine.h
│           ├── syncfileitem.h
│           └── syncresult.h
├── lib64
│   ├── libnextcloud_csync.so -> libnextcloud_csync.so.0
│   ├── libnextcloud_csync.so.0 -> libnextcloud_csync.so.3.2.50
│   ├── libnextcloud_csync.so.3.2.50
│   ├── libnextclouddolphinpluginhelper.so
│   ├── libnextcloudsync.so -> libnextcloudsync.so.0
│   ├── libnextcloudsync.so.0 -> libnextcloudsync.so.3.2.50
│   └── libnextcloudsync.so.3.2.50
└── share
    ├── applications
    │   └── com.nextcloud.desktopclient.nextcloud.desktop
    ├── caja-python
    │   └── extensions
    │       └── syncstate-Nextcloud.py
    ├── cloud-providers
    │   └── com.nextcloudgmbh.Nextcloud.ini
    ├── icons
    │   └── hicolor
    │       ├── 1024x1024
    │       │   └── apps
    │       │       └── Nextcloud.png
    │       ├── 128x128
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       ├── 16x16
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       ├── 24x24
    │       │   └── apps
    │       │       └── Nextcloud.png
    │       ├── 256x256
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       ├── 32x32
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       ├── 48x48
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       ├── 512x512
    │       │   └── apps
    │       │       └── Nextcloud.png
    │       ├── 64x64
    │       │   └── apps
    │       │       ├── Nextcloud_error.png
    │       │       ├── Nextcloud_error_shared.png
    │       │       ├── Nextcloud_ok.png
    │       │       ├── Nextcloud_ok_shared.png
    │       │       ├── Nextcloud.png
    │       │       ├── Nextcloud_sync.png
    │       │       ├── Nextcloud_sync_shared.png
    │       │       ├── Nextcloud_warn.png
    │       │       └── Nextcloud_warn_shared.png
    │       └── 72x72
    │           └── apps
    │               ├── Nextcloud_error.png
    │               ├── Nextcloud_error_shared.png
    │               ├── Nextcloud_ok.png
    │               ├── Nextcloud_ok_shared.png
    │               ├── Nextcloud_sync.png
    │               ├── Nextcloud_sync_shared.png
    │               ├── Nextcloud_warn.png
    │               └── Nextcloud_warn_shared.png
    ├── kservices5
    │   └── nextclouddolphinactionplugin.desktop
    ├── mime
    │   ├── aliases
    │   ├── application
    │   │   └── vnd.nextcloud.xml
    │   ├── generic-icons
    │   ├── globs
    │   ├── globs2
    │   ├── icons
    │   ├── magic
    │   ├── mime.cache
    │   ├── packages
    │   │   └── nextcloud.xml
    │   ├── subclasses
    │   ├── treemagic
    │   ├── types
    │   ├── version
    │   └── XMLnamespaces
    ├── nautilus-python
    │   └── extensions
    │       └── syncstate-Nextcloud.py
    ├── nemo-python
    │   └── extensions
    │       └── syncstate-Nextcloud.py
    └── nextcloud
        └── i18n
            ├── client_af.qm
            ├── client_bg.qm
            ├── client_br.qm
            ├── client_ca.qm
            ├── client_cs.qm
            ├── client_da.qm
            ├── client_de.qm
            ├── client_el.qm
            ├── client_en_GB.qm
            ├── client_en.qm
            ├── client_eo.qm
            ├── client_es_AR.qm
            ├── client_es_CL.qm
            ├── client_es_CO.qm
            ├── client_es_CR.qm
            ├── client_es_DO.qm
            ├── client_es_EC.qm
            ├── client_es_GT.qm
            ├── client_es_HN.qm
            ├── client_es_MX.qm
            ├── client_es.qm
            ├── client_es_SV.qm
            ├── client_et.qm
            ├── client_eu.qm
            ├── client_fa.qm
            ├── client_fi.qm
            ├── client_fr.qm
            ├── client_gl.qm
            ├── client_he.qm
            ├── client_hr.qm
            ├── client_hu.qm
            ├── client_id.qm
            ├── client_is.qm
            ├── client_it.qm
            ├── client_ja.qm
            ├── client_ko.qm
            ├── client_lt_LT.qm
            ├── client_lv.qm
            ├── client_mk.qm
            ├── client_nb_NO.qm
            ├── client_nl.qm
            ├── client_oc.qm
            ├── client_pl.qm
            ├── client_pt_BR.qm
            ├── client_pt.qm
            ├── client_ro.qm
            ├── client_ru.qm
            ├── client_sc.qm
            ├── client_sk.qm
            ├── client_sl.qm
            ├── client_sr.qm
            ├── client_sv.qm
            ├── client_th.qm
            ├── client_tr.qm
            ├── client_TW.qm
            ├── client_uk.qm
            ├── client_zh_CN.qm
            ├── client_zh_HK.qm
            └── client_zh_TW.qm
```

**Comment by elsiehupp** [comment]
FYI this is where I have the libraries installed from:

https://packages.debian.org/bullseye/nextcloud-desktop
https://tracker.debian.org/pkg/nextcloud-desktop

I don’t know exactly what goes into the packaging process.

**Comment by FlexW** [comment]
Just for the record @elsiehupp. If you do a development build and work without `LD_LIBRARY_PATH`, and you don't install the libraries with `sudo make install` into /lib64 etc, and then start the client from the build directory, you are not going to use the source code that you have compiled, and you may not see changes that you made. That may not be an issue for you now, because all areas that you worked on are compiled into the executable (things in `src/gui`), but if you make changes, for example in `src/libsync`, then you won't see the changes in your running program. I will close that issue for now, because I don't think issue is on our side. Please request to reopen it if you think different.

**Comment by elsiehupp** [comment]
To summarize the Issue as I’ve reframed it:

## Expected Behavior
When you run `sudo make install`, the resulting installed build should be properly linked and should be fully functional on a system with only the listed external dependencies installed, and on a system with an existing Nextcloud installation, the build should not use any preexisting Nextcloud components in place of components from the fresh build.

## Actual Behavior
When you run `sudo make install` on Debian or Ubuntu (and possibly some other distros), CMake does not properly install/link `libnextcloudsync.so`. Because of this, the resulting build will either try to use whatever version of `libnextcloudsync.so` it happens to find, or it will fail on launch if it can’t find anything.

**Comment by FlexW** [comment]
@elsiehupp I've tested now on Ubuntu and if you set the `CMAKE_PREFIX_PATH` to `/usr` on Ubuntu, the libraries and files are put in the correct directories. I was able to run the client after doing that. Could you please confirm that it this works for you too? If yes, please close the issue.

@lolaum I think your issue is that you try to install the client in a non standard directory and the dynamic linker can not pick up the libraries from there. You need to tell your dynamic linker where it can find these libraries.

**Comment by elsiehupp** [comment]
@FlexW sorry it’s taking me a little bit to get around to testing this on my end. I’ll try and do it ASAP.

**Comment by mgallien** [comment]
Is there really still a problem to be solved here?
I would believe that if our build system is broken Linux distribution packagers would complain. At least I hope so.

**Comment by elsiehupp** [comment]
I still haven’t had a chance to double-check this.
