### ISSUE TITLE
Waiting for {x} other folder{s}..../undefined state

### ISSUE THREAD

**Issue by GieltjE** [nextcloud/desktop#1189]
### Expected behaviour
Proper status messages

### Actual behaviour
Accounts go into "Waiting for {x} other folder{s}...." and the tray icon displays "undefined state". The F12 log does sometimes display endless checking for rename e.t.c. before finally (maybe) starting a sync

### Steps to reproduce
1. Windows desktop client (2.5.1 or current daily as of 05-april-2019)
2. Add multiple accounts (600GB orso) with added folder sync connections

### Client configuration
Client version: 2.5.1 and daily as of 05-april-2019
Operating system: Windows 10 x64 1809 fully up to date
OS language: en_GB
Installation path of client: C:\Program Files (x86)\Nextcloud

**Comment by bingen** [comment]
I have the same issue with 2 accounts on linux, version:
```
/usr/bin/nextcloud --version
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Nextcloud version 2.5.2git
Using Qt 5.11.3, built against Qt 5.11.1
Using 'OpenSSL 1.1.1b  26 Feb 2019'
```

**Comment by themisanthrope** [comment]
Noticed I'm getting this on a newly installed Linux box.
Sync eventually starts, but I've had it stuck in this state for a couple of hours before there's any activity.

**Comment by tryallthethings** [comment]
Seeing the same on my system.

Windows 8.1
OS-Language: en_us
NextCloud Desktop Client 2.6.4 stable
NextCloud Server: 18.0.1
![image](https://user-images.githubusercontent.com/11146296/76527826-20f0fb00-6470-11ea-8700-7a3c99c6bb8a.png)
![image](https://user-images.githubusercontent.com/11146296/76527838-26e6dc00-6470-11ea-9fd2-d68c7f4f8b4f.png)
![image](https://user-images.githubusercontent.com/11146296/76527844-28b09f80-6470-11ea-89e9-e2b4b18cd072.png)

As per the screenshot I'm using 2 different NextCloud servers. The sync seems to work fine - just a user experience issue IMHO.

**Comment by okko7** [comment]
I can confirm the same issue on MacOS. As others mention, I have accounts on two different servers.

**Comment by loxK** [comment]
I am just facing this too on latest NC20, and latest client on Ubuntu 20.04

**Comment by color-space** [comment]
Still have this problem on the newset 3.1.1 with newest server update aswell.

`2021-01-16 17:23:17:330 [ info nextcloud.gui.account.settings ]:	Application: enable folder with alias  "2"
2021-01-16 17:23:17:373 [ info nextcloud.gui.folder ]:	Saved folder "2" to settings, status QSettings::NoError
2021-01-16 17:23:17:374 [ info nextcloud.gui.folder.manager ]:	Schedule folder  "2"  to sync!
2021-01-16 17:23:17:374 [ info nextcloud.gui.folder.manager ]:	Sync for folder  "2"  already scheduled, do not enqueue!
2021-01-16 17:23:17:374 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "2" because status() is 1
2021-01-16 17:23:17:376 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://url-to-cloud-web-dav" :  "Not yet Started"
2021-01-16 17:23:17:376 [ info nextcloud.gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:D:\\Sync\\Redacted" to QLocalSocket(0x1be2b5f4f50)`
