### ISSUE TITLE
Desktop Notifications not working

### ISSUE THREAD

**Issue by Kiaatix** [nextcloud/desktop#1197]
No desktop notifications are shown since client version 2.5.
Notifications worked correctly in client version 2.3.x.

### Expected behaviour
Tray Notification Bubble for Server-Notifications and Sync-Activity

### Actual behaviour
No notifications.

### Workaround
At least for Sync-Activity notifications, removing line 420 in folders.cpp works for me.

https://github.com/nextcloud/desktop/blob/8491ef428eba12dc95a3eb5f5a1e426808a9f6bc/src/gui/folder.cpp#L418-L422

### Client configuration
Client version:
2.5.2

Operating system:
Ubuntu Mate 18.04

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.9.5

### Server configuration

Operating system:
Ubuntu 16.04

Web server:
Apache

Database:
MySQL

PHP version:
7.2

Nextcloud version:
15.0.7

**Comment by camilasan** [comment]
Hi! This is expected since we decided to not display the syncing files activities pop up message anymore. You will be able to see them only in the :zap: tab on the main window of the application. See PR https://github.com/nextcloud/desktop/pull/491

**Comment by Kiaatix** [comment]
Ah ok. I found it quite nice to get at least a pop up if a new version of Nextcloud or an App was available, though. I don't get server notifications in the :zap: tab, even though Server-Notifications is checked in the settings tab...

**Comment by MacGuGuSS** [comment]
it would be good to have chose to show this notification on mac
many of my client works with them....

**Comment by derdershat** [comment]
Came here to see if this problem is fixed in newer versions and read that it was expected to remove the Notification Bubble/Toast messages if files are synced. 
This was very nice in Nextcloud but stopped with Versions above 2.3. Couldn´t this be implemented again in NC Client as option?  
Par ex if I get an E-Mail Outlook displays a smart notification with short infos and I don`t need to open the main program every time. 
If I get an update from Nextcloudpi I recieve a notification and if I miss it it is shown in my Windows 10 Notifications.
If someone uploads stuff I get a notification with sound.(Here I can understand that it would be irritating on big clouds.)

Was this decision absolutely necessary because otherwise it led to major complications in newer versions?
Isn`t a reimplementation with choosable settings the better way to go? I mean I can only speak for Windows but here 
the Toast Notification and Action Center is made for this.

**Comment by JWilliamCupp** [comment]
I have a problem with this.  Often I am in areas of poor network connectivity.  How can I tell if my NextCloud documents have synched or not?  What happens if NextCloud goes down without warning?  I could go for days without any synchronization and have no visual indication this is the case.  Please return at least the option for the user to choose to display in the system tray / notification area.

**Comment by FelixBuehler** [comment]
I would be very happy, if this behaviours could come back. Checkbox in the settings might do the trick for those who are annoyed by the pop-ups?

**Comment by schniepp** [comment]
I need to get NC notifications, do approve login requests (2FA). Currently, I do not get any notifications in the desktop client whatsoever, so I cannot approve login requests.

**Comment by camilasan** [comment]
Sorry @jancborchardt... what do you think?

**Comment by jancborchardt** [comment]
Seems like there are a lot of different things lumped into one here. Will try to unravel.

The short reason of why we _reduced_ (not removed) notifications is to keep them useful. If you get a notification for everything, nothing is important. You need notifications for errors, approvals, etc., but not for things which work as expected.

As for settings, we try to keep these minimal for several reasons. 2 big ones are:
- if we have a lot of settings, regular users can’t find the important ones
- if we have a lot of settings, we have a way bigger test matrix and potential for bugs. And no one wants more bugs.

----------------------


I’ll attempt to reply to individual points:


> I need to get NC notifications, do approve login requests (2FA). Currently, I do not get any notifications in the desktop client whatsoever, so I cannot approve login requests.

@schniepp @camilasan these notifications should of course be shown since they require interaction.


> I found it quite nice to get at least a pop up if a new version of Nextcloud or an App was available, though.

@Kiaatix @camilasan if you are an admin of the instance, then you should also get notifications about the new version of Nextcloud, yes. New version of an app is less important, let’s only slowly reintroduce stuff.


> Often I am in areas of poor network connectivity. How can I tell if my NextCloud documents have synched or not?

@JWilliamCupp that is what the system tray icon is for. It indicates the current status, which is a green checkmark if everything is fine. Same as others like Dropbox and Google Drive do it.


> Par ex if I get an E-Mail Outlook displays a smart notification with short infos and I don`t need to open the main program every time.

@derdershat but you don’t get a notification every time an email of yours was successfully sent, or e.g. a deletion was synced.


----------------------

Keep in mind we will eventually work on an **improved tray menu #877** and then all activity including notifications will be much more present.

If there are any specific further points you want to bring up, please open _separate_ new issues for it. Discussing several different things in a long closed thread makes it a bit difficult to fix things.

Thanks everyone! :heart:

**Comment by paccerdk** [comment]
I am not getting any 2FA (& other) notifications on Nextcloud desktop 2.6.4stable-Win64 (build 20200303)
User is in admin group, the notification is there if i log in to the web interface,
"show server notifications" is enabled in the general tab of the desktop client.

**Comment by loelkes** [comment]
> > Often I am in areas of poor network connectivity. How can I tell if my NextCloud documents have synched or not?
> 
> @JWilliamCupp that is what the system tray icon is for. It indicates the current status, which is a green checkmark if everything is fine. Same as others like Dropbox and Google Drive do it.

The reality is that most users (not to say all non-tech people) tend to forget to check the icon.

> You need notifications for errors, approvals, etc.

AFAIK there is currently no notification for errors. This would be my feature request. Related to #1726 and maybe #1618 and #877

**Comment by er-vin** [comment]
Closing it, since I think @jancborchardt addressed most concerns. If still some concern is left unanswered, please open a new issue about that particular concern. This issue went in enough directions to not be really possible to deal with anymore.
