### ISSUE TITLE
Notifications about app updates are way too frequent

### ISSUE THREAD

**Issue by inputsh** [nextcloud/desktop#1229]
### Expected behaviour

One notification per app per day, *maybe* two.

### Actual behaviour

I think we could all agree that this is a bit too much:

![Screenshot from 2019-05-01 20-30-50](https://user-images.githubusercontent.com/4890548/57034538-0b0b8a80-6c50-11e9-8e58-efcf2ddecbcf.png)

I've experienced the same on multiple Linux-based operating systems over the years. This issue usually makes me turn off the notifications all together, but I'm surprised that I could not find an open issue about this behaviour. I do want to be reminded that there's an app update available, just not this frequently.

### Client configuration

* Client version: 2.5.2git
* Operating system: elementary OS 5.0
* OS language: Eng 
* Client package (From Nextcloud or distro) (Linux only): From Nextcloud
* Installation path of client: nextcloud: /usr/bin/nextcloud /usr/lib/x86_64-linux-gnu/nextcloud /usr/share/nextcloud

**Comment by camilasan** [comment]
Do you have a screenshot of what this looks like in the Notifications/Activities tab of the main windows of the client? Thanks.

**Comment by selaux** [comment]
I have the same issue using Gnome. In the activity tab the notification shows only once. E.g. `Update to Nextcloud 16.0.0 is available - 5 days ago`. Same for app updates.

**Comment by aleksandar-todorovic** [comment]
@camilasan Sorry, I had to wait for the next app update in order to see the behaviour in the Activity tab. 

Now I have four of them displayed in the notifications area in my OS, oldest of which was four hours ago:

![Screenshot from 2019-05-12 20-43-28](https://user-images.githubusercontent.com/4890548/57586475-cd7fea80-74f6-11e9-9c8a-7e309184521d.png)

The Activity tab only shows it once, 1 day ago:

![Screenshot from 2019-05-12 20-46-00](https://user-images.githubusercontent.com/4890548/57586502-06b85a80-74f7-11e9-9f47-ec31aa652db9.png)

Clicking on the Activity tab clears them out from the desktop's notification center. I can re-trigger the notifications  manually by restarting the desktop client. After my notification screen was cleared, I've restarted the desktop client twice. One new notification was generated each time:

![Screenshot from 2019-05-12 20-46-45](https://user-images.githubusercontent.com/4890548/57586511-30718180-74f7-11e9-882a-47c9685c21bf.png)

I can confirm what @selaux is saying, I've experienced this in GNOME as well as its forks (like elementary OS' Pantheon). I have no experience with other desktop environments, so this might be platform-specific.

**Comment by hpaantee** [comment]
I also have this problem. Probably once per hour I get a notification in KDE about some App update.

**Comment by bes1002t** [comment]
Same issue in Fedora 31.

I would suggest to make the frequency configurable. I want a notification per week, but maybe there are other users who want a notification once per day. Sure we could dismiss the notification on server GUI but then we don't get notifications anymore. This could cause security issues which is not the intention I think.

**Comment by bes1002t** [comment]
Just to provide an example, as well:
![notification_spam](https://user-images.githubusercontent.com/3890580/82765029-9cc5d700-9e13-11ea-82d9-fd73fe859a61.png)

**Comment by bes1002t** [comment]
any progress so far? It's really annoying.

**Comment by er-vin** [comment]
Well, we shouldn't emit system notifications for those anymore in 3.0.x they just appear in the activity list which is probably enough. Please someone confirm and I'll just close it.

**Comment by bes1002t** [comment]
I think system notifications would be ok, but not every hour. I want the notification if there are updates, but probably once a day or after the application has started.
