### ISSUE TITLE
App name in windows notification system is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/desktop#123]
Running 2.3.3 on WIndows 10
Same issue on my wife's mashine:
> ![client-bug](https://user-images.githubusercontent.com/213943/34951083-5ffff660-fa15-11e7-8d97-0a817bc04ea4.png)

The `Microsoft.Explorer.Notification....` should say `Nextcloud`

**Comment by arnowelzel** [comment]
Happens here too (Windows 10 Pro).

**Comment by arnowelzel** [comment]
Update: it seems only to happen, when the client is started automatically during boot. When I stop it and restart it manually, the notification is labeled properly.

**Comment by DominiqueFuchs** [comment]
Hey @arnowelzel , thanks for reporting this and sorry that this went unnoticed for so long. I just tried to reproduce this issue with the latest stable client (2.6.0) on Windows 10 with autostart enabled and everything displayed as expected when triggering some notifications server-side.

There haas been a bunch of improvements and changes regarding the notification system and logic over the past month. Are you still there, could you report back if this issue is solved for you, too?

**Comment by nickvergessen** [comment]
Yes, I'm still here (and still employed at Nextcloud :smile: )

Works fine with 2.6 and also I didn't notice it anymore lately, so let's close this and in worst case reopen it, when it happens again.

**Comment by arnowelzel** [comment]
Yes, I'm still a happy user of Nextcloud :-) and I can confirm that notifications in the current version works correct.
