### ISSUE TITLE
App tries to connect to 127.0.0.1 even though the server is distant

### ISSUE THREAD

**Issue by Ked57** [nextcloud/desktop#1233]
### Expected behaviour
1. Enter the address into the app
2. Click on "Log-in" button
3. See the Log in fields

### Actual behaviour
1. Enter the address into the app
2. Click on "Log-in" button
3. See a "firefox like" error page saying 127.0.0.1 is not accessible, and of course it's not. The server is distant

### Steps to reproduce
I wouldn't really know but my server runs in a docker container behind an apache reverse proxy, with cloudflare https

### Client configuration
Client version: Latest

Operating system: Windows 10

OS language: French

### Server configuration

Operating system: Debian 9.4

Web server: Apache

Database: Postgres

PHP version: 7 I guess 

Nextcloud version: latest docker image

Storage backend (external storage): 2TO softraid

### A little more information 

I have no problem accessing the server using the web client, it's the desktop client that fails and tries to redirect me to 127.0.0.1
I think this might be because of this in the settings "settings/user/sync-clients"
![image](https://user-images.githubusercontent.com/2174111/57155388-9a917480-6ddb-11e9-8569-615532c73600.png)
The server thinks its url is 127.0.0.1 but it's actualy running behind a reverse proxy. Did I miss an env variable when I did my docker run ?

**Comment by Schmuuu** [comment]
Hi, 
Such questions are better posted in the Nextcloud forum:
https://help.nextcloud.com

Your issue is rather a misconfiguration than a bug. When you post your issue on the Forum, please add the information if you really entered the full qualified domain name (=fqdn; like cloud.yourdomain.com) in the client app, when you try to connect and if this is the same address you use in your browser.

**Comment by camilasan** [comment]
Agreed with @Schmuuu, this should be fixed with the correct configuration.
