### ISSUE TITLE
Windows client 2.5.1 & 2.5.2 crashes when changing proxy/no proxy

### ISSUE THREAD

**Issue by ReinerNippes** [nextcloud/desktop#1261]
### Expected behaviour
Client should not crash

### Actual behaviour
Changing from corporate network with internet access via proxy to a mobile/home network without proxy the client in version 2.5.1 and 2.5.2 doesn't recover status "red" and just crash if you double click on the systemtray icon.

### Steps to reproduce
1. Start client in a network with proxy. (Network settings "Use System Proxy")
2. Change network to a network with direct internet access
3. Wait till state becomes red.
4. Double click systemtray icon

### Client configuration
Client version: 2.5.1, 2.5.2

Operating system:
Windows 10 

OS language:
German

Installation path of client:

### Server configuration

Operating system: Ubuntu 18.04

Web server: nginx

Database: postgres

PHP version: 7.3

Nextcloud version: 15 & 16

**Comment by Mr-Bart-Simpson** [comment]
This also seems to be a problem in 2.6.0 stable.

**Comment by ReinerNippes** [comment]
And Version 2.6.1 still can't handle this.

**Comment by walserc** [comment]
Same on Version 2.6.4 for me - whenever the proxy changes, the client crashes when opened the next time.

**Comment by lk3de** [comment]
I can confirm this issue still exists with 2.6.5:

- Client version: 2.6.5
- Client OS: Windows 10 Enterprise 1809
- Client OS language: German
- Client is set to "Use System Proxy"

- Server version: 19.0.0
- Server OS: Ubuntu 18.04
- Server PHP version: 7.4.8

Possibly related to #1654, since I'm having this issue both when switching between proxy/nonproxy networks and when switching between VPN (IKEv2) and direct internet. Probably the VPN configuration is setting new proxy settings in the background as well.
