### ISSUE TITLE
Web login has not working context menu items

### ISSUE THREAD

**Issue by csware** [nextcloud/desktop#1267]
Open the context menu on the Web login view. There are the options "Back, Forward, Reload, Save page, and View page source".

### Expected behaviour
All options are localized and

* Click on "View page source", I get an editor with the HTML code of the page.
* Click on "Save page", I get a save file dialog.
* **Or:** The context  menu item is not available.

### Actual behaviour
All options are Englisch only and

* Click on "View page source": The default browser opens
* Click on "Save page": Nothing happens.

### Steps to reproduce
1. Try to set up a Nextcloud server connection.

### Client configuration
Client version: 2.5.2git (https://github.com/nextcloud/desktop/commit/56c905819ee6d48db136e7b5978bdf2a42677f3f)

Operating system: Win7 x64

OS language: de

**Comment by Apromixately** [comment]
This login form should probably redirect to the default browser. That would also allow using the probably existing web session for granting access.

**Comment by Apromixately** [comment]
And of course it would be even nicer if already logged in sessions would display this prompt. That way logging in on a phone would just require clicking okay on the desktop.

**Comment by misch7** [comment]
Please try the new version 2.6 of the Desktop Client:
https://nextcloud.com/install/#install-clients

One of the new features in this version is the Login Flow v2 which uses your system's default browser for the login if you connect to NC server 16.x or newer.

Also we're about to release version 2.6.1 soon.

**Comment by Apromixately** [comment]
@misch7 I just tried and it kind of works.
1. It doesn't display which account is being used anywhere. This might not be a common problem but I have multiple accounts on the same server and it would be nice if it was at least displayed which account is being used.
2. Of course it would be much nicer if there was also an option to log out to select a different one.
3. Even when logged in I am still prompted to login + prompted to grant access. I don't see why the first is happening. No password or anything is required it's just a button saying "Log In ->".

**Comment by misch7** [comment]
@Apromixately Thanks for checking and for your suggestions.

1. It's luckily not that common but either way one thing to take into consideration for UI improvements.

2. In general or specifically on first auth or re-auth?

3. That's actually pretty weird and shouldn't happen of course. Does it happen every time you open the client or did it just happen once upon re-auth?

Regarding overall usability we have some promising design work ongoing :)
https://github.com/nextcloud/desktop/pull/1565

**Comment by Apromixately** [comment]
@misch7 
1. Agreed, but should also be a simple change. If you would be willing to support I might be interested in trying. Not sure how difficult it is to set up a development environment. :)
2. I think  this will probably happen so rarely it would be overkill to actually add this feature.
3. Not sure I described this well. In the browser part there are two clicks. Let me add screen-shots.
This is the first prompt:
![image](https://user-images.githubusercontent.com/19586851/68837789-9fee4680-06bd-11ea-9201-7c14b9d97256.png)
This is the second prompt:
![image](https://user-images.githubusercontent.com/19586851/68837819-b09ebc80-06bd-11ea-9fe1-2474f82d04ef.png)

I don't understand what the first one does.

Maybe we should move this discussion to a new issue?

**Comment by misch7** [comment]
@Apromixately Sry, too busy and forgot the issue here ^^

I think now I got the problem, after re-reading your description, thanks to your screenshots above.

When you click "Log in" and directly get the "Grant access" prompt, then you must have been logged into your account already in your browser.
To check this just enter your server URL in a new tab for example and then you should see your files.

If you then want to use a different account, do the following:
- _Browser:_ Log out of your Nextcloud in the browser
- _Desktop Client:_ Add a new account again and let it open the browser
- _Browser:_ When you click "Log in" you should get a login prompt, enter username and password
- _Browser:_ Then click "Grant access"
- _Desktop Client:_ Wait until the Client fetches the app password in the background and continues
- Report back here with the result ;-)

Regarding setting up a development environment: It's actually quite easy nowadays, especially on Windows :)
Here is our official repo, used for creating our daily builds and the releases: https://github.com/nextcloud/client-building/

It contains detailed instructions on how to get and configure all the tools and after your first successful build, your just can open the Visual Studio solution file in the build folder to rebuild only your changes and for debugging.
