### ISSUE TITLE
Monochrome icon does not change color following Windows theme settings

### ISSUE THREAD

**Issue by edmael** [nextcloud/desktop#1276]
### Expected behaviour
When using the light theme in Windows nextcloud monochrome icon in the icon tray should turn black.

### Actual behaviour
No matter what Windows theme (light or dark) I use, nextcloud monochrome icon is always white.

### Steps to reproduce
1. Change Windows theme between light and dark
2. All Windows tray icons turn to black, nextcloud icon does not

### Client configuration
Client version: 2.5.1final build 20181204

Operating system: Windows 10, version 1903 build 18898

OS language: italian

**Comment by DominiqueFuchs** [comment]
Just noticed the same. With the intention to fix this I just polished my buildchain on Windows (quite a hassle, but now works fine - that said: IMHO it would be a great idea to unify the several snippets explaining partly massively outdated instructions or a at least point out more strongly which is right for the moment - NextcloudWebsite/GithubWiki/Build-Client-Repo)..

However, I totally got lost in Qfiles while debugging/stepping through the client in VS to get to the point where theme switching is handled. Never worked with QT before, however a lot with C++. Can anyone with more NC-Experience point out where to look for or what's the general approach for this with the QT framework?

**Comment by Nextcloud-MichaelSchuster** [comment]
Hey @DominiqueFuchs, regarding the Qt thing I'm pretty new to this and the NC codebase too, even though also not to C++ ;-)
This kind of stuff should reside somewhere in desktop/src/gui but there is also theme stuff in desktop/src/libsync (like theme.cpp & theme.h).

Building was also an issue for me when I made my way through all the outdated documentation. That's why I ended up doing this here:
https://github.com/misch7/nextcloud-client-building

That's currently the official Windows building repo and updating the old docs is also on our endless list of to-do's. ^^

**Comment by misch7** [comment]
Hey @DominiqueFuchs, regarding the Qt thing I'm pretty new to this and the NC codebase too, even though also not to C++ ;-)
This kind of stuff should reside somewhere in desktop/src/gui but there is also theme stuff in desktop/src/libsync (like theme.cpp & theme.h).

Building was also an issue for me when I made my way through all the outdated documentation. That's why I ended up doing this here:
https://github.com/misch7/nextcloud-client-building

That's currently the official Windows building repo and updating the old docs is also on our endless list of to-do's. ^^

<br/>
(was logged in with the wrong user - re-posted this)

**Comment by DominiqueFuchs** [comment]
Hi Michael,
thanks for the follow-up! Yeah, I realized that building was mostly a doc issue, when you get the grip it's pretty straightforward even for windows. I ended up building my own cmd pipeline before I saw your repo and it ended up pretty much the same (except stuff I don't need for testing). 

I'll take a deeper look into this the next days, guess I just have to get a little more familiar with the Qt concept. I also noticed that there already **is** a dark monochrome file set in the src for about a year or so and wondered where this comes from?

**Comment by misch7** [comment]
Hi Dominique,
you're welcome ;) And cool btw. you want to contribute and take the time for this (also saw your Windows UI tile contributions 👍    :)

Know what you mean - really satisfying once you get it working to build, right? =)

I also think it's really a matter of getting more familiar with Qt concepts and the way everything works together in the NC codebase.

Dark icon set: that's a good point - I've seen this too - maybe @camilasan has an idea and can tell? ;)

There are a few outdated bits in the repo and need some cleanup, like old installer scripts. Would be good to know how current this stuff under `desktop/theme` is.

<br/>
Another thing worth noting: Do you know about the Nextcloud conference this month? Berlin Sep 14-15 and there is also a hack week afterwards till Sep 20 where Nextclouders come, think and hack together :)
https://nextcloud.com/conf-2019/

In case you have the time and want to join us there / attend the conference, contributors also get a free ticket 😼

**Comment by DominiqueFuchs** [comment]
OK, got it. Made a PR. Works fine, but happy to receive comments or concerns.

Thanks Michael! Didn't know about this and sounds like a really fun thing to participate at. Looking forward to next year as I'm pretty much ooo this month, but was happy to see that this takes places annualy. Definitely on my bucket list now 💯

**Comment by misch7** [comment]
Very cool, thank you!

I will review this soon 😸 

And looking forward to meet you (latest) at the conference next year ;)

**Comment by Eurbaix** [comment]
Same issue with gnome (Linux), and probably other Linux GUI.

Same steps to reproduce (in my case Zorin OS):
1. Use Zorin with normal theme. Icon is white (OK if the bar is transparent, but it becomes white in some cases, and is always white in Zorin Lite).
2. Switch to dark theme (Zorin Appearance), it stays white, which is a good thing this time.

Considering the diversity of GUI for Linux, or even gnome implementations, implementing dynamically switching from a dark icon to a light icon may be a daunting task for Linux. So, I suggest adding fixed choices for Light, Medium and Dark icons, to allow the user to at least choose a monochrome icon appropriate for its GUI theme (may be only for Linux builds if dynamic monochrome icons work properly for Windows and MacOS).

Now, I understand Linux is not as widespread as Windows, but consider that organizations switch to NextCloud mainly for privacy reasons, and their next goal is probably to switch to a more private desktop OS like Linux (or, more and more, just because they would rather spend tax-payers money on something else than an OS license). That said, I understand if this issue remains on the back-burner for a while.
