### ISSUE TITLE
I'm caught in a dead circle of login and authorization with 3.5.2

### ISSUE THREAD

**Issue by ryanrain2016** [nextcloud/desktop#1302]
### Expected behaviour
login normally.

### Actual behaviour
while login with the latest version（2.5.2）, I'm caught in a dead circle of login and authorization. But it's Ok with version 2.3.3.1.
### Steps to reproduce
1. I deploy it on my VPS in a docker container.
2. reverse proxy with nginx
3. Install desktop client(2.5.2) ,on my win 10 PC.
4. login with the client, got stuck in the circle
### Client configuration
Client version:
2.5.2
Operating system:
Win 10
OS language:
Chinese
Installation path of client:
default path

### Server configuration
docker command
```shell
docker run --name nextcloud -d --network subnet --ip 172.18.0.101 --restart=always -v /app/nextcloud/:/var/www/html nextcloud
```
nginx configure
```nginx
server {
    server_name xxxx.xxx.xxx;
    location / {
         proxy_pass http://172.18.0.101:80;
         proxy_set_header Host $http_host;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
    }
    listen 80;
}
```
Nextcloud version:
Nextcloud 16.0.1
Storage backend (external storage):
disk
### Logs
1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):0.

**Comment by lieryan** [comment]
It looks like you have nginx set up as a reverse proxy? I find that the Android client is able to tolerate misconfigured reverse proxy but the desktop client is a bit more fickle about it being configured correctly.

You may need to change some of the settings in config/config.php to tell nextcloud about the reverse proxy. There are two ways you can configure a reverse proxy:

- trusted_proxies: you'll need to add nginx's IP address (as seen by nextcloud container) to this list, otherwise the nextcloud will not use the proxy headers set by that proxy (i.e. X-Forwarded-Proto, X-Real-Ip, Host)

- overwriteprotocol/overwritehost: this will tell nextcloud to completely ignore the proxy headers and always use the protocol/host that is statically specified in the config.php when generating urls

And another config I have also needed to change:

- trusted_domains

You'll need to add all the domain names that you want to access nextcloud from.

**Comment by ryanrain2016** [comment]
@lieryan Thanks for your help. I add `overwriteprotocol` and `overwritehost` to `config/config.php`, and it works fine now. Thanks again.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?

**Comment by ryanrain2016** [comment]
@mgallien I'm sorry, I have no environment to test the latest version, since I've changed my OS to Linux. After I added `overwriteprotocol` and `overwritehost` to `config.php`, It works fine all the time.
