### ISSUE TITLE
e2e Encryption + Desktop Sync buggy 

### ISSUE THREAD

**Issue by ad2003** [nextcloud/desktop#1333]
For some reason the e2e encryption is buggy with the desktop sync client. I know - it seems not 100% compatible with 16 release, but I want to use it. 

### Expected behaviour
All files should sync

### Actual behaviour
only one file at a time is synced. When for instance putting more than one file into the encrypted folder, the syncing gets stuck.

### Steps to reproduce
1. create encrypted folder
2. put in some random files
3. let it sync

### Client configuration
Client version:
  (build 20190319)

Operating system:
Win7
OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

**Comment by slsimic** [comment]
I have played just recently with my instance of Nextcloud 18 and activate E2E encryption module.
At first, it seemed that there is some issues with E2EE module since I have trouble syncing two desktops with client app and one phone with android app.
At the end it was clear to me that E2EE working just fine but desktop client app have trouble syncing when dealing with more than one file at the time. Upwards or downwards.
When I upload few files from Android app, everything goes OK and desktop clients stucked at the first file. Force sync again, second file gets synced, force - third...
I manage to reproduce this every time.
Tried both, Windows 2.6.3 and Linux 2.5.1 desktop-clients.

**Comment by bcutter** [comment]
Things have improved a lot meanwhile (new client versions and updated e2e encryption app running on nextcloud server v19.0.1).

BUT there still are sync and especially performance issues, see https://github.com/nextcloud/desktop/issues/2298   /   https://github.com/nextcloud/desktop/issues/2298#issuecomment-678814108

**Comment by csware** [comment]
Related to issue #2287

**Comment by camilasan** [comment]
Yes, performance it is a known issue.

Make sure that before you open an bug report:
- you are running the recommended version of the server and the desktop client - in the case of end to end encryption the client must be at least 3.0 and the server at least 19 with the end to end encryption app version at least 1.5.2 
- If you ever tried end-to-end encryption before version 3.0, follow the instructions from this post:
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590 - to clean up the keys as that can break the functioning of >3.0 if you had a malformed key.
-  if that doesn't work we need the logs because we don't know how to do magic here :) - please run the client with --logdebug
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files
