### ISSUE TITLE
NextCloud Desktop Client, always looks like it is syncing

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/desktop#1390]
Since a few versions now my Nextcloud Desktop client never stops too "Wait" for files. It always looks like it is in syncing mode and to make it actually sync new files I have to go in and manually "force sync". Unless I do this it just stays on waiting and looks like it is syncing. 

This happens both on my Windows 10 and my Ubuntu desktop.

![image](https://user-images.githubusercontent.com/5912371/63741569-ea69df00-c895-11e9-937e-6975f3ef0056.png)

**Comment by warnerbryce** [comment]
Try the 2.3.3 version and tell me if you still have this issue. https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.3.1-setup.exe

**Comment by TobiasDev** [comment]
Installing now and will try it out for tomorrow and see. :)

**Comment by misch7** [comment]
Did you also try the latest builds?

https://download.nextcloud.com/desktop/daily/

The old 2.3 versions use outdated OpenSSL libraries. This is especially a problem on Windows since the libraries are bundled with the client.

**Comment by soffigy** [comment]
Thank you warnerbryce, I made the mistake of updating from 2.3.3 to 2.6.0 and experienced numerous bugs. The worst was this issue of sitting there stuck using 27% CPU and not doing anything. Going back to 2.3.3 solved several issues!

* Loads of spurious sync errors, complaints of the server responding with the wrong error code, a few corrupted files which I had to delete off the server and replace from clients.
* pointless scanning of directories which I had deselected from syncing which contain thousands of small files that shouldn't be being synced or even looked at.
* The 'Activity' tab has lost its neat separation of items into the 3 tabs 'Server Activity' 'Sync Protocol' and 'Not Synced' instead everything is scrambled in together making it hard to find the problem.
* The 'Activity' tab now lists each item on 3 whole lines instead of 1 wasting masses of screen space and making me have to scroll much further through the list to find what's going on.
* The progress indication on the main Folder Sync list tab shows in white on a light grey background making it impossible to see what is going on.
* Old versions such as 2.3.3 are not findable on the web site download page making it impossible to go back to an older more stable version, I had to search on github to find it here.

v2.6.0 seems to be an extremely buggy beta quality client and ought not to have been released as a production version, as well as number of brain dead UX changes making it much harder to use.

**Comment by warnerbryce** [comment]
@soffigy for me v2.6.0 is working fine for all my clients and myself. 
But if you still suffer from such bugs even on 2.6.0, open a new topic on Github giving more informations about them. 
Feed the topic with your logs from the server / client, it will be really helpful for solving issue and made 2.6.1 a lot better for everyone.

**Comment by mgallien** [comment]
Can you please try with the latest version of the client ?
It has been much improved.
