### ISSUE TITLE
Nextcloud desktop does not handle u2f authentication well,

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/desktop#1391]
I tried different versions of the nextcloud desktop application every day, and having activated the double authentication via u2f key it works very well when I access via the web, but when I try to install account on nextcloud desktop app it is not recognized or managed well and I was forced to use backup codes to add accounts.

can you fix that?

**Comment by misch7** [comment]
We've recently implemented a new login method to fix such issues, using the standard browser.

Could you give it a try and get back to me with the result?

It will get into the next release but for now it's available only in our daily builds:
https://download.nextcloud.com/desktop/daily/

**Comment by tigernero79** [comment]
Then I tested the build:
"Nextcloud-2.5.3.5740-daily-20190828-Release.exe 2" and as you said, it opened me automatically in chrome where I then proceeded to enter credentials and then u2f authentication. All ok I'm happy though the authentication procedure in the window was nicer in my opinion and more appropriate for an application. but that's fine too and thanks

**Comment by misch7** [comment]
Very nice that it worked for you 👍 

I know what you mean but the new login flow has several advantages over the previous embedded browser approach.
There were lots of problems with the embedded browser since not all it's functions were accessible through the native Qt code. For example it wasn't possible to use SSL client certificates and also TLS 1.3 was not working, even when bundled with Qt 5.12.4 and OpenSSL 1.1.1c.

And even though it might feel strange to be pushed to your own browser, this also has more advantages. First you don't have to trust the browser in the window, you never enter your real credentials into the desktop client. (Might be not an issue with program downloads from trusted sources but it's nice to be more secure).
With the new browser flow there are no limits to more complex authentication systems anymore, especially interesting for organizations with large user base, SSO (Single Sign On).
You may also copy the authorization link to another device and open it there if you have trouble doing it on the same machine.

Since the issue seems to be solved, I'm closing it 😼

**Comment by tigernero79** [comment]
thanks :-)
