### ISSUE TITLE
TLS 1.3 (openssl 1.1.1) support for MacOS Desktop Client

### ISSUE THREAD

**Issue by Yzed** [nextcloud/desktop#1419]
For Windows TLS 1.3 is already avail now as part of:

https://github.com/nextcloud/desktop/issues/906

but the issue got closed before MacOS Desktop client TLS 1.3 is added. As we have also OSX users, thats a missing piece currently to enforce TLS 1.3 as min. version on the servers.

**Comment by misch7** [comment]
@Yzed You're absolutely right. That's on our list and we are going to apply this for the Mac build too.

Actually this implies to upgrade Qt and since we've had some issues due to the upgrade on Windows we're just taking extra care before applying the changes for Mac too.

So please stay tuned, upgrade for Mac is coming.

**Comment by Derridaralalala** [comment]
@misch7 this would be great! Waiting for it so long. Thank you.

**Comment by misch7** [comment]
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 and OpenSSL 1.1.1d on all platforms, so it features TLS 1.3 :-)

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

**Comment by Derridaralalala** [comment]
@misch7 Awesome! Thank you! Seems to work like a charm (checked with only TLS 1.3 enabled server side) so far; No errors. Sync work like always. No other strange behavior. 

(Built from Git revision 325dd8 on Oct 21 2019, 03:31:20 using Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019)
