### ISSUE TITLE
Ability to disable update check.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/desktop#1480]
### Expected behaviour

The client should have an option to disable its internal update check, as I do not wish to ping your server every time I start my machines. Additionally, the check is useless as I'm using a Debian-based system, so I'm going to update when the packages are available in the repositories, not sooner.

### Actual behaviour

There is no option.

### Client configuration
Client version: 2.5.2

Operating system: Ubuntu 16.04

Client package (From Nextcloud or distro) (Linux only): ppa.launchpad.net/nextcloud-devs/client/ubuntu

**Comment by bjhgov** [comment]
from the docs (autoupdate.rst)

Preventing Automatic Updates in Linux Environments
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Because the Linux client does not provide automatic updating functionality, there is no
need to remove the automatic-update check.  However, if you want to disable it edit your desktop
client configuration file, ``$HOME/.config/Nextcloud/nextcloud.cfg``.
Add this line to the [General] section::

    skipUpdateCheck=true

**Comment by RobertZenz** [comment]
Great, thank you.

Now there's still a button missing in the options dialog for that...and neither is this setting being written by default in the file (otherwise I would have found it when skimming the file).

**Comment by claell** [comment]
@RobertZenz since there was already an option, it might sense to update this issues' description and title to request a GUI option.

**Comment by claucambra** [comment]
We now have a GUI option + compile time parameters to disable the updater component
