### ISSUE TITLE
New login flow in 2.6.0 doesn't offer authentication via App-Token any more

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/desktop#1491]
### Expected behaviour
Version 2.3x and 2.5.x offered a login via App Token. I've preferred this because our AD-accounts need to change their passwords after 90 days and with an App Token there's no need to enter the new password within the Desktop Client. Furthermore using tokens I'm able to revoke specific tokens, e.g. after a notebook was stolen.

### Actual behaviour
Login to an cloud account is possible only with it's regular password.

### Steps to reproduce
1. Add new account
2. Select "Register" ("Anmelden" in german)
3. Enter URL
4. In the browser that opens select "Anmelden"
5. Login using UserID and Password works, UserID and App Token doesn't. 

### Client configuration
Client version: 2.6.0

Operating system: Win 10

OS language: german

Client package: From Nextcloud 

Installation path of client: default

### Server configuration

Nextcloud version: 16.0.3

**Comment by misch7** [comment]
Hey @Volker-K,

actually that's not true. We only changed the way, the app tokens are being acquired from the server.

Authorization is now completely left up to the server so you may implement any kind of login scenario you desire, like SSO.
The client doesn't even have to know your users passwords, everything is handled by the server with your standard browser.

We made the switch away from the embedded web-view component because it caused a lot of trouble and wasn't capable of client SSL certificates and TLS 1.3.

For technical details of the new Login Flow v2 please see:
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2
