### ISSUE TITLE
nextcloud desktop hang, while sharing a folder

### ISSUE THREAD

**Issue by rguenther-dz** [nextcloud/desktop#1505]
### Expected behaviour
with nextcloud desktop try to share a folder 

### Actual behaviour
nextcloud desktop hangs

### Steps to reproduce
from windows explorer
use context menu
-> share via nextcloud -> share options
klick plus sign after Link Teilen
the app hangs
![grafik](https://user-images.githubusercontent.com/56460325/66692733-82365780-eca1-11e9-9f5d-6be19799dcc9.png)

I think this happens only, when in nextcloud configuration the option is set to require passwords

### Client configuration
Client version: 2.6.0 stable

Operating system: windows 10

OS language: german

### Server configuration
![grafik](https://user-images.githubusercontent.com/56460325/66692832-8747d680-eca2-11e9-8a70-02f6cd4dd649.png)

Nextcloud version: 16.0.4

**Comment by highlightCH** [comment]
We can confirm the bug. https://help.nextcloud.com/t/nextcloud-client-2-6-0-link-teilen-share-freigabe/61975

**Comment by sagitariozod** [comment]
I confirm the problem, since version 2.5.3 to 2.7.0. Only when a password is mandatory to share a file in serve configuration.

> [OCC::AccessManager::createRequest 	4 "" "https://minube.albacoy.com/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json" has X-Request-ID "b6633279-afcd-4217-acbf-3d7d6e43738c"
[OCC::AbstractNetworkJob::start 	OCC::OcsShareJob created for "https://minube.albacoy.com" + "ocs/v2.php/apps/files_sharing/api/v1/shares" ""
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::ContentAccessDenied "El servidor respondió \"403 Forbidden\" a \"POST https://minube.albacoy.com/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json\"" QVariant(int, 403)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::ContentAccessDenied
[OCC::WebFlowCredentials::stillValid 	"Error transferring https://minube.albacoy.com/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json - server replied:  Forbidden"

**Comment by helmut72** [comment]
Same on macOS 10.15.2 with Nextcloud Desktop 2.6.2, because for security reason a password is mandatory.

I run everytime into an obvious bug of Nextcloud + Clients when doing just a bit more than basic stuff... :(

**Comment by mgallien** [comment]
Can you still reproduce the issue with the latest version ?
