### ISSUE TITLE
"Edit collaboratively" from the desktop client, in file manager and tray menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#1564]
Currently we have "Open in browser" in the right-click menu of a file. For specific files which enable collaborative editing we can change it to "Edit collaboratively".

- This can replace the "Open in browser" entry as it’s basically the same thing but better
- "Open in browser" should be called "Open online", just minor wording
- The entry should be called "Edit collaboratively"
- For odt/ods/odp documents, we need to check  on the server if Collabora Online is installed.
- For txt/md we need to check for Nextcloud Text on the server
- We shouldn’t expose the app name as this is not really relevant to regular people.
- It’s focused on Collabora Online, OnlyOffice and Text, and if there are multiple apps to edit with it should just pick 1 for simplicity.

Similarly we could do that for the activity stream in the **improved tray menu #877**: If a synced file is txt/md/odt/etc the action button could say "Edit" (better wording welcome, but we are short on space).

cc @camilasan @misch7 @DominiqueFuchs for Nextcloud 18, also ref @juliushaertl @karlitschek 

![right click menu](https://user-images.githubusercontent.com/925062/67633415-e23b1980-f8af-11e9-8bc0-f57bed0c0311.jpg)
(The mockup has a unified menu for right-click, that’s a separate discussion though so feel free to ignore that. ;)

**Comment by karlitschek** [comment]
Very cool!!!!

**Comment by jancborchardt** [comment]
For the right-click menu part of this, there actually is already a pull request open at https://github.com/nextcloud/desktop/pull/1442 :D

**Comment by jancborchardt** [comment]
This was fixed by https://github.com/nextcloud/desktop/pull/1735 and will be in 2.7! :)

**Comment by e-alfred** [comment]
How does the selection of an editor work if multiple options are available? Can the admin set a preferred editor or is there an "Open with" menu like in all major desktop and mobile operating systems available?

**Comment by jancborchardt** [comment]
I answered exactly this in the issue you opened: https://github.com/nextcloud/android/issues/5729#issuecomment-603153715

**Comment by e-alfred** [comment]
I am sorry, but I don' think this is completely answered except from a "simplicity by design" point of view.

Simplicity is fine for users who aren't computer literate and have problems with even the most simple tasks, **but** this simplicity is simply an abstraction from the end users perspective. Somebody has to make the decision which app is the right choice for the end user in this case. Given the vast majority of use cases out there, not every tool is the right choice for the task at hand. 

So who makes this choice? The developers by making a "one size fits it all"  solution or the  person that probably knows his organization best, the system administrator who is hopefully competent enough to run his installation in accordance to organizational needs laid out by the organization? As I said, even those operating systems and desktop environments that are considered "easy to use" all allow the user to select their preferred application utilizing an "Open with" menu.
