### ISSUE TITLE
outdated desktop app for Ubuntu 19.04

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/desktop#1581]
@ivaradi can you have a look at this?

### Expected behaviour
i expected to see a recent version of the Nextcloud Desktop app in Ubuntu

### Actual behaviour
When you install the desktop app through  "Ubuntu Software" there is an outdated version.
Version 2.5.1 is available instead of the most recent version 2.6

### Steps to reproduce
1. under Ubuntu 19.04 (Codename:	disco)
2. go to Ubuntu Software
3. see that the version is 2.5.1 an old version instead of a more recent one

![outdated-desktop-app-ubuntu19-04](https://user-images.githubusercontent.com/32508629/68148607-a3a30000-ff3c-11e9-9615-11862f534fc1.png)

**Comment by ivaradi** [comment]
@alexbijma This package is the one in the official Ubuntu distribution. On one hand it can be expected to be a bit old, since the official packages are often somewhat behind the cutting edge, and it is most apparent in case of a software, such as the Nextcloud client, that is being actively developed. On the other hand this is good news, because eventually the PPA will become unncecessary :)

Anyway, I cannot do anything about what is in Ubuntu officially. If you need a more recent version, please, use the PPA.

**Comment by alexbijma** [comment]
Hi @ivaradi sorry for the late reply;-) I just updated to ubuntu 19.10. Can you give me short explanation about how to deinstall the by the ubuntu software package installed version and install the ppa version? so i do it the correct way. i would like to keep the nextcloud data on my laptop during de-install and install

**Comment by ivaradi** [comment]
Hi @alexbijma to uninstall you can issue the command:

  ```sudo apt-get remove nextcloud-desktop libnextcloudsync0```

To add the PPA, please, follow the instructions on the PPA's page (e.g. 
https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client for the stable version), and then 
 
  ```sudo apt-get install nextcloud-client```

**Comment by claell** [comment]
@alexbijma did you manage to set up the PPA? Aftwards this can probably be closed.

**Comment by alexbijma** [comment]
@claell yes i did, meanwhile also updated to Ubuntu 20. With the PPA i have the newest version, at the moment V3.

**Comment by claell** [comment]
Nice, thanks for getting back and closing 😃
