### ISSUE TITLE
Desktop App does not reconnect after Server was offline

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/desktop#1609]
Longer offline periods are not unlikely for self-hosted Servers (due to DynDNS trouble, unreliable connection through private DSL lines, because the home admin thinker on the server HW, etc.) 

An annoying behavior of the Nextcloud Desktop App is, it does not reliably reconnect once the Server is back online after longer offline phase. Instead, the Desktop App symbol remains grey and does not become green anymore. The only ways to get it back working is either to close the Desktop App and start it again, or open the Desktop App and click “connect”. 

I have recognized this behaviour sometimes after longer offline phases (but never if the Server outages is only short). Eventually the Desktop App try to reconnect x times or over a period of x minutes, but then give up and never try again later on. 

It would be very desirable, if the Desktop App would reliably gets back working without manual interaction even after long Server outages.

**Comment by mcnesium** [comment]
A [try to reconnect] button next to the "Signed out from <server> as <username>" note would do as a workaround…

**Comment by buergi** [comment]
I severly suffer from this problem as well since some month. I constantly (multiple times a day) get connection failures resulting in a "red x" status of the client usually with the error message "An error occurred while opening a folder Network access is disabled." 

However, the problem happens to all accounts and all my NextCloud instance are on hosted servers, and always running, but I guess the problem occurs when resuming the notebook from hibernation or similar.
To reconnect I simply go into the network tab and change the proxy setting to "No proxy" and back to "System-proxy" (my network doesn't require a proxy) then all accounts reconnect perfectly and everything is "green-checkmark" again.

This problem ist present on all my devices (all Windows 10, 1909 and 20H2) and as noted above to both my NextCloud instances, so it is not an individual problem with one machine.

The problem is incredible annoying primarly because due to the long "offline" periods in which the client doesn't sync I constantly get synchronisation conflicts on my machines.

**Comment by NiklasRosenstein** [comment]
I've got the same issue that @buergi describes. Thanks for the No proxy/System proxy trick! Still quite an annoying issue. 🙃
