### ISSUE TITLE
No Update button on macOS

### ISSUE THREAD

**Issue by helmut72** [nextcloud/desktop#1620]
### Expected behaviour
Show an Update function, not just a message

### Actual behaviour
Only a message appear that an update is available in the "system-updatetool" (whatever this should be on macOS)

<img width="614" alt="Bildschirmfoto 2019-11-17 um 12 17 34" src="https://user-images.githubusercontent.com/1388751/69006860-c5858500-0935-11ea-9a82-5ffc209fd200.png">

There is **no**:
- Update in the App Store (of course)
- Update in Preferences / Software-Updates
- Update function the menu bar, because NC client doesn have a menu bar at all
- Update button in the NC desktop Preferences window

### Steps to reproduce
1. manually install 2.6.0 client
2. open Nextcloud Preferences
3. choose "General" tab
4. look at the message

### Client configuration
Client version:
2.6.0stable (build 20190927)

Operating system:
macOS 10.15.1

OS language:
german

**Comment by misch7** [comment]
This has been fixed with #1580 for all platforms and will get into the upcoming 2.6.2 release.

The confusing "system-updatetool" is actually a hard-coded fallback message.

Native update support is work in progress :)

Here is an example how it might look soon with #1651:

![gui-update](https://user-images.githubusercontent.com/48932272/70086644-10c8b480-1613-11ea-92d4-fbaaac32451e.png)

**Comment by helmut72** [comment]
No updates in the settings window, but got a notification with visible HTML!? Crazy... :)

<img width="1090" alt="Bildschirmfoto 2020-03-06 um 20 12 03" src="https://user-images.githubusercontent.com/1388751/76114955-831cac80-5fe7-11ea-83be-c11403e23b5d.png">

**Comment by misch7** [comment]
> No updates in the settings window, but got a notification with visible HTML!? Crazy... :)

Thanks for reporting - this must be because of the changed rollout cycle xD

Our servers got flooded by update requests (downloads) so we had to take measures.

Btw.: There's work in progress, see #1847 - you'll get a real button ;)

The updating functionality deserves some more attention, it had to step back for bug fixing and providing releases more regularly.
