### ISSUE TITLE
NextCloud client deletes files on server

### ISSUE THREAD

**Issue by Kassec** [nextcloud/desktop#1625]
Hello,

My nextcloud client deleted a list of files server side (but **kept them localy**). It's the second time it happens to us, first we thought about a user mistake, but now no more doubts.

There was no possible human mistake (I was sleeping at that time). No hacking either (client's IP address in audit log was my laptop).

### Expected behaviour
Client should not delete files randomly on the server.

### Actual behaviour
Client deletes files on the server without user interaction.

### Steps to reproduce
Unknown.

### Client configuration
Client version: 2.6.1-20191017.124538~bionic1

Operating system: Mint 19.2

OS language: English/French

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only): 2.6.1-20191017.124538~bionic1

Installation path of client:

### Server configuration
Nextcloud version: 16.0.3

Storage backend (external storage):

### Logs
Audit log:
{"reqId":"1wT9DPKIaMyQMdvkLV8Q","level":1,"time":"November 16, 2019 00:24:00","remoteAddr":"X","user":"X","app":"admin_audit","method":"DELETE","url":"\/remote.php\/dav\/files\/...","message":"File deleted: \"...","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.6.1git (Nextcloud)","version":"16.0.3.0"}

**Comment by 5a54a** [comment]
I can confirm this behaviour. 

Also had multiple deleted documents on November 18. When looking at the activities it seems one user is uploading a document and my Sync Client is almost immediately deleting this document (and afterwards also immediately restoring some but not all documents). 

Unfortunately no logs available any from November 18. I cannot exactly reproduce versions of NextCloud and Sync Client, because around this date I also upgraded NextCloud from v16 to 17.0.1 and Sync Client from 2.5.1 to 2.6.1.

**Comment by Kassec** [comment]
In my case, there was no other simultaneous request on the server. Just the client deciding to cascade delete something like 100 GB of data (80GB of which was not synchronized on the workstation).

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

There has been significant changes in the sync engine since this issue was opened.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
