### ISSUE TITLE
Pixelmator (PXM) Files synced as folders instead of files

### ISSUE THREAD

**Issue by adegans** [nextcloud/desktop#1640]
### Expected behaviour
Sync PXM files as files.
These are Pixelmator image files.

### Actual behaviour
macOS sync app - Uploads/treats PXM files as folders.
Web UI/Mobile app - Shows PXM files are browsable folders.

Recent activity may show a slew of internal items from the PXM file.
(This is how I noticed, investigating what these files were)

### Steps to reproduce
1. On macOS, sync any random PXM file from Pixelmator or Pixelmator Pro to NC.
2. Look in webUI/Mobile App and notice that all pxm files show up and can be browsed as folders.

Note: I suspect the PXM files are similar in structure as macOS App files.

### Client configuration
Client version:
Latest as of Nov 23 2019 for macOS, iOS and Android.

Operating system:
macOS Catalina, iOS 13

OS language:
English (US)

Installation path of client:
All defaults

### Server configuration
Mostly stock, with some non-relevant apps installed from market.

Nextcloud version:
17.0.3

Storage backend (external storage):
None
<img width="762" alt="macos" src="https://user-images.githubusercontent.com/9438487/69485931-b4e07d80-0e13-11ea-9540-bfd5615808ec.png">
![ios-filelist](https://user-images.githubusercontent.com/9438487/69485932-b4e07d80-0e13-11ea-9004-9887f923c0c1.png)
![pxm-contents](https://user-images.githubusercontent.com/9438487/69485933-b4e07d80-0e13-11ea-9050-606fa8f102ce.png)

### Logs
N/a

2. Web server error log:
N/a

3. Server logfile: nextcloud log (data/nextcloud.log):
N/a

**Comment by adegans** [comment]
For some context https://twitter.com/Arnandegans/status/1198180519449694208

**Comment by adegans** [comment]
Further information - PXD files (from regular Pixelmator) do seem to sync as files and as intended. So only PXM files from Pixelmator Pro are affected as far as I can see.

**Comment by jospoortvliet** [comment]
So the issue is that Mac OS X treats certain folders as 'files', if they have certain - well, either metadata, or a specific file in them. They ARE folders, and thus synced as such as that's the only way to treat them if you have to show them on Linux or Windows or Android or, well, any platform that isn't OS X.

What I'm missing from this bug report is what behavior you would expect. Are the folders not fully or properly synced? If you are on another Mac OS X system, do they 'work', are they acting like 'files' again? It seems, from your description, that they are treated as you'd expect on mobile, Windows and Linux (a folder yes, they are folders after all).

What would you want those to do? Android, Windows and Linux don't have the Mac OS X feature to treat a folder as a file, so we can't fix how they show up in their file managers. We could, I suppose, create a special case in our web UI and mobile apps at least, that treats these not as folders but as files (though I can imagine the bug reports you get when you treat something as something it isn't). And we could hide the activities that happen inside them, just say "this file changed" each time. But that's a work-around for an app doing something very weird, creating a folder and then treating it as a file. I'd rather have this be fixed by Pixelmator - just zip the folder, with 0 compression for example, if you really want to have a bunch of files in one place.

Or are there dozens of applications, well known and often used and cross-platform ones I mean - like Adobe apps?

If it is just weird behavior of this single app that isn't available on Windows or Linux, I'd rate this "very low priority".

**Comment by adegans** [comment]
To every mac user they're files.
In windows they also show up as non-folders if I remember correctly.
Dropbox, iCloud and Google drive sync them as files.

For all intents and purposes they are files, even though technically they maybe are not.
So obviously, the expectation is that nextcloud does this also.

**Comment by adegans** [comment]
Any update on this?
Is NC going to support Mac users properly by supporting this kind of file.
Or is NC going to ignore it and only support Windows going forward?

**Comment by FlexW** [comment]
@adegans Can you tell us what the issue here is? As I understand they are synced correctly. I'm not sure what we can do here.

**Comment by adegans** [comment]
@FlexW As explained/indicated above - Nextcloud syncs Pixelmator Pro files as folders. This means that once they're synced and I want to download one of those files from the webinterface I can not.
Not to mention the confusion it causes when browsing files on a mobile device. Or when a non-mac user looks at these things.

The fix obviously would be that Nextcloud gets support for this kind of file so that it works as expected.

**Comment by FlexW** [comment]
What is the problem if you want to download these files/directories? What does not work?

I think what you wish is not possible. We can't sync a directory as file. What we can do and what macOS finder is doing, is to display such a directory as a file. But the desktop client is not involved there. If you want that these directories are displayed as files in the webui, you should write an issue there. But I think it's very unlikely someone will implement that or even wants that. The same goes for android. On Windows for example it will never be possible to display these directories as a file, because files are usually displayed through the windows explorer and we can not influence how the windows explorer displays files or directories.

**Comment by adegans** [comment]
@FlexW You're wrong there, as far as I can tell Windows shows PXM and similar files as files. Not as folders. Though I Don't have or use Windows, so I'm not sure on current affairs with that.

That's besides the point and issue though. I don't care how Windows handles these files. I care how macOS and Nextcloud does things.
But if it's too much hassle to cater to macOS users and try to make NC better and more useful, then don't bother. I mean, it's only compatibility with a broader audience right? 🙄 You know, capture more of the market? More revenue/customers/users perhaps? Not important at all...

This whole mindset of "oh its a fringe case thats impossible and nobody wants that" pisses me off every time I contact someone from Nextcloud of whoever responds to it.
It's NOT impossible (Dropbox and Google Drive knows how to sync these things properly) and EVERY mac user would want this as files like this are a common occurrence. 

But I guess that's too hard to understand. 🤬 So nevermind, yet again. And YET ANOTHER reason to not recommend Nextcloud to anyone I know.

**Comment by FlexW** [comment]
@adegans Sorry, but I still do not understand what functionality is not working and how Dropbox oder Google Drive do better in this specific case. I collected some screenshots:

Here you can see that these pxm files are in fact directories even on macOS (screenshot was taken on a mac)
![Screenshot 2021-06-15 at 09 44 26](https://user-images.githubusercontent.com/19961516/122015038-09659800-cdc0-11eb-8c60-55a5326277db.png)

Dropbox displays these pxm directories as ordinary directories
![Screenshot 2021-06-15 at 09 45 11](https://user-images.githubusercontent.com/19961516/122015137-1e422b80-cdc0-11eb-8040-50f8fb04185f.png)

Windows explorer also displays them as ordinary directories
![image](https://user-images.githubusercontent.com/19961516/122024820-12a73280-cdc9-11eb-880c-e32012836ed4.png)

Google Drive also displays them as directories
![Screenshot 2021-06-15 at 11 03 11](https://user-images.githubusercontent.com/19961516/122025086-5732ce00-cdc9-11eb-9b58-3a774f89fa2d.png)


and this is how Nextcloud displays the pxm directories
![Screenshot 2021-06-15 at 09 53 47](https://user-images.githubusercontent.com/19961516/122015206-2ef2a180-cdc0-11eb-9c05-bf0aa1bfd104.png)

Which looks very similar to the above.

We can't sync directories as files. Thats not possible. The only thing that could be done is displaying the pxm directories in a special way in the webui. If you want that you can file an issue on the server. The desktop client can't do that. If you are not happy with how fast and what features are added, then keep in mind that Nextcloud is Free software. That means that you can at every time grab the code yourself and implement functionality on your own.
