### ISSUE TITLE
Running Nextcloud client prevents pinned folders from opening

### ISSUE THREAD

**Issue by goddib** [nextcloud/desktop#1679]
### Expected behaviour
Hi everyone, I'm running Nextcloud Desktop on Windows 10 and I am experiencing an unfortunate interfierence with Windows functionality.

I have pinned several folders to my task bar which act as quick open links. These work flawless when Nextcloud is not running

### Actual behaviour
The pinned folders in the task bar do not open when clicked while Nextcloud is running.

### Steps to reproduce
1. Open folder in Windows
2. Right-click folder in task-bar and select "pin"
3. Close folder
4. Right-click folder in task bar
5. Select Entry in pop up menu

### Client configuration
Client version:
2.6.2rc1-Win64 (build 20191209) 

Operating system:
Windows 10

OS language:
German

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs
There is no issue with the Nextcloud App itself, thus no logs.

**Comment by ralf-f** [comment]
This is exactly the behaviour I experience since client Version 2.6.1stable-Win64 (build 20191105) on all my Win 10 Systems too.
Closing the nextCloud client immediately causes the described quick open links to work again.
Must have something to do with the nextCloud client's Windows Explorer integration feature.

**Comment by ralf-f** [comment]
Sorry, just discovered: same as #1599

**Comment by goddib** [comment]
Thanks for pointing that out! I searched for it but didn't find it. Let's continue over there.
