### ISSUE TITLE
Feature Request: Files on-demand Desktop client

### ISSUE THREAD

**Issue by service-paradis** [nextcloud/desktop#17]
Google just launched [Drive File Stream](https://gsuiteupdates.googleblog.com/2017/09/drive-file-stream-from-google.html).

It would be nice to enhance Nextcloud desktop client to access files on demand.

**Comment by service-paradis** [comment]
https://github.com/owncloud/client/issues/4341

**Comment by pieter-groeneweg** [comment]
I would like to see this reopened.
1. The link is to owncloud client, not nextcloud client.
2. This feature would sure make things easier on small windows devices like 2in1s..

**Comment by withhawaii** [comment]
+1

**Comment by alexknobbe** [comment]
+1

**Comment by thiesschneider** [comment]
+1

**Comment by AndrewBucklin** [comment]
DropBox also has this now with "[selective sync](https://www.dropbox.com/help/syncing-uploads/selective-sync-overview)". 

ExpanDrive [just released](http://www.expandrive.com/expandrive-6-the-fastest-most-powerful-expandrive-ever/) this feature in their product (they call it “offline-sync mode”).

ODrive has had this feature for a while (they call it "[progressive sync](http://blog.odrive.com/blog/2014/11/10/what-is-progressive-sync)").

I’d be over the moon if it came to Nextcloud. I'd even offer [some bounty](https://www.bountysource.com/issues/44909892-smart-sync) for this feature request; anyone else with me?

**Comment by michaelstingl** [comment]
Upstream project is experimenting with this in the [2.5.0 alpha1](https://owncloud.org/news/owncloud-client-goes-virtual-sync-files-demand/). Please help testing and provide feedback.

Main thread is here: https://github.com/nextcloud/desktop/issues/184

**Comment by egeu5** [comment]
Awesome, I'll test it immidiatly :-)

**Comment by jospoortvliet** [comment]
(closed, let's discuss in one place: #184 )

**Comment by fuzzy76** [comment]
But #184 is about selecting which files to sync. I interpreted this issue as on-demand sync without having to select (VFS style)?

**Comment by Trackhe** [comment]
+1

**Comment by jospoortvliet** [comment]
@fuzzy76 yes - we want to have multiple policies as well as manual override. So, for example:
"sync the 5GB most frequently used files"
"sync the last 1000 used files"
and "sync this file" ;-)

**Comment by fuzzy76** [comment]
That is not "on demand". On demand is syncing when a file is accessed, not before.

**Comment by pieter-groeneweg** [comment]
"sync this file" as in see the file in your explorer but only sync/download when opened on device?

**Comment by fuzzy76** [comment]
Yes, that's what "on demand" generally means. And that's what atleast both iCloud Drive and OneDrive presently does by default. I know Dropbox also has that feature, but I think it was premium last time I checked - but that is atleast a year or two ago.

**Comment by jospoortvliet** [comment]
@fuzzy76 if you want to sync a file only when accessed, then edit, save, and have it disappear again, just use webDAV to mount Nextcloud... If you want to keep it cached (and regularly synced) then, that's what the drive will do. It can't figure out what to download after you first set up the account, anyway. So the drive will probably do things the same way as iCloud and OneDrive, how else is the drive going to predict what files you want (unless it is "all"). The question is when to remove files. Example:
* You have 2TB of files. By default, the client is set to keep at most 500 mb of files. When you set up the account, nothing is synced. When you click a file, it gets synced and kept. When you hit 500 mb of locally available files, the least-recently-used files get removed from the cache until you are under 500 mb again

And instead of 500 mb as limit, we could also set "3 weeks" or "100 files" (hum, not sure if that makes sense). But that's about removing files, not deciding what to sync.

Maybe at some point we can tell the client to sync files set as favorite or something...

**Comment by fuzzy76** [comment]
That is exactly what this issue is about, which files to download, and which files to just show without having the content ready.

**Comment by jospoortvliet** [comment]
Yes, and as I say, that's what the drive will do. So what is the problem?

**Comment by fuzzy76** [comment]
Which drive are you talking about? The Nextcloud Desktop Sync client does not do this. And that is the software this issue is about.
