### ISSUE TITLE
Error "Could not read system exclude file"

### ISSUE THREAD

**Issue by jeronimofagundes** [nextcloud/desktop#172]
Hi, just installed Nextcloud-TECH-PREVIEW-E2E-x86_64.AppImage. 
The sync fails with error "Could not read system exclude file". 
System: 
$ uname -a
Linux jeronimofagundes 4.13.0-31-generic #34-Ubuntu SMP Fri Jan 19 16:34:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Let me know how I can help you debug this.

**Comment by amanusk** [comment]
Having a similar issue

**Comment by neutrno** [comment]
I too have the same issue

**Comment by camilasan** [comment]
We should have a new tech preview soon.
cc @rullzer

**Comment by riprop** [comment]
same issue 
Linux dl 4.13.0-21-generic

**Comment by camilasan** [comment]
We didn't experienced this problem with the merge in master. 
cc @tcanabrava @dantti

**Comment by dantti** [comment]
Have you marked any folders as Encrypted?

**Comment by tcanabrava** [comment]
This is not related to end-to-end-encryption.

**Comment by GustavoMarcante** [comment]
Hi!
I got the same error.

As I understood, there is a file, called "system exclude file", where Nextcloud stores the list of the files that are not synchronized. In my Ubuntu installation, this file is */etc/Nextcloud/sync-exclude.lst*.
This error came to me because this file was missing (probably I deleted it by mistake when I was fully uninstalling Nextcloud).

As I have Nextcloud client in other machine, *I copied it again... and the error was solved!*

It is possible also to create this file using:
```sudo gedit /etc/Nextcloud/sync-exclude.lst```
And copying and pasting the following content:
```
*~
~$*
.~lock.*
~*.tmp
]*.~*
]Icon\r*
].DS_Store
].ds_store
._*
]Thumbs.db
desktop.ini
System Volume Information

.*.sw?
.*.*sw?

].TemporaryItems
].Trashes
].DocumentRevisions-V100
].Trash-*
.fseventd
.apdisk

.htaccess
.directory

*.part
*.filepart
*.crdownload

*.kate-swp
*.gnucash.tmp-*

.synkron.*
.sync.ffs_db
.symform
.symform-store
.fuse_hidden*
*.unison
.nfs*

My Saved Places.
```
To ensure owner and permissions as they are in my "working" install, I also did:
```
sudo chown root:root /etc/Nextcloud/sync-exclude.lst
sudo chmod 644 /etc/Nextcloud/sync-exclude.lst
```

Maybe this can be checked by the application to avoid this error.

**Comment by rootbsd** [comment]
If you use the e2e client the exact path is: /etc/Nextcloud-e2e/sync-exclude.lst

P.

**Comment by camilasan** [comment]
This is fixed in the current builds available at https://download.nextcloud.com/desktop/daily/.

**Comment by javl** [comment]
Quick question: I apt-get purged the nextcloud desktop client and reinstalled it (version 2.3.3-20171224.060956~zesty1 in Debian) and I got the same error of ```sync-exclude.lst``` missing. I copied it beforehand before I already had this problem before so I just put it back, but shouldn't this have been fixed, as per @camilasan comment? It seems to me this is a file that should be created automatically when installing the client, or is there something I'm missing?
