### ISSUE TITLE
Move client internal files with their own .nextcloud folder instead of /

### ISSUE THREAD

**Issue by laodc** [nextcloud/desktop#173]
As someone who has hidden files shown on my system, having all the app hidden files in the root folder is rather messy, especially when syncing.

Can these files be moved to their own hidden folder instead? This keeps things much more organized.

**Comment by DominiqueFuchs** [comment]
@laodc Just to clarify this, when talking about _all the hidden files_ we are talking about three the db files? or are there more that don't appear on my test side?

**Comment by rugk** [comment]
There are also these strange log files: `.owncloudsync.log` and `.owncloudsync.log.1`. IMHO, these should be moved into the appropriate locations, too.

Remember that as for Linux desktops [XDG has some standards on this](https://0x46.net/thoughts/2019/02/01/dotfile-madness/) and where to put each file according to some env variables. :smile:

**Comment by DominiqueFuchs** [comment]
Thanks for the input, @rugk - guess I’ll look into this within the next days and sort a few things 👍🏻

**Comment by laodc** [comment]
as @rugk mentioned, when files are syncing additional hidden files are created making the home folder rather cluttered. having a home for all these files will make it a lot cleaner (and less chances of accidentally being deleted by a user)

**Comment by DominiqueFuchs** [comment]
@rugk and @laodc The logfile (the general one, that you mentioned as .owncloudsync.log) has already moved (and been approp. renamed) since the middle of last year, this is why I wondered:
[see this commit](https://github.com/nextcloud/desktop/commit/faf64958ec1f74c3842aa1f37716231057902077#diff-dc7eb0a55af6dd21f848f0f6f0650fd9)

The log location is an appropriate folder depending on the platform. On linux:
`~/.local/share/Nextcloud`

However, I'll still take a look in the runtime files for the database

**Comment by laodc** [comment]
Well, I lodged this issue back in Feb 2018...

**Comment by DominiqueFuchs** [comment]
No offense, was just referring to the owncloudsync.log comment and wrongly assumed this was an right-now-observation

**Comment by rugk** [comment]
Yes it was a current observation. 😄 

> has already moved (and been approp. renamed

Then I guess the old file has not been deleted then or so. I'll check the date or so.

**Comment by DominiqueFuchs** [comment]
Merged #1451 🚀
