### ISSUE TITLE
macOS client uses keychain for server login credentials. Data automatically passed along to apple servers

### ISSUE THREAD

**Issue by Oclair** [nextcloud/desktop#1732]
Nextcloud Desktop Client on macOS is using the macOS keychain to store server, login user name, and passwords which by default macOS settings are uploaded to apple servers. (if the user has setup their icloud account and affiliated it with the os.)

**This is outright NOT best practice**

### Expected behaviour
Server url, user login, password data should NOT ever be passed along to Apple without the user's express authorization.  Data privacy responsibilities for EU users on macOS cannot be passed along to Apple.

### Actual behaviour
Nextcloud Desktop Client on macOS uses Keychain and Apple servers receive Nextcloud server, login credentials and passwords by default.

### Steps to reproduce
1. Install mac os, or system preferences, or system or app updates an Apple ID is required, Apple by default automatically turns on iCloud, all keychain passwords are uploaded to apple servers.
2. install nextcloud desktop client on mac os and configure sync with nextcloud server
3. your nextcloud data is synced with apple

### Client configuration
Client version:
Version 2.6.2stable (build 20191224)

Operating system:
macOS 10.15.2

OS language:
English

Installation path of client:
/Applications/nextcloud.app

### Server configuration
Not applicable

### Logs
mac OS client using keychain is not being disputed?

**Comment by janvlug** [comment]
I propose to add the "security" label to this issue.

**Comment by SimJoSt** [comment]
In https://github.com/nextcloud/desktop/issues/2768#issuecomment-751298370 a rough answer was given. If this issue is important to you, please supply more information and reasoning for this request, so it can be discusses if this is actually a security issue.

**Comment by Oclair** [comment]
You have it backwards @SimJoSt first discuss then use keychain not the otherway around.  Users were not notified Apple was getting their login, password and url for their nextcloud account.  Get a lawyer

**Comment by SimJoSt** [comment]
@Oclair development on Nextcloud software is mostly run by volunteers who donate their free time, so I urge you to take more care in your requests and issues. So threatening with lawyers or suggesting there will be a legal consequences, is a serious issue.

Apparently you are assuming everybody already knows what the issue is and no additional information is needed. This clearly isn't the case as multiple people have asked for feedback in various places (other issue and forum).  
I understand you consider the current state of storing credentials on macOS a privacy or security issue. Please elaborate on that and substantiate your reasoning.  
I also understand that you are disappointed that you didn't know the macOS keychain was used to store credentials. I assume the developers were following the best practices and wanted to use a proven and reliable system and avoid overhead and possible points of failure.  
If you have any information, that they macOS keychain is not secure, especially when used with Apples iCloud, please share your resources and bring this issue to the communities attention.

If you don't supply more information to outline the issue you have and supply background information and maybe even recommendations on how to proceed, I will close the issue until a time you do so.

**Comment by Oclair** [comment]
@SimJoSt 
>  So threatening with lawyers or suggesting there will be a legal consequences, is a serious issue.
There are legal issues informed consent to share user data (GDPR, EU/US data sharing).  Taking liberties with other's rights is your organization/company's legal issue, Nextcloud fancies it's self as an open source project.  Is using the Apple Keychain on the Roadmap?

**Comment by SimJoSt** [comment]
@Oclair I am not affiliated with the Nextcloud company nor am i making decisions. I sometimes supply bug reports, feature suggestions and fixes for the documentation.  
If you want to do the same here or start an open discussion, you are free to do so. But please be considered of people trying to help you or are not affiliated with the cause of the problem. You can always ask for more information on this issue in the forum or contact the Nextcloud corporation.

For now you have just have had vague complaints. I am still not sure what you are trying to achieve.  
Maybe a notice on macOS clients where the credentials are stored or a different storage system all together?  
Until you have elaborated on this, I will close the request.

**Comment by Oclair** [comment]
> For now you have just have had vague complaints.
that's inaccurate

**Comment by SimJoSt** [comment]
Than please properly correct me and explain the problem in detail and add what you propose should be changed.

**Comment by jospoortvliet** [comment]
The Nextcloud clients preferably use the operating systems' facilities for credentials management. This is what the vast majority of users expects, and it guarantees a reliable service. If the user has authorized Apple to sync credentials to the Apple servers, that will include the Nextcloud credentials, just like those of all other apps. If you do not trust Apple with your credentials, I suggest either not using their cloud services or installing a more privacy-friendly operating system.

**Comment by rullzer** [comment]
Your keychain is encrypted before it is synced to your iCloud.

https://developer.apple.com/documentation/security/keychain_services
https://hackmag.com/uncategorized/in-the-depths-of-icloud-keychain/

So I would be very much interested in what information you have that this is insecure.
Note that KeyChain is one of the only mechanisms we can use to securely store the data on macOS. As otherwise any other program could read the user/pass/server.
