### ISSUE TITLE
"Please use system's update tool" message doesn't make sense on macOS

### ISSUE THREAD

**Issue by scheinercc** [nextcloud/desktop#1766]
### Expected behaviour
I'd expect to see an "Update" button there which would download and install the latest version of the client.

### Actual behaviour
I see a message referring to "the system's update tool", without further exlpanation. I suspect in the case of macOS that would be the App Store, but as I haven't downloaded it from there - I don't even think that is possible - trying it wouldn't make any sense to me.*
<img width="817" alt="image" src="https://user-images.githubusercontent.com/817856/73587575-df387080-4511-11ea-977a-5af9b1a9a687.png">

### Steps to reproduce
1. Click on the NC client icon in the macOS toolbar
2. go to _Settings_
3. go to _General_
4. check out _Updates_

### Client configuration
Client version:

This is not for the latest version 2.6.2, but for 2.6.0, though the message was always there (likely to be there in 2.6.2 as well), I just never came around to file this ticket.

Operating system: macOS 10.14

OS language: English

*I tried anyway and just found this:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/817856/73587663-cd0b0200-4512-11ea-99d1-3b3542ee4ff2.png">

**Comment by mddvul22** [comment]
I don't understand your screenshot.  I have the same issue, though.  I solved it, by just downloading a new version and installing it over the top of my previous version.

**Comment by scheinercc** [comment]
> I don't understand your screenshot.

Which one? The first one shows part of the NC desktop app, the second one shows the Apple app store.

**Comment by mddvul22** [comment]
Sorry, it was the second image.  I wasn't sure what that screenshot is showing you.  Thanks for the clarification.

**Comment by gfairchild** [comment]
I experienced this same issue (same version and everything). It's not clear at all how to update automatically.

**Comment by mburnicki** [comment]
I **_think_** this depends on the operating system. If you run Windows, you can just download a precompiled executable program from some website to upgrade your client. So a hint makes sense because you can easily install the update.

If you run Linux and similar systems, unless you build the program yourself from source, or run a compatible AppImage or similar, you have to wait until the new version is provided by the package management team maintaining your distribution, and the new version will be installed by the package management software once an update package is available.

So for these systems it doesn't make much sense, IMO, to ask the user to update. He can't, but it will be done automatically if a new version is available for his distribution, and online updates for the operating system are being used.

I'm assuming the latter also applies to MacOS.

**Comment by scheinercc** [comment]
So far the only way I found for macOS is, as already mentioned by @mddvul22 further up, to go to the download page and do it manually. It would just be good if the text would be adjusted to the OS, ideally at least with a link, if that's what it is.

**Comment by RogoTe** [comment]
+1
Can confirm this issue meaning that I also got confused by this message.

**Comment by scheinercc** [comment]
Found this update message with link today
<img width="728" alt="image" src="https://user-images.githubusercontent.com/817856/74650496-fba50000-51d5-11ea-80d0-387218c0d6fd.png">

linking to: https://nextcloud.com/install/?pk_campaign=clientupdate#install-clients

closing this ticket.
