### ISSUE TITLE
Unable to Upgrade Nextcloud Client on Windows: "error open file for writing"

### ISSUE THREAD

**Issue by Mebus** [nextcloud/desktop#1781]
Hallo,

due to the attached error message I am unable to Upgrade the Nextcloud Client to Version 2.6.2 on Windows 10. Please refer to this screenshot:

![nextcloudfail](https://user-images.githubusercontent.com/271557/74429333-09b3f300-4e5b-11ea-81f5-18e29e03aef0.PNG)

Kind Regards

Mebus

**Comment by misch7** [comment]
Hey @Mebus, this happens when the shell extension DLL libraries are still registered in the Windows Registry. Normally they should have been unregistered by the (un)installer but sometimes this doesn't work properly.

These libraries are used for the Explorer overlay icons and the right-click integration.

Did you try to restart the system and re-run the installation?

**Comment by Mebus** [comment]
Probably the problem was that I was trying to install Version 2.6.2  over Version 2.6.2  :-P

Mebus

**Comment by misch7** [comment]
Haha^^ Nice idea but even this shouldn't be a problem for the then re-installer ;)

So I guess you managed to install your desired version in the meantime and we can close the issue? ;p

**Comment by AlexanderKgr** [comment]
![image](https://user-images.githubusercontent.com/25532758/76059863-94829c00-5f88-11ea-948b-7e55a99d2b4c.png)
i have the same issue with updating to 2.6.4.
uninstalled it an then couldn't remove some files. tried to install again and the same error occured

**Comment by misch7** [comment]
> i have the same issue with updating to 2.6.4.
> uninstalled it an then couldn't remove some files. tried to install again and the same error occured

@AlexanderKgr 
Did you try to reboot your machine and then install 2.6.4 again?
