### ISSUE TITLE
No daily updates for MacOS for a long time

### ISSUE THREAD

**Issue by Babene03** [nextcloud/desktop#1788]
Hi, why are there no more daily updates for MacOS? **The last one was on "2020-01-19".**

Is there so much renovation that this has been paused, or is there a mistake?

**Comment by misch7** [comment]
Hey @Babene03, thanks for your interest in the daily builds and pointing out to this.

Since we merged the new QML code for the 2.7 UI we had some issues with the build scripts on macOS. This is why the daily build uploads have been paused in favor of publishing 2.7 Beta 1 and the 2.6.3 release.

I'll leave this open here to notify once we've finished the new build chain for macOS.

**Comment by Babene03** [comment]
Ok thank you in advance for the information, since the beta still causes problems, see my other post (https://github.com/nextcloud/desktop/issues/1742) and 2.6.1 with HTTP / 2 sync has problems I currently use the daily version on all productive systems (so that it runs largely stable).

**Comment by er-vin** [comment]
Mac daily builds have been back for a while now, I'm closing this one.
