### ISSUE TITLE
linux version crashes with too many open files, 2.6.4

### ISSUE THREAD

**Issue by dkebler** [nextcloud/desktop#1876]
### Expected behaviour
not crash

### Actual behaviour
after some time the client exits

### Steps to reproduce
1. launch client via command line, or background
2. wait

Get too many files open error.

The too many files open error kinda fits with the issue.  Works for awhile until too many files are open then crashes.  What files?  why are they getting opened and not being closed.

### Client configuration
Client version: 2.6.4

```
nextcloud --version
qt5ct: using qt5ct plugin
Nextcloud version 2.6.4git
Using Qt 5.9.5, built against Qt 5.9.5
Using 'OpenSSL 1.1.1  11 Sep 2018'
```

Operating system: linux

OS language: ubuntu bionic

Qt version used by client package (Linux only, see also Settings dialog):
see above

Client package (From Nextcloud or distro) (Linux only):
distro bionic

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Nextcloud version: 17.0.2

Storage backend (external storage):
// local storage on same machine as nextcloud webapp

### Logs

```
...
(nextcloud:16504): GLib-GIO-CRITICAL **: 02:27:52.268: g_menu_insert_item: assertion 'G_IS_MENU (menu)' failed

(nextcloud:16504): GLib-ERROR **: 02:34:10.533: Creating pipes for GWakeup: Too many open files

Trace/breakpoint trap (core dumped)
```

**Comment by bleidingGOE** [comment]
seems related to #1035 ?

**Comment by claell** [comment]
Looks like a duplicate of #1769, can you check @dkebler and close this if appropriate?

**Comment by sh2515** [comment]
I have the same issue
Nextcloud goes through the files and checks for the ones that need syncing, then starts with errors stating that "too many files open" and stops syncing

I tried changing
```/etc/systemd/user.conf
DefaultLimitNOFILE=99999```
```/etc/security/limits.conf
*       soft    nofile  99999
*       hard    nofile  99999```

But this did not work for me

Any help would be great.  

I sorry I can't be more specific as to what has changed as it works on an older laptop running Ubuntu 18.04 so I am unsure at which point the app stopped working on the syncing for large volumes of files.  Also I am unsure if this is server side or client side that is affectting this syncing .

**Comment by sh2515** [comment]
I have the nextcloud desktop app log and want to share it if it helps, however it is 10's of thousands of lines long and want to:
1) only get the pertinent lines uploaded
2) not have my personal info uploaded e.g. website, file names etc

Can someone help me get the right info please? I have searched for the error message in the app but that isn't on the log file. Is there any key words i should be searching for?

**Comment by Zoarial94** [comment]
I have been having troubles with the Linux Nextcloud client and I came across a solution that works for me. 

TLRD - Removing any encryption and disabling the default encryption module fixed my Linux client.

Fedora 30
Nextcloud Client: 
```
Nextcloud version 2.6.4git
Git revision b45f5fd1a947dc21eb11c69049a99616a2ec950e
Using Qt 5.12.5, built against Qt 5.12.5
Using 'OpenSSL 1.1.1g FIPS  21 Apr 2020'
``` 
AND
```
Nextcloud version 2.7.0daily (build 20200629)
Git revision 6ec5f9ea1041196b99a90856a2055353264d4883
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1g  21 Apr 2020'
Running on Fedora 30 (Thirty), x86_64
```
Nextcloud Server Version: 19
E2E Version: 1.5.1

I would get errors like #1035 and the client would sometimes crash while trying to download a large amount of photos (~30-40GB). I tried re-adding the sync folder and re-adding my account, but neither worked. I figured the linux open file limit and I started monitoring how many file were opened. I used `cd /proc/$(pidof nextcloud)/fd` and `watch -n 0.5 'ls -l | wc -l'` to list the number of files continuously. The client would (sometimes) crash after 1024 open files. After upping the limit with `ulimit -n 262144` the problem seemed to stop for a short time. The client opened ~2000 file and stopped to download files. After some time, the client opened more files reaching +3000 and crashed again. I repeated this a couple times with no avail.

A couple days later I was looking into https://github.com/nextcloud/server/issues/21578 and I decided to just remove encryption as I had no real reason for it. This fixed any problems I had with the client and I've had no issues since last night. 

I have also had problems with the new iOS client (3.0.0.76) and E2E. I'm not sure if it changed with Nextcloud 19 or with the new iOS update. I would rather not deal with any more E2E for the time being.

**Comment by Zoarial94** [comment]
I should note, the photos were not in an E2E folder.

**Comment by sh2515** [comment]
I have added
50000 to the no file limit in 
/etc/security/limits.conf
/etc/systemd/user.conf
/etc/systemd/system.conf

the nextcloud app searches the files now but crashes when it is time to sync.

**Comment by dkebler** [comment]
I haven't had this issue since 2.6.5.  Also 3.0 is out now although not via the ubuntu ppa so when I try it this will continue to be the case.  So closing this as fixed.
