### ISSUE TITLE
Linux client crashes on "Grant access"

### ISSUE THREAD

**Issue by valpo** [nextcloud/desktop#1878]
### Expected behaviour
Grant access after login and open the settings window

### Actual behaviour
Click on Grant access after successfull login crashes the client

### Steps to reproduce
1. start nextcloud client
2. login into nextcloud (either with credentials or with app token, does not matter)
3. click on Grant access

### Client configuration
Client version: 2.6.4git

Operating system: Ubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.9.5

Client package (From Nextcloud or distro) (Linux only): //ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client:
/usr/bin/nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
log file ends with: 
[OCC::AccountManager::saveAccount 	Saved account settings, status: QSettings::Status(NoError)
[OCC::AccountState::slotCredentialsAsked 	Credentials asked for "https://kooperation.seim-partner.de/owncloud" are they ready? true
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::AccountState::slotCredentialsAsked 	Credentials asked for "https://kooperation.seim-partner.de/owncloud" are they ready? true
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[unknown 	QCoreApplication::postEvent: Unexpected null receiver

gdb says:
Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
0x00007ffff03afa54 in QtWebEngineCore::WebContentsAdapter::stopFinding() () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5

**Comment by pkeroulas** [comment]
Finally, I just removed the account, re-created it using same local folder, and everything is back to normal. I thought the problem could be the local .db file, but apparently not.

**Comment by PavlosIsaris** [comment]
@pkeroulas How did you removed the account?

**Comment by pkeroulas** [comment]
@PavlosIsaris , using the desktop graphical client:
Click on Tray Icon > Settings... > Account > Remove

**Comment by wayneoutthere** [comment]
I had the same issue. 
The issue started when I changed the password in the GUI for my user.
I cannot open Nextcloud-client at all now because after i click "Grant Access' the app stops there so I can't even get to my working account on my other server.

I can, however, confirm that both accounts were both working fine together until I changed the password on the one.

I tried deleting config files in ~./config/Nextcloud because I didn't know what else to do and that didn't seem to help either...

Anyway, I can't remove the user because I can't get the app open to remove the user.  Hopefully there is a command line way to remove the user and I will try that way....  Just wanted to report this.

I'm ubuntu 18.04.5 and most recent nextcloud-client as the date of this posting.

Thanks!

**Comment by AkechiShiro** [comment]
Here is the version I'm using :
```
Nextcloud version 3.1.0daily (build 20201102)
Git revision 5a8c2bab89de2f637814acf0a74d95a7121c35a9
Using Qt 5.12.9, built against Qt 5.12.9
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1g  21 Apr 2020'
Running on Arch Linux, x86_64
```
I'm facing kinda of the similar issue but using `GDB` I got a backtrace after logging in here it is.
[Here the backtrace](https://gist.github.com/AkechiShiro/384b3073bab57e73aa2a61fcd5ce4a76)
It happens right after logging in.
My backtrace although looks a bit different from the one that is reported here.
Is there any patch for this ? Beside logging out and then logging in back again ?
