### ISSUE TITLE
Release date Virtual Drive

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/desktop#1951]
Virtual Drive was announced in January 2019. It has become very quiet since then. Is the product still under development?

**Comment by JarbyDev** [comment]
I would to know the release Date as well.

**Comment by Escubaer** [comment]
Obviously the paying customers aren't interested into it ... like end-to-end encryption in the desktop client ... I don't trust any of those announcements anymore, if the code proves that things work - perfect ... otherwise I don't worry and use solutions which fit the purpose for my clients.

**Comment by kesselb** [comment]
As per https://github.com/nextcloud/desktop/pull/1626 there is no release date. It seems the feature is more complex than expected.

**Comment by jpbraun** [comment]
Hi kesselb,
thank you for your response.
I think this is a realy important feature. In my opinion Nextcloud is the better alternative to OneDrive und GDrive.
From a user perspective, the integration of GDrive and OneDrive in Windows Explorer is almost perfect. Nextcloud does not yet have this feature. Here Nextcloud should catch up with the Microsoft and Google prodcucts.

**Comment by jpbraun** [comment]
I would also help finance the development of the function if it could speed up development.

**Comment by kesselb** [comment]
Cool. You might talk to Nextcloud GmbH about that: https://nextcloud.com/contact/.

**Comment by jpbraun** [comment]
I just send them an e-mail.

**Comment by lordraiden** [comment]
I hope they can implent this soon, I think is a quite importan feature and the only thing that still keeps me in onedrive.

**Comment by alexander-rieder** [comment]
I am looking forward to this feature as well... @jpbraun what amount are you talking about?

**Comment by jpbraun** [comment]
Unfortunately, it is not possible to pay a certain amount of money to develop a function. Nextcloud has a different business model.

**Comment by fdzaebel** [comment]
I would also support this feature by finance.

**Comment by ptr2null** [comment]
> Unfortunately, it is not possible to pay a certain amount of money to develop a function. Nextcloud has a different business model.

I wonder if Bounties are their "business model"?
https://www.bountysource.com/teams/nextcloud/bounties

**Comment by HammyHavoc** [comment]
Eager to see this added. Has it been scrapped?

**Comment by mr-manuel** [comment]
Since there is no real progress, you can use the ownCloud Client in the meanwhile like others (including me): [ownCloud Download Desktop App](https://owncloud.com/desktop-app/)
For me it works without problems, but someone other say it's not stable: [[Feature Request] File Download on Demand #2444](https://github.com/nextcloud/desktop/issues/2444)

**Comment by Zegorax** [comment]
@mr-manuel I would like to thank you SO MUCH for this tip. It didn't even came to my mind to use the Owncloud client. It works perfectly, and I haven't seen any problem with NextCloud. Thanks a lot.

**Comment by dennisTGC** [comment]
our preliminary tests also show the OwnCloud client working with a Nextcloud server, although we haven't used it in production (yet).

**Comment by DaBlitzStein** [comment]
Is this project dead? Because this is the most important feature on all the set.

**Comment by aarononeal** [comment]
@er-vin This is a Windows only feature?

**Comment by FlexW** [comment]
No it's not. Please have a look at this blog post [here](https://help.nextcloud.com/t/help-test-our-desktop-client/107344).

**Comment by aarononeal** [comment]
Thanks. Is there an explanation for why Linux and Mac use `.nextcloud` files rather than something like [FUSE](https://github.com/libfuse/libfuse/)?

**Comment by er-vin** [comment]
Turns out that FUSE is the wrong level of abstraction for that. Any file manager or file dialog which would happen to try to sense the mimetype of the file or produce a thumbnail would end up triggering a download of the file. Do that often enough and you spend your time downloading files, not what you want. This could only be solved via extra API or collaboration with the desktop environment, there's another experimental backend in the works which is exactly about that. Will take time to deliver since it probably needs to go all the way to freedesktop.org first.

**Comment by aarononeal** [comment]
Why can't the files be partially hydrated or mime data cached from the server and FUSE abstract that?

**Comment by er-vin** [comment]
Because FUSE is basically just open/close/read/write there's no concept of mimetype or anything at that level. That's why extra API would be necessary (it's no surprise other platforms have extra API for that use case, you need something sitting between file system level and file dialog/manager app level which is known to the later, Linux doesn't have that).

**Comment by zaynetro** [comment]
> there's another experimental backend in the works which is exactly about that

Do you happen to know the name of it?

**Comment by aarononeal** [comment]
Is partial hydration a feasible approach? I would like to learn more about what the file managers are doing that makes it problematic.

This seems to indicate that Linux file managers use registered MIME types and infer them from file extension patterns and registered apps.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/desktop_migration_and_administration_guide/file_formats

**Comment by er-vin** [comment]
> Is partial hydration a feasible approach? I would like to learn more about what the file managers are doing that makes it problematic.

Well they open files and start to read them to either guess the mimetype based on content or produce thumbnails (depends on user settings). At that point you need the file to fulfill the request. Problem is that through FUSE the communication with them is "just" open/read/close... it's very low in semantic to reliably know what the file manager wants to do.

**Comment by er-vin** [comment]
> > there's another experimental backend in the works which is exactly about that
> 
> Do you happen to know the name of it?

It is the xattr backend.
