### ISSUE TITLE
macOS Pictures folder permission denied

### ISSUE THREAD

**Issue by weiw11** [nextcloud/desktop#2133]
### Expected behaviour
Adding macOS user's Picture folder syncs the folder to nextcloud.

### Actual behaviour
Permission denied.
Possibly because nextcloud client doesn't ask macOS for folder's permission when adding custom folders?

### Steps to reproduce
1. Add Folder Sync Connection for Pictures Folder to Nextcloud
2. Permission denied message

### Client configuration
Client version: v2.6.4

Operating system: macOS

OS language: English

Installation path of client: ~/Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

```
[OCC::SyncEngine::handleSyncError 	ERROR during  csync_update :  "Permission denied."
[OCC::ActivityWidget::addError 	Item  "Pictures"  retrieved resulted in  "Permission denied."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Permission denied."
```

**Comment by NobleWolf** [comment]
The exact same thing is happening to me. Client v3.0.2 server v19.0.3

**Comment by CoolDreamZ** [comment]
Same thing happened to me too, I am on Mac OS Mojave (10.14.6) and Nextcloud client 3.0.3. The issue seems to be that the Nextcloud App does not have permission to access the 'Photos' folder. It also does _not_ appear in the list of apps which have requested access to 'Photos' see here:

<img width="667" alt="Screenshot 2020-12-05 at 13 49 04" src="https://user-images.githubusercontent.com/70951446/101244893-faab7380-3700-11eb-9f5d-ec15e803c976.png">

A workaround is to give Nextcloud **full** access to the disk (not ideal but works):

<img width="667" alt="Screenshot 2020-12-05 at 12 33 24" src="https://user-images.githubusercontent.com/70951446/101244911-24649a80-3701-11eb-8592-3de10dd35d24.png">

I will be updating to Mac OS 'Big Sur' soon (which has tighter security on file access) and I hope this workaround continues to work!!

**Comment by NobleWolf** [comment]
I can confirm it does work on Big Sur. I just installed Nextcloud on my
wife's computer, immediately gave it full disk permission and all was well.
Though her photo library is quite small I never got any errors.

**Comment by CoolDreamZ** [comment]
@NobleWolf that's good news :-) thanks!

**Comment by er-vin** [comment]
So can be closed I guess?

**Comment by CoolDreamZ** [comment]
Ideally the nextcloud macOS app should follow the Apple guidelines and explicitly request access to 'photos', see here:

[https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/)

In the meantime I suggest updating the docs to include the workaround documented on this issue.

**Comment by CoolDreamZ** [comment]
(the workaround is a bit of a "sledge hammer" and does have security implications)

**Comment by huggx01** [comment]
> (the workaround is a bit of a "sledge hammer" and does have security implications)

@cooldreamz 
Absolutely right! A better workaround is to edit the ~/Library/Application Support/com.apple.TCC/TCC.db file in a SQL Editor (ex: SQLite). And add a row with the app's namespace to the kTCCServicePhotos service in a row..
a kind like this:

![nc_tccdb](https://user-images.githubusercontent.com/101991092/165987383-1c94b34d-b27d-4213-9862-f73b50704e23.png)


so the nc-client gets only permissions to photos and not the whole filesystem.

![settings](https://user-images.githubusercontent.com/101991092/165988602-eb0229e1-3039-4117-bfa1-eef6527fb4bf.png)

as you suggested in:
https://github.com/nextcloud/desktop/issues/2133#issuecomment-739899633
The nextcloud-client on MacOS should follow the Apple permissions guidelines by requesting the user to grant access when Accessing to certain sensitive folders.
