### ISSUE TITLE
Extending client to support app functionality

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/desktop#217]
It would be great if there was a way to add app support in the desktop client; specifically to support key features of apps that otherwise are less useful.

The original motivation for this came from discussions around file locking for collaborative edits; we can satisfy some people's file locking need with the locking apps, Workin2Gether and W2G2, but others make extensive use of the desktop app and see having to open a browser just to mark a file in use as inconvenient or simply not a solution.

**Comment by BloodyIron** [comment]
It surely would be swell if we could have right click contextual menus on desktops (like with Explorer.exe) to "check out" or "lock" a file to work against, then unlock it or something. Naturally, we would need a way server-side to override things if locks got lost due to clients being offline.

But I agree, extending the desktop client with apps would be really cool I think! :)

The locking functionality itself is a pretty big pain point, and most seem to be drawn to Sea File since NC does not yet have a way to address this.

**Comment by notthesame23** [comment]
I would vote against this just being an enterprise big $$$ feature.
I'm currently doing the research for my own cloud solution. I would be really happy if I could work collaboratively during my spare time with friends on some short movie 2D/3D animation projects. Unfortunately in my area, it's hard to make 
NextCloud looks like it could be the perfect solution for us...except this one missing feature.

**Comment by Rello** [comment]
Hello,
meanwhile, file locking was implemented in Nextcloud and its clients
e.g. https://www.youtube.com/watch?v=6VuNbMuTxnQ

thank you
