### ISSUE TITLE
Windows 10: add medium sized program icon

### ISSUE THREAD

**Issue by j-ed** [nextcloud/desktop#22]
## Expected behavior
The desktop client should provide a medium sized program icon which is shown in on a startmenu tile.

## Current behavior
The desktop client only provides a small sized program icon. As a reference I've added a Firefox and Thunderbird tile:

<img width="156" alt="windows10_nc-logo-zu-klein" src="https://user-images.githubusercontent.com/2572764/31771108-21fab4ec-b4db-11e7-9b47-40bf53daf04e.png">

### Steps to reproduce
1. Drag and drop the Nextcloud app to the tiles menu.

## Log entries
Nothing special has been logged.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.28
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.0.3

#### Client Configuration
Browser: Mozilla Firefox 56.0
Nextcloud app version: 2.3.2 (build 1) and v2.3.3.1-beta
Operating system: Windows 10 Pro

**Comment by camilasan** [comment]
@jancborchardt do we have one?

**Comment by jancborchardt** [comment]
@camilasan yep, the icon is at https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-android.svg – round, and with the dots in the background.

**Comment by jpnurmi** [comment]
I'm not a Windows export so I'm not sure what's right and wrong here, but could it be that it's actually Firefox that has a strangely large icon?
![startmenu](https://user-images.githubusercontent.com/140617/47936675-b379a580-dede-11e8-8164-12d9b53c8bb4.png)

**Comment by j-ed** [comment]
@jancborchardt As @jpnurmi wrote, he's not a Windows expert. As described in the original issue ticket Windows apps should by default provide two different sized icons, a small and a medium size one. From my understanding this change has primary been introduced to make Windows desktops better usable on tablet PCs. Firefox and Thunderbird both support both icons sizes.

These are the small sized icons of Firefox, Thunderbird and Nextcloud - everything is fine:
![grafik](https://user-images.githubusercontent.com/2572764/49217801-e4120980-f3ce-11e8-8931-27cd57e42985.png)

These are the medium sized icons of Firefox, Thunderbird and Nextcloud:
![grafik](https://user-images.githubusercontent.com/2572764/49218042-a2ce2980-f3cf-11e8-8c42-cb8563bb7b2f.png)

As you can see the Nextcloud app is not providing a medium sized icon and therefore a fallback to the small sized icon is done.
From my point of view we should be aware that there might be reasons to use medium sized icons, at leased e.g. by people with eye problems or only to be able to identify apps better. So why not providing one, it should be an easy task for the developer.

**Comment by jancborchardt** [comment]
Alright, sure – do you have more info about it, like what dimensions are needed? Thanks :)

**Comment by j-ed** [comment]
I think the following information will answer your question in detail and and also provides recommendations how the different tiles should look like: 
https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos

**Comment by DominiqueFuchs** [comment]
I made the necessary changes / files in an IMHO appropriate manner and leave them here as proposal so this can get finished soon. For tldr; look at the files and just read the bottom line.

### Background/Summary:
Desktop applications like FF/TB etc. accomplish the tile style control by the placement of a special file in the installation folder (besides the executable). Windows looks out for a file called [programname].VisualElementsManifest.xml and checks if content. There are strict rules what this file may and **must** contain. Necessary if file is used:
-  Backgroundcolor of tile
- (Text) Foregroundcolor of tile

That said, I propose these to properties as an example because I like them (Text 'light', background dark blue #293976. They can be changed, but have to be there. For more infos see [1] and [2]. Even though the title of [1] states 'runtime apps' this methods works for all kind of applications.

Old (current) logo:

![Nextcloud_OldTile](https://user-images.githubusercontent.com/32204802/64078592-e5b18a80-ccdc-11e9-832c-b55c13a46586.png)

![Nextcloud_OldTile_small](https://user-images.githubusercontent.com/32204802/64078629-46d95e00-ccdd-11e9-83d5-b30ecfc5ec6f.png)


### Option 1: Full-Tile logo

Based on the assumption that we want to keep the text ('Nextcloud' on tile) we have to consider readability when this text may collide with the bigger logo. One option is to scale the flat SVG-version across the whole 150px-Tile as the logo has a nice blue background already:

![Nextcloud_NewTile_flat_medium](https://user-images.githubusercontent.com/32204802/64078656-adf71280-ccdd-11e9-9198-92480cb2dced.png)

![Nextcloud_NewTile_flat_small](https://user-images.githubusercontent.com/32204802/64078667-c36c3c80-ccdd-11e9-953d-2a9fb37927cb.png)

### Option 2: 'Boxed' (current) logo, but well placed

I rescaled and positioned the current logo for both sizes (150px with a little border and slightly shifted to the top to stay in harmony with the text)
):

![Nextcloud_NewTile_boxed_medium](https://user-images.githubusercontent.com/32204802/64078687-f4e50800-ccdd-11e9-94ae-108ac0535eb5.png)

![Nextcloud_NewTile_boxed_small](https://user-images.githubusercontent.com/32204802/64078698-17772100-ccde-11e9-8c0c-017baf6c8c51.png)

You can find both variants of the corresponding manifest file as well as the generated assets attached. Pathes are based on the fact that I placed the assets in the 'resources' folder in my existing installation for testing. For the flat version, the same asset for 70 & 150px entry is used.

One more thing: If you're trying to test this or want to make your own variants: Windows needs a trigger to update the tile specs, just changing the assets and updating the manifest won't result in anything. The easiest way I found is to rewrite the timestamp of the corresponding link (in the start menu folder), this triggers an update. Powershell variant:

`(ls "$env:ProgramData\Microsoft\Windows\Start Menu\Programs\Nextcloud.lnk").lastwritetime = get-date`

[NC_TileIcon.zip](https://github.com/nextcloud/desktop/files/3563657/NC_TileIcon.zip)

[1] [How to customize Start screen tiles for desktop apps](https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn449733(v=win.10))
[2] [App icons and logos](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos)

**Comment by DominiqueFuchs** [comment]
Update: Nevermind, I think I got it now with the 'new' repository regarding the packaging process. 

If this gets acknowledged / polished here, I can do a corresponding PR with changes to _desktop_ (resource files) and _client-building_ (packaging/distribution).

@camilasan would be nice if you could take a look at this some time

**Comment by DominiqueFuchs** [comment]
Here are new assets with the updated logo, as I noticed after first seeing this issue. Thanks to the [promo]([https://github.com/nextcloud/promo](url)) branch they are also based on the svg version (thus pixel perfect). Only change I made to the logo is a slight rescale and shift upwards for the 150px variant. 

![Nextcloud_NewLogo_Shifted](https://user-images.githubusercontent.com/32204802/64091127-129e8580-cd4f-11e9-9c97-c42ad0c2a36b.png)

![Nextcloud_NewLogo_Centered_small](https://user-images.githubusercontent.com/32204802/64091132-16320c80-cd4f-11e9-8f9d-4e4a9986e076.png)

[tileassets_newlogo.zip](https://github.com/nextcloud/desktop/files/3564512/tileassets_newlogo.zip)

**Comment by camilasan** [comment]
Closing this issue thanks to #1401 :heart:
