### ISSUE TITLE
PPA: nextcloud-client vs. nextcloud-desktop

### ISSUE THREAD

**Issue by x86dev** [nextcloud/desktop#2205]
When having a peek into the official Launchpad PPA over at [https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client](url), there now are two packages, namely **nextcloud-client** (until 2.6.4) and **nextcloud-desktop** (2.6.5 only so far). 

Why is this naming change? Do we need to uninstall nextcloud-client first in order to nextcloud-desktop? The help text in the PPA still talks about installing nextcloud-client.

Some clarification would be nice. Thanks!

**Comment by ivaradi** [comment]
Debian (and thus Ubuntu) now provides official packages of the desktop client. They worked independently of me, and came up with a different package naming scheme. This caused problems for people who wanted to upgrade to the PPA version because of files being present in two different packages (e.g. nextcloud-desktop and nextcloud-client). So I have taken the official Debian packaging files (with some modifications), and package naming and structure now matches the official one. 

Packages with the old names (e.g. nextcloud-client) are still provided as transitional packages so that people using the PPA could uprade properly. It is not necessary to uninstall nextcloud-client, just upgrade your system and you should get the newer, transitional version of nextcloud-client as well as nextcloud-desktop. Then you can remove nextcloud-client, but that is not necessary.

The 2.6.4 and earlier nextcloud-client packages are present only for some old distributions for which the client is not built anymore.

The help text should indeed talk about nextcloud-desktop (although nextcloud-client still works). Thanks for catching it, I have updated the text.

**Comment by x86dev** [comment]
Ah good, thanks for the explanation and fixing it!

**Comment by zchap26** [comment]
> So I have taken the official Debian packaging files (with some modifications), and package naming and structure now matches the official one.

Does your use of the official Debian packaging files mean that the resulting packages would by definition be compatibile with Debian the distribution?

**Comment by ivaradi** [comment]
Yes, they should be, though they might have diverged a bit since the official files. 

But note, that the packages for Debian Testing are available in the OpenSuse Build Service: https://build.opensuse.org/package/show/home:ivaradi:alpha/nextcloud-desktop.testing or https://build.opensuse.org/package/show/home:ivaradi/nextcloud-desktop.testing, the PPA is meant for Ubuntu mainly.

**Comment by zchap26** [comment]
Unfortunately,  Download package results in:

```No data for home:ivaradi / nextcloud-desktop.testing```

Regards

**Comment by ivaradi** [comment]
You need to add the repository to `sources.list`, like:

 `deb https://download.opensuse.org/repositories/home:/ivaradi/Debian_Testing /`

You might also need to download the release key:

```
wget -O - https://download.opensuse.org/repositories/home:/ivaradi/Debian_Testing/Release.key | sudo apt-key add -
```
