### ISSUE TITLE
MacOS sync client does not trigger creation of conflict file

### ISSUE THREAD

**Issue by sh903** [nextcloud/desktop#225]
### Steps to reproduce
1. A Mac user (MAC) and a Windows user (WIN) open the same .docx file locally with Microsoft Word around the same time. Both have the file stored in a local folder that is synchronized with Nextcloud 12.0.3. Both use client version 2.3.3.1.

2. The MAC user writes something and saves the changes. The file is then synchronized and this version is kept on the server. So far so good. Meanwhile, the WIN user, having the document still open and not knowing about those changes, adds a few lines to the file and then saves the changes as well. When synchronizing, the file previously saved by the MAC user is kept and a conflict file with the WIN user's changes is created and uploaded. Everything works as expected.

3. We now switch the scenario: the WIN user writes something and saves the changes. The changed file is then synchronized. Meanwhile the MAC user, having the document still open and not knowing about those changes, adds a few lines to the file and then saves the changes as well. But instead of a conflict file being created, the MAC user's file version is uploaded and the WIN user's file is overwritten. The WIN user's changes are lost.

I consider this a serious bug, because without a conflict file nobody will ever know that there have been some changes to the file in the first place. This way, data loss will be detected only by chance and detection will probably come at a time when recovery of lost data is difficult or even impossible.

### Expected behaviour
A conflict file should be created and uploaded like in 2).

### Actual behaviour
No conflict file is created. The MAC user's file version is uploaded and the WIN user's file is overwritten.

### Server configuration
**Operating system**:
Ubuntu LTE 16.04
**Web server:**
Apache 2.4.18
**Database:**
mariadb 10.0.34
**PHP version:**
7.0.28
**Nextcloud version:**
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
github
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

### Client configuration ###
**Operating system:**
Windows 7 and MacOS High Sierra
**Client Version for both operating systems:**
2.3.3.1

**Comment by camilasan** [comment]
The difference here is not under control of Nextcloud, but a platform difference. On Windows, the Nextcloud client can't change files that are open because Windows locks them. On Mac and Linux, Nextcloud doesn't even know if files are open.

So if there's a conflict with editing a file on Windows like that, a conflict file is created. Meanwhile, most Mac and Linux editors will warn the user when the file has changed on disk and a save will overwrite those changes. If your editor does not keep tabs on the file and warns the user, there is nothing Nextcloud can do about this.

In theory, we could try to implement our own file locking, but that is a lot of work. It would also probably require a lot of resources and occasionally still go wrong as we can not continuously check.

**Comment by clecap** [comment]
Could we not detect opening of the file using an inotify feature?

**Comment by camilasan** [comment]
Since 3.1.0 we have improved conflict handling (see https://github.com/nextcloud/desktop/pull/2527). We tested that on Mac OS too. It worked as expected.

If you still have this problem with 3.1.2 ([https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients)), please re-open the issue.
