### ISSUE TITLE
Nextcloud desktop client keeps logging out

### ISSUE THREAD

**Issue by quantizzed** [nextcloud/desktop#2260]
### Expected behaviour
Nextcloud desktop keeps logged in after first successful login.

### Actual behaviour
Nextcloud desktop keeps asking to log in on every start up.

### Steps to reproduce
1. Launch Nextcloud desktop client.
2. Log in via a browser.
3. Exit Nextcloud desktop client or reboot.
4. Launch Nextcloud desktop client.

### Client configuration
Client version: 2.6.5

Operating system: Manjaro Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.0

Client package (From Nextcloud or distro) (Linux only): nextcloud-client

Installation path of client: /usr/bin/nextcloud

The issue is especially annoying, since I use two-factor authentication (TOTP).

**Comment by er-vin** [comment]
Could you please check the version of qtkeyring installed in your system and used by nextcloud-client?
Could you also check if the auth token is correctly saved in your desktop passwords? (gnome keyring or kwallet depending on your environment)

**Comment by thanhtam4692** [comment]
I got this problem too. My setup is Ubuntu server with MacOs desktop client

**Comment by raketti** [comment]
Same here:
**Client configuration**
Client version: 2.6.5
Operating system: FerenOS
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 5.14.2
Client package (From Nextcloud or distro) (Linux only): nextcloud-client / nextcloud PPA
Installation path of client: /usr/bin/nextcloud
Keyring: gnome-keyring - 3.28.0.2-1ubuntu1.18.04.1
QtKeyring: libqt5keychain1 0.7.0-3

**Comment by quantizzed** [comment]
> Could you please check the version of qtkeyring installed in your system and used by nextcloud-client?
> Could you also check if the auth token is correctly saved in your desktop passwords? (gnome keyring or kwallet depending on your environment)

I have no desktop environment, I only use Sway window manager, so I have neither `kwallet`, nor `gnome-keyring`. Nextcloud client does not depend on either of them, but instead depends on `qtkeychain` (v. 0.10.0), which in turn depends on `libsecret` (v. 0.20.3).

**Comment by er-vin** [comment]
> I have no desktop environment, I only use Sway window manager, so I have neither `kwallet`, nor `gnome-keyring`. Nextcloud client does not depend on either of them, but instead depends on `qtkeychain` (v. 0.10.0), which in turn depends on `libsecret` (v. 0.20.3).

Well that's the issue then, you need a storage system to be active. QtKeychain is just a wrapper API for abstracting away credentials storage services, but if none of them are running it can't store anything. That explains what you're seeing.

So you need to pick one between kwallet and gnome-keyring and make sure it runs at your session startup.

Similarly for @raketti the QtKeychain version you have is *ancient* and known to break with gnome-keyring. IIRC there was a bug there which was fixed in QtKeychain 0.10.

In both cases those are platform specific integration issues we can't do much about.

Lastly @thanhtam4692 what you're describing sounds like something else which might be mac specific. Please open a separate issue for this with as many details as you can (and client debug logs would be needed).

I'll thus close this one.
