### ISSUE TITLE
[BUG] Files randomly error out

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#228]
**Issue:**

Files randomly error when syncing, the error message appears briefly but is not detailed and then disappears entirely. There appears to be no pattern in terms of the files it errors out on, different sizes, different file types, etc.

**What should happen:**

The errors should be persistent in the client error log and they should be a bit more informative as to what occurred.

**Screenshots:**

https://i.imgur.com/bEEU3H0.png

https://i.imgur.com/k3PysLj.png

**Log:**

https://hastebin.com/heluwoyefu.log

**Comment by DominiqueFuchs** [comment]
Hi @c0fe , quite some time since your report here. Do you still experience this issue? Unfortunately, your hastebin link ends empty now and from your description and the images I am still unsure what the actual problem is. Your activity view notifies you about skipped hidden files just as intended, doesn't it?

**Comment by c0fe** [comment]
This issue can be closed I haven't had these issues repeat.
