### ISSUE TITLE
client falsely reports of successful sync

### ISSUE THREAD

**Issue by Orbital-Bit** [nextcloud/desktop#229]
sync icon on a folder and in tray  should not be Green Checks when some files did not sync
(and tray message should not report success)

## Details
Nextcloud Server 12.0.6.1
Desktop Client: 2.3.3
OS: Windows 10

For whichever reason modified files do not sync to server, they get a red overlay icon in windows explorer, but the tray icon is a check mark and reports successful sync. 
In the Main Client window the folder also shows as synced with green check mark, but under activity the files are reported as not synced because of a server error.
If a user did not check the files directly (or the activity section) they would have a false sense of proper operation.

Perhaps the tray icon should show a warning, and the folder icon in the main window definitely should show an error.

**Comment by DominiqueFuchs** [comment]
Hey @Orbital-Bit , thanks for reporting here. With the latest stable client (2.5.3) I can not reproduce this issue. Several fixes regarding the UI/informational icons have been merged since your post here (example: [this merge](https://github.com/nextcloud/desktop/commit/ae6483862eb366f8799bb3f74cc09f4670ccd7bb)). Do you still experience this issue?

**Comment by Orbital-Bit** [comment]
@DominiqueFuchs,
this has not reoccurred with the updated client.
