### ISSUE TITLE
Add back context menu entry for opening the NC folder

### ISSUE THREAD

**Issue by Croydon** [nextcloud/desktop#2311]
### Expected behaviour
Make a right click on the NC icon in the tray / status bar. I would like to see again an "Open folder" option like it was the case < 3.0.0.

### Actual behaviour
I first have to open the context menu, then open the "main windows", then click on the folder symbol. This is too annoying for something I'm doing regularly.

### Steps to reproduce
1. Update to 3.x.x from 2.x.x
2. Miss the context menu entry

### Client configuration
Client version: 3.0.0

Operating system: Win10

**Comment by camilasan** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Not sure I understand – as far as I can see both actions take the same amount of time:
- Right-clicking on the icon and clicking on "Open folder"
- Left-clicking on the icon and clicking on the folder icon

Additionally, with the right-click menu the problem is how to display multiple configured accounts. If we do it with a submenu it’s even more steps, and if we do it in a list then people will also ask us to put other stuff in there. The right-click menu is not the main dialog.

**Comment by Croydon** [comment]
For some reason, a left-click option did not exist in my mind, probably because I used only the context menu option for years

I still don't like it as much as the old version, but I think I can get used to this and your points sound reasonable

Thanks
