### ISSUE TITLE
Activity text / file name cut off too early

### ISSUE THREAD

**Issue by apg1980** [nextcloud/desktop#2325]
Hello,
in Desktop Client 3.0 Windows the new Apperance of events is unreadable, all the Texts are cropped and i am unable to read what has exactly changed, no mouse hover to see whats the whole text of it.

![grafik](https://user-images.githubusercontent.com/9514965/91387101-bcb2cf80-e834-11ea-8a4e-6830b72a1977.png)

**Comment by haukepetersen** [comment]
Hi,
same under Linux (Mint 20, Cinnemon). This new design seems to be quite a step backwards in terms of usability to me. Any chance to make this view optional and give users the choice to go with the old view?! Or at least add the option to change the size of that window?!

Thx!

**Comment by er-vin** [comment]
@DominiqueFuchs @jancborchardt opinions on how to improve the new design to deal with this? (tooltip looks like a good stop gap measure, although admittedly it's kind of lacking in space to display text)

**Comment by helmut72** [comment]
Same on macOS, this changelog view is nearly useless.

> opinions on how to improve the new design to deal with this

Just show the icon and the filename.

Also show on the top row an icon to open a changelog window with complete folder path.

**Comment by jancborchardt** [comment]
Yep, so we should fix this by using a different wording:

Yeah, so a better structure for the file messages would be:
> **Filename.pdf**
> Edited 4 hours ago · Documents / Project / Customer A

If it’s by someone else:
> **Design review call – Text app.md**
> Added by Julius · 2 days ago · Documents / Project / Customer A

Yes, this can now of course cause the path to ellipsize. That is fine though. Also, we could middle-ellipsize the path so that both start and end is visible? What is definitely more important is what the file name is and who changed it.

-------------

Also you can tell from the screenshot that the text is ellipsized too early – one icon width too early in fact. The ellipsizing should always depend on how many icons are actually there in the row, so that it ellipsizes correctly no matter if there are 1 or 2 action icons.

**Comment by er-vin** [comment]
> Yep, so we should fix this by using a different wording:
> 
> Yeah, so a better structure for the file messages would be:
> 
> > **Filename.pdf**
> > Edited 4 hours ago · Documents / Project / Customer A
> 
> If it’s by someone else:
> 
> > **Design review call – Text app.md**
> > Added by Julius · 2 days ago · Documents / Project / Customer A
> 
> Yes, this can now of course cause the path to ellipsize. That is fine though. Also, we could middle-ellipsize the path so that both start and end is visible? What is definitely more important is what the file name is and who changed it.
> 
> Also you can tell from the screenshot that the text is ellipsized too early – one icon width too early in fact. The ellipsizing should always depend on how many icons are actually there in the row, so that it ellipsizes correctly no matter if there are 1 or 2 action icons.

I like the form you're proposing there. I just got one concern. We got a report somewhere (can't find it now...) where people mentioned the need to copy/paste the path + file. If that's split in two that makes it harder I guess. Do we care?

**Comment by er-vin** [comment]
Fixed via @allexzander work. Can't remember the PR number right now. :-)

**Comment by tomasz-lasko** [comment]
I confirm, I just installed 3.6.0 on Windows and still there is no popup/showing full text when mouse hovering over the text, but when I hover the mouse over the button to the right, there is a working tooltip indeed - as shown on this screenshot:
![image](https://user-images.githubusercontent.com/6689052/189603471-31d5efd3-de01-41a5-a296-9c1d0ee58a44.png)




**PLEASE FIX IT, BECAUSE I CANNOT DIAGNOSE WEIRD SYNC ERRORS THAT HAPPEN FROM TIME TO TIME that are presented in the message** because I can't even see what the error message is, so I don't even know what is the problem!!! and although I am a very experienced developer myself, I can't find the error in the debug log (text file) of the app! This is absurd! I have the error message right in front of me, but it is chopped and the significant part is hidden! and this message is nowhere in the log file. 

**THIS IS ABSURD AND STOPPING PEOPLE FROM RESOLVING ISSUES BY THEMSELVES, AND YET THIS WOULD BE VERY EASY TO FIX: ADD A FREAKIN' TOOLTIP OR EXPANDING TEXT TO FULL LENGTH (WRAPPED) OR _ANYTHING_ LIKE THAT**

**Comment by tomasz-lasko** [comment]
> Fixed via @allexzander work. Can't remember the PR number right now. :-)

@er-vin or @allexzander - could you please reopen the issue and/or verify if someone already wrote the fix? Because as stated above, the fix has not been in the released apps, and the issue completely destroys administration and problem resolution that I have now

**Comment by tomasz-lasko** [comment]
PS. I saw that yesterday one error message was wrapped (text wrap) and not cut off, so I could resolve the problem. But I guess it was just short enough to fit into text wrap; however I suspect that if the message was longer, it would have been cut anyway - just as on the screenshot I pasted in my message above (two messages earlier)
