### ISSUE TITLE
Please offer a FLOSS compatible Flatpak

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [nextcloud/desktop#2373]
To concern https://github.com/nextcloud/desktop/issues/1598#issuecomment-554726094

A signed .flatpakref officially provided by the Nextcloud team and offered at https://nextcloud.com/install/#install-clients would solve the problem for me. At least until there is a FLOSS spin-off from Flathub. So it could also be for the transition.

I am grateful for an ethical solution.

**Comment by er-vin** [comment]
To be honest I don't think it's going to happen soon, unless someone wants to contribute it like our Debian packages.

**Comment by 4jNsY6fCVqZv** [comment]
https://gitlab.gnome.org/GNOME/fractal/-/issues/619#note_938057

> AppImage are certainly very convenient when it comes to installing. They do not offer however everything that flatpak does (no updates for the user, no builtin sandboxing with portals, no dependency handling for developers)

Why did you decide to use AppImages?

**Comment by 4jNsY6fCVqZv** [comment]
As a development team, what do you think the impact of the Flatpak format will be for Linux users?

So are there people in the community who want to work together on the realization of a FLOSS compatible Flatpak package?

It would also be important to me that there is an official package from Nextcloud that I can trust. Not just another third party package of the client.

**Comment by 4jNsY6fCVqZv** [comment]
I wonder, if there are people in the community who want to work together on the realization of a FLOSS compatible Flatpak package?

It would also be important to me that there is an official package from Nextcloud that I can trust. Not just another third party package of the client.

**Comment by sudwhiwdh** [comment]
@er-vin How do you at Nextcloud evaluate the significance of the Flatpak format as a tool for software distribution on Linux?

**Comment by sudwhiwdh** [comment]
How do you at Nextcloud evaluate the significance of Flatpaks as a utility for software deployment on Linux?

**Comment by er-vin** [comment]
Well, from a company perspective, this is more a question of effort. All the packages except the AppImage builds are community contributions.

**Comment by mgallien** [comment]
There is already a third party providing this on Flathub: https://flathub.org/apps/details/com.nextcloud.desktopclient.nextcloud
Development is being done there https://github.com/flathub/com.nextcloud.desktopclient.nextcloud

**Comment by julianfairfax** [comment]
I believe the Flatpak should be taken over by the Nextcloud developers directly. An official Flatpak would also allow for verification on the Flathub website, and would be more trustworthy for users.

Related: https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/119

**Comment by joshtrichards** [comment]
> I believe the Flatpak should be taken over by the Nextcloud developers directly. 

I'm not sure about "taken over", but there might be a path here. As I see it there are two goals in an ideal world:

1. The Flathub distributed client gets Verified status
2. A non-Flathub distributed (and verifiable) release artifact is made available for direct download

Leaving aside what the definition of "official" really is, there are community maintained efforts that are hosted underneath the @Nextcloud project. That has some benefits - such as ease for members to help out more directly - but it doesn't mean the core devs are going to assume day-to-day responsibility for the endeavor. It does mean, however, that there are additional options and people that can step in as needed (i.e. any of the members).

At least this is my interpretation of how things have conventionally worked.

The community-maintained Docker Official Image https://github.com/nextcloud/docker is an example of this.

So I think there would be five requirements when it comes to the Flatpak:

1. @nextcloud would have to be willing to host the sub-project
2. The current Flatpak maintainers would have to be willing to move the current project (https://github.com/flathub/com.nextcloud.desktopclient.nextcloud) under the @nextcloud umbrella
3. The Flathub verification process (https://docs.flathub.org/docs/for-app-authors/verification) would have to be executed
4. For an independently downloadable install artifact: Someone would need to volunteer to build whatever pipeline is necessary to build/push out a signed build artifact from this community-maintained repository hosted under the @nextcloud umbrella
5. Someone that is willing to steward all of the above :-)

Some of the top contributors to the unofficial NC flathub are already @nextcloud members. @tilosp and @juliushaertl come to mind. 

That said, this has come up before (#1598). I presume there are good reasons why this hasn't already been done - whether due to the perceived effort-to-reward ratio not being sufficiently beneficial (relative to other priorities) - or something else.

**Comment by juliushaertl** [comment]
Something for @tobiasKaminsky to consider.

I started doing the flatpak builds back in the days but am mostly out of contributing there as I don't use them anymore and lack time to continue, glad that @tilosp is still actively pushing forward there.
