### ISSUE TITLE
Update to 3.0.1 Windows not working

### ISSUE THREAD

**Issue by h4knet** [nextcloud/desktop#2386]
### Expected behaviour
Left click on the taskbar icon should have the menu appear.ing correctly?

### Actual behaviour
The menu do not appear at all if I've an app already open; when I only display the desktop, the menu display with a strange looking as follow:
![nextcloud-bug](https://user-images.githubusercontent.com/1595901/92460550-5f216a00-f1c8-11ea-896a-71e80977ad1e.png)

### Steps to reproduce
1. Install the latest version from the updater
2. Have Nextcloud launched

### Client configuration
Client version: 3.0.1 Windows (latest official)

Operating system: Windows 10 2004
OS language: English
Installation path of client: Default

### Server configuration
Nextcloud version: 17.0.8

**Comment by Id3aFly** [comment]
@h4knet What is the menu you expect to appear?

Since nextcloud 3.0 there is a new tray menu, which just looks exactly as the menu you've shown.
If you want to see the "old" window, you need to open the "settings" (via right clicking the tray menu).

So what you see as error just could be the new layout, which I replaces the old one,
Or did I get you wrong?

**Comment by er-vin** [comment]
@Id3aFly I think his point is that he doesn't even see it on screen when another window is around + in the screenshot you can see the colors are weird (kind of washed out).

**Comment by h4knet** [comment]
The tray menu do not render properly and it do not appear if I click on the tray icon while I already have an opened window on the desktop.
@er-vin you said: "This looks like an issue with your graphics drivers or how Qt interfaces with it, can't do much about this." I'm running windows inside a VM with VMware workstation; As a result I'm not sure this issue would be driver related.

Regard,

**Comment by er-vin** [comment]
Well, yes it could be still driver related (although you'll note I said this on a different issue). VMware has its own drivers inside the VM which either forward the OpenGL calls to the drivers of the host in some way or emulate them internally. Something seems off in that chain to me.

That didn't show before because prior to 3.0 all our GUI stack was raster based but not the case anymore with that new window.

**Comment by nophead** [comment]
The activity list used to be a proper resizable and movable window. With 3.0.1 it was just a small panel in the top right hand corner of my screen, not big enough to show any of my file paths, so useless.

**Comment by er-vin** [comment]
@h4knet did you try disabling the 3D accel on the VM settings btw? I'd expect it'd somehow fallback to raster and we could see how this goes.
