### ISSUE TITLE
Upgrade to 3.0.1 on Win 10 does not respect previous "Ask for confirmation before syncing folders larger than" setting

### ISSUE THREAD

**Issue by deadwax** [nextcloud/desktop#2410]
Basically as noted in the title.

Upon upgrading to 3.0.1 from 2.6.5 the settings reset to ticking the "Ask for confirmation before syncing folders larger than" setting with the size set to 500mb.  It does this silently and the user is not aware that syncing has ceased on any large folders.  This is not good.

**Comment by mschoettle** [comment]
I am having this problem on macOS 10.14.6. After installing 3.0.1 there was a notice about large folders. I had to re-enable the folders I previously chose to sync.

I expected that that's it but unfortunately my Pictures folder (the largest of all) started to re-sync completely. In the activity log the files have 'File has changed since discovery'. Nothing changed, though, and it is not clear what has changed (maybe some properties?).

**Comment by er-vin** [comment]
I think it is a duplicate of #2279

(Different symptom but likely same cause)

**Comment by Niklasschoenb** [comment]
This is a serious issue.
In my case, the same happened after installing the 3.x client (previously on 2.x), so I had to reselect big folders for sync again,
That alone was not a big deal for me, but then the devastating thing happened:
Nextcloud would not treat the existing files in the folders as already synced, but would instead rename them all into some weird format (ending with ~ plus some random numbers) and download the files from the server again.
Seriously, the owncloud app is pushing me every day to install the update, then I finally install it and end up with havoc.
This is a huge disappointment and undermines my trust in nextcloud as a safe solution to sync my data.
