### ISSUE TITLE
Details of 'conflicts' missing in desktop client 3.0.x

### ISSUE THREAD

**Issue by jokuha** [nextcloud/desktop#2411]
Using the new 3.0.1 desktop client on macOS, I have a problem about missing information on conflicts, son errors, etc. – due to the removal of the activity tab from the separate dialog and "cutoff" of info in the menubar popup. 

I attach two screenshots showing such info in principle, but they do not provide any filenames (and the "details" link does not do anything) or only the beginning the full name, which misses many levels of directories and the actual filename. AFAICT there is no way to get the full filenames (without getting separate log files). 

Am I overlooking something or is this indeed a bug?

<img width="65" alt="Screen Shot 2020-09-11 at 09 48 45" src="https://user-images.githubusercontent.com/13561679/92886797-4907e980-f414-11ea-9b28-e31ce2d005d9.png">
<img width="566" alt="Screen Shot 2020-09-11 at 09 46 23" src="https://user-images.githubusercontent.com/13561679/92886821-4dcc9d80-f414-11ea-9c5f-92cfaa34fd4b.png">

**Comment by vasyugan** [comment]
I see the same on Linux. But I think that there are already bug reports about this. BTW, I think that the way conflicts are currently being handled in Nextcloud, even without this bug, doesn't meet the needs of non-technical users. In my experience, it leads to users just getting used to the yellow icon sitting in their systray forever, because the have no idea what to do with it. See https://github.com/nextcloud/desktop/issues/1195

**Comment by Derkades** [comment]
I believe this has been fixed already, see #2299

**Comment by er-vin** [comment]
Yes, should be addressed by the new tooltip introduced in #2396. Will be available as part of 3.0.2.
