### ISSUE TITLE
Please restore Managed Folders to the Windows tray icon menu

### ISSUE THREAD

**Issue by redfoxhub** [nextcloud/desktop#2474]
Version 3 of the client has removed a few right click options from the Windows tray menu, some of which have issues open for them, but I haven't noticed one for the Managed Folders menu.

Up until v2.6.5 of the Windows Client, the right click tray icon menu would list would include a list of managed folders (one for each sync connection) that you could use to quickly open the sync folder in Windows Explorer. I appreciate that not everyone uses the client to sync with multiple connections, but I found this very useful and the context menu was by far the quickest way to jump to each folder. 

Would it be possible to restore this functionality in a future release?  Personally, I'm happy for it to be off by default with a setting to enable it (if that helps).

Thanks

**Comment by alex-dacosta** [comment]
I did use it often also, as the one-click sync pause. But I used this last feature mainly to circumvent the fact that Nextcloud client slows Windows Explorer and put it in an unusable state.

**Comment by er-vin** [comment]
@jancborchardt any opinion? Right now this is indeed click to bring up the main dialog, select the account on the left hand side, then click the folder icon in the top stripe.

**Comment by dajusc** [comment]
A big **+1** for (optionally) restoring the old context menu entries. 

I can't help but to feel anger when my everyday tasks (stop/start sync) require more clicks and longer mouse-travel after a software was updated.

**Comment by alex-dacosta** [comment]
I had to downgrade Nextcloud desktop client to version 2.6, in order to keep using this suspend possibility which alleviates the Windows Explorer overload due to the client.
Again the solution is either of these:

1. fix the Explorer overloading
2. create a _temporary_ sync suspension like OneDrive does
3. restore the one-click sync suspension

**Comment by jancborchardt** [comment]
@alex-dacosta separate issue, and we will bring back "Pause sync" to the right-click menu.

@redfoxhub so your main issue is that right now it is only possible to open the main folder instead of all the individual ones, right?
In that case @er-vin I’d say the proper fix is that if an account has multiple sync folders, clicking on the folder icon should open a dropdown to show them. In the default case of only one sync folder, directly opening that on click of the icon is still the desired action.

**Comment by dajusc** [comment]
> [...] we will bring back "Pause sync" to the right-click menu.

Its good to hear/read that! :+1:

**Comment by camilasan** [comment]
@jancborchardt 
> I’d say the proper fix is that if an account has multiple sync folders, clicking on the folder icon should open a dropdown to show them.

This folder icon?
![foldericon](https://user-images.githubusercontent.com/241266/176009556-fbe8ec8f-449a-4dde-a215-b251599c7cb5.png)

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
