### ISSUE TITLE
Make main window notifications understandable

### ISSUE THREAD

**Issue by wahboh** [nextcloud/desktop#2515]
As of now the Desktop Client shows "You created..." "Synchronized... " "Changed..." etc, which makes no sense. WHERE was it created? What does "Synchronized" mean? What action is taken on "Changed" items?

### Expected behaviour
"Tell us what should happen" - exactly! Let the main windows tell us EXACTLY what happened. Why not write clearly and understandably: "Uploaded", "Downloaded", "Deleted on server", "Deleted locally" instead, showing exactly what happened?

### Actual behaviour
"You created..." "Synchronized... " "Changed..." 

### Steps to reproduce
1. Any synchronization
2.
3.

### Client configuration
Client version: 3.0.2

Operating system: Windows 10 2004

OS language: Swedish

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

**Comment by elsiehupp** [comment]
Additionally, it would be nice if the small popover showed sync errors and conflicts, rather than burying them in the "Settings" window, which does not remotely make sense.

Furthermore, sync errors and conflicts should open a meaningful log entry when you click on them. Currently the text "There are unresolved conflicts. Click for details." does not, in fact, do anything, when you click it. (Clicking on other notifications doesn't necessarily do anything useful, either.)

**Comment by joshtrichards** [comment]
Related: #2518 & #4352

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by wonx** [comment]
Not the original requester, but I'd say it's still totally relevant.
