### ISSUE TITLE
Switching from OC to NC client with OC server caused client crash

### ISSUE THREAD

**Issue by PVince81** [nextcloud/desktop#2536]
### Steps to reproduce
** as far as I can remember them**

1. Setup OC desktop client sync folder against OC server (version 10.4)
1. Close all clients
1. Rename ".config/ownCloud" to ".config/Nextcloud"
1. Rename "owncloud.cfg" to "nextcloud.cfg"
1. Start nextcloud client and enter credentials

### Expected result
Works fine after login, syncs.

### Actual result
A segfault happens:
```
% nextcloud
   2020-10-01 10:56:01:847 [ fatal default ]:      ENFORCE: "allow_failure" in file /home/abuild/rpmbuild/BUILD/desktop-3.0.2/src/common/ownsql.cpp, line 267 with message: SQLITE Prepare error
		[1]    10214 abort (core dumped)  nextcloud
```

As a workaround I deleted the config and redid it from scratch, then I could use the NC client against OC 10.4.

### Env
- client distro: openSUSE Tumbleweed
- OC desktop client openSUSE owncloud-client-2.6.3.14058-2.3.x86_64 (from openSUSE repos)
- NC desktop client openSUSE nextcloud-desktop-3.0.2-1.1.x86_64 (from openSUSE repos)

### Notes

This is only a temporary measure until server migration can be done.

I'm unsure whether this client migration path is even relevant any more, considering that a server side migration is not directly possible any more. People are more likely to re-setup everything from scratch anyway, so feel free to close. I just wanted to document this :-)

@nickvergessen mentioned that day that it might be a discrepancy in database fields

**Comment by er-vin** [comment]
It is indeed a discrepancy in database structure. I don't remember the specifics (we got that reported a little while ago already). The ownCloud client inserted a new index in the database which depends on a function injected by the client (since sqlite3 allows to inject this kind of stuff). But we don't provide it and there's no real way for us to recover from that, sqlite just asserts when that happens.
