### ISSUE TITLE
[Feature Request] Store e2e key in 3rd party application

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2544]
I'd like to request optionally storing and re-calling the e2e key from a secure 3rd party application such as Keepass, Bitwarden or a system's keyring as opposed to storing it plain text in the Desktop app.

Thanks for considering and great work.

**Comment by er-vin** [comment]
This is not stored in plain text. This is stored in the system keyring.

**Comment by sunjam** [comment]
I'm hopeful that it could be possible to store the e2e key in a password
manager such as Keepass or Bitswarden...  or some other method for locking
it away rather than displaying it under Desktop client settings.  Cheers.

**Comment by er-vin** [comment]
That's two different things.

It *is* stored in the system password manager (which BTW could be KeePassXC nowadays since it supports the secret services API that QtKeychain uses, although I'm not aware of any user who tried it in practice).

Still, as a convenience we allow easily displaying it from the settings dialog to allow people to setup other devices (which was requested by @jospoortvliet). This is only a convenience though, if the system password manager is locked the client won't be able to retrieve the mnemonic and so won't be able to display it.
