### ISSUE TITLE
Nextcloud client's window disappears instead of staying visible

### ISSUE THREAD

**Issue by boreq** [nextcloud/desktop#2549]
When running the Nextcloud client by executing `nextcloud` the program immediately forks to the background and goes away. 

Right now I have to try to launch it multiple times in the row until the window finally appears and I am quick enough to mouse over it and then the only way to keep it open is to go to the "settings" screen immediately.

Is it possible to always keep the initial window open or always start the program straight in the settings mode? The man page doesn't list any solutions I am afraid.

```
$ nextcloud --help
Nextcloud version 3.0.2git
```

**Comment by er-vin** [comment]
This forks to the background because it is already running. When it runs you should have a systray entry which gives you access to all the windows.

When you run it again it will popup the main window which will stay around until it loose focus (but still systray should be here).

**Comment by boreq** [comment]
Why was this closed? I do not have a sys tray and I do not want the UI to close itself, is there no way to change this behaviour?

**Comment by er-vin** [comment]
Well, I closed it because this was already discussed on other tickets when we rolled this out.

Other people having no systray successfully get the window when launching a second time. The window shows up and goes away when clicked somewhere else. If for some reason it's not the behavior you get, I'd tend to look at the window manager you got which doesn't properly give the focus or such.

Which environment is it?

**Comment by philliptaylorpro** [comment]
Are you actually happy with this behaviour? Run the program. Wait a bit. Run the program again?

`--nosystray` would be an acceptable option but yeah I guess this is fine, it works. People will no doubt repeatedly stumble across this post and "workaround" regardless. I'm on [DWM](https://dwm.suckless.org/) which has no systray.

**Comment by jorsn** [comment]
> Other people having no systray successfully get the window when launching a second time.

For me, this sometimes works, and sometimes just not. If other people have a similar problem, but the solution does not work for me (and @boreq), this is no reason to close the issue. We need maybe a different solution.

> The window shows up and goes away when clicked somewhere else. If for some reason it's not the behavior you get, I'd tend to look at the window manager you got which doesn't properly give the focus or such.

What is ”properly”? Not everybody likes the focus to change only on click. If I change workspace (which is very common on linux WMs), my window manager focuses the top/last focused window on that workspace. I consider this sane behavior, but still I don't want any window to disappear without me closing it. Even on Gnome, you can configure [focus change on mouse over](https://superuser.com/questions/238169/in-gnome-is-there-a-way-to-focus-activate-a-window-on-mouse-over).

There are just different philosophies of window managers: In some (classical windows-like desktop) the window essentially manages itself, but in every tiling window manager, the window should be strongly managed by the WM, and should let itself be managed. This is what nextcloud used to do in the past.

**Comment by rknop** [comment]
OK, this is an old issue, but it's driving me crazy.

I would like the NextCloud window to not close until I tell it to close.  I want to be able to move it.  (That is, I *can* move it, but it closes as soon as it's done moving.)   Is there a settings anywhere that would accomplish this?  To tell it to just make the window you get when you click on the systray icon to just be a normal window?

(I also want it to have my standard window manager borders, but I can accomplish that with my window manager, at least for now; I have no idea if any Wayland window managers (or whatever it has instead of "window managers") let you override that.)

**Comment by rknop** [comment]
> Is there a settings anywhere that would accomplish this? To tell it to just make the window you get when you click on the systray icon to just be a normal window?

Answer: yes.  (Leaving this here and not deleting the comment, because I managed to find this issue before the nextcloud documentation when searching for this, so just in case somebody else gets the same search results, hopefully this will help them.)

Documentation on the NextCloud desktop config : https://docs.nextcloud.com/server/stable/user_manual/en/desktop/configfile.html (at least as of this writing).

The option is in `~/.config/Nextcloud/nextcloud.cfg` ; under [General], add a line `showMainDialogAsNormalWindow=true`.

**Comment by costis-t** [comment]
> The option is in `~/.config/Nextcloud/nextcloud.cfg` ; under [General], add a line `showMainDialogAsNormalWindow=true`.

Many thanks, this should be the default. Now I have titlebar again (plasma 6).
