### ISSUE TITLE
Client window closes immediately when pressing SUPER key combo in i3

### ISSUE THREAD

**Issue by SpyceTewan** [nextcloud/desktop#2569]
### Expected behaviour
Window should stay open and behave like every other window in i3

### Actual behaviour
When pressing any SUPER button combo in i3 (for example, to resize or move the window), the window immediately closes, which makes it impossible to manage it with i3

### Steps to reproduce
1. Open the client in i3 (I'm actually using regolith linux)
2. Press any key combo using the SUPER key (Windows key)
3. It closes

#### Client version:

3.0.2

#### Operating system:
Ubuntu 20.04.1 LTS x86_64

Kernel 5.4.0-51-generic
WM: i3
DE: Regolith

#### OS language:
EN

#### Qt version used by client package (Linux only, see also Settings dialog):
Doesn't show in app. I have 5.12.8 installed

#### Client package (From Nextcloud or distro) (Linux only):
From [here](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client)

#### Installation path of client:
Default

### Server configuration
Not relevant.

**Comment by er-vin** [comment]
This is likely because this window hides when it looses the focus, or I didn't get what you meant?

**Comment by SpyceTewan** [comment]
Yep. That makes it unusable in i3.

**Comment by er-vin** [comment]
Well the designers decided that it was behaving "like a menu" which indeed when it looses focus disappears. Are you in focus follow mouse mode or something like this?

Because otherwise I'd expect i3 to give it the focus when the window is raised... in which case it'd disappear only when you send the focus back somewhere else.

**Comment by FlexW** [comment]
I use the client every day in i3 and I could observe that if you have your mouse on the main dialog and then press any key combination the main dialog gets closed. But I think this is the normal behaviour on all other window managers.  @SpyceTewan wants to resize and manage the main dialog like any other window I guess. However, since it was decided that the window should behave like a menu this will not be possible to implement.

**Comment by er-vin** [comment]
Alright, I'll close this one then. This is supposed to be "menu like" and is not going to change.
