### ISSUE TITLE
Desktop client resets config randomly at startup

### ISSUE THREAD

**Issue by David-Lor** [nextcloud/desktop#258]
Sometimes, the desktop client looses his config at startup, having to re-enter the server, login and sync everything again. This doesn't happen at every but, it's random.

OS: Kubuntu 14.04 LTS x86_64

Nextcloud version: 2.3.2

**Comment by camilasan** [comment]
At first, could you try to update the client to 2.3.3?

**Comment by EnforcerZhukov** [comment]
That's the latest version available in repositories

**Comment by camilasan** [comment]
Could your issue be the same as #230? In any case, you can run the client in the command line to look for errors.

**Comment by EnforcerZhukov** [comment]
I'm not sure, because credentials are kept saved between reboots except when the bug happens, which is random. For example, after this bug happened for the last time and I re-entered all the login info, the computer was shutdown and started up like ~4 times with no problems. It probably will keep working for some weeks/month/s until It might fail again.
