### ISSUE TITLE
Update notification not working

### ISSUE THREAD

**Issue by DrCarsonBeckett** [nextcloud/desktop#2609]
### Expected behaviour
Receiving an update availalbe notification ones a new client update is released (3.0.3 as an example).

### Actual behaviour
You receive a message that there is no update and its the latest version.

### Steps to reproduce
1. Install any Nextcloud client version older than 3.0.3 .
2. Check for update.

### Client configuration
Client version:
3.0.3 (now, previous version was 3.0.2).

Operating system:
Windows 10 Pro x64

OS language:
German

Installation path of client:
Original one: "C:\Program Files\Nextcloud\"

In regard to #1798 , not sure if its necessary. _Originally posted by @DrCarsonBeckett in https://github.com/nextcloud/desktop/issues/1798#issuecomment-700047178_ like I already said there, I could confirm that issue since version 2.3.* .

**Comment by claell** [comment]
Do you say that the notification does not work for you since version 2.3.* (and has been working before)?

Also a screenshot of the problem might be helpful.

**Comment by DrCarsonBeckett** [comment]
I started to use the Nextcloud client since that version and it never worked for me. I tested it on three different PC's.
![2020-10-31_14h31_39](https://user-images.githubusercontent.com/38506927/97780610-f6ca8580-1b85-11eb-98a7-f271a15f795b.png)
![2020-10-31_14h30_56](https://user-images.githubusercontent.com/38506927/97780612-f7631c00-1b85-11eb-823f-b7ccb9b0749c.png)
I tested it again ones with auto update check enabled and ones with it being disabled.

**Comment by claell** [comment]
Thanks for providing the details. It seems to be working for others, not sure what causes this for you.

**Comment by ifrh** [comment]
I can confirm that behavior.

> I started to use the Nextcloud client since that version and it never worked for me. I tested it on three different PC's.

On Windows 10 Pro Version 1909 (Build 18363.1139) (64bit) and on Windows 10 Home Version 2004 (Build 19041.572) (64bit) Nextcloud has found no Update.

**Comment by er-vin** [comment]
Well, "no update notifications ever" and "no update notification for 3.0.3 as of today" are two different things.

To reduce the stress on the update server, we have several measures in place to roll out new releases very gradually. So that's why you don't necessarily get a notification on the same day the release is announced. We're in the process of changing the way we deliver those so post-3.1 that period of time should become gradually shorter (that won't be overnight though).

That's why if this is your issue... well this is not a bug and has to be like this for now.

Now if you *never* get update notifications, something else is at play, this is unexpected and could be a bug indeed.

**Comment by DrCarsonBeckett** [comment]
> Well, "no update notifications ever" and "no update notification for 3.0.3 as of today" are two different things.
I and I highly assume everyone else does indeed know that. I only said that I never get any update notification till this day on three different PC's with Nextcloud clients since version 2.3.* . 😃 
So no, the rest isn't from me and thats not the issue ... sadly.^^

**Comment by er-vin** [comment]
> > Well, "no update notifications ever" and "no update notification for 3.0.3 as of today" are two different things.
> > I and I highly assume everyone else does indeed know that. I only said that I never get any update notification till this day on three different PC's with Nextcloud clients since version 2.3.* . smiley
> > So no, the rest isn't from me and thats not the issue ... sadly.^^

Yes sure, wasn't for you but previous commenter seemed slightly ambiguous about it. :-)

**Comment by claell** [comment]
@DrCarsonBeckett So it might be possible that you never got notifications because of the reasons @er-vin provided? Might be worth testing with an older release to confirm (assuming older releases get update notifications more immediately).

@ifrh Same question for you. Hopefully you can test somehow whether the possible explanation @er-vin gave applies to you or whether you are experiencing a bug instead.

**Comment by DrCarsonBeckett** [comment]
@claell 
I did test that in the past and it didn't really solve the issue. For whatever reasons, after literally testing every client since version 2.3.3.1 it started to work after I installed 3.0.0 again (after going up to 3.0.1). 😕 
But thanks for the hint, glad it at least somehow works again now. Even though the download speed is seriously low (I can understand the reasons behind that).^^

**Comment by claell** [comment]
Maybe the older versions are not able to show notifications anymore because they are incompatible with the current format?

Do you also get notifications when using 3.0.2 now? Maybe that only means that the rollout continued in the meantime and this is not a sign of a bug but the currently used rollout procedure.

**Comment by DrCarsonBeckett** [comment]
I tested version 3.0.0 first and it didn't offer an update. Same for 3.0.1.
It started to work after I installed every version since 2.3.31 up to 3.0.1 (and then down to 3.0.0 again).
3.0.2 still doesn't offer me an update.

**Comment by er-vin** [comment]
Well right now you might or might not get an update, since we flipped the switch regarding 3.0.3 recently.

**Comment by DrCarsonBeckett** [comment]
Yea, well thats nice to hear but you successfully evaded my question.^^
Any idea why it started to work with that way? Also taking in regard it didn't help to install older versions in the past?

**Comment by er-vin** [comment]
I think we're talking on parallel lines in fact. :-)

The thing is: shortly after a release the updater doesn't serve the new release to everyone at the same time. It depends on the update segment which can delay you getting a release up to something like 5 days (IIRC). And on top of that for those in the right update segment we serve the release only 10% of the time (in a random fashion) the other 90% get served 3.0.2 at the moment. Both combined means it can take a while before you get a notification about 3.0.3.

That's the case right now (since the updater got bumped on Friday) so if you got 3.0.2 chances are you don't get a notification yet. For releases older than 3.0.2 chances are that you get 3.0.2 right away.

Now if you don't get notifications for releases older than 3.0.2 there is a problem of course.

Am I less confusing? :-)

**Comment by DrCarsonBeckett** [comment]
I don't think you actually got my point. I already got the information you just posted in detail already the first time.
What I meant is why didn't it work when I installed 2.3.3.1? Same goes for the other versions. It started to work after I tried all the version and rolled back to 3.0.0.
I already tried that in the past and it did not work. So why now? Thats my point.
Also for a fact I know that I had 1-2 weeks sometimes before I noticed that there was an update (for some older clients).

**Comment by claell** [comment]
> Now if you don't get notifications for releases older than 3.0.2 there is a problem of course.

He doesn't seem to get notifications when he tested with older releases. From my understanding he only got a notification for those older ones when he rolled back to 3.0.0 (after testing older ones first).

It is not that easy to follow, but I assume the following procedure (please correct @DrCarsonBeckett if I am wrong):

- Was on 3.0.2 with no update notification when creating this issue. - Behavior can be explained by staged rollout.
- Tried 2.3.3.1 afterwards and still got not update notification. - Behavior can most likely not be explained by staged rollout, possible bug.
- Tried versions in between (up to version 3.0.1) and still no update notification. - Behavior can most likely not be explained by staged rollout, possible bug.
- Roll back to 3.0.0 and then there was an update notification (possibly to update directly to 3.0.2) - Behavior is unexpected after it failed to show a notification before on this version.
- Now on 3.0.2 again without a notification. - Behavior can be explained by staged rollout.

**Comment by DrCarsonBeckett** [comment]
Thats correct except the last part, which itself is correct but I updated to 3.0.3 manually again.

**Comment by claell** [comment]
Alright, I slightly adjusted it accordingly.

We all don't speak English as native language afaik, so that makes it harder, indeed. Also you of course know what happens to you, so that might make it harder to clearly communicate that to people not knowing what is going on, since some statements might feel over precise to oneself, while they might be required for others to properly understand what is going on.

**Comment by er-vin** [comment]
From @claell's bullet points I have to admit I'm not quite sure what to conclude. The fact that 3.0.0 didn't propose and update and later on after installing it again it started to propose an update is particularly puzzling.

That makes me think it might not be with the client but with the updater server... looking at the history we had adjustments to it during the past month so I wonder if that's related.

@DrCarsonBeckett do you happen to know how much time there was between your two 3.0.0 attempts?

**Comment by DrCarsonBeckett** [comment]
It is indeed odd, thats true. 
Downgrading from 3.0.2 to 2.3.31 and through the previous version up to 3.0.2 and then back to 3.0.0 took around 10 minutes the most.
Previously when I tried to reinstall 3.0.0, meaning after I noticed the update to 3.0.1 after a few days, I tried to reinstall it. Which didn't help.
Also die autoupdate often had multiple days, ones even close to two weeks to update to the latest version and nothing happened.

**Comment by r2evans** [comment]
Is it normal for the normal rollout to take over 11 days? I understand why you may not want auto-updates to hit everybody at the same time. Is it normal for manual checks to say that I'm not the most recent version, when in fact there is a more-recent stable version available for download? (Two in fact.) While I understand the delay in the auto-update, I am surprised by manual update button.

Another data point: I'm on desktop 3.0.3 (installed Oct 30 or so). Desktop version 3.1.0 was release was released Dec 14; I use my computer daily for at least 8 hours per day; usually it sleeps or hibernates, but I have power-cycled at least twice in this time frame. I've manually killed/restarted the nextcloud desktop app once or twice. My desktop client is configured to "Automatically check for Updates".

Not once in the last 11+ days has it notified me that 3.1.0 was available. Today, I see on the blog that 3.1.1 has been released, so I clicked on the "Check for Update now", and am told that I am on the latest version.

![image](https://user-images.githubusercontent.com/5815808/103144319-76438380-46f5-11eb-8091-599be8c2079f.png)

I checked https://docs.nextcloud.com/desktop/3.0/autoupdate.html as well, and:

- I do not have `skipUpdateCheck=true` in my `nextcloud.cfg`.
- No `skipUpdateCheck` entry in `HKEY_LOCAL_MACHINE\Software\Wow6432Node\Nextcloud\Nextcloud` (the folder is not present/found) or `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Nextcloud GmbH\Nextcloud` (folder *is* present, DWORD not found)
- No `skipUpdateCheck` entry in `HKEY_LOCAL_MACHINE\Software\Policies\Nextcloud GmbH\Nextcloud`
- I have none of those entries under `HKEY_CURRENT_USER`

There is no https://docs.nextcloud.com/desktop/3.1/autoupdate.html, it's currently HTTP 404. (How long do docs lag software releases?)

(I'm on win10 64bit 20H2 os build 19042.685.)

**Comment by er-vin** [comment]
Regarding 3.1.0 we didn't deliver it through the update server due to a couple of issues which were found soon after. 3.1.1 should start to roll out though, although it'll take time to hit everyone due to the bucket system it's not on the day and yes it can take something like 10 days.

**Comment by DrCarsonBeckett** [comment]
Kind of sounds like the issue I had, which somehow and somewhat is "fixed" (better to say "solved") now.

**Comment by r2evans** [comment]
Looks like https://github.com/nextcloud/client_updater_server/pull/49 finally did the trick: I'm still on 3.0.3, and 18 days after 3.1.1 was released (and checking daily), I finally received a notification of the available update to 3.1.1. Thanks for the help.

**Comment by er-vin** [comment]
Yes, I finally got rid of the extra throttling code we had to add due to load issues. Hopefully the server won't crumble. At least now we're back on the update segment system only which gives us a predictably time before updates are proposed. At most you get a 5 days delay with that system (if your update segment is 99).
