### ISSUE TITLE
Adding account from tray window doesn't work if settings were never opened

### ISSUE THREAD

**Issue by nicolasfella** [nextcloud/desktop#2653]
With current master "Add account" in tray window does nothing on a fresh start of the client. Only if the settings have been opened once it works.
This is because otherwise the `connect` in https://github.com/nextcloud/desktop/blob/master/src/gui/accountsettings.cpp#L211 is never called

**Comment by er-vin** [comment]
That's due to the delayed creation of the settings dialog which got repaired. One might wonder why such a connected ended up there... *sigh*

@allexzander that could be an interesting one for you to look at if you want. It's an area of the code you didn't visit yet and might require some design changes.

**Comment by er-vin** [comment]
This got solved now in 3.1.1.
