### ISSUE TITLE
First Sync is Unreasonably Slow - takes hours on large folders

### ISSUE THREAD

**Issue by ringe** [nextcloud/desktop#2669]
### Expected behaviour
Install Nextloud Desktop on a new computer and set up an account, pointing at a new (empty) local folder.
I would expect Nextcloud to realize the local folder is empty, and quickly download content from the provider.

### Actual behaviour
Nextcloud seems to loop over every single folder and file by doing API calls, to decide which folders and which files have changed. This takes a very long time when there are hundreds of folder and files to download.

### Steps to reproduce
1. Make deep folder tree with a lot of files in a Nextcloud-synced folder
2. Share the deep tree with another user
3. Install Desktop on a new computer for the other user

### Client configuration
Client version: v3.0.3

Operating system: Windows

OS language: English

Installation path of client: Default

### Server configuration
Nextcloud version: 20.0.1

Storage backend (external storage): local/SSD

### Logs

1. Client logfile: 
https://gist.github.com/ringe/5e8403e772ec6c3d9d50da7c027dffeb

**Comment by hdlineage** [comment]
Do you have end to end encryption enabled? There is a bug with E2EE right now that basically cripples syncing. Disable E2EE on the server side fixed it for me.

**Comment by ringe** [comment]
No encryption. Group folders.

28. nov. 2020 01:51:53 hdlineage <notifications@github.com>:

**Comment by Sonique** [comment]
Have same problem. Encryption enabled. I can't understand why on first initialization when you have empty folder nextcloud-desktop starts to checking diff between folder and server, it's looks completely weird and also it's extremely slow, moreover sometimes it's crashes and you should restart or select sync folders on by one. Yes I have encryption enabled.

**Comment by ringe** [comment]
I get the closing, but this is a necessary feature?

**Comment by ringe** [comment]
@er-vin Doesn't this bug deserve a closer look than getting stale?

We are providing private Nextcloud instances as a service, and some customers are suffering.

Are there any ways to optimize first sync?
Now it's doing PROPFIND HTTP requests for every. Single. File. and it takes waaay too long to be usable.

**Comment by mgallien** [comment]
> @er-vin Doesn't this bug deserve a closer look than getting stale?
> 
> We are providing private Nextcloud instances as a service, and some customers are suffering.
> 
> Are there any ways to optimize first sync?
> Now it's doing PROPFIND HTTP requests for every. Single. File. and it takes waaay too long to be usable.

if you really need support from Nextcloud company you would need to get an [enterprise subscription](https://nextcloud.com/enterprise/)

the support on github is done as a best effort without any guarantee

speaking of this ticket it got closed automatically due to inactivity

please provide logs to help us analyze what is going wrong for you ?

I am going to reopen

**Comment by ringe** [comment]
Thanks @mgallien, I appreciate the reopening.

This is not a support issue, it's a critical bug that makes Nextcloud practically unusable.

Barring a major improvement on this issue, I will need to reconsider using Nextcloud as a primary storage for customers that have huge shared document structures.

I have shared the client logs and will share the server log as well.

**Comment by ringe** [comment]
I believe it's the looping over every file that's the culprit.

**Comment by liberare** [comment]
I have the exact same issue. Someone shared a large folder structure with me, that contains thousands of small files (file size approx. 2-6 kB). The Nextcloud sync client is syncing them one after another, which takes a loooong time because it uses only a fraction of the available bandwidth, and it has a relatively high CPU usage (permanent 100% on one core). I think it is not a bug, because it seems to be intended to work this way. But there should be an enhancement for large folder structures and small files to make the sync much faster. E.g. download files simultaneously or a detection that a folder is empty and simply download everything from the server without checking every single file.

**Comment by ringe** [comment]
This is most clearly still an issue. :)

**Comment by PhilippSchlesinger** [comment]
See https://github.com/nextcloud/desktop/issues/4918 for a bug that is maybe related to that issue.
