### ISSUE TITLE
Client does not recover from standby #970

### ISSUE THREAD

**Issue by fkbreitl** [nextcloud/desktop#2678]
This bug was accidentally closed.
Please reopen #970 or continue here.

**Comment by anteract** [comment]
Win10, 20H2, same behavior.  My "quick fix" is.
Opening the client, hitting the network button, and change the proxy settings from "Use system proxy" to "No proxy" fixes it for me, until it sleeps again.  Basically a guess says that it's not seeing the network come back.
3.0.2 didn't do this to me.
And no, there are no proxy's in use on this computer.

**Comment by namob** [comment]
Same problem for me with 3.0.3. After resuming Windows 10 2004 from sleep I get this error. Restarting nextcloud by killing the process or doing the proxy trick mentioned above fixes the issue until next sleep/resume.

**Comment by Heptalon** [comment]
Same problem here since version 3.0.3.

**Comment by anteract** [comment]
Installing new Windows client 3.10 fixed it for me, Really appreciate the way the issue was acknowledged.  Oh well, at least it was fixed.  Thanks!

**Comment by nursoda** [comment]
My colleague suffers this bug in 3.1.0, it worked fine in 3.0.3. What debug info should we provide?

**Comment by er-vin** [comment]
> My colleague suffers this bug in 3.1.0, it worked fine in 3.0.3. What debug info should we provide?

Debug logs might be useful. In 3.1.0 this is one click away in the settings dialog. Make sure to reproduce the issue then go click on that settings dialog button to create the debug archive.

**Comment by nursoda** [comment]
My colleague created a ZIP. But I suspect that it contains sensitive data: There are four files `._sync_<ID>.db` that sum up to 23MB…do you need them? __nextcloud_client_buildinfo.txt, __nextcloud_client_parameters.txt and nextcloud.cfg are very small. The `logs` directory contains several (2-4MB sized) gzipped files and a current (40kB) `20201222_1411_owncloud.log.1`.

**Comment by er-vin** [comment]
Yes, it will contain sensitive data, if you trust us with said data, please upload the zip file there: https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

There are other people dropping sensitive data in that file drop so please make sure to name it properly so that we get a chance to figure out who posted it and which issue it is related to.

It's especially important because it is unlikely we would look at it right away.

**Comment by nursoda** [comment]
Sorry, read your first sentence, clicked/uploaded first, then read the rest… It's "2020-12-22 Debug-Archiv NC-Client BS.zip", I'll upload a text file next to it containing backreference to this bug.

**Comment by kanderss** [comment]
Here is a fix

**Comment by kanderss** [comment]
Using the .exe installer instead of the msi installer fixes this

https://github.com/nextcloud/desktop/issues/482#issuecomment-750834686

**Comment by Heptalon** [comment]
Can confirm this.  Version 3.1.1 with the .exe installer fixes it for me as well.

**Comment by namob** [comment]
Can confirm aswell, reinstalled with the .exe and haven't seen this issue since.

**Comment by VincentSch4rf** [comment]
I am running into the same problem since I installed `3.1.1-x64` via MSI installer. After a hibernate or suspend under Windows I get this very error message. The only fix that works for me is to exit the application and restart it.

I will try to reinstall the client using the `Nextcloud-3.1.1-setup.exe`, however, since the official client that can be downloaded from the Nextcloud webpage is the `.msi` version this is only a "hotfix" to me.

**Comment by xam-ps** [comment]
Same problem here. Client Version 3.1.1

Already reinstalled the Client through the exe version did not fix the problem on my machine.

**Comment by camilasan** [comment]
> Same problem here. Client Version 3.1.1

The fix is not in 3.1.1. You should install 3.1.3 (or at least 3.1.2).

https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.1.3-x64.msi
https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.1.3-x86.msi
