### ISSUE TITLE
System tray font size and Nvidia notice when activated

### ISSUE THREAD

**Issue by joho1968** [nextcloud/desktop#2681]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When I click on the Nextcloud tray icon, I'd expect the interface to look at least *similar* to Windows 10. 

### Actual behaviour
The font size is too big, the UX isn't what I would call "a well integrated application" :-) It reminds me a bit of the problems with GNOME/KDE/QT, except this is Windows (but possibly caused by QT configuration anyway I guess).

Also, on machines with Nvidia drivers as their primary display driver, I get a notice about how I can access Nvidia screenshots/moments as soon as the Nextcloud tray is "opened", as if it thinks something is using accelerated graphics.

### Steps to reproduce
1. Click on Nextcloud tray icon

### Client configuration
Client version: 3.0.3

Operating system: Windows 10 (64-bit)

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

![Nextcloud_Client_Big_Tray](https://user-images.githubusercontent.com/3135227/100907418-999a5a80-34ca-11eb-8b04-a91a92110258.png)

**Comment by er-vin** [comment]
Thanks for the report.

> The font size is too big,

We got other issues reported regarding this, it seems that something's goes off on some machines especially when hidpi is involved, we didn't find it yet.

> the UX isn't what I would call "a well integrated application" :-) It reminds me a bit of the problems with GNOME/KDE/QT, except this is Windows (but possibly caused by QT configuration anyway I guess).

Well, this is the design as requested by the designer team, the overall look is going to stay like this sorry.

> Also, on machines with Nvidia drivers as their primary display driver, I get a notice about how I can access Nvidia screenshots/moments as soon as the Nextcloud tray is "opened", as if it thinks something is using accelerated graphics.

Well this is indeed using accelerated graphics for that GUI. It's done using QtQuick which uses in turn GPU acceleration.

Since the only real issue I can see here is the font size for which we have another ticket, I'll close this one though.
