### ISSUE TITLE
Tray icon is very small and 'Use Monochrome Icons' setting does nothing. (minor issue)

### ISSUE THREAD

**Issue by ACodingGenie** [nextcloud/desktop#2684]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Description 
- The Sync tray icon on Pop!_os is very small compared to the other icons and 'Use Monochrome Icons' setting doesn't work at all. Its hard to tell when files are syncing because of the really small icon.
### Expected behaviour
Icon should be the same size as other icons on the taskbar and when monochrome icons are enabled it should work properly like it does on Windows 10.

### Actual behaviour

Icon looks really small:
![image](https://user-images.githubusercontent.com/68975831/101127674-09dcd500-35cc-11eb-9848-e8c0c23e931f.png)
Setting to use monochrome icons is enabled but doesn't work as seen above:
![image](https://user-images.githubusercontent.com/68975831/101127836-5fb17d00-35cc-11eb-8bca-9df9bc3f2376.png)
Using "journalctl -f" command in terminal shows: "Nextcloud, Impossible to lookup icon for 'state-ok-panel' in default theme"
### Steps to reproduce
1. View the icon on the taskbar on Pop!_OS. 
2. Turn on the setting for monochrome icons and see if anything changes.

### Client configuration
Client version: Version 3.0.2 (KDE).

Operating system: Pop!_OS 20.10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Not installed I guess, I get an error when checking.

Client package (From Nextcloud or distro) (Linux only): Installed using a flatpak from Pop!_Shop

Installation path of client: Unfortunately not aware where flatpaks are installed by default. 
- Output of Nextcloud Flatpak info.
![image](https://user-images.githubusercontent.com/68975831/101130109-dfd9e180-35d0-11eb-9d1e-b5fe32306cb7.png)

## Logs
- Not sure how to get logs for a flatpak.

**Comment by er-vin** [comment]
Well, in fact it's not small. If you look very very closely and zoom in you'll see there's a small cloud also displayed and the checkmark is in a corner of it.

It just so happens that the color of that cloud outline almost matches the color of your panel.

Now the thing is... I will have to close it because we don't provide that icon, it seems that something on your OS is catching the theming of that icon and replacing it by the equivalent from the breeze theme... we can't do anything about this it needs to be brought up to whoever made the flatpak (we don't).
