### ISSUE TITLE
UI to resolve all conflicts en masse

### ISSUE THREAD

**Issue by gbakeman** [nextcloud/desktop#2786]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The new conflict resolution UI for files added recently has been a great help when you know which file you need and don't want to go into your folders to resolve the conflict manually. To take it a step further, it would be great if the window we currently have for resolving singular file conflicts could me modified so we can easily resolve all conflicts within one dialog.

### Actual behaviour
We need to go through each file conflict one-by-one, resolving conflicts in individual dialogs.

### Steps to reproduce
1. Have several different files change on the local filesystem without the Nextcloud client being aware, or several files change on the server while disconnected.
2. File conflicts will be found

### Client configuration
Client version: 3.1.1

Operating system: Windows 10

OS language: English

**Comment by rugk** [comment]
Some design ideas:
* Group files by directory
* Chekboxes next to each directory and file 
* Optionally have an additional "flat" view, where you can see all files as a list
* show some indicator on how many files have conflicts, how many you solved, how many you already selected etc.
* indicate which file is newer/larger anyway

As especially the last point is hard to doo in a condensed UI, maybe there should be some mockups first. How do you imagine such a UI?

**Comment by bjoern-tantau** [comment]
I would envision when clicking on the yellow "There are unresolved conflicts. Click for details." (paraphrased, as I have the German translation) that you would get the option to either "Keep all local versions", "Keep all server versions" or "Keep all newest versions". Maybe with the option to confirm every action enabled by default.

I guess this would probably be easier to implement before creating an enhanced mass-resolution dialog.

That would at least make it easier for people suffering from #2467.

**Comment by maroelawerner** [comment]
It would be nice if we could choose how Nextcloud decides if a file has changed. In other words tell it to just look at the file size and ignore creation or modification dates. With just about all my conflicts, they are picture files and they are identical.

**Comment by HydrodynamicSynchrotron** [comment]
Or to have an option to actually download and compare hashes and auto-resolve those. It is insanely painful and pretty much unusable. Since I've restored a backup on my new phone I have ~5000 pending conflicts and, no, I won't continue using it like this.

**Comment by MarcelRobitaille** [comment]
I am very much for the proposals by others, but I realize that this will probably take some time to implement correctly. I have some ideas for quick changes that can make conflict resolution usable in the mean time.

I was quite happy with the previous solution of adding `conflict` to the name. This allows people who know what they are doing to quickly do whatever they want. Delete all the local conflicts? No problem: `find . -name '*conflict*' -delete`. Delete the conflict if some condition is met? Take the most recent? Or diff each one? Easy. I understand that this is not a good option for most people, but the new solution is very tedious to use if you have more than one or two conflicts. A temporary solution could be to add an option to go back to creating a file with `conflict` in the name.

Another nice improvement, which would be easy to add quickly, would be to add the full path to the conflict in the dialog window. It can be very difficult to figure out which file you are being prompted about otherwise.

**Comment by bgeneto** [comment]
A "Keep All Newer Files" would be a great solution instead of ticking hundreds of files one by one.

**Comment by mgallien** [comment]
this could also allow setting an automated resolution if we do get new conflicts (see https://github.com/nextcloud/desktop/issues/4705)

**Comment by SlappyHours** [comment]
Resolving conflicts is a nightmare currently. At least on Ubuntu: 6 clicks per conflict -> so 10 conflicts ^⁼ 60 clicks...

**Comment by mind-overflow** [comment]
Missing this is terrible and it feels like the conflict file renaming idea was rolled out without giving users an easy way to get out of that terrible mess. I was offline for a few days and upon reconnecting to my Nextcoud instance, in a matter of 30 seconds, it renamed THOUSANDS of files to `... (conflicted copy of...`.  
  
You implemented a system that can completely mess up your setup in a matter of seconds but could require hours of manual user labor to get solved. For every file Nextcloud renames automatically in the blink of an eye, add 30 seconds to the user physically going to the file location and deleting the conflicted one, or manually selecting the file from the list and selecting which one to keep. Terrible UX and it should definitely have been accounted for when someone had the idea to rename all files systematically AND automatically without also giving a way to rename the files sytematically AND manually. When you add a feature that generates a requirement of work, you should also add an equally fast way to revert whatever happened. Not just leave users with thousands of unresolved conflicts to manually solve one by one.  
  
I proceeded to write a script that also renames all files by removing the `(conflicted copy` part, instead of manually fixing it, but not everyone knows how to do this. We desperately need a user friendly way. A poorly designed feature imho.

**Comment by mbnoimi** [comment]
Very vital feature request. 
I've one PC connected to my cloud. I  didn't sync it since some months. Today I launched recent NC client (v3.7.3) to see tons of conflicts!!!
Although I'm so frustrated for this issue but it could be much relief it there is a button choice to fix all the conflicts one time.

**Comment by mbnoimi** [comment]
I stopped using NC until implementing this feature. My files are MESSY NOW!
I'll backup my files using rsync/ssh NC no longer a practical solution for me.

**Comment by linshutan** [comment]
this is really easy to solved so why we havent met it been solved till now .

**Comment by HydrodynamicSynchrotron** [comment]
> this is really easy to solved so why we havent met it been solved till now .

Oh, is it? Then, go on, why don't you submit a PR? After all it's "really easy to solved". As much as I think this missing feature sucks, insulting the people who voluntarily work on this in their own spare time achieves exactly nothing. It's a FOSS project, YOU can participate. After all, it's really easy, eh?

**Comment by mgallien** [comment]
Current implementation of a dialog to resolve all conflicts



![Image](https://user-images.githubusercontent.com/168967/235127417-de6687e2-af20-45d1-8896-86db6cb4d17e.png)

**Comment by bjoern-tantau** [comment]
> Current implementation of a dialog to resolve all conflicts

Nice! Checkboxes to select all newest or all oldest files would also be good.

**Comment by MarcelRobitaille** [comment]
> Current implementation of a dialog to resolve all conflicts
> 
> ![Image](https://user-images.githubusercontent.com/168967/235127417-de6687e2-af20-45d1-8896-86db6cb4d17e.png)

Thanks for the updates. This just looks like it's dealing with "Text File.txt". Is that just because it's a mock-up? This issue is about resolving a large number of different conflicting files.

**Comment by SlappyHours** [comment]
Feedback regarding the dialog: Just be aware that there can be scenarios with a lot of conflicts - let's say 100. Is the dialog able to  handle this?

**Comment by gowthamnatarajan** [comment]
> Current implementation of a dialog to resolve all conflicts
> 
> ![Image](https://user-images.githubusercontent.com/168967/235127417-de6687e2-af20-45d1-8896-86db6cb4d17e.png)

How do I get this interface? Is this in the mobile app?

**Comment by bgeneto** [comment]
> How do I get this interface in the mobile app? The conflict is happening for the photos auto upload folder. Here I can only resolve 1 conflict at a time. Not bulk resolve.
> 

Just upgrade to the (current) latest desktop client version 3.9.0. And disable dark mode theme because in dark mode those checkboxes are not visible in this window.

**Comment by northben** [comment]
I just wanted to say thank you for this feature, and for the tip about dark mode!
<img width="544" alt="2023-07-31_18-10-35" src="https://github.com/nextcloud/desktop/assets/2553902/1b22e4e9-8f47-457f-b2a6-ee5c7e35aab5">

by the way, I still had to click quite a few times because of this prompt but it was much better than it would have been without the "all versions" checkbox.

<img width="420" alt="2023-07-31_18-10-53" src="https://github.com/nextcloud/desktop/assets/2553902/6d99f0c3-3588-4be3-a9bd-e945f4fdd1ee">

**Comment by mstrauss2018** [comment]
I have a situation where all my loca files got corrupted. No idea how.
Restoring everything fron the server results in a lot of conflicts.
The ability to choose All Server Version made things easier however I still had to click Yes for each conflicted file to delete locally.
That wasn't a problem until the last folder where it showed over 10,000 conflicts. This means I have to click Yes over 10,000 times.
Honestly, who could do that?

Please add the ability to choose to delete all local versions of conflicts with 1-click of a button


Thanks

Mike

**Comment by szmania** [comment]
> > Current implementation of a dialog to resolve all conflicts
> > ![Image](https://user-images.githubusercontent.com/168967/235127417-de6687e2-af20-45d1-8896-86db6cb4d17e.png)
> 
> How do I get this interface in the mobile app? The conflict is happening for the photos auto upload folder. Here I can only resolve 1 conflict at a time. Not bulk resolve.

I see this was merged in v3. I'm no v33 and I don't see this. Any idea where it is in the windows client? Thanks.

**Comment by szmania** [comment]
> > > Current implementation of a dialog to resolve all conflicts
> > > ![Image](https://user-images.githubusercontent.com/168967/235127417-de6687e2-af20-45d1-8896-86db6cb4d17e.png)
> > 
> > 
> > How do I get this interface in the mobile app? The conflict is happening for the photos auto upload folder. Here I can only resolve 1 conflict at a time. Not bulk resolve.
> 
> I see this was merged in v3. I'm no v33 and I don't see this. Any idea where it is in the windows client? Thanks.

nvm, I've found this, it was sort of blended into the UI when you click on resolve conflicts for a sync you have in settings, the window pops up with all listed conflicts, then at the top of that is a Resolve Conflicts button meant for all conflicts, but it looks like the same color as the individual resolve conflict buttons so its hard to notice.
