### ISSUE TITLE
Windows Client - Screenshot Uploading

### ISSUE THREAD

**Issue by Ackis** [nextcloud/desktop#283]
I thought this would have been a common request/problem but I only found this through google:
https://help.nextcloud.com/t/printscreen-saves-to-screenshot-folder/9673

And nothing on the tracker:
https://github.com/nextcloud/client/issues?utf8=%E2%9C%93&q=is%3Aenhancement+screenshot

So I apologize if this has been handled elsewhere and I'm just to dense to find it.

One of the nice features with Dropbox and OneDrive is the ability to automagically upload screenshots from your PC.  You're able to do this with the Android app because screenshots are immediately saved as files in their own directory, however in Windows it's different.

I simple would like to see an option to upload screenshots as soon as they're taken.

Thanks.

**Comment by torrbox** [comment]
Couldn't you save screenshots to a Nextcloud folder on Windows, too, hence automatically upload them? I believe Windows key + Print Screen key saves to Pictures\Screenshots on Windows 8/10. (can't try due to lack of Windows) Or just use a third party program.

**Comment by reflectively** [comment]
I have the same request for Mac OSX! I am desparately looking for a screenshot app which automatically uploads the files to my nextcloud AND add puts a shareable link into my clipboard

**Comment by sbonds** [comment]
Using a third party add-on to allow compatibility with **any** cloud storage drive seems like a good plan to me since it decouples you from any dependency on a specific cloud provider.

I found this question on superuser about how to do that in Windows:

https://superuser.com/questions/1319897/automatically-save-a-snipped-screenshot-to-disk

(They suggest using the Open Source "[Greenshot](http://getgreenshot.org)" program.)

For MacOS automatically saving screenshots appears to be built into the OS itself based on [Apple support article HT201361](https://web.archive.org/web/20181204144606/https://support.apple.com/en-us/HT201361). The bottom of the screen explains that the thumbnail or Options can be used to change the save location to your cloud-synchronized folder.

**Comment by hi-ko** [comment]
I'm also using Greenshot. A Nextcloud addon for Greenshot as described here: https://blog.bartdemeyer.be/2015/05/create-your-own-greenshot-plugin/ would be a valuable daily helper putting the optional internal or shared url in the clipboard. Maybe someone from the win client team volunteers to write an addon in visual studio?

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
