### ISSUE TITLE
Letsencrypt Intermediate Certificate (R3) not accepted on Nextcloud Desktop-Client 3.1.1 (macOS)

### ISSUE THREAD

**Issue by aquadraht** [nextcloud/desktop#2869]
Hi,

yesterday my Letsencrypt certificate for my nextcloud server aotu-renewed. Some weeks ago Letsencrypt changed their root & intermediate certificates (see https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html).
When I use the newly generated cert with an R3 intermediate the Nextcloud Desktop-Client warn and doesn't connect to the server.
Access via browser works without problems, also on iPhone app no issues.

Is this issues known to you developers and do you plan to implement a solution?

Thanks!
a2

**Comment by er-vin** [comment]
I'm using Let's encrypt as well for my personal server and I don't have that issue. I suspect this is your system SSL keychain which doesn't contain the new root and intermediate certificates for let's encrypt (it's what Qt uses by default). You might not see it with browsers because they tend to ship their own certificate chains with their updates.

Which system is that BTW? And which version of the client are you using?

**Comment by abrain** [comment]
> Which system is that BTW? And which version of the client are you using?
It wasn't mentioned in the description, but the title suggests Client version 3.1.1 on macOS.

I'm using macOS 10.15.7 with Nextcloud Client 3.1.1 and it connects without any issues to a server with an R3-signed certificate.

**Comment by aquadraht** [comment]
Hi, 
excuse my late answer.
I'm using the client v3.1.1 and the server OS is debian jessie which is outdated and probably the source of my problem. I'll investigate the OS and the intermediate certificates.

Thank you,
a2

**Comment by er-vin** [comment]
OK, so indeed looks like a stable SSL certificate chain. Closing this.
