### ISSUE TITLE
"nextcloud" app is written lowercase in macOS applications list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2898]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The name is written "Nextcloud" as usual.

### Actual behaviour
In the applications list, and also when searching with spotlight, it’s lowercase "nextcloud".

### Client configuration
Client version: 3.1.1

Operating system: macOS

OS language: German

**Comment by elsiehupp** [comment]
This is almost certainly due to an issue in [MacOSXBundleInfo.plist.in](https://github.com/nextcloud/desktop/blob/aa6f5f59c437ed244c949857b2bbb6b961d59d0a/cmake/modules/MacOSXBundleInfo.plist.in), which appears to be missing key-value pair
```
<key>CFBundleDisplayName</key>
<string></string>
```

**Comment by elsiehupp** [comment]
The [`plist` template for Nextcloud Extensions](https://github.com/nextcloud/desktop/blob/4b985ab3b322d18773c76e1d1afd6cbad3cdbba2/shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/Info.plist) includes the following key-value pair:
```
<key>CFBundleDisplayName</key>
<string>$(OC_APPLICATION_NAME) Extensions</string>
```
So I could try adding
```
<key>CFBundleDisplayName</key>
<string>$(OC_APPLICATION_NAME) Desktop</string>
```
to MacOSXBundleInfo.plist.in.

**Comment by er-vin** [comment]
Thanks. If you can try it that'd be welcome of course.

**Comment by elsiehupp** [comment]
This has turned out to be a bit of a rabbit hole, but I've made a lot of progress!

**Comment by elsiehupp** [comment]
To summarize what I found, basically the problem is that the norm on macOS is for the application package to have the same name as the executable, and `cmake-qt` consequently uses the executable name for the macOS application package. My previous thought regarding `CFBundleDisplayName` doesn't work because CMake doesn't support writing it from a variable (unlike Xcode, which apparently does), so it wouldn't be possible to theme.

One workaround would be to use the themed variable `APPLICATION_SHORTNAME` for the main Qt target and the executable name on macOS but not on any other platform. The reason I suggest `APPLICATION_SHORTNAME` rather than `APPLICATION_NAME` is that while Qmake supports spaces in Target names, Cmake flips out if you try to do that. Basically, the short name would be required not to have spaces or any other illegal characters in it.

Obviously this workaround would involve significant mucking around in `CMakeLists.txt` (and other makefiles), so it isn't something I would be particularly well equipped to take on myself.

**Comment by elsiehupp** [comment]
To emphasize/clarify: the variables for naming the macOS application package in the existing CMake script don't actually appear to do anything, due to the fact that CMake just uses the executable name. There might actually be some entanglement between the two variables; you could try changing the themed executable name from `nextcloud` to `nextcloudexec` (i.e. not just a lowercase version of the application shortname) to suss out where exactly the CMake script is using it instead of the application name or the application shortname. What I found when playing around with the three name variables was that the components of the application ended up being split between two or more different packages with the different names.

**Comment by elsiehupp** [comment]
Oh, and I noticed that the `Info.plist` uses a version of the application name with spaces replaced with dashes, which is unnecessary (though not particularly noticeable to the end user).

Also there are tons and tons of places where the application uses OwnCloud metadata, which could probably be phased out, though admittedly I can imagine that being a low priority due to the overhead of debugging.

**Comment by elsiehupp** [comment]
I decided to do a quick test with alternate theme values to see what ended up where. These are the OEM values:
```
set( APPLICATION_NAME       "Nextcloud" )
set( APPLICATION_SHORTNAME  "Nextcloud" )
set( APPLICATION_EXECUTABLE "nextcloud" )
```
I replaced them with these values:
```
set( APPLICATION_NAME       "Whiskey" )
set( APPLICATION_SHORTNAME  "Tango" )
set( APPLICATION_EXECUTABLE "Foxtrot" )
```
And the values appeared in the following places:
```
Foxtrot.app (no icon)
Foxtrot.app/Contents/Frameworks/libFoxtrot_csync.0.dylib
Foxtrot.app/Contents/Frameworks/libFoxtrotsync.0.dylib
Foxtrot.app/Contents/MacOS/Foxtrot
Foxtrot.app/Contents/MacOS/Foxtrotcmd
Foxtrot.app/Contents/MacOS/libFoxtrot_csync.3.1.50.dylib
Foxtrot.app/Contents/MacOS/libFoxtrot_csync.dylib
Foxtrot.app/Contents/MacOS/libFoxtrotsync.3.1.50.dylib
Foxtrot.app/Contents/MacOS/libFoxtrotsync.dylib

CFBundleExecutable Foxtrot
CFBundleIconFile Nextcloud.icns
CFBundleIdentifier com.nextcloud.desktopclient
CFBundleLongVersionString Whiskey 3.1.50git

UTTypeIdentifier com.nextcloud.desktopclient.VIRTUALFILE
public.filename-extension nextcloud
CFBundleTypeName Foxtrot Download Virtual File
LSItemContentTypes com.nextcloud.desktopclient.VIRTUALFILE

CFBundleDisplayName: Whiskey Extensions

/Users/elsiehupp/Library/Preferences/Whiskey 
/Users/elsiehupp/Library/Preferences/Whiskey/Foxtrot.cfg
2021-02-21 10:46:36:508 [ info nextcloud.gui.application ]:	"################## Tango locale:[en_US] ui_lang:[] version:[3.1.50git] os:[macOS 11.2]"
```
I backed up my settings and tried running `Foxtrot.app`; because the name was different, it didn't seem to read my existing preferences, but neither did it crash on startup. I didn't test to see if there were any other errors, though.
