### ISSUE TITLE
How to geneate qt creator or xcode project

### ISSUE THREAD

**Issue by wxz879526** [nextcloud/desktop#2956]
How to geneate qt creator or xcode project

**Comment by FlexW** [comment]
To open the project in QtCreator just open the `CMakeLists.txt` file in QtCreator. 

The best way to configure the project and open it in QtCreator is in my opinion to build the project from the command line and then open the project via the `CMakeLists.txt` in QtCreator and then import the existing `build` folder in the project wizard.

You can find the build instructions [here](https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client).

@elsiehupp If you have some extra time you could add an explanation on how to open the project in an IDE ;)

**Comment by elsiehupp** [comment]
As far as Xcode goes, the main project actually generates its Xcode project dynamically during the CMake build process, so it isn't really feasible as an IDE for Nextcloud desktop. (The Finder Extensions have a conventional Xcode project, though.)

As far as using an IDE goes, [VS Code](https://code.visualstudio.com/) is free and cross-platform, and it has third-party integrations to support the wide variety of languages and libraries used by Nextcloud Desktop. There isn't a documentation section explaining how to set up a VS Code workspace, but one could be added at some point down the line.

It's presumably also possible to use the Community Edition of the non-free Visual Studio, but there are significant differences between Windows and Mac, and there isn't a version for Linux, so it's less feasible to document how to use it for developing Nextcloud Desktop.

I have zero experience with Qt Creator.

**Comment by er-vin** [comment]
This is a CMake project, you can use any IDE which understands CMake (like QtCreator or VS Code if you install the CMake support). I don't think it's wise to add documentation on how to deal with specific IDEs.

**Comment by elsiehupp** [comment]
IMHO VS Code, again, has the advantage that it's probably the only IDE other than QtCreator that has support for all three of Linux, macOS, and Windows. The idea with adding a (brief) IDE setup guide is, like the guide for setting up the build environment, to create a minimum viable IDE environment, with the explicit caveat that it's not the only (or even the best) way of doing things, just the simplest-to-explain way to get people up and running.

Obviously this is a low priority, and would only potentially happen after the main build instructions and everything have already been updated. Past a certain point any onboarding instructions would have to be further broken down into subsections, because the build instructions alone are already getting quite lengthy. Having multiple subsections would allow the documentation to expand further without getting too unwieldy, and FWIW not everything necessarily has to go in the main documentation. We can discuss it when we get there.
