### ISSUE TITLE
Tray window opens at startup

### ISSUE THREAD

**Issue by tamis-laan** [nextcloud/desktop#3056]
When starting the app the tray popup window automatically opens. 
Because I'm on a tilling window manager it opens as a large window and does not close automatically. 

How do I prevent or event better disable this pop up window? I have never found a use for it anyway.

**Comment by FlexW** [comment]
Which window manager and status bar do you use? Have you support for tray icons? At least for me on i3 (with i3bar) the main dialog never pops up if the app starts. Also on my side the popup is treated like a foreground dialog and does not fill a whole tile. It's not possible to disable the main dialog.

**Comment by FlexW** [comment]
Now I'm really curious which window manager you use?

I'm not an expert in this area but I think in the last instance the window manager decides how a window is displayed. So for example we set on the main dialog that it should be treated as a dialog. It's then up to the window manager to full fill this contract. So for example in i3 you can configure which windows should be treated as dialogs and which not.

Anyway the main dialog should not popup after the start. Which program do you use to display tray icons?

**Comment by tamis-laan** [comment]
I'm using qtile window manager.

"Anyway the main dialog should not popup after the start. Which program do you use to display tray icons?"
It no longer pop up when I start, however it is drawn as a "regular window" and not as a "pop up window" this causes qtile to draw a border around the window. Other tray apps when you click on them do not have a border around the popup window.

**Comment by FlexW** [comment]
> Other tray apps when you click on them do not have a border around the popup window.

That may be the case because these windows/menus are part of the tray icon. For example if you right click on the Nextcloud tray icon, I expect that dialog that opens then, to also have no borders on your side because this menu is part of the tray icon implementation. The main dialog is indeed a regular window and is independent of the tray icon implementation. However, we set the frameless window and dialog hint on the main dialog. Maybe qtile does not respect that hint? Would be interesting to create a small Qt test application that sets the frameless window hint and then see how qtile draws that window. If it does draw the window with borders, then qtile is misbehaving.

https://doc.qt.io/qt-5/qtwidgets-widgets-windowflags-example.html

**Comment by m-col** [comment]
Hey there, I've come over from Qtile to see if we are managing this wrong. From what I can tell we are managing it correctly based on the information provided by the window. As the window does not set Qt's "X11 bypass window manager" flag, the window gets managed by Qtile. This results in it being bound to a specific desktop and getting window decorations. Default floating rules make it float because it is a dialog. This is the same management you'd expect on, for example, a "Select a file" window. I think the confusion here comes from the expectation that this tray window not be treated in this way and instead not be managed by the window manager at all. This results in a window not being bound to a specific desktop and not receiving window decorations. An example of this kind of window is Firefox's own notification windows, which are visible on all desktops (even when switching between them) and do not receiving decorations:

![image](https://user-images.githubusercontent.com/44536113/113506324-17837680-953c-11eb-9c52-5d9c8aabb74c.png)

I believe this is what @tamis-laan is expecting from the tray window, and I suspect to get this behaviour that the "X11 bypass window manager" flag would need to be set.

**Comment by m-col** [comment]
I just installed i3 to test it out and it does seem like they are handling it slightly differently (not giving it a title bar and border) but I'm familiar with i3's configuration or default settings so it could be a rule-based "do not decorate" thing. If we can identify that then it might make sense to implement something similar in Qtile.

**Comment by m-col** [comment]
I investigated this a bit deeper and I've summarised what's going on on the Qtile thread [here](https://github.com/qtile/qtile/issues/2342). FWIW I think there is no issue with what the Nextcloud client is doing (though perhaps it may want to bypass the window manager, which would be more consistent with other from-the-systray windows). It's probably unrelated but I noticed that on both Qtile and i3 the rounded corners are actually filled in with black pixels.

**Comment by FlexW** [comment]
> It's probably unrelated but I noticed that on both Qtile and i3 the rounded corners are actually filled in with black pixels.

I noticed that too.

I think there can nothing be done from our side and everything works as expected. Please tell me if you think different.
