### ISSUE TITLE
icon display error on mac menu bar when connect two screens

### ISSUE THREAD

**Issue by 81pla** [nextcloud/desktop#3064]
### Expected behaviour
icon should display same on mac menu bar when i connect two screens

### Actual behaviour
one screen icon display normal on menu bar, the other screen (The mouse is not on this screen ) display error.

![image](https://user-images.githubusercontent.com/17949410/113651903-6e688780-96c5-11eb-9b79-abe9dc8b047d.png)
![image](https://user-images.githubusercontent.com/17949410/113651915-7294a500-96c5-11eb-8915-15603f6d5118.png)

Whether to use Monochrome icons or not

### Steps to reproduce
The mouse is on which screen,the icon can display normal

### Client configuration
Client version: the latest stable client 

Operating system: macOS Big Sur 11.2.3

OS language: Chinese

Installation path of client: /Applications/nextcloud.app

### Client logfile
i can't upload zip on here.

**Comment by 81pla** [comment]
its the client logfile
http://101.132.162.107/debug.zip

**Comment by elsiehupp** [comment]
This is a [known issue](https://github.com/nextcloud/desktop/issues/2584) with the version of Qt used for Nextcloud’s release builds. The squished icon appears to be fixed in Qt 5.15.1, but the oversized icon only appears to be fixed in Qt 5.15.3, which isn’t available to Nextcloud because Qt’s licensing is structured in such a way as to “strongly encourage” open-source Qt licensees to migrate to Qt 6.

**Comment by elsiehupp** [comment]
Closing because this is a duplicate, but if you’d like, you can follow any subsequent progress over on the other Issue: https://github.com/nextcloud/desktop/issues/2584
