### ISSUE TITLE
Remove need for a system tray

### ISSUE THREAD

**Issue by stobbsm** [nextcloud/desktop#3094]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On many linux distributions (Fedora, elementary os, anything with modern Gnome), the system tray has been deprecated for a long time. I propose adding a check for the system tray on startup, and having the window stay in the foreground where it can be minimized if it is not found.

### Actual behaviour
On the effected distros, no system tray shows up, and no indicators or notifications are displayed. This is obviously a bad thing.

### Steps to reproduce
1. Open nextcloud client on one of the effected OS's
2. Go through the setup wizard
3. No tray icon means the window is completely gone without notifications of sync issues.

### Client configuration
Client version: Any with a system tray

Operating system: Linux with modern gnome without extensions

OS language: English, although I doubt this has any effect

Client package (From Nextcloud or distro) (Linux only): Snap, flatpak, compiled from source, or system package

Installation path of client: Doesn't have any effect.

**Comment by stobbsm** [comment]
Not an expert in modern C++, but I expect it could be handled with a check to https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable
`bool QSystemTrayIcon::isSystemTrayAvailable()`

**Comment by FlexW** [comment]
I think it's not as easy as adding a check for the system tray. The clients user experience is built around that tray icon. I think this was done to align it more with services like DropBox and OneDrive to make it users easier to transition to Nextcloud. It's unfortunate that GNOME killed tray icons. Maybe @jancborchardt can say more about it.

**Comment by mortie** [comment]
So, in my view, the icon provides the following features:

1. It's the easiest way to access the "Settings" screen
2. It reassures to the user that Nextcloud is in fact running
3. It tells the user about any connection/sync issues
4. It tells the user when Nextcloud starts syncing, and when it's done syncing, so that the user knows when it's safe to suspend or shut down the machine

I believe that GNOME's replacement for these features would be:

1. The "Settings" screen can be accessed through the applications menu or otherwise through launching the Nextcloud app
2. Nextcloud should always be running, it should never fail to start, never crash ([easier said than done](https://bugs.launchpad.net/ubuntu/+source/nextcloud-desktop/+bug/1923053))
3. It can send a notification if it's unable to connect to the server
4. The user shouldn't need to know when syncing starts and stop, because Nextcloud should inhibit suspension and shutdown until it's sure that all changes are synced

An observation is that the "Main" screen is less useful when there's no app icon. To me, it never really worked extremely well and was just an extra step inbetween me and the settings screen anyways, but it makes even less sense when there's no icon.

**Comment by stobbsm** [comment]
I was thinking just letting the application icon open the main screen, allowing for a minimize functionality, and allowing the main window to be opened is enough. Those of us without a system tray are used to having the main window open.

Basically, as it stands now, the client is useless to those like me. It already has a main window, why not just let that be minimizable, instead of having a hard requirement on something that may or may not exist?

**Comment by elsiehupp** [comment]
From my understanding of GNOME’s approach to the “System Status Area”, the best way to get Nextcloud to work without a tray icon on GNOME would be to contribute to the upstream code. I don’t fully understand how `libcloudproviders` works, but the issue seems to be that it assumes cloud directories should be treated like virtual drives and doesn’t account for the ability to synchronize arbitrary local folders.

Probably the approach to take with contributing to upstream code would be to fully segregate Nextcloud’s `libsync` from the Qt frontend and incorporate some degree of support for it into both the [GNOME Shell](https://gitlab.gnome.org/GNOME/gnome-shell), [Gnome Settings](https://gitlab.gnome.org/GNOME/gnome-control-center), and [GNOME Online Accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts). Fully segregating the frontend and only interacting with it through a documented API would also allow the frontend and the backend to run as separated processes, which may improve stability and responsiveness. In this scenario, the Nextcloud Desktop client would be a secondary frontend that might even be optional; to that effect the backend should deliberately support multiple simultaneous frontends.

Of course, this would all be a substantial undertaking, and I personally wouldn’t be in a position to do most of it myself, lol.

**Comment by FlexW** [comment]
The need for a system tray was removed with 3.3.0.

**Comment by ml4nC3** [comment]
I'm sorry but I just installed 3.10 through Appimage because Arch repo ar still on 2.3, and I still don't see any way of opening the nextcloud window without systray icon...

**Comment by ml4nC3** [comment]
> I'm sorry but I just installed 3.10 through Appimage because Arch repo ar still on 2.3, and I still don't see any way of opening the nextcloud window without systray icon...

Ok... We have to run the application twice to get it...

**Comment by elsiehupp** [comment]
> The need for a system tray was removed with 3.3.0.

Regarding running without the system tray, I've been running Nextcloud Desktop on elementary OS, and while it does basically work it's not always clear whether it's running in the background, and various random little things are still kind of janky, presumably because of differences in assumptions between desktop environments. I should probably try and open some issues related to this, but I don't know how, e.g., dark mode or interface scaling or the dock work in elementary OS, so it would take me a while to figure out where to start.

**Comment by nekohayo** [comment]
> Regarding running without the system tray, I've been running Nextcloud Desktop on elementary OS, and while it does basically work it's not always clear whether it's running in the background, and various random little things are still kind of janky, presumably because of differences in assumptions between desktop environments. I should probably try and open some issues related to this, but I don't know how, e.g., dark mode or interface scaling or the dock work in elementary OS, so it would take me a while to figure out where to start.

I filed the required issue here: #10162
