### ISSUE TITLE
Tray Menu Improvment

### ISSUE THREAD

**Issue by DarXas** [nextcloud/desktop#3235]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

**Here is my suggestion for the improvment of the current tray menu:**

![Improved Tray Menu](https://user-images.githubusercontent.com/83289920/116600561-b9bf3000-a929-11eb-8191-a66688a70275.jpg)

* There should be some kind of sorting function to communicate relevant information better
  (e.g. by the use of tabs and prioritization of important messages - *currently just sorted by time of notification*)

* The status indicator should be better visible on a quick glance (located in the empty space between profile and files)

### Related Issue

Improved tray menu #877

**Comment by splitt3r** [comment]
I think it looks way to cluttered in your version.

**Comment by elsiehupp** [comment]
I’ve had some similar thoughts regarding introducing more hierarchy in the tray menu, but I would do so using native menu widgets, rather than the completely custom interface that currently exists.

For example, aggregating notifications by type and listing a summary with tallies could help make large numbers of notifications easier to visually parse. The individual notifications could then be in a submenu or behind a disclosure triangle.

One of the advantages with native menu widgets is that they are much easier to bring in compliance with the native GUI skin, which they inherit from Qt, whereas [the existing fully custom view is stubbornly alien on every platform](https://github.com/nextcloud/desktop/issues/3094).

(I personally think there should be some redundancy in terms of facilities for the user processing large numbers of notifications. That is, it could make sense to have something like a sortable spreadsheet view in the Settings app that could persist on screen while the user clicks through on notifications one by one. This would be particularly useful for acting on multiple sync-conflict notifications, for example.)

**Comment by FlexW** [comment]
We decided to go with a little bit different approach: The current conclusion is that tabs will complicate the interface and will hide information from the user. Closing in favour of https://github.com/nextcloud/desktop/issues/3644
