### ISSUE TITLE
windows server os

### ISSUE THREAD

**Issue by ctyjiuh** [nextcloud/desktop#3262]
Hi team.
Do you plan to release a nextcloud desktop client for Windows Server OS family?
Particularly I'm interested in Windows Server 2016 as it is involved in our VDI service due to Datacenter Edition licensing.

**Comment by mgallien** [comment]
I do not have access to Windows Server 2016 right now but I would say that this should be supported.

Which version did you try ?

I would recommend to start with previous stable version 3.1.3 because we added some versions check in newer one that might be buggy with respect to Windows Server detection.

**Comment by lucasgruembel** [comment]
Hello Matthieu,
we have the same problems. Our customers usually work with Windows Server 2016/2019 Standard Terminalservers.
With the latest version 3.2.1, the installation / update on Windows Server 2016 Standard (1607) failed due to the version check. We had no problems with version 3.2.0 on these systems.
Under Windows Server 2019 Standard (1809) we had no problems with the installation / update.
I think this is caused by the version check due to "1709 and above".
Please add the Windows Server 2016 versions to the allowed versions. This is an extended support version of Windows Server and will be supported by Microsoft until December 1st, 2027.
Thanks in advance!
![image](https://user-images.githubusercontent.com/72384754/117141225-958ea380-adae-11eb-9fc6-09c6cf5c29e0.png)

**Comment by ctyjiuh** [comment]
I got the same error.

**Comment by mgallien** [comment]
> Hello Matthieu,
> we have the same problems. Our customers usually work with Windows Server 2016/2019 Standard Terminalservers.
> With the latest version 3.2.1, the installation / update on Windows Server 2016 Standard (1607) failed due to the version check. We had no problems with version 3.2.0 on these systems.
> Under Windows Server 2019 Standard (1809) we had no problems with the installation / update.
> I think this is caused by the version check due to "1709 and above".
> Please add the Windows Server 2016 versions to the allowed versions. This is an extended support version of Windows Server and will be supported by Microsoft until December 1st, 2027.
> Thanks in advance!
> ![image](https://user-images.githubusercontent.com/72384754/117141225-958ea380-adae-11eb-9fc6-09c6cf5c29e0.png)

Thanks for the info.
We are currently requiring 1709 version due to the addition of Virtual drive support on Windows that require an API that was introduced on 1709 release.
I will check what is the status in Windows server editions.

From what I understand in your message, you had no missing dll error dialog ?

**Comment by lucasgruembel** [comment]
I tested a bit and got following results:
if i install "Nextcloud-3.2.1-x64.msi" normally, the message apperes and the installation adort, but no .dll error (see following log)
[InstallNextCloudClient3.2.1_orginal-installer.log](https://github.com/nextcloud/desktop/files/6428068/InstallNextCloudClient3.2.1_orginal-installer.log)

if i remove the LaunchCondition with orca.exe from "Nextcloud-3.2.1-x64.msi", i can install the Client.
[InstallNextCloudClient3.2.1_without-LaunchCondition.log](https://github.com/nextcloud/desktop/files/6428069/InstallNextCloudClient3.2.1_without-LaunchCondition.log)
But i get the following error, if i start the application (like it was in Version 3.2.0 without the LaunchCondition by default):
```
---------------------------
nextcloud.exe - Systemfehler
---------------------------
Das Programm kann nicht gestartet werden, da CLDAPI.dll auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben. 
---------------------------
OK   
---------------------------
```

is there the possibility, to make this "Virtual drive support" feature optional for installation, for future support of [Windows Server 2016](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2016) and [Windows 10 2016 LTSB](https://docs.microsoft.com/en-us/lifecycle/products/windows-10-2016-ltsb)?

**Comment by nanaya** [comment]
Making the "cloud files" feature optional means it should also work with windows 7 and 8.1... :eyes: 

And I would be surprised if qt6 supports windows 2016 considering it targets 1809 minimum which is higher than the current 1709 one (the other reason for dropping 7/8.1 support).

**Comment by lucasgruembel** [comment]
Hello, any Updates here?

**Comment by PlantafelAdmin** [comment]
any update?

**Comment by calvinthefreak** [comment]
The Problem is still there... I am running an Win2016 Server for RDP Access into my Network... and I want my files to be there also...

**Comment by techguyalabama** [comment]
Having the same problem on Windows 2012 R2 as of release 3.2.1. It was working fine until this update now I cannot install the update. Says the operating system is not supported.

**Comment by berberisD** [comment]
Same problem on our Win2016-RDP servers here. Find soluton please ..

**Comment by nanaya** [comment]
It looks like 3.3.0 will support ws2016 again (among other windows versions). Related pr: #3437.

**Comment by rschitz** [comment]
NC was running fine under Windows 2012R2 until version 3.1.3
Many of us use desktops on windows server, some cloud providers even offer VDI that way so do not make the mistake to lock NC on "desktop" version of Windows only, you'll loose customers and community...

`You have nextcloud-client v3.1.3 installed. Version 3.3.0 is available based on your source(s).
Progress: Downloading nextcloud-client 3.3.0... 100%

nextcloud-client v3.3.0 [Approved]
nextcloud-client package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: nextcloud-client requires Windows 10
The upgrade of nextcloud-client was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nextcloud-client\tools\chocolateyinstall.ps1'.
 See log for details.`

**Comment by nanaya** [comment]
I think that's on chocolatey side as they seem to [not have updated the version requirement check](https://community.chocolatey.org/packages/nextcloud-client).

**Comment by rschitz** [comment]
This was with the NC installer on version 3.2.3
![image](https://user-images.githubusercontent.com/8385646/128677726-3c30acf6-3127-478a-88d0-87755b0a2194.png)

Now with 3.3.0 the installation is fine, my bad.
Thanks @nanaya

**Comment by FlexW** [comment]
I think this can be closed now.

**Comment by TheCakeIsNaOH** [comment]
@nanaya The check has been removed in the latest version of the Chocolatey package. It should be installable on older versions of Windows now.
https://community.chocolatey.org/packages/nextcloud-client/3.3.1.20210824
