### ISSUE TITLE
ENFORCE: "allow_failure" in file ./src/common/ownsql.cpp, line 265 with message: SQLITE Prepare error

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/desktop#3302]
ruediger@helge:~$ nextcloud 
2021-05-10 19:24:51:820 [ fatal default ]:	ENFORCE: "allow_failure" in file ./src/common/ownsql.cpp, line 265 with message: SQLITE Prepare error
Abgebrochen (Speicherabzug geschrieben)

**Comment by FlexW** [comment]
Did you downgrade the client? This error usually occurs if the sync journals schema is not compatible with the schema the client expects.

**Comment by affinityv** [comment]
I have this message, I did downgrade the client to match that of other machines and due to the fact that my NC server is not new enough.  How do I fix it at the client end, or do I need to do something at the server end to fix it?

**Comment by FlexW** [comment]
You just need to delete the sync journal. These are the files starting with `.sync` in the folder you want to sync. I'm closing this now, as there is not much we can do.

**Comment by ChristianNext** [comment]
In my case: after removing ._sync* it worked again. Tks FlexW.

**Comment by pikurasa** [comment]
I experienced this as well, and I recommend that, if possible, the client should display a message to the user the next time it opens.

I suggest this because, if you open the client without using the terminal you don't see that error message, so you're pretty clueless as to why it crashes.

And, if it is also possible, it might be nice to have a button that says "delete .sync files" -- or at least gives instructions on how to troubleshoot.
