### ISSUE TITLE
Optimize the Overlay Icons of Finder Integration

### ISSUE THREAD

**Issue by iaurman** [nextcloud/desktop#3321]
I know someone else has requested to disable the overlay icon before. Your replied "the requests for this are quite low". Well it's not.
![finder](https://user-images.githubusercontent.com/46162162/118374376-5c480600-b5ee-11eb-9cb0-73d5f069b464.jpg)
I know the icon is an necessary indicator. But at least it's not done elegantly.
Every folder looks the same only except those are integrated with nextcloud. It doesn't look nice or unified.

Apple's iCloud also uses overlay icon. But it's a well designed mono icon. And it only shows when a file is not synchronized. When everything is synchronized, the overlay icons disappear, leaving the interface looks clean and unified. It's so much better.
![icloud1](https://user-images.githubusercontent.com/46162162/118374958-33754000-b5f1-11eb-8307-9889b5f88659.jpg)
![icloud2](https://user-images.githubusercontent.com/46162162/118375022-9c5cb800-b5f1-11eb-818f-e866be93f2ff.jpg)

Now look back to the overlay icon of nextcloud finder integration... it looks ugly.
Until the icon gets optimized, some people like me will not integrate nextcloud into their finder.
I can't bear such thing exist in my finder.

Regards.

**Comment by FlexW** [comment]
@jancborchardt thoughts?

**Comment by 1ndeed** [comment]
I just found out that dropbox also uses the same thing. But at least they offer an option to disable it like I said!

And I found that you can disable it in the Preference with no side effects.
![see](https://user-images.githubusercontent.com/46162162/120068547-c3b48a00-c0b3-11eb-862b-771da3898746.jpg)

Wouldn't it be nice if nextcloud just put this in the setting menu instead of letting us research your app?

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
