### ISSUE TITLE
Ubuntu: Add $RECYCLE.BIN to ignore list

### ISSUE THREAD

**Issue by torrbox** [nextcloud/desktop#333]
When using the same Nextcloud folder on Ubuntu 18.04 and Windows 7 (dual boot), Ubuntu will upload all files that were deleted on Windows. Adding $RECYCLE.BIN to the ignore list solves this.

The client used is the one from "Ubuntu Software", not AppImage, in case it matters.

**Comment by k1l1** [comment]
I could add it to the _sync-exclude.lst_ file

**Comment by camilasan** [comment]
> I could add it to the _sync-exclude.lst_ file

I second that.

**Comment by tilllt** [comment]
i am voting to reopen this issue, and generalize it for all sync clients, since it does not seem to be resolved. I have "$RECYCLE.BIN" on my exclude list, still the desktop client (Version 3.6.2) on windows (Windows 11 Pro 22H2)  is complaining every time that it cannot sync it since it is a reserved name.

![grafik](https://user-images.githubusercontent.com/1854364/201291257-d2acbaab-d1e1-472d-a22c-a5f60e993c9d.png)

![grafik](https://user-images.githubusercontent.com/1854364/201291308-59b623ba-50a8-416c-a471-27ef1ac1475a.png)



also see https://help.nextcloud.com/t/recycle-bin-download-client-windows/30073/10
