### ISSUE TITLE
Windows client should display that it is unable to retrieve a file/folder due to windows naming constraints

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/desktop#3414]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The windows client does not sync files and folders which do not meet the naming allowed in windows. For example folders with a trailing dot in the name. See for example this bug report: https://github.com/nextcloud/server/issues/18066

**Describe the solution you'd like**
The windows client should report new files and folders it will not sync in the Activity log as it does with other sync issues. Currently there is only a generic message listing a few folders and it only mentions the ignore list and symbolic links. Not for example that the actual issue is a windows naming constraint.

**Describe alternatives you've considered**
Trying to find a message  in the debug log. But that is not for a normal user.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue with logs.
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file. 
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)

Thanks!
