### ISSUE TITLE
Enable Windows Server Support again for desktop app

### ISSUE THREAD

**Issue by IdefixRC** [nextcloud/desktop#3416]
Hi,

I'm running a Windows Server 2016 and have issues getting any version of the desktop sync app > 3.1.3 to install.
The app complains it needs Windows 10 version 1709 or higher (the Windows 2016 server runs the latest available patch level).

Thanks !

**Comment by andyxheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/121224544-4aa0f980-c84e-11eb-9773-6bea6a460831.png)

**Comment by andyxheli** [comment]
Since 3.2.X supports virtual files my guess is that's why Nextcloud  put the warning about 1709 on install 
 

Per Microsoft below comments. I would think there would need to be a different client for Server Support. 

A sync engine is a service that syncs files, typically between a remote host and a local client. Sync engines on Windows often present those files to the user through the Windows file system and File Explorer. Before Windows 10, version 1709, sync engine support in Windows was limited to scenario-agnostic ad-hoc surfaces, such as File Explorer’s navigation pane, the Windows system tray, and (for more technical applications) file system filter drivers.

Windows 10 version 1709 (also called the Fall Creators Update) introduced the cloud files API. This API is a new platform that formalizes support for sync engines. The cloud files API provides support for sync engines in a way that offers many new benefits to developers and end users.

https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine

**Comment by andyxheli** [comment]
@FlexW Dup of https://github.com/nextcloud/desktop/issues/3378 ?

**Comment by FlexW** [comment]
@andyxheli thanks for your explanation. Yes it's a duplicate.

**Comment by andyxheli** [comment]
@FlexW You're Welcome! Thank you for the quick response. Here's mine Server 2016 Im guessing @IdefixRC might be on the same version "mine 2016 server version is also getting that warring on install" 

![image](https://user-images.githubusercontent.com/59488153/121250274-29023b00-c86b-11eb-86b7-c5d2118049a0.png)

**Comment by FlexW** [comment]
@andyxheli @IdefixRC I've checked again the documentation and Microsoft says that the cloud provider API is only available for Windows Server 2019 and not 2016. No matter how updated your Windows 2016 server is. I close this now because the Windows server is and was never officially supported. To run the client on older Windows servers the solution is for now to run client version 3.1.3.

Reference: https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-10-0e6860d3-d9f3-4971-b321-7092438fb38e

**Comment by andyxheli** [comment]
@FlexW thanks for looking into that. I figured that was the case. I was doing some reading last night as well and a lot of comments not supporting server 2016.

**Comment by FlexW** [comment]
There will eventually be a solution to this problem, but I will make no promises.

**Comment by andyxheli** [comment]
@FlexW Maybe there can be a document or a disclaimer that would show supported operation systems version based on the nextcloud client version so maybe on the NX 3.2.X Support Windows 10 Version 1709 and above and Server 2019 above. ? Then the users or systems admins would know what to install based on there Operating System. Dose that make sense

**Comment by andyxheli** [comment]
Never mind that makes sense. Completely understand. Thank you :)
