### ISSUE TITLE
First Syncing takes too long time

### ISSUE THREAD

**Issue by vgdh** [nextcloud/desktop#3509]
### Expected behaviour
After a clean installation, I start NC in virtual files mode.
It must just start working.
 
### Actual behaviour
It starts searching for a change in files. But local folder is empty. What changes it gonna find?
I have more than 300000 files on a server, and it take sooooooo much time for searching changes in empty space. )))

### Steps to reproduce
1. Try to sync files with "virtual files" option

Client version: 2.3.2 Win

Operating system: win10 19043.1055

OS language: rus

Installation path of client: default

All application settings are on default.

**Comment by camilasan** [comment]
Make sure you are running the latest recommended version of the desktop client and of the server. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If the error still occurs after upgrading then re-open the issue and **do not forget to post the logs**:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file. 

Thanks!
