### ISSUE TITLE
3.2.3 and newer: build from release tarball now requires inkscape dependency (should be optional)

### ISSUE THREAD

**Issue by voyageur** [nextcloud/desktop#3518]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Issue
3.2.3 includes #3466 backport for icons generation. This made inkscape a (large) mandatory build dependency, while default Nextcloud_*.png icons are still available in tarball.

When building with this icons, inkscape should be an optional dependency (either checked only if image build/rebuild is needed, or deactivatable via a configure option)

Downstream bug: https://bugs.gentoo.org/800857
Workaround patch applied for 3.2.3: https://gitweb.gentoo.org/repo/gentoo.git/diff/net-misc/nextcloud-client/files/nextcloud-client-3.2.3-inkscape.patch

### Client configuration
Client version: 3.2.3

Operating system: Gentoo Linux
Qt version used by client package (Linux only, see also Settings dialog): 5.15.2
Client package (From Nextcloud or distro) (Linux only): Gentoo ebuild from source

### Logs
CMake Error at src/gui/CMakeLists.txt:245 (find_program):
  Could not find INKSCAPE using the following names: inkscape, inkscape.exe

-- Configuring incomplete, errors occurred!

**Comment by camilasan** [comment]
Sorry but we had to remove the png files: #3536 
We do need to require inkscape.

**Comment by pprkut** [comment]
@camilasan Do you perhaps have a link to a previous issue/pull request that explains this further? Or can elaborate? Because with the information here, that makes absolutely no sense. Whatsoever.

**Comment by FlexW** [comment]
@pprkut We introduced the Inkscape dependency because we do branding for clients and it easier for them to provide the assets as svg files. As svg files can not directly be used as for example executable icons, we decided to use Inkscape to convert them to actual png files. It was decided that it would be the best and most portable to do it directly in CMake.

**Comment by pprkut** [comment]
@FlexW Thank you! That part makes sense, and for builds from git that seems fine to me as well. However, having releases depend on inkscape seems not really ideal. Wouldn't there be a way to publish source tarballs with pre-rendered pngs?
Or support tools other than inkscape to generate them?

I'm not gonna depend on inkscape for my packaging, since that isn't even part of our core distro and adding it just to generate a handful of pngs seems disproportionate in effort. I'd either pre-render the pngs and patch the build to use those, or alternatively look into other ways to generate pngs, like `rsvg-convert`.

**Comment by FlexW** [comment]
@pprkut If you know an easy way to generate the release tarballs with pre-rendered png images in an automated way, then please submit a pull request or tell me how to do it, otherwise I don't see that happen soon because that is not really a priority at the moment :)

I was not aware of `rsvg-convert`, but that might be an alternative to inkspace. We could modify the CMake scripts in a way that they either use `rsvg-convert` or `inkscape`. Are you feeling up to the challenge of adding support for it? You would just need to modify the `find_program` calls to inkscape in `src/gui/CMakeLists.txt` and the function `generate_sized_png_from_svg()` in the same file.

**Comment by pprkut** [comment]
I'm fine trying :)
Will have to wait for the weekend though
