### ISSUE TITLE
VFS not show files which contains a : in filename

### ISSUE THREAD

**Issue by AndreKoepke** [nextcloud/desktop#3544]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I can see all files in VFS.

### Actual behaviour

https://user-images.githubusercontent.com/15613049/126009373-979c100d-313e-4a65-afe3-1baff5d50592.mp4

(Sometimes you have to press `F5` to see the action)

### Steps to reproduce
1. Just add `:` somewhere in the filename.
2. The file will disappear.

### Client configuration
Client version: 3.2.4

Operating system: Windows

OS language: German

Installation path of client: C:/Programme/Nextcloud

### Server configuration

Nextcloud version: 21.0.3

### Logs

1. Client logfile: [nextcloud debug.zip](https://github.com/nextcloud/desktop/files/6810848/nextcloud.debug.zip)

**Comment by FlexW** [comment]
Do you do the renaming on the local machine or on the server behind it's back?

**Comment by AndreKoepke** [comment]
Directly on the server.

**Comment by AndreKoepke** [comment]
Finally I found the issue. VFS can't display the files, when their name contain double-point (`:`). I will update the issue.

**Comment by FlexW** [comment]
@AndreKoepke That is an issue with the Windows file system that we can't solve. Windows filesystems are unable to display/save files that have a colon in their name.

**Comment by AndreKoepke** [comment]
@FlexW Should we not print a fallback-character? Or should nextcloud-server block these names (or display at least a warning)?  
I think, that would prevent more tickets like mine.

**Comment by FlexW** [comment]
Probably one could add a fallback character but that might be a non-trivial change to the sync engine that will probably take a long time to implement and is not planned at the moment. Blocking on the server will also be difficult. You could block the creation of such files through the webui, but then again a client can upload these files and if the server blocks these uploads the people will wonder: Why get my files not uploaded? In the new feature release (3.3.0), the desktop client will show a more visible warning if a file could not be created because of bad characters in the filename.
