### ISSUE TITLE
Sync client is aborted in windows 11.

### ISSUE THREAD

**Issue by Chuanbin-Wang** [nextcloud/desktop#3568]
### Actual behaviour
Sync client is aborted in windows 11.

### Steps to reproduce
1. sync folder with vfs.
2. waiting.
3. it's aborted.

### Client configuration
Client version: 3.2.4
Operating system:windows 11
OS language: en-us
Installation path of client: default

**Comment by FlexW** [comment]
How is it aborted? Is there any crash? A message?

**Comment by Chuanbin-Wang** [comment]
The program ends without any prompt. 
I'm find something in %APPDATA%/nextcloud/logs
![image](https://user-images.githubusercontent.com/76732400/126282308-6c6a5745-1775-4f6e-b66c-8c2d914d43b2.png)

**Comment by Chuanbin-Wang** [comment]
maybe need sync a big folder? when I sync a very small folder it's OK.

**Comment by alex6480** [comment]
Sounds like a duplicate of #3349 

It is random which files it crashes on, which is why it can often handle small folders but not large ones.

**Comment by Chuanbin-Wang** [comment]
@alex6480 you are right.
I can see the error in event log viewer.
![image](https://user-images.githubusercontent.com/76732400/126293618-d2f217a2-d61e-443e-987d-d9e40c3c8113.png)

**Comment by allexzander** [comment]
@Chuanbin-Wang Can you try this build with a potential fix to CLDAPI from our community member https://cloud.nextcloud.com/s/9CiRxYQaFnXcwqK?

**Comment by Chuanbin-Wang** [comment]
this version not abort. but have error when sync folder. 
![image](https://user-images.githubusercontent.com/76732400/128120421-32956ce5-eb28-4261-9d5b-fe7531c63d57.png)

**Comment by mgallien** [comment]
> @alex6480 you are right. but in windows 10 never see it.
> I can see the error in event log viewer.
> ![image](https://user-images.githubusercontent.com/76732400/126293618-d2f217a2-d61e-443e-987d-d9e40c3c8113.png)

thanks for the test

just to be sure, you ever only see crashes with Windows 11 ?

**Comment by Chuanbin-Wang** [comment]
yes.
I've never started the program manually before update to windows 11. so I think it's never crashed.

**Comment by RCmarkus** [comment]
> @Chuanbin-Wang Can you try this build with a potential fix to CLDAPI from our community member https://cloud.nextcloud.com/s/9CiRxYQaFnXcwqK?

Thanks it fixed my Problem ... on a Windows 11 ... now Nextcloud start work again

**Comment by BungyStudios** [comment]
Is anyone else experiencing this issue on Windows 11?

**Comment by lfcoml** [comment]
Same issue!

**Comment by mgallien** [comment]
> Seconded. I'm also experiencing this problem on my Windows 11 Surface Book.
> 
> After installing the hot-fix above, it didn't spontaneously quit. But instead resulted in (and I'm paraphrasing) "unable to update placeholder file" error where the sync bar is.
> 
> Just as a control test, I tried the exact same setup with my Windows 10 PC and it works like a charm.

could you share your logs ?
that would be helpful to understand the problem

**Comment by leuedaniel** [comment]
Which log you mean? The log under \AppData\Roaming\Nextcloud\logs don't have any errors. The last entrys on my log was:
`2021-09-08 09:53:19:315 [ info nextcloud.sync.engine ]:	#### Reconcile (aboutToPropagate OK) ####################################################  13486 ms
2021-09-08 09:53:19:315 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post treewalk" and starting new transaction
2021-09-08 09:53:19:315 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT tmpfile, etag, errorcount, path FROM downloadinfo"
2021-09-08 09:53:19:315 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path,transferid FROM uploadinfo"
2021-09-08 09:53:19:315 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM blacklist"
2021-09-08 09:53:19:315 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post stale entry removal" and starting new transaction
2021-09-08 09:53:19:318 [ info nextcloud.sync.engine ]:	#### Post-Reconcile end ####################################################  13489 ms
2021-09-08 09:53:19:320 [ info nextcloud.gui.folder ]:	#### Propagation start ####################################################
2021-09-08 09:53:19:320 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "2" because status() is OCC::SyncResult::SyncRunning
2021-09-08 09:53:19:326 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://cloud.ehv.ch/remote.php/dav/files/admin/" :  "Sync Running"
2021-09-08 09:53:19:328 [ debug nextcloud.gui.folderwatcher ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "C:/Users/leuen/Cloud_EHV/Ausbildungskommission"
`

**Comment by mgallien** [comment]
@leuedaniel from your message, I fail to understand how this is related to the error encountered by @BungyStudios who no longer have a crash but other errors.
Better open a different issue and please put more context into your logs otherwise we cannot know what is going on.

**Comment by mgallien** [comment]
@claell if you reopen at least provide information that would help us act on it otherwise we just will close it again.
this is already tracked on #3937 and #3405

**Comment by claell** [comment]
@mgallien If it is a duplicate than it can be marked as one. As of now, I don't have seen indications of triaging here, and so I was not sure whether it is a duplicate. I'll mark it accordingly now, but don't want bugs to simply get closed by the stale bot. This happens way too often to still existing bugs. I don't like to lay the work to keep existing issues open (and thus making sure they get fixed) to the users.

**Comment by claell** [comment]
Duplicate of #3937

**Comment by ben25belot** [comment]
Hi,
I had the same issue : starting and crashing. I found a workaround that works for me
As I saw that may come from a too large download, I selected only some directories in real download (not virtual) and after a whilen I re-enable the virtual download which downloaded all directories without crash

I hope that will help
Benjamin
