### ISSUE TITLE
Concurrent upload

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3658]
As discussed with @mgallien and @juliushaertl 
- support concurrent upload on Desktop
- define proper max number
- server: proper reply if queue is full
- fallback: if no proper reply is possible, maybe define admin setting to set max number of concurrent uploads
- have some rough numbers for marketing

**Comment by mgallien** [comment]
Current parallel download is depending on this sync option code https://github.com/nextcloud/desktop/blob/master/src/libsync/syncoptions.cpp#L47

**Comment by mgallien** [comment]
Dynamic adjustment of the number of parallel jobs depending on the HTTP2 support being enabled
https://github.com/nextcloud/desktop/blob/master/src/gui/folder.cpp#L910

**Comment by tobiasKaminsky** [comment]
@PVince81 we would use same threshold (6 with http/1 and 20 with http/2), which we currently use for download also as value for uploads.
Do you have any concerns on this? :)

**Comment by PVince81** [comment]
@icewind1991 @juliushaertl @CarlSchwan ^

**Comment by juliushaertl** [comment]
For single file put requests concurrent upload may cause wait locks on the database, so there may be a limit depending on that. Might need some extra investigation but I'd say a higher limit is fine for concurrent chunk uploads, but for the others I'd probably stick to a lower limit (around 5)

**Comment by allexzander** [comment]
So, after some investigation, I have realized that Propagation jobs are already running in parallel. Using a separate thread for each job won't work because the QNetworkAccessManager requires its network requests to run in the same thread. One other thing, [QNetworkAccessManager's ](https://doc.qt.io/qt-6/qnetworkaccessmanager.html#details)requests are all asynchronous, and, up to 6 requests can run per port.
