### ISSUE TITLE
Client logout after boot + login not possible

### ISSUE THREAD

**Issue by PierreSchwang** [nextcloud/desktop#3704]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
- After booting into windows the client should retrieve the stored credentials and don't require me to login again.
- The login flow should work
### Actual behaviour
When booting into windows the client asks for authorization everytime. Often the login flow does not work. I grant access (/login/v2/grant) but the client does not recognize that.
Also, when opening the client, I'm stuck in the loop that I was logged out from ... and must login again. Closing the notification results in opening the notification again.
Problem does not happen to collegue under macOS with NextCloud client and connection to the same NX server.

### Steps to reproduce
1. Install NextCloud Client in Windows
2. Login
3. Reboot

### Client configuration
Client version: 3.3.1

Operating system: Windows 10 Version 2004 (Build 19041.1165)

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 22.1.0

Storage backend (external storage): 

### Logs

1. Client logfile: https://gist.github.com/PierreSchwang/75ee605eb3b48cdd8092ad4eae53a02e

**Comment by ttobsen** [comment]
Same behavior with Nextcloud Server Version 21.0.4 and Linux Client 3.3.1

**Comment by Commifreak** [comment]
#3677

**Comment by PierreSchwang** [comment]
> #3677 

Yeah, no. The buttons work, but the Auth flow does not work. Plus, the Keychain does not seem to work, which could be the root cause of the broken Auth flow

**Comment by cycotron69** [comment]
Same behavior with Server Version 22.1.0.1 and MacOS Client 3.3.1.

It works fine for adding new account, but not log in for old logged out account.

**Comment by PierreSchwang** [comment]
> Same behavior with Server Version 22.1.0.1 and MacOS Client 3.3.1.
> 
> It works fine for adding new account, but not log in for old logged out account.

So, logging out, removing the account with its data and readding the account should fix the issue?
I'm gonna try that when I'm home

**Comment by JBM888** [comment]
I'm experiencing the same issue after change of password for security reasons and upgrade of client to Version 3.3.2 (Windows) from . I'm on NextCloud 20.0.12.

**Comment by JBM888** [comment]
I decided to do a little testing and may have found a way to move back to version 3.3.0 which from the looks of things seem to work as it should when, as in my case, a change of password forces the user to re-authenticate by login in again. I know run the **Windows Nextcloud Client** ver 3.3.0 x64 again and so far haven't seen any issues, perhaps due to lack of extensive testing... How this would pan out for other OS's or even other Windows versions I have no way of knowing. But because of a directory backup there should be a way back to your present state, if this doesn't pan out...  
Anyway, this is what I did:

1. Backup the program directory where the NextCloud client resides.
2. Download the last working client file which in my case was **Nextcloud-3.3.0-x64.msi**, you may have to choose another file for several obvious reasons such as your OS and architecture (x86/x64).
3. Close EVERYTHING even vaguely connected to/with NextCloud such as File explorer. You will still need to reboot since not everything will be available to close or could potentially cause direct problems if so.
4. Run the installation. It should behave like a new install. After it is finished you should reboot and can try and start NextCloud but at least in my case Nothing happened since the Nextcloud.exe where missing! 
5. Run the installation file AGAIN, in my case **Nextcloud-3.3.0-x64.msi**. But this time the installation should recognize itself as installed  will prompt you and ask what tod do. Choose **REPAIR**. 
6. Let it finish and reboot. 
7. Start NextCloud! Login as the new procedure dictates. 
8. BACK IN BUSINESS! 

There are no guarantees that  this will work for everyone but it's a fair chance for many, I would say... 
Here you find the new & older versions of the clients [NextCloud Clients](https://download.nextcloud.com/desktop/releases/)

Happy Hacking! 🤓
