### ISSUE TITLE
Tray windows looks corrupted

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3759]
![image](https://user-images.githubusercontent.com/5836855/132332298-61bd450d-c750-4079-9385-11cdd62c3c2d.png)

Arch Linux
installed via package manager: 3.3.0 currently

Nvidia drivers 470.63.01

NVIDIA GeForce GTX 760 (GPU 0)
3840x1200 pixels (2120x331 millimeters)
46x92 dots per inch

Xorg:
Version Number: 11.0
Vendor version: 1.20.13 (12013000)

**Comment by mgallien** [comment]
This is directly running on bare metal ?
Could you check the version of Qt ?
I am not too familiar with Nvidia drivers but is there a way to force using Mesa. I tested forcing software rendering and it seems to work fine for me.
You would have to use `LIBGL_ALWAYS_SOFTWARE=1`.

**Comment by tobiasKaminsky** [comment]
QT 5.15.2

And as always…since I reported the bug I cannot reproduce it anymore, so closing…
If it happens again, I'll test mesa.

**Comment by mgallien** [comment]
I have another idea, did you suspend your laptop before you saw that ?
could you test because I think we are missing some fixes related to proper suspend handling related to Nvidia driver
see [Nvidia context loss events](http://blog.davidedmundson.co.uk/blog/plasma-rendering-handling-nvidia-context-loss/)

**Comment by tobiasKaminsky** [comment]
Yes, cool!
Now i can reproduce it. 
If you need me to test something, I know how to run an AppImage 🤣

**Comment by FlexW** [comment]
Reading the article that @mgallien posted, the issue could be fixed with qt 5.15. @tobiasKaminsky could you try an daily app image and see if it's gone? because on master we use qt 5.15.

https://download.nextcloud.com/desktop/daily/Linux/

EDIT: Looks like the dailies there are too old. Seems like something got broken.

**Comment by mgallien** [comment]
> Reading the article that @mgallien posted, the issue could be fixed with qt 5.15. @tobiasKaminsky could you try an daily app image and see if it's gone? because on master we use qt 5.15.
> 
> https://download.nextcloud.com/desktop/daily/Linux/
> 
> EDIT: Looks like the dailies there are too old. Seems like something got broken.

yeah sysadmins should fix that in a way that works

what makes you think that we do not need to add a fix by our own ?

I read again the Qt API documentation and nothing makes me think that we do not need to set that specific option to improve Nvidia driver support (and most probably other OpenGL drivers also).

**Comment by FlexW** [comment]
@mgallien This:
> After over a year of gradual changes all of Plasma now handles this event and recovers gracefully. Some of these changes are in Qt5.13, but some more have only just landed in Qt 5.14 literally this evening.

**Comment by claucambra** [comment]
@tobiasKaminsky Does this issue still appear with the latest version of the client? Thanks!

**Comment by tobiasKaminsky** [comment]
No, looks good now after hibernate/suspend 🎉
