### ISSUE TITLE
[ARM -M1] Garbled graphics on Activity Screen

### ISSUE THREAD

**Issue by freumichCH** [nextcloud/desktop#3801]
### Expected behaviour

Activity Screen shows correct rendered graphics

### Actual behaviour

Activity Screen shows garbled graphics

### Steps to reproduce

1. Building desktop client based on instructions from [This Manual](https://raw.githubusercontent.com/nextcloud/desktop/master/doc/building.rst)
2. Installed on a macOS 11.6 with M1 - ARM main processor
3. Logged in with test account and setup client
4. Open activity Screen 
![Bildschirmfoto 2021-03-02 um 18 08 41](https://user-images.githubusercontent.com/22443781/109686256-65ded780-7b82-11eb-8311-09992f6cfa5a.png)

Doing the same procedure with a intel mac shows correct rendered graphics in the activity screen

### Client configuration
Client version: 3.3.3

Operating system: macOS 11.6

OS language: German / Swiss-German

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.15.2

Installation path of client: /Volumes/Applications/

**This only happening on self build clients. Clients downloaded from nextcloud.com does show correct rendered graphics***

Does someone have an idea what could be wrong? I'm pretty sure it's my build environment. But have no clue where to start.
Has someone experienced the same?

Thanks in advance ✌🏻🤙🏻

**Comment by FlexW** [comment]
Clients downloaded from nextcloud.com are compiled for the Intel architecture and run under Rosetta on the M1.

Arm support is experimental at the moment and we do not provide official builds for now because Qt5 does officially not support the M1.

Having said that, a few other people and I were able to build Arm binaries successfully and haven't experienced the issue. Have a look at the discussion here https://github.com/nextcloud/desktop/issues/2659#issuecomment-891462200 maybe you could try to build with the latest Open-Source Qt5 version that was not officially released.

Maybe you could post your Hardware configuration.

**Comment by freumichCH** [comment]
Hi @FlexW 

Thanks for your quick respond. 
Great! That gives me a new approach. 

I'm not owning a Mac with ARM processor. But i will check that with my coworkers and will come back with a update!

**Comment by freumichCH** [comment]
Here the details of the affected machine: 

Modelname: MacBook Pro 
Model Identifier: MacBookPro17.1
Chip: Apple M1
Count of Cores: 8 
Memory: 16GB 
System Firmware: 6723.140.2
OS Bootloader: 6723.140.2
