### ISSUE TITLE
Nextcloud chooses older files by default when re-creating a folder sync 

### ISSUE THREAD

**Issue by ghost** [nextcloud/desktop#3860]
Hi

I'm ~~pretty pissed~~ immensly relieved right now. I'm not sure where to report this so I'll do it here.

I have my computer synced up to a fileserver with nextcloud.
There was an update to the client available, so I installed it. 
There were a few updates available since after updating I was prompted to update again.
I did this over the course of a few days.
Then I didn't realise that my sync definition had disappeared at some point, so a few days after that I realised and added it again.
This is where the bug happens. 
Nextcloud decided to 'update' all of my documents to the old ones on the fileserver, and not update the fileserver with the newer ones on my computer.

~~I have the most important ones backed up in other places, so not the end of the world. But still a lot of lost work.~~
It did create backup files marked as "conflicted copy".
Why would it behave like this? 

I'm using 3.3.5 desktop version and windows

**Comment by FlexW** [comment]
How did you add the sync folder again? Normally if you set up a folder which contains files, Nextcloud will ask you if you want to keep the files or not.

**Comment by andresgunn** [comment]
I just clicked the "Add folder sync connection" button in the client, and then chose a local folder and remote folder just like I usually do.
Therefore I wasn't so concerned that anything unexpected would happen.

However, I just now discovered that it seems that for all of these files, a "conflicted copy" file was created that contains the newer version. So it seems that no data was actually lost but it will be a little work to restore the files since there were a few of them.

I didn't get any pop-up asking about it as I recall, but I did get a notification that nextcloud would remove some files but that was in the notification stream one can see by clicking the icon in the system tray so I did not notice it until too late.

In any case I am very happy about the "conflicted copy" files that got created, that means probably nothing was lost.

Perhaps the application needs to be a bit clearer about what it is doing, and in any case I find it a bit odd that the newer timestamped file is not used by default, but it seems all is well :)

**Comment by andresgunn** [comment]
This will probably be a continuing headache for me for the months to come.
One of the problems is that the default sync option in the new client is the virtual file option.
So it actually removed a lot of files before I realized the mistake. Fortunately I've got some of them version controlled but for the ones that aren't I have possibly lost some of them.

After manually reviewing all the files in one of my synced folders, I have recovered them to the state I want.
Then I made sure this state was committed to my version control system and tried to create the nextcloud sync again, this time I made sure to uncheck virtual file.
Nextcloud has again decided that the older timestamp on the server should be the correct file and reverted everything I did again. This time it's okay since I'll just remove the nextcloud sync and restore via version control. 
But it seems clear to me that my nextcloud sync is now completely useless and I will have to create a new empty server folder and define a new sync. 

The other way would be to manually go through all of the conflicts in nextcloud and resolve them there, which would probably take even more time than it took to examine all of the conflict files.

Then I'll have to figure something out for the other sync folder that was not version controlled. These are 100s of thousands of files.
