### ISSUE TITLE
Research: open office file from web directly in Office

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3890]
- on web offer option to "edit locally"

Research:
- special link to Desktop client, which then 
  - downloads file (if not already synced/VFS used)
  - opens LibreOffice/Office
  - uploads it after finishing working on it
 OR
- File can maybe directly opened in LibreOffice as they support webDaV (@juliushaertl maybe?)

**Comment by allexzander** [comment]
@tobiasKaminsky Let's say I access the NC instance on `cloud.example.com`, and, click - "Edit locally" on some file. Then, let's assume I have an NC desktop client installed but, connected to `cloud.nextcloud.com`, then, should I still make the desktop client open this file in Office and then upload it back to the server?

What are the credentials used for upload? If the NC desktop client is not connected to that NC instance, that will mean we need some sort of credentials to allow us then upload that file to an instance we are not connected to. Will these credentials be sent as headers to an NC desktop client when downloading a file?

**Comment by tobiasKaminsky** [comment]
I think this should only work for connected accounts.
If file changed meanwhile, then it should create a copy.

This should be separate from actual Desktop sync, as it just downloads file, opens it in Excel, Word, Libreoffice and then sync back.

@juliushaertl Or can this even be done on LibreOffice side? So that Desktop only needs to provide correct url?

**Comment by jancborchardt** [comment]
We discussed a similar thing with Collabora Online Draw, which also has PDF functionality. For that we considered that we could add a button "Open in Office" (or something similar) in our PDF viewer. cc @juliushaertl since you were in that discussion.

Similar to that, we could do it in this case by adding a button "Edit locally" into Nextcloud Office, probably on the top right somewhere in the actions. (Not anything in the Files action menu, since at that point you likely don’t know yet if there are things that you can’t do yet with Office, and it also clutters the menu.)

**Comment by tobiasKaminsky** [comment]
> We discussed a similar thing with Collabora Online Draw, which also has PDF functionality. For that we considered that we could add a button "Open in Office" (or something similar) in our PDF viewer. cc @juliushaertl since you were in that discussion.

Please create for this a specific issue in office/pdf, otherwise it will be forgotten.

As this is "only" research issue, I will create a new one for Desktop: https://github.com/nextcloud/desktop/issues/4297
