### ISSUE TITLE
Nextcloud crashes during sync on Windows 11

### ISSUE THREAD

**Issue by stepanov1975** [nextcloud/desktop#3937]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Expected sync to work

### Actual behaviour
After some time client crashes

### Steps to reproduce
1. Run Nextcloud app
2. Enable sync
3. Wait for 1-2 minutes
4. THe app crashes

### Client configuration
Client version:
3.3.6

Operating system:
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎08/‎10/‎2021
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

```
OS language:
English

Installation path of client:
"C:\Program Files\Nextcloud\nextcloud.exe"

### Logs

1. Client logfile: 
[log.zip](https://github.com/nextcloud/desktop/files/7435847/log.zip)

Error from windows events viewer

```
Log Name:      Application
Source:        Application Error
Date:          28/10/2021 19:21:21
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      alex-pc
Description:
Faulting application name: nextcloud.exe, version: 3.3.6.25940, time stamp: 0x617a888f
Faulting module name: CLDAPI.dll, version: 10.0.22000.258, time stamp: 0xc4c18194
Exception code: 0xc0000005
Fault offset: 0x0000000000015877
Faulting process id: 0x4504
Faulting application start time: 0x01d7cc17a12f719f
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\SYSTEM32\CLDAPI.dll
Report Id: 485afb55-13ea-4c18-b30b-34e84ee8a957
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-28T16:21:21.8155881Z" />
    <EventRecordID>6063</EventRecordID>
    <Correlation />
    <Execution ProcessID="5832" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>alex-pc</Computer>
    <Security />
  </System>
  <EventData>
    <Data>nextcloud.exe</Data>
    <Data>3.3.6.25940</Data>
    <Data>617a888f</Data>
    <Data>CLDAPI.dll</Data>
    <Data>10.0.22000.258</Data>
    <Data>c4c18194</Data>
    <Data>c0000005</Data>
    <Data>0000000000015877</Data>
    <Data>4504</Data>
    <Data>01d7cc17a12f719f</Data>
    <Data>C:\Program Files\Nextcloud\nextcloud.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\CLDAPI.dll</Data>
    <Data>485afb55-13ea-4c18-b30b-34e84ee8a957</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by Erisa** [comment]
It does seem to be a duplicate of #3349 (Right down to the error code and dll), but the issue in question occurs significantly more often on Windows 11 than it does on 10, or more specific the version of cldapi.dll that Windows 11 ships with (You can see references of people having it happen on Windows 10 Insider buildss leading up to W11 reveal that also use affected cldapi)
I saw at least one person that had it happen on release Windows 10, but for the majority of cases it only happens on Windows 11. My case specifically for example, it works fine on both machines when running Windows 10 but happens always on Windows 11.

**Comment by Albonycal** [comment]
It worked fine, with no crashes on windows 11 home (dev channel:latest) 
Sync also worked

**Comment by Happyfeet01** [comment]
worked fine here.. Win11 Pro. Channel latest (3.3.6)

![win11info](https://user-images.githubusercontent.com/3295104/140562715-101125b6-42ed-4570-a4c5-729873750209.png)

**Comment by BK787** [comment]
I am also experiencing this, using Win11, although I don't think it is necessarily Win11 specific, as it would happen with Win10 also. Just seems to occur more in Win11 to the extent that the client is currently unusable for me.

I open the client, it checks files, but the moment it tries to do the actual sync? Crashes.

**Comment by claell** [comment]
Alright, marking as duplicate of #3349 for now. If anyone doesn't think this is correct, just comment here and it can be reconsidered.

**Comment by claell** [comment]
Duplicate of #3349

**Comment by mgallien** [comment]
@BK787 could you share your logs with us ?
I cannot reproduce any crash when running the desktop client on Windows 11.

You can check this page that explains how to create desktop client logs
https://docs.nextcloud.com/desktop/3.4/troubleshooting.html#obtaining-the-client-log-file

Since the 3.1.0 release we made it easier for users to provide debug information: debug logging is enabled by default with expiration time set to 24 hours and under the “General” settings, you can click on “Create Debug Archive ...” to pick the location of where the desktop client will export the logs and the database to a zip file.

**Comment by BK787** [comment]
Hi mgallien!

Certainly, I'll see what I can do (assuming it will stay open long enough...)

**Comment by BK787** [comment]
OK, I managed to get a .zip while it was preparing to sync. Then it started to sync and crashed, as mentioned previously. I don't think there is a problem with the server as I am the only one of my colleagues having an issue (but also, I think, the only one on Win11 too. But that may be irrelevant, of course
[BK787.zip](https://github.com/nextcloud/desktop/files/7627869/BK787.zip)
).

**Comment by mgallien** [comment]
@BK787 thanks for the logs
going to have a look at them

**Comment by mgallien** [comment]
@BK787 please upgrade to our latest version and test again
your problem might be fixed with it
so please test with 3.4.0 release and if you still have the crash I will be happy to help you

**Comment by BK787** [comment]
Cheers @mgallien. My version is showing 3.3.6 and no updates. Shall I move to beta or remain with stable?

![image](https://user-images.githubusercontent.com/94053955/144223362-14f01304-e9b2-45b0-b6ed-1ed5c43857df.png)

**Comment by BK787** [comment]
The website shows a download for 3.4.0-x64 so I will manually download. Interesting the Windows download button only shows Windows 8.1. Should it show Win 10 etc. too?

![image](https://user-images.githubusercontent.com/94053955/144223742-14e61d03-0af4-4d75-92b3-aff86c766701.png)

**Comment by claell** [comment]
@BK787 I think that you are right about the download button. Can you open an issue for that?

**Comment by claell** [comment]
@mgallien so this is not a duplicate of #3349?

**Comment by BK787** [comment]
OK, installed 3.4.0. Restarted. Exactly the same behaviour. Prepares to sync and as soon as it goes green, momentary freeze and then crash.

New logs here:
[BK787 v3-4-0.zip](https://github.com/nextcloud/desktop/files/7633478/BK787.v3-4-0.zip)

**Comment by NepBlanc** [comment]
I have client 3.3.6
I have the same issue also with logs.
Though I don't want to share these publicly.
Where could I post the logs?

**Comment by cah-98** [comment]
I believe i may have the same issue, nextcloud starts to sync and after a while the whole program freezes up and also freezes the windows file explorer. Unless i kill the nextcloud process the windows file explorer wont open. It also uses about 20% cpu while doing seemingly nothing, i have left it on for many hours to see if it actually was working on something to no avail. Attached is my debug archive
[debug-archive.zip](https://github.com/nextcloud/desktop/files/7807899/debug-archive.zip)
.

**Comment by xxxsskxxx** [comment]
I also have this same issue, windows event log attached as well as debug data (Win 11 NC 3.4.1)
[Nextcloud Win 11 Crashing on Sync.txt](https://github.com/nextcloud/desktop/files/7841334/Nextcloud.Win.11.Crashing.on.Sync.txt)
[Windows 11 Crash NC 3.4.1.zip](https://github.com/nextcloud/desktop/files/7841335/Windows.11.Crash.NC.3.4.1.zip)
.

**Comment by BTessoulin** [comment]
Exactly same here, Nextcloud client has been unusable for more than 3 months from now. 
Preparing Sync, then crashes, systematically.
One odd thing is that the tray icon will stay on "sync status" for a very long period of time (not doing anything in background though) and when I fly over with the mouse, the icon vanishes. 
Client 3.4.2 
Win11 at last stable version
Nothing really fancy about the install process and/or running programs. 
Thanks for your help!!

**Comment by stone1978** [comment]
Hello. I have the Same Problem. On my WIN 10 Clients it worked fine on my WIN 11 Client it crashed after 1 min

Is there any Solution?

Regards

**Comment by stone1978** [comment]
Here is my DEBUG LOG
[nc_debug_archiv.zip](https://github.com/nextcloud/desktop/files/8073870/nc_debug_archiv.zip)

WIN 11 PRO (latest Updates FEB 2022)
Nextcloud Client 3.4.2
Nextcloud Server Version 23 

Regards Stone

**Comment by ben25belot** [comment]
Hi,
I had the same issue : starting and crashing. I found a workaround that works for me
As I saw that may come from a too large download, I selected only some directories in real download (not virtual) and after a whilen I re-enable the virtual download which downloaded all directories without crash

I hope that will help
Benjamin

**Comment by quzyp** [comment]
Win 11, client 3.4.3, wincfapi

Same problem here , and I can confidently say that the cause is not a file or folder.

To narrow it down, I first paused the client to keep it from crashing, and then excluded every main folder. Unpaused and client runs fine (not syncing anything of course). Also runs fine after restart and reboot.

Then I removed exclusions one by one, but it turns out there is no clear pattern. When I un-exclude folder `tmp/`, it syncs fine. Then I restart the client and it crashes again. Then I un-exclude `/images`, it crashes. I restart, everything is stable.

What can I do to help finding the cause?

Here is a log file with the last messages before crashing, but I think it doesn't help much:
`C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\libsync\syncengine.cpp:687 ]:	#### Reconcile (aboutToPropagate OK) ####################################################  1543 ms
2022-03-08 11:48:36:034 [ debug nextcloud.sync.database C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\common\syncjournaldb.cpp:2439 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post treewalk" and starting new transaction
2022-03-08 11:48:36:035 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\common\ownsql.cpp:295 ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT tmpfile, etag, errorcount, path FROM downloadinfo"
2022-03-08 11:48:36:035 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\common\ownsql.cpp:295 ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path,transferid FROM uploadinfo"
2022-03-08 11:48:36:036 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\common\ownsql.cpp:295 ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM blacklist"
2022-03-08 11:48:36:036 [ debug nextcloud.sync.database C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\common\syncjournaldb.cpp:2439 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post stale entry removal" and starting new transaction
2022-03-08 11:48:36:036 [ info nextcloud.sync.engine C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\libsync\syncengine.cpp:741 ]:	#### Post-Reconcile end ####################################################  1546 ms
2022-03-08 11:48:36:062 [ info nextcloud.gui.folder C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\gui\folder.cpp:957 ]:	#### Propagation start ####################################################
2022-03-08 11:48:36:062 [ debug nextcloud.gui.socketapi C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\gui\socketapi\socketapi.cpp:485 ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "1" because status() is OCC::SyncResult::SyncRunning
2022-03-08 11:48:36:075 [ info nextcloud.gui.application C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\gui\owncloudgui.cpp:199 ]:	Sync state changed for folder  "https://cloud.paletti.org/remote.php/dav/files/David/" :  "Sync Running"
2022-03-08 11:48:36:076 [ info nextcloud.sync.propagator.root.directory C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\libsync\owncloudpropagator.cpp:1282 ]:	scheduleSelfOrChild OCC::PropagatorJob::NotYetStarted pending uploads 0 subjobs state OCC::PropagatorJob::NotYetStarted
2022-03-08 11:48:36:077 [ debug nextcloud.gui.folderwatcher C:\Users\sysadmin\AppData\Local\Temp\2\windows-9389\client-building\desktop\src\gui\folderwatcher_win.cpp:160 ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "C:/Users/David/Nextcloud/3D-Druck/Esstisch Ersatzteil"
`

**Comment by LarsLeferenz** [comment]
Windows 11 Education (=Pro)
Client 3.5.0 Beta and 3.4.4
Server 23.0.3

I also have this issue, and my log file looks the same as quzyp's .
Disabling virtual downloads fixes it, as pointed out before.
But re-enabling virtual downloads after everything is on my disk causes the app to crash again.

**Comment by Pwuts** [comment]
Same problem here. Client 3.4.4 on Windows 11 Pro build 593. Any timeline for a fix? https://github.com/nextcloud/desktop/issues/3349 has been open for almost a year now, https://github.com/nextcloud/desktop/pull/3461, https://github.com/nextcloud/desktop/pull/3623 are both waiting for action. :)

**Comment by Excel1** [comment]
Also got the problem after a freshly reinstall of nextcloud client (Windows 11). It happens by both options: virtual / local files

**Comment by Erisa** [comment]
There are no new details to share, this issue still exists and affects a subset of people without being fixed. There are PRs open that have worked for those affected, but are not merged.
This issue is not stale, so I am commenting to prevent it from closing.

**Comment by BTessoulin** [comment]
Same, no improvement regarding this issue.

**Comment by Erisa** [comment]
There was an answer though?

**Comment by gvansanden** [comment]
Same here, 3.5.1 as well

**Comment by mgallien** [comment]
so we are working on crashes but I cannot yet have anything to show you
hopefully we will reach out to get more testing before putting this into a release

**Comment by Erisa** [comment]
Can you reopen the issue?

**Comment by mgallien** [comment]
see https://github.com/nextcloud/desktop/issues/3349

**Comment by Erisa** [comment]
Thanks, having another issue to reference instead works too. 👍

**Comment by gvansanden** [comment]
@mgallien it indeed does not hit all client machines, but it is getting worse (perviously unaffected machines are increasingly getting it too for me)

**Comment by adrienbricchi** [comment]
Same here. No virtual drives at all. I found that some folders do crashes, some don't.  
No explaination, nothing in the logs.  
It's been almost 6 month.  

I'm leaving Nextcloud for something else.  
Maybe I'll come back if I need a Chat, a Calendar, a Weather, or a Notes software.  
But right now I just need a FOSS Dropbox-like software.

**Comment by fairok** [comment]
same here, but this ticket was closed, any solution?

**Comment by nagarrido** [comment]
Still happens to me, any chance of re-opening the issue?

**Comment by mgallien** [comment]
> Still happens to me, any chance of re-opening the issue?

will do but I would need first that you share with us a debug archive or the affected client
we do not reproduce this issue so we cannot analyze it to find a solution
if need, we can create an upload only link for you to share the debug archive in a private way

**Comment by Excel1** [comment]
I got this iusse again - recently on windows 10. It happens on specific .pdf in my case. 

On an older Version of Nextcloud it never happend

**Comment by Excel1** [comment]
Via Webupload and then sync to computer still works - just sync from computer to cloud didnt work.

**Comment by mgallien** [comment]
> I got this iusse again - recently on windows 10. It happens on specific .pdf in my case. Version 3.7.3
> 
> On an older Version of Nextcloud it never happend...
> 
> Also if nextcloud try to sync the files and crashes the user cant open any explorer related context menu. If the user trys to the windows file explorer crashes too (only if you linked nextcloud to the file explorer)

@Excel1 I am not sure your issue with windows 10 is really relevant for this issue about windows 11

**Comment by Excel1** [comment]
@mgallien However, the error appears to be independent of the Windows version. I have this error with Windows 10 and 11 on several devices and it occurs almost exclusively with PDF files - the desktop client has become so unusable for me....Synchronisation no longer takes place, Nextcloud hangs and Explorer freezes when opening the context menu and windows restarts it.

Thought it could be helpful for debug purposes

**Comment by Jundor-y** [comment]
Having exactly the same issue: The Nextcloud client crashes during the sync phase on Windows 11. With sync disabled, the client does not crash. 

Here are the log archives:
[debugNextcloudOnWindows11.zip](https://github.com/nextcloud/desktop/files/10919910/debugNextcloudOnWindows11.zip)

**Comment by mgallien** [comment]
@Jundor-y I do not understand what is inside the debug archive
from the configuration file, your sync folder should be located in one place
from the logs, your sync folder should be located in another place
do you remember what you did to get there ?
