### ISSUE TITLE
Windows client keeps crashing

### ISSUE THREAD

**Issue by MenooMeow** [nextcloud/desktop#3992]
Windows client keeps crashing.  Is there some way to get an error log or equivalent from the Windows client?  Sync is totally broken now.

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by camilasan** [comment]
For the logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file. 
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)

If you not running a 3.x version of the desktop client, please try to update. And let us know in the bug report what version of the client and server you are running.

**Comment by joshtrichards** [comment]
Closing since this doesn't have enough actionable info in it after almost 3 years.
