### ISSUE TITLE
NextCloud client version 3.4.0 still crashing upon virtual files sync

### ISSUE THREAD

**Issue by nlvkhang2105** [nextcloud/desktop#4019]

**Comment by mgallien** [comment]
Could you please share your logs with us otherwise we cannot do anything ?

**Comment by tensor5g** [comment]
Same issue, and I had it before the update too. Here is the event log entry
```
Faulting application name: nextcloud.exe, version: 3.4.0.26041, time stamp: 0x61a54ae0
Faulting module name: CLDAPI.dll, version: 10.0.19041.1288, time stamp: 0x662391d3
Exception code: 0xc0000005
Fault offset: 0x0000000000015a7a
Faulting process id: 0x4338
Faulting application start time: 0x01d7e70359cf76e7
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\SYSTEM32\CLDAPI.dll
Report Id: 32c634da-4e9d-4191-9ed2-7f70fb40a09b
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by fireeater112** [comment]
Same issue here with W10 21H2 since update to 21H2 and Desktop 3.3.6. Also same behavior with 3.4.0. Nextcloud stops completly and no sync is possible - no access to files on NC.
tried to use the modified NC desktop solution from here: 
 https://github.com/nextcloud/desktop/pull/3461#issuecomment-977321374
and the solution works for me. However this should not be the final solution for 3.4.x because it's still a woraround.

**Comment by dsahlberg-apache-org** [comment]
I had the same problem (see #3349). Version 3.4.1 was released a few days ago and it seems to solve the problem for me.

**Comment by stereu** [comment]
Same here, not usable on terminal servers actually.

**Comment by limatus** [comment]
I still have the same issues as well. The solution mentioned in #3461 does work for us as well.
