### ISSUE TITLE
Windows Nextcloud Agent 3.4.0 - since installing - file_versions creating "*.v-3600". in a never ending loop

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/desktop#4048]
### Actual behaviour

After installing Nextcloud Agent 3.4.0 some days ago (in the meantime a rollback was done to 3.36),
it shows now, that the never-ending sync loop is caused by file versions with ending "*.v-3600".
That means - there are thousand of files with the same ending, which are created ever and ever.

The fact is, that they are NO file changes, but every second for each single file a new version is created with ending "v-3600".
This gives a huge load to the server and also fills the storage space.

### Steps to reproduce

Installing Agent 3.4

### Expected behaviour

Any file version  into the appropr. files_versions Directory should only be created, when files change.

### Client configuration details
Windows 10 Pro, 21H2
Nextcloud Agent current: v. 3.36 (rolled back from: 3.40)
### --------------------------------

Version: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
Max Speed    : 4300 MHz
Current Speed: 3300 MHz
Memory: 16GB
----------------------------------------------

Operating System:  CentOS Linux release 8.5.2111

Upstream OS     :  Derived from Red Hat Enterprise Linux 8.5

Webserver:  Apache/2.4.37 (centos) 

Database:  mysql 10.3.28-MariaDB,

PHP version:  PHP Version => 7.4.26

Nextcloud:    - version: 22.2.3.0
### Updated from an older Nextcloud/ownCloud or fresh install:

Updated from: nc 21.0.5/21.07

### Where did you install Nextcloud from:

Nextcloud Source

### Signing status:

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

**Comment by harripj** [comment]
I am also having a similar issue- I upgraded to 3.4 but rolled back to 3.3.6 because of the sync issue. Despite this my files are constantly resyncing unnecessarily.

@Githopp192 I could not find the `v-3600` files you mentioned. Do you find these in your local folder (for Desktop client) or on the server (web app)?

**Comment by harripj** [comment]
I am also having a similar issue- I upgraded to 3.4 but rolled back to 3.3.6 because of the sync issue. Despite this my files are constantly resyncing unnecessarily.

@Githopp192 I could not find the `v-3600` files you mentioned. Do you find these in your local folder (for Desktop client) or on the server (web app)?

**Comment by Githopp192** [comment]
@harripj  - Paddy .. the ...v-3600 files are located on server-side in the users versions directory (files_versions)
