### ISSUE TITLE
Nextcloud Windows Client 3.4  - Right-click Share Options does not provide public links

### ISSUE THREAD

**Issue by NovacomExperts** [nextcloud/desktop#4107]
### Expected behaviour
Using Windows Desktop client 3.3.6, Explorer - Nextcloud drive, we right-click on a folder, Nextcloud / Share Options dialog provides a "+" for creating a public link. we could then copy it to clipboard and so on...

### Actual behaviour
Windows Client started proposing 3.4 (by auto-updates)
Once Windows Desktop client 3.4 is installed, the the right-click Nextcloud / Share Options does not provide the + for creating a public link.  The Sharing Option dialog box seems to shrink at the last minute, hiding the needed option.

This was observed on french Windows clients (no english version to test), 2 different sites, on more than 50 users.

### Mitigation 
Roll back to 3.3.6 - untick auto update - advise user NOT to update
or
Use web client directly

### Steps to reproduce
1. Update to 3.4 
2. right-click Nextcloud / Share Options
3. No option to create Public link under the text box for typing users in.

### Client configuration
Client version:
Nextcloud-3.4.0.20211129 - auto updated by the Windows client 

Version provided manually on https://nextcloud.com/install/#install-clients is 3.3.6 and it works as expected. Auto update always try to go to 3.4 afterward.

Operating system:
Windows 10 Pro 

OS language:
French (Canada)

Installation path of client:
C:\Program Files\Nextcloud

### Server configuration
Nextcloud version (snap) :
22.2.3snap1  28654  latest/stable  nextcloud

### Logs
All clients were reverted to 3.3.6 but I will provide logs if needed

**Comment by NovacomExperts** [comment]
Just confirmed that 3.4.1 have the issue too.

**Comment by allexzander** [comment]
Could not reproduce on 3.4.1. Or, is there a misunderstanding? @NovacomExperts 
![image](https://user-images.githubusercontent.com/12224014/147478773-27394153-08b3-4540-87c7-8b866a775d27.png)

**Comment by schmittst** [comment]
@NovacomExperts Thanks for opening this.
I can confirm the problem (Win10 Pro, German Version).
@allexzander The issue is not that the entry "Share Options" is missing but that the subsequent window (i.e. when you click on "Share Options" does not display any Share Options, except the field needed to select users.
![Nextcloud_Client_Win10_SharingProblem2](https://user-images.githubusercontent.com/19912701/147859399-68b87fc7-0b29-43c2-9766-99b672ff0538.png)
As mentioned by the TO, the "Sharing Option" will open larger on clicking, however, directly shrinks again so the options are "hidden".

Just to confirm: the function "Share by link" is working well (e.g. if you click on "Copy public link"). Just the "Sharing Option" window will never display more options.
![Nextcloud_Client_Win10_SharingProblem1](https://user-images.githubusercontent.com/19912701/147859426-0d3712ef-cf95-48ba-901e-3b1db6e73ff6.png)

**Comment by allexzander** [comment]
@NovacomExperts Is Public Link Sharing enabled on the server via the admin account?

**Comment by schmittst** [comment]
Interesting. For me its enabled:
![grafik](https://user-images.githubusercontent.com/19912701/147872281-7a52f384-7637-46f6-bf49-4ce00e20f087.png)

**Comment by schmittst** [comment]
I just checked the logs of Nextcloud Desktop. I get the following entry:
`2022-01-02 12:40:17:490 [ info nextcloud.sync.networkjob C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\abstractnetworkjob.cpp:361 ]:	OCC::PropfindJob created for "https://cloud.XXXX.YYY" + "/Attachments" ""`
`2022-01-02 12:40:17:490 [ warning nextcloud.gui.sharing C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\gui\sharedialog.cpp:143 ]:	The file cannot be shared because it does not have sharing permission.`

That's very interesting because I can share via link via "Copy public link" and it works as well via the web interface - here all sharing options are displayed...

**Comment by allexzander** [comment]
@schmittst I have one idea. Can you make sure you also have "Reshare" and "Allow resharing" enabled in Web UI, similar to this sreenshot? 
![image](https://user-images.githubusercontent.com/12224014/148176167-26b73cd1-002c-42b0-94e5-991526e7a597.png)

**Comment by allexzander** [comment]
@NovacomExperts ^^

**Comment by allexzander** [comment]
@camilasan Could be related to https://github.com/nextcloud/desktop/pull/3713

**Comment by schmittst** [comment]
@allexzander Thanks. I tried that right now (activating both, "Allow resharing" and "Default permission reshare".
Did not work.

However, I tried also something else:
1) I use LDAP authentication on a Active Directory backend (which works fine for the website, Desktop and Talk). The user I reported this issue for is a user that is only added to LDAP-groups (in the format "XXXX Team", "XXXX Orga", ...)
2) If I use a Local Nextcloud User (i.e. that was created as admin during the installation process and only belonging to the local "admin" group") the issue disappears (sharing dialog is fully shown).
3) Now, I took the user from (1) and added him to the local "admin" group, disconnected and reconnected his account in Nextcloud Desktop. Now the sharing dialog is fully shown - the issue disappeared.
4) Next, I removed the local "admin" group from that user again, and reconnected the account again. And, the sharing dialog is still fully shown, so the issue is gone.

I have no clue why this now works. I am pretty sure that just "reconnecting" the account in Nextcloud Desktop did not help in the first place, this I tried several times. But adding and removing a local group to that user did do the trick in my case...

**Comment by szaimen** [comment]
I also have this problem but it also with 3.3.81. 
Those are my default sharing permissions:
![image](https://user-images.githubusercontent.com/42591237/148201131-77f14056-6da7-404f-8a56-c75b855c0088.png)
Seems like ticking the `Reshare` permission shows the link option again reprodibly. (Although resharing is forbidden - so this should be probably checked as well).

**Comment by schmittst** [comment]
Just a quick follow-up. I just tried my trick from above on another user: Here this did not work.
Looks like the problem is somehow around the issue with local vs. LDAP Users, but I cannot provide a fully functional workaround.

**Comment by NovacomExperts** [comment]
Sorry Guys... I took some time with the familly during the holiday.

Like @schmittst posted, his screenshot shows the exact behavior I see on all upgraded Windows clients past 3.3.6.
All server options remained the same for both tenants (around 30 users each) 

I will try options like reshare provided by @allexzander but they are again a workaround. This should be working out of the box. And resharing is not permitted technically.

@schmittst All my users on both tenant are local.

**Comment by NovacomExperts** [comment]
@allexzander

1. I installed a fresh V 3.4.1 Windows Client on a new Workstation
2. Confirmed the said behavior. Share Option windows seems to reduce itself, preventing public link.
3. The reshare option was then ticked globally, as suggested (both checkboxes)
4. Not change in the problem reported
5. Rebooted
6. ***** The Share Option is now displayed correctly.

Maybe I did not understand the Reshare correctly. I was under the impression that another user could not not share something that was shared with him. This should be limited like previous versions I think  

I will do further testing, like remove the reshare and see if this was just a "once re-tick" glitch.

Thanks for the info.

**Comment by julian70400** [comment]
> @allexzander
> 
> 1. I installed a fresh V 3.4.1 Windows Client on a new Workstation
> 2. Confirmed the said behavior. Share Option windows seems to reduce itself, preventing public link.
> 3. The reshare option was then ticked globally, as suggested (both checkboxes)
> 4. Not change in the problem reported
> 5. Rebooted
> 6. ***** The Share Option is now displayed correctly.
> 
> Maybe I did not understand the Reshare correctly. I was under the impression that another user could not not share something that was shared with him. This should be limited like previous versions I think
> 
> I will do further testing, like remove the reshare and see if this was just a "once re-tick" glitch.
> 
> Thanks for the info.

Thanks ! it worked for me

**Comment by schmittst** [comment]
> @allexzander
> 
>     1. I installed a fresh V 3.4.1 Windows Client on a new Workstation
> 
>     2. Confirmed the said behavior. Share Option windows seems to reduce itself, preventing public link.
> 
>     3. The reshare option was then ticked globally, as suggested (both checkboxes)
> 
>     4. Not change in the problem reported
> 
>     5. Rebooted
> 
>     6. ***** The Share Option is now displayed correctly.
> 
> 
> Maybe I did not understand the Reshare correctly. I was under the impression that another user could not not share something that was shared with him. This should be limited like previous versions I think
> 
> I will do further testing, like remove the reshare and see if this was just a "once re-tick" glitch.
> 
> Thanks for the info.

I can confirm: Also worked for me! Thanks!

**Comment by allexzander** [comment]
@NovacomExperts This is not a forever workaround. My idea was to just let you test my suggestion so I could decide if I have a correct assumption on why the issue could be happening, based on the logic that's in the Desktop client's part of UI where the Public Link share option is displayed/not-displayed. This is caused by the fact that I could not reproduce the issue locally with standard settings for sharing. So, we might have a bug in the desktop client, but, I just wanted to know what might have caused it, as, when we introduce a fix, the reviewer will want to know the reason for applying the fix in a certain way.

**Comment by NovacomExperts** [comment]
@allexzander Allright ! I'll be happy to provide feedback once a fix is released.

**Comment by kce68** [comment]
> > @allexzander
> > ```
> > 1. I installed a fresh V 3.4.1 Windows Client on a new Workstation
> > 
> > 2. Confirmed the said behavior. Share Option windows seems to reduce itself, preventing public link.
> > 
> > 3. The reshare option was then ticked globally, as suggested (both checkboxes)
> > 
> > 4. Not change in the problem reported
> > 
> > 5. Rebooted
> > 
> > 6. ***** The Share Option is now displayed correctly.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe I did not understand the Reshare correctly. I was under the impression that another user could not not share something that was shared with him. This should be limited like previous versions I think
> > I will do further testing, like remove the reshare and see if this was just a "once re-tick" glitch.
> > Thanks for the info.
> 
> I can confirm: Also worked for me! Thanks!

Works also on **macOS**. I had the same problem with the latest macOS Desktop-Client on latest NC22 & 21 (as of writing)
