### ISSUE TITLE
Research: put in app store

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4178]
- research what needs to be done to put Client in app store (Windows and iTunes)
- requirements
- limitations (e.g. sandbox on Mac?)
- additional work during release
  - can this be automated?

**Comment by kaystrobach** [comment]
maybe start with a browser as wrapper? like electron?

**Comment by allexzander** [comment]
- A WinRT application may not do socket-based communication with another application running on the same host (as this would violate the sandboxing) That means, sync-state overlays might get broken and require to be implemented from
scratch, without sockets (but, is this possible? Not sure)
- Some paths returned by QStandardPaths::writableLocation() may be empty.
-  Applications run in fullscreen mode only (see QStyleHints). On a desktop, the screen size varies as the application is resized.
- There is this so-called **Desktop Bridge**, where they claim to allow running non-WinRT apps from the store, or, c**onvert them to WinRT apps** (though, some APIs we use might become unavailable) https://techcommunity.microsoft.com/t5/windows-dev-appconsult/desktop-bridge-8211-the-bridge-between-desktop-apps-and-the/ba-p/316488
-  An app must be **packed to .appx format before submitting it to a Windows Store**
-  **Desktop Bridge samples** https://github.com/microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples
- We need to **register a Windows Store account** https://developer.microsoft.com/en-us/microsoft-store/register/ and pay a one-time $99 USD fee for a company account. There is also a verification of a company required. This verification can take from a few days to a couple of weeks, and often includes a phone call to your company. See also policies https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#1014-account-type
-  Sysadmins may not install apps (we, currently install the DC into `C://Program FIles/`, so this might need some changes)
-  Because we are writing to the **HKLM Registry section**, we need to find another way around as this won’t work with the Windows Store app (we use **HKLM** when creating an entry in **SyncRootManager** for Virtual Files shell-integration bells and whistles to work)
-  This section https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#installation says that **the app run outside the container** (we can probably allow **running Nextcloud DC normally, just let it be installed via Windows Store**)
-  It should be possible to **automate the deployment via CI** (in any case, we will need some sort of APPX packaging script such that we do not just create MSI but also APPX, or, alternatively, we should be able to **switch to MSIX** that has all the benefits of APPX but works as a standard MSI - and we can probably just use it without MSI at all and use Wix Toolset extension for MSIX https://www.firegiant.com/products/wix-expansion-pack/msix/

**Comment by allexzander** [comment]
I am not sure about the real benefit of making the Nextcloud Desktop client available via the Windows Store. This store is not widely used and most users would just download and install the app manually.

Best, if we could first wor on `Apple Store` availability, as, `Apple Store` is used much more often. For Mac, store integration will most likely be more beneficial than for Windows.

I can't provide any estimates on how long it would take to integrate this to Windows. The rough estimation would be 1 month. Thi is because I haven't ever integrated anything to Windows Store, and, it is not that popular for app distribution, so, not much information on how to implement the interaction is available. There are mostly short guides here and there that needs to be studied first and a test version needs to be deployed.

Good thing is, we just need to pay $99 according to Windows Store guides, and, this is a one-time payment.

**Comment by allexzander** [comment]
@tobiasKaminsky ^^

**Comment by claucambra** [comment]
On the technical side: for the macOS store, we currently use some deprecated functionality linked to the LaunchServices framework that is central to some of the setup of the client on Macs (adding the Nextcloud folder to Finder's sidebar in the "Favourites" section, automatically setting the client to launch on system start-up). 

Some of these can be reimplemented with newer supported frameworks; AFAIK the Service Management framework can handle the client starting on boot, though the client will no longer show up in the user's system preferences "Open applications on login" section, which may not be desirable. Others, such as adding the Nextcloud folder to the sidebar, have no replacement as of now.

The thing is, the app store guidelines are unclear about the use of deprecated APIs. Section 2.5.1 of the App Store guidelines says:

"Keep your apps up-to-date and make sure you phase out any deprecated features, frameworks or technologies that will no longer be supported in future versions of an OS."

It's not clear if this is a suggestion or a requirement...

Another important section of the guidelines is 2.5.2:

"Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps."

Not sure how this affects things like the Finder Extension, but at the very least this implies we'll need to store the user's files within the app bundle sandbox and not just on the user's home directory.

**Comment by allexzander** [comment]
@tobiasKaminsky So, I don't see what more research can be done from Windows Store's side.

**Comment by ccptr** [comment]
>I am not sure about the real benefit of making the Nextcloud Desktop client available via the Windows Store. This store is not widely used and most users would just download and install the app manually.

Windows S mode users cannot install applications except through the Microsoft Store. Unfortunately, I was unable to find MS Store usage statistics.

**Comment by tobiasKaminsky** [comment]
Right now, we decided to not put it in any stores, due to above concerns.
We will re-evaluate, if things change, e.g. Windows S becomes more important.
