### ISSUE TITLE
Files are note upladed

### ISSUE THREAD

**Issue by holzfelix** [nextcloud/desktop#4210]
I have some problems with a client, Windows 10.

Not all files are synchronized. The client says that it is up to date but it is missing about 1.2GB of data that was not uploaded. 

What is the reason for this and how can I find the error?

Thanks in advance

**Comment by Id3aFly** [comment]
So you mean the files are not uploaded and they are missing on the server?

**Comment by maja68** [comment]
Your issue could be same as https://github.com/nextcloud/desktop/issues/4141 ?

**Comment by claucambra** [comment]
Could you provide logs for the desktop client? Thanks!

**Comment by Lars1963** [comment]
> I have some problems with a client, Windows 10.
> 
> Not all files are synchronized. The client says that it is up to date but it is missing about 1.2GB of data that was not uploaded.
> 
> What is the reason for this and how can I find the error?
> 
> Thanks in advance

Try a downgrade with client 3.3.6. If the syncing then works, it's the same as #4141

As @jospoortvliet and @allexzander stated, solving the syncing problems in the 3.4.x branch has no priority, allthough it affects paying and non-paying customers alike. 🥴

**Comment by holzfelix** [comment]
a downgrade to 3.3.6 solved my issue.

**Comment by mgallien** [comment]
@Lars1963 
Hi, I would like to point out that we are a community project and want to keep this a place that is nice and positive for everyone. These kind of comments are not welcome. Please try to be more respectful going forward, see our Code of Conduct for the why and what: https://nextcloud.com/code-of-conduct/.

**Comment by Lars1963** [comment]
@mgallien
Hi, first of all I'd like too point out, that I very much respect all the work that is being done by the paid and non-paid developers in this community! I'm way too old and using IT for too long to disrespect the work of developers. 

Secondly and with all due respect, I personally don't think I offended the rules of conduct, as I pointed out the clear  non-priority of solving this/these annoying bug/s, which is involving more and more users. I merely repeated which was said here: #4202. On the contrary, as a member of this community, I gave a temporary solution in form of downgrading the client. This solves the problem for seamlessly all affected users.

I'm not a developer, otherwise I surely would try to a fix it and make a PR. But what other way do users have, to emphasize the severity of a problem as the community seems not to pick it up? A little bit of critisism should be allowed here (and as can be read in other issues: not only be me) as clearly the 3.4-branch has problems.

I'm very sorry if you should feel personally offended as that was and will never be my goal.
