### ISSUE TITLE
Improve safety of every files deletion by doing more checks

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4233]
Improve safety of files/folders deletions by making redundant checks to ensure that those decisions are safe and could not lead to data loss.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by allexzander** [comment]
I am not sure if it is possible to add these more checks. At least, this makes some tests fail and will also lead to files that were renamed/moved on the server to be reuploaded by the desktop client. The desktop client does not know if the file/folder was moved/renamed vs if it was deleted and a new file/folder was uploaded instead. That's why, if the desktop client has a certain file/folder locally and in the local database, it will have no other choice but delete this file locally.
This is opposite to the local move/rename, as the desktop client detects this by locating an old record in the local database.

We need to implement a feature on the server that will let the desktop client know the reason a file/folder has stopped being available (either it was deleted or moved). For now, I don't see an easy solution on the client's end without involving server changes.

As for the trash bin, no, that's another feature.

Closing this issue as there is nothing I can come up with that needs changes.
