### ISSUE TITLE
scan_group_folders.sh "invalid i   nput syntax for type bigint:"

### ISSUE THREAD

**Issue by theinfguy** [nextcloud/desktop#4250]
When attempting to run the scan_group_folders.sh to resolve the invalid date modified issue caused by the broken client, I get these errors:

![image](https://user-images.githubusercontent.com/92925859/152502122-3a68036f-23af-4009-8007-2b737fa37693.png)

**Comment by joshtrichards** [comment]
Hi @theinfguy - I'm cleaning up old issues. Hopefully you figured out a solution via a different channel! 

The correct place to ask this probably would be: https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit

The script was slightly updated at one point around when you created this issue. It's possible you were running an older version. It's also possible it was something with `groupfolders` itself.

It might be informative to have seen the output from the following:

```
php ./occ groupfolders:list --output=json_pretty | grep '"id":' | sed "s/.*id\": //" | sed "s/,//"
```

But today the groupfolders scanner supports the `--all` parameter (nextcloud/groupfolders#2214) so that particular script probably isn't even needed. Just do this instead:

```
php ./occ groupfolders:scan --all
```
