### ISSUE TITLE
Allow Resize of Window

### ISSUE THREAD

**Issue by internettechnik** [nextcloud/desktop#4289]
Allow resizing the client window.

In terms of Usability it would be much better (faster, more transparent) to allow users resize the window for having the chance to see full file names of conflicting files.

Currently, file names are truncated (at the end) and therefore often not identifiable by users. 

Further Note: truncating file names at the end is   not helpful when trying to distinguish files in folders (with long paths). A better approach would be to remove parts of the filename from the middle of the file (as used by macOS in the Finder).

**Comment by Paradyx** [comment]
The shortened messages have a greater impact than one might think. In other languages the messages can loose all their meaning and render the UI completely non intuitive. Let me give a real-world example from today (german localization)

When deleting a file the message reads `Sie haben {name of file}...`. Translated to english this means `You have {name of file}`. Note that the crucial verb `deleted` to make sense of this message is truncated. When clicking on `Show all activity` you get an empty white page. With the very intimidating red cross the user (my mom) thinks something is wrong. The UI appears unresponsive/broken (white page) and clicking on the messages she is sent to the web-frontend non telling her anything about what actually happened. There is no little pop-up expanding the message and at the end she deletes and reinstalls everything just to get rid of that red cross. 
She never learned the meaning of the symbols and I can't really blame here since it was never written on screen.

IMHO restricting all the UI to this little window is a bad design choice. People don't expect a little popup to contain all the functionality of a tool. The wan't to see a full size window. 
Other possible solutions to this issue:
- allow multiple lines for the message and truncate only the filename
- add a little popup that expands the message to its full length
- shrink the symbols to gain more space for the actual message. 
- redesign the symbols to better reflect the importance: a red looks more important than the b/w conflict icon

**Comment by PhilippSchlesinger** [comment]
temporary workaround:

in file `nextcloud.cfg` set option

`showMainDialogAsNormalWindow=true`

and restart. Now you can resize the window as appropriate.

(see https://github.com/nextcloud/desktop/issues/4337#issuecomment-1060866262)

**Comment by Nadahar** [comment]
This (and #4337) remains a problem in 3.8.1 for Windows. It's difficult for me to understand why you'd hide `showMainDialogAsNormalWindow=true` so that users must look this up on GitHub and then figure out where to find `nextcloud.cfg` to get the desktop client to work properly. This should be exposed as a setting under "General". Everything is as it should once this _hidden_ option is set.

For others that need to jump through the same hoops, to save you some time, here's where you find `nextcloud.cfg`:


* On Linux distributions: `$HOME/.config/Nextcloud/nextcloud.cfg`
* On Microsoft Windows systems: `%APPDATA%\Nextcloud\nextcloud.cfg`
* On macOS systems: `$HOME/Library/Preferences/Nextcloud/nextcloud.cfg`
