### ISSUE TITLE
Configure Number of Menu Bar Icons (for multiple accounts)

### ISSUE THREAD

**Issue by internettechnik** [nextcloud/desktop#4290]
Allow users to configure the number of Menu Bar NextCloud icons to improve usability. Users need the choice to see only one icon (for the sake of saving space) or multiple icons (for the sake of having detailed information on single accounts, status of server connections)

Currently, users cannot distinguish which server sync connection is ok, and which needs inspection (solving conflicts). Only one single icon is shown. 

Furthermore, many clicks are necessary to switch to the proper account, inspect problems, change configurations and quit/stop/resume sync with a single server (when multiple connections are available)

**Comment by jancborchardt** [comment]
Since most of the time the status is "All synced" and any issues bubble up, there should not be a need to show multiple icons. Especially since then there would be follow-ups about which icon relates to which account, and to customize each icon etc.

All this should be properly done through the tray menu via e.g. improvements as discussed in https://github.com/nextcloud/desktop/issues/4152

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
