### ISSUE TITLE
Windows client gives error "<filename> cannot be downloaded because of a local file name clash!"

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/desktop#4324]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I just set up Nextcloud on my Windows partition. During setup, it asked me if I wanted to use "virtual" files. The initial sync worked fine. I can see the "virtual" files in my file explorer. However, the next time it tried to sync, it gives the error "<filename> cannot be downloaded because of a local file name clash!" for each file. I cannot be entirely sure, but I suspect that this is caused by the virtual files option. This is my first time using this feature, and the first time seeing this issue. Maybe the virtual file existing in the file system but being different than the server version is tripping this.

### Expected behaviour
The virtual file feature works correctly. The client will report that everything is synchronized and no errors will be shown even if some files are virtual.

There should also be a way to change from using a virtual file system to a normal file system where you can enable and disable different folders that you want to sync with checkboxes like with the linux client.

### Actual behaviour
The error "<filename> cannot be downloaded because of a local file name clash!" for each file.

Here is a video of the client. Maybe this should be a separate issue, but the scrolling seems very broken. It's like the height of the error box is not taken into account for the scroll bar.

https://user-images.githubusercontent.com/8503756/156458726-b04fc80d-6718-4e73-b01e-e2f8668a2b95.mp4

### Steps to reproduce
1. Install the Nextcloud client on Windows
2. When prompted, enable the virtual file option
3. Let nextcloud sync

### Client configuration
Client version: 3.4.2 (Windows)

Operating system: Windows 10.0.19044

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: `C:/Program Files/Nextcloud/nextcloud.exe`

### Server configuration

Nextcloud version: 22.2.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://gist.github.com/MarcelRobitaille/ee00a1d1d4f290191851534f73b04dc7

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by marbx** [comment]
I don't believe that I used a "virtual file system".

After months of operation:
- the NextCloud icon in the system tray turned into a white cross in a red circle
- The main window reads "Some files couldn't be synced! See below for errors"
- The list in the main window contains File <filename> cannot be downloaded because of a local file name clash!
- Clicking into the file offers no help.

The files in Windows explorer have a white cross in a red circle. The context menu of the file is not offering help.

Searching the internet revealed this issue.
Restarting the computer did not help.

**Comment by marbx** [comment]
Pause sync and resume sync do not help
Force sync does not help

**Comment by marbx** [comment]
A Linux client contains not only the file that causes above error (under Windows), but also a file whose name only differs in capitalization, right next to the offending file.

Linux can save two files in the same folder whose name only differs in capitalization. e.g. `Notes.txt` and `notes.txt`
Windows can not.

So the problem is not caused by Windows, and cannot be resolved under Windows, but by collaboration between Windows und Linux clients.

**Workaround** renaming or deleting files on Linux, so that no two files in the same folder have the case-insensitve same name.

A solution would involve changing the error messages.

**Comment by marbx** [comment]
A related open issue is https://github.com/nextcloud/desktop/issues/4103
