### ISSUE TITLE
Lock code for desktop application

### ISSUE THREAD

**Issue by gmkrab** [nextcloud/desktop#445]
Can you implement lock code for desktop application?

**Comment by GLLM** [comment]
Is this similar to #292 ?

**Comment by gmkrab** [comment]
No. It`s new feature. Block application via PIN ( as on mobile version ).

**Comment by gmkrab** [comment]
But without this feature (https://github.com/nextcloud/desktop/issues/447) it`s not security, because you can open folder via explorer.

**Comment by GLLM** [comment]
You are expecint features from nextcloud client that even nextcloud is not meant for, I think :)

**Comment by gmkrab** [comment]
:)

**Comment by juliushaertl** [comment]
As @GLLM said, having a passcode for the application isn't that useful on desktop systems, since you can still access files though the file system. A passcode works for mobile devices, since the access to data is quite locked there though the system apis. There is no way I'm aware of to get some similar thing for desktop applications.

**Comment by gmkrab** [comment]
p.s. Yes, you can access files through the file system, but if implement this closed feature https://github.com/nextcloud/desktop/issues/447 than it will actual.
