### ISSUE TITLE
Make desktop client check external storage

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#4462]
Currently if a file is added to an exteral storage not via Nextcloud the desktop client will not detect there's a change. You have to go under Nextcloud web and open the folder and then it will updated the external folder and then the desktop client will sync it down.  Is there a way to make the desktop client request for an update on the external folders. I think this would be awesome and I'm sure alot of people would like the same thing. 

https://help.nextcloud.com/t/external-storage-not-updating/61879/3
https://help.nextcloud.com/t/smb-share-external-storage-support-not-syncing-to-client/93551
https://github.com/nextcloud/server/issues/1564
https://github.com/nextcloud/server/issues/10413

![image](https://user-images.githubusercontent.com/59488153/165626208-1d81d4da-3b3d-489a-8072-b9a335f6e886.png)
Since the sever only has an option for updated once every direct access can you make the desktop client request for the change making the server access the folder ?

**Comment by sm8ps** [comment]
I support this and would like to ask for what reasons this is not the standard behavior. From a user perspective it does not make sense having external storage shown in the web-interface but changes not reflecting in their local files. One expects the two to simply agree when using a sync client. Maybe there are cases where it is not desirable or possible but IMHO it should be at least optional to have the client sync with the server state also for external storage.

I have been struggling with this issue for years until I finally realized that this seems to be expected behavior for the current state of the sync client. Please make it behave more as expected from a user's perspective.

**Comment by johnnyq** [comment]
I have this problem too
I have a printer/copier that sends the scans to an FTP Server (Its the only option it allows)
I created an external share in nextcloud called scans that connects to the FTP Server
I set the check for changes once every direct access
Everyone uses the Desktop Sync Client so this option does not work
My hacked up solution was create a seperate nextcloud user called scan_user
setup the external storage on that user and share the external storage with everyone
Create Cron script that runs every minute to check for file updates only for the scan_user so this cuts down on scanning everyones files each time.
`
* * * * * root docker exec -t nextcloud-aio-nextcloud php occ files:scan scan_user`

This is obviously a very hacked solution but it does work

**Comment by FesTGig** [comment]
same issue here.
we run NC on a productive server and have big problems with people not having the lates files from the external storage. I would call this not only an enhancement, for us it is more a bug! Any chance that will get a fix?

**Comment by sm8ps** [comment]
I could finally resolve the problem by using the files_inotify app which needed some additional tweaking, cf. https://github.com/icewind1991/files_inotify/issues/23.

**Comment by swartzlib7** [comment]
Hi y'all,

thank you for this here. I had no idea this could happen, but I think it will not happen for my setup.

See my last comment on this issue here today for a possible workaround that might suite you (or not).

https://github.com/nextcloud/desktop/issues/6099


Sincerely,
Stephen

**Comment by gbcatrinoiu** [comment]
@swartzlib7 do you know if any solution has been implemented for this? I cannot find any updates related on this matter. This is still a very important feature that is missing from the external storage functionality.

**Comment by swartzlib7** [comment]
Hi @gbcatrinoiu 

> [@swartzlib7](https://github.com/swartzlib7) do you know if any solution has been implemented for this? I cannot find any updates related on this matter. This is still a very important feature that is missing from the external storage functionality.

I have no idea my friend, sorry. I just installed NextCloud on the same external storage disk so that if the "storage ship" hits a rock then captain NextCloud goes down with it - nothing has a chance of getting lost that way. I don't think I'd ever install it along side a massive external storage disk ever again.

If this does not get resolved by end December I might just jump in and code a solution myself for the project using some free time and if it will be allowed.

**Comment by swartzlib7** [comment]
Here is my technical opinion for a solution:

The only way I would ever install my NextCloud server separately from an external disk is if the NextCloud sync client handles external disks completely separately. This whole idea of "let's show the folders like they are all part of the same bucket" is a design flaw. I would not design software like that. I would make that a feature, but keep the underlying architecture as close as possible to the technical infrastructure. This allows functional parity which we can see is missing from the project in this particular regard.

Rather have the sync client show the external drives and by means of a feature let you sync those drives to the same base sync folder on your device. This can then keep track of which external storage drives sync to your base folder and when they go offline the sync client can easily alert you and leave things alone.

**Comment by reefsofts-rhosds** [comment]
+1, really needed. I use nextcloud also for apps, not just storage, but my NAS isn't very good, so i'm effectively locked out from the NC client.
