### ISSUE TITLE
Allow to recover from lost keys/mnemonics from desktop client

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4534]
Offer a way to automatically reset the encryption keys from desktop client. That would avoid people having to directly execute the API calls via a command line tool or similar stuff.

In any case, this will allow people to loose access to their files so should feature prominent warnings and require multiple steps to ensure people are not doing it by accident.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Ah, sorry, then I misunderstood you.
I thought this would be about removing the key from desktop-internal database/wallet, so that user can try to re-setup the e2e system for this client without uninstalling client entirely.

Removing it from server should be done via server and not (only) one client…

**Comment by mgallien** [comment]
@tobiasKaminsky so we prefer not to give access to keys deletion from client ? in that case, let's close this issue or should I move it to e2ee app ?

**Comment by tobiasKaminsky** [comment]
We can close it here, no need to have such a rarely used function in any client.

We have it already on server: https://github.com/nextcloud/end_to_end_encryption/issues/32
