### ISSUE TITLE
[Bug]: nextcloudcmd ignoring exlude list and davpath

### ISSUE THREAD

**Issue by wieluk** [nextcloud/desktop#4621]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description
When using the nextcloudcmd command like this:

nextcloudcmd --user ... --password ... --davpath /test --unsyncedfolders "/home/pi/nextcloud-sync-cron/remote_sync-exclude.lst" --exclude "/home/pi/nextcloud-sync-cron/sync-exclude.lst" --trust /media/test http://nextcloud-server

It still syncs everything to the main davpath and doesn't respect the local exclude list. The unsyncefolders list is repected.

### Steps to reproduce

1. use nextcloudcmd latest stable debian bullseye version (version 3.1.1-2+deb11u1)
2. use exclude or davpath option
3. both not respected
...

### Expected behavior

Ignore files in excluded list. Use davpath
...

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

debian 11

### Package

Distro package manager

### Nextcloud Server version

24.0.1

### Nextcloud Desktop Client version

3.1.1-2+deb11u1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by camilasan** [comment]
I just realized that with the AppImage you won't be able to use nextcloudcmd, sorry for that.
Could you try to upgrade somehow? There is a 'testing' and 'unstable' 3.5.1 versions listed here:
https://manpages.debian.org/unstable/nextcloud-desktop/nextcloud.1.en.html 🤷🏻‍♀️

**Comment by camilasan** [comment]
The 'unstable' version would require a newer version of Qt so you could try to mount the AppImage and run nextcloudcmd from there:
https://docs.appimage.org/user-guide/run-appimages.html#mount-an-appimage

**Comment by mosandlt** [comment]
I dug into this and found the actual root cause — it's not in the CLI argument parsing (`cmd.cpp`'s `--exclude`/`hasUserExcludeFile` handling has been correct since well before 3.1.1), it's one level deeper.

`ExcludedFiles::reloadExcludeFiles()` in `src/csync/csync_exclude.cpp` silently drops a registered exclude file from its internal list whenever `QFile::exists()` returns `false` for it — no warning, no error, `success` stays `true`. So if the path passed via `--exclude` doesn't resolve at the moment the sync engine reloads it (wrong path, or a relative path that resolves differently under a cron job than in an interactive shell — which fits `/home/pi/nextcloud-sync-cron/...` in the original report), `nextcloudcmd` just proceeds with **zero exclusions and no diagnostic whatsoever**, which is exactly the "still syncs everything... doesn't respect the local exclude list" behavior described here.

(The `--davpath` part of the original report is a separate, already-resolved issue: that flag doesn't exist anymore, it was replaced by `--path` a while back.)

Opened a fix: #10283 — logs a warning when a registered exclude file can't be found, and makes `nextcloudcmd` fail fast with a clear error if a user-supplied `--exclude` path doesn't exist, instead of silently ignoring it.
