### ISSUE TITLE
MSIX instead of MSI

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4642]
MSIX will help us to use sync states in VFS (https://github.com/nextcloud/desktop/issues/4219) and thumbnails (https://github.com/nextcloud/desktop/issues/3407)

Ref: https://docs.microsoft.com/en-us/windows/msix/overview

**Comment by allexzander** [comment]
This is no longer needed for VFS thumbnails and sync states as I set all required Registry keys during sync root registering.
One possible scenario when this could help is if we decided to put the app into Windows Store, then we'd certainly have to switch to MSIX.

**Comment by beedell-roke** [comment]
> https://github.com/nextcloud/desktop/issues/4642#issuecomment-1321717815

@allexzander, MSIX provides significantly more benefits than merely those. Why I care is because of much easier it is to provision, and how much more scriptable [un]installation is. Similarly, it provides a better unattended installation experience when installing from WinGet.

Although I'm not confident, I believe it might assist with https://github.com/nextcloud/desktop/issues/6526#issuecomment-3240252240, too. [^1]

[^1]: [`learn.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-update`][1]

[1]: https://learn.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-update

> https://github.com/nextcloud/desktop/issues/4642#event-7855205257

Best to at least close as unplanned for now, although I believe that this should be reopened.
