### ISSUE TITLE
Allow to create a new encrypted folder from the settings

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/desktop#468]
To add a new encrypted folder, it is required to have the folder already created on the filesystem. Since you cannot encrypt folders that have content, it should be possible to create a new folder and encrypt it right from within the client settings.

**Comment by allexzander** [comment]
@er-vin 

We've got 2 options:
- add a UI feature to create an encrypted folder by displaying a popup/or just a textbox element and asking to type a name, while proposing a default name as well, then after confirming the name input, a folder will get created and encrypted
- add a UI feature for just creating a new folder that is not encrypted by default and also making it possible to rename it in the settings dialog, then, in order to encrypt a folder, one would need to use the standard way of right-clicking on the folder element and selecting **Encrypt**

I find the second way more preferable, as it makes not much sense of adding a feature for creating only the encrypted folders from the UI. Why not allow creating just folders that can also be encrypted straight from within the same UI dialog?

**Comment by er-vin** [comment]
Yes, agreed, second option is likely better.

**Comment by allexzander** [comment]
We went with the second option, and now the folder can be created via the context menu in the Settings dialog. After the folder is created, the sync will run, and after that, the folder can be encrypted via the same context menu.

Closed in  https://github.com/nextcloud/desktop/pull/2897
