### ISSUE TITLE
Review & fix "add account" screen

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4896]
- review with @jancborchardt "add account" view
- check e.g. if buttons can be bigger, more fitting into NC look&feel

**Comment by jancborchardt** [comment]
Went through it with @claucambra, we are thinking:

As quick fixes:
- [ ] Increase the text size of the text below the icons "Keep your data secure and under your control" in the slideshow
- [ ] Reduce the size of the window so all elements don’t look as small and lost
- [x] We keep the button sizes as is since they are the native sizes and bigger buttons are non-native

In the long run:
- [ ] Rewrite to QML as we do with other components so we can do proper layouting
- [ ] Then we can also e.g. make the whole background blue and the icons and text white, like e.g. on the Android setup screen

**Comment by tobiasKaminsky** [comment]
Thanks for looking into this.
Then please @claucambra work on quick fixes, within this ticket.

And create a second one with "long run" tasks and describe the things, together with Jan, in a precise way (can also be a "we do 1:1 what Android has" along with a screenshot), but "e.g." is not specific enough to judge scope/effort of a ticket.
Please then ping me, so I can put it on board for next time.
