### ISSUE TITLE
nextcloud client can't log after exit

### ISSUE THREAD

**Issue by remydev** [nextcloud/desktop#5]
### Steps to reproduce
1. start sync with nextcloud client
2. exit nextcloud client
3. start nexcloud client, the current user can't sync the files

### Expected behaviour
Nextcloud client should start a new sync

### Actual behaviour
The serveur can't be 

### Server configuration

**Operating system**:
Deban 9
**Web server:**
Nginx with reverse proxy

**Database:**
Postgresql

**PHP version:**
php 7

**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
last.zip

**http://example.com/index.php/settings/integrity/failed **
No errors have been found.

![bug1](https://user-images.githubusercontent.com/10176486/31227058-c1275fd8-a9d8-11e7-8cd4-366bce76e104.jpeg)

![big2](https://user-images.githubusercontent.com/10176486/31227100-f400e910-a9d8-11e7-8ec5-582851877ffc.jpeg)

In can use the file systeme explorer to login with webdav... it's long but it's works.

In nexcloud client I can login again with the same user so one is ip the second down .. but it's the same.

**Comment by Marcool04** [comment]
Hi,
I am experiencing this issue also, which is related to #4 I believe, and is caused by the latest update to nextcloud server, rather than client. I have tried multiple client versions, including the latest, on mac os, and have this error on server side:
````
SSL Library Error: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol
````
Will post on issue tracker at server also.

**Comment by Maxattax97** [comment]
I am having a similar issue to the original post I believe. @Marcool04's issue related to #4 is distinct because the connection can't be started when _creating_ a connection. In my case, creating connections to my server are just fine, everything syncs perfectly fine. However, whenever I reboot and Nextcloud client autostarts, or I quit the client and open it back up, it will fail to connect (`No connection to Nextcloud at https://place.com/nextcloud Operation canceled` like in screenshot above).

The only way to fix this currently is to do Account > Remove, then create a new Nextcloud connection using the existing folder and contents of the previous account. This will properly synchronize up until after the client exits.

**Comment by Maxattax97** [comment]
For reasons unknown to me, this issue has magically disappeared today.

**Comment by Maxattax97** [comment]
And now it has magically reappeared... 😢

**Comment by camilasan** [comment]
And today? Is it working for you? :/

**Comment by remydev** [comment]
Sorry, always the same for me.
I use syncthings

**Comment by Maxattax97** [comment]
I have not had issues since. I couldn't tell you what caused this. I didn't change anything. :man_shrugging:

**Comment by bystrano** [comment]
Same here, I have this problem on ubuntu and osx. Runs fine on android though.

**Comment by Aninstance** [comment]
Exactly the same here. 

This issue has been ongoing for at least a year for me, on multiple Linux distros, across a range of hardware, on a variety of servers running different OSs. Even the desktop client snap package is affected. 

Once there is some kind of connection issue which causes either a failure to connect or a drop in an established connection, which is caused by whatever reason (network, OS crash, or whatever), the client refuses to reconnect thereafter, until a full system reboot - and even then that's hit and miss. The only sure way to re-establish a connection is to remove the account from the client and re-add it again from scratch.

This issue happens so commonly (almost daily) that I'm unable to use Nextcloud for anything serious, as connecting to the server with the desktop client is just so desperately unreliable. Which is a shame, as it's a fantastic project - when it works.

**Comment by gergelypolonkai** [comment]
For me the problem seems to be that when I close the client window, the process stays alive. If I kill the process (on Linux, with SIGTERM) and start the client again, it works as expected.

**Comment by Tupi42** [comment]
Same issue here, any updates ?

Tks;)

**Comment by claell** [comment]
@remydev @Maxattax97 are you still experiencing this with current client versions?

**Comment by Maxattax97** [comment]
@claell Have not had this issue for a long time.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
