### ISSUE TITLE
Allow syncing file with case clash names

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#5099]
Some platforms (macOS and Windows) may have restrictions on file names if they only differ in case. Their filesystem are case insensitive.
The idea would be to still sync those files (but rename the files like it is currently done with conflicting files).
We could use a schema like `<real file name> Case Clash (<date>)`.
The user would then be able to get a specific dialog from the activity list by clicking on the specific error entry to be able to rename the file in the server. A subsequent sync would then resolve the clash.
In the meantime, the user would still be able to access the case clashing files.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
In our planning meeting we agreed on:
- if there is a file that cannot be synced, show it as warning (not error!)
- show an explanation, e.g. this file cannot be synced since a file with the same name exists. Please click here to resolve this conflict on server.
- clicking on it in activity list opens conflict resolution on server
- next sync will update it and sync should work again

**Comment by tobiasKaminsky** [comment]
Please also check if this same approach can be used for other files/folder that cannot be synced
- files that have too long file name
- files that have non-allowed characters in its name
