### ISSUE TITLE
Please add support for `.heic` and `.mp4` files for virtual file thumbnails in Windows 

### ISSUE THREAD

**Issue by watermelonpizza** [nextcloud/desktop#5100]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
The virtual file thumbnail support was a very welcome feature😃, however for modern phones using a newer format such as `.heic` (https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format), or for videos such as `.mp4` files there is no current thumbnail which is generated, windows does natively support thumbnails for both such files.

An example of `.heic` files without thumbnails until they are downloaded locally
![image](https://user-images.githubusercontent.com/2477709/198197468-c1973d12-e4f4-45d7-bed3-9894ae8058f3.png)

**Comment by joshtrichards** [comment]
Do those previews show up in in the Nextcloud web UI for you? If not, the issue is a configuration issue on your server. Video previews, for example, aren't enabled by default. E.g. See the NC Server Admin Manual and https://github.com/nextcloud/desktop/issues/3407#issuecomment-1265068079

And HEIC support has similar server side requirements.

**Comment by joshtrichards** [comment]
Closing due to no response to follow-up query after nearly a year.
