### ISSUE TITLE
Fix the PC client PLEASE

### ISSUE THREAD

**Issue by sausje** [nextcloud/desktop#5166]
Why does it NEED to restart explorer.exe AND reboot Windows after?  EVERY update!!
It makes zero sense that you have to do this, the dropbox client functions the exact same way yet hasn't need for all those things when updating!

**Comment by tflidd** [comment]
There are old issues regarding the restart problem that were mostly closed (e.g. https://github.com/nextcloud/desktop/issues/3551). As you see in these discussions, it depends if you installed it via the MSI installer or the simple exe installer. There are certain versions that had a bug that were fixed later, ... so there are quite a few conditions.

For that reason, it is helpful to specify under which conditions you still see problems. I just posted under the linked topic that I still see the issue going from 3.6.2->3.6.4 on Windows 10 Pro with the MSI-Installer.


> It makes zero sense that you have to do this, the dropbox client functions the exact same way yet hasn't need for all those things when updating!

To update with a restart was done in the past and keep it like this is easier. Just that dropbox does it shows only that it is possible, you don't know how much effort it is and since it is a closed-source program, you can't even see how they are doing it.

It's a nice thing to have, while Mac users still report crashes with the client at startup, or if there are real issues with the synchronization procedure ...

**Comment by Magneticdud** [comment]
It needs to restart explorer.exe due to the extensive integration it has. It might be not very needed but in order to be sure that everything is working as expected it's better be safe than sorry.

Dropbox has the millions needed to pay the hundreds of hours of testing required for skipping a explorer relaunch: there are too many variables involved that might cause weird issues later

Reboot is not mandatory, it just asks, at least it's not like before where it rebooted automatically without any confirmation

**Comment by claucambra** [comment]
> It needs to restart explorer.exe due to the extensive integration it has. It might be not very needed but in order to be sure that everything is working as expected it's better be safe than sorry.
> 
> Dropbox has the millions needed to pay the hundreds of hours of testing required for skipping a explorer relaunch: there are too many variables involved that might cause weird issues later
> 
> Reboot is not mandatory, it just asks, at least it's not like before where it rebooted automatically without any confirmation

Yes. We cannot account for every edge case in explorer integration or for potential weirdness with other installed explorer integrations

Reboot is no longer mandatory. If this is still happening please open an issue with a descriptive title and that follows the issue template as the above is not helpful nor actionable to us

Closing

**Comment by Poikilos** [comment]
In case anyone is interested, I found #5251 which follows the issue template.
