### ISSUE TITLE
[Bug]: Nextcloud deletes local files when sync is going wrong

### ISSUE THREAD

**Issue by Dsw77** [nextcloud/desktop#5169]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
Pasted a directory to sync in a nextcloud folder, then moved it to another folder during sync.
Nextcloud gave a sync  error "File allready exists" and then deleted all files online and locally. now everything is gone!!!

### Steps to reproduce

1. Cut and paste a directory into the nextcloud folder or a subfolder
2. When sync is not yet finished move the files to another folder in your Nextcloud directory
3. An error occures and al files are deleted
...

### Expected behavior

Nextcloud deletes nothing. maybe wait until sync is finished and the moves files.

### Which files are affected by this bug

fthis were mkv files and directories

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Distro package manager

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by rgreeott** [comment]
We have seen this issue to with NC 24.0.5 and client 3.6.2.  Both windows 10 and 11

**Comment by ymilhahn** [comment]
I experienced this with Nextcloud Desktop-Client 3.6.2 (Arch) on two different Nextcloud instances V. 23.0.3 and the other V. 24.0.2.

**Comment by Githopp192** [comment]
i noticed a similar behave with the current version (3.6.2), but also with all previous Versions of Nextcloud Windows Desktop Agents.
Nextcloud Windows Agent is not able to handle simultan operations, like moving a folder while a sync operation is running.
This needs to be improved urgently.

**Comment by rgreeott** [comment]
> i noticed a similar behave with the current version (3.6.2), but also with all previous Versions of Nextcloud Windows Desktop Agents. Nextcloud Windows Agent is not able to handle simultan operations, like moving a folder while a sync operation is running. This needs to be improved urgently.

I could not agree more on urgency.  We have 30-50+ sync clients attached at any given time.  When files get deleted during a move or rename operation, we're forced to restore from a rolling backup.  It should be noted, the web client will still list the file, as if it was there.

**Comment by anonbergine** [comment]
Also experienced this. Win10 with latest stable versions of server and desktop client.

Overall impression after ~6 months of using NC is that the sync suffers a vast array of reliability issues, particularly on Windows, but also on linux (eg. a recent sync issue caused 100GB of data corruption on server). The Sync feature is categorically not production-ready.

**Comment by byiigor** [comment]
Same problem.

And another step to reproduce:
Download file through browser to syncing directory.
When download is not yet finished and sync is not yet finished an error occures and files are deleted. 

version 3.6.6 (Windows) 
windows-10.0.19045

**Comment by Githopp192** [comment]
may be another context, but i don't want ot create a new issue, because is problem has been solved in the meantime ... 

what i experienced yesterday: NC Agent 3.4.4

1. from PC 1 with Virtual Agent active: move a sub-folder from folder 1 to folder 2
2. PC 1: Windows Explorer shows: moving was successful, NC Agent shows: moving was successful
3. Login to the WEB, same: sub-folder was correctly moved (not existing on source, existing on destination)
4. PC 2 with Virtual Agent NOT active: NC shows sync errors - permission errors on sub-folder from folder 1

![image](https://user-images.githubusercontent.com/32612067/215700561-277a1d32-e364-425f-88e6-b0a081c19ea4.png)

5. (NC Agent on PC 2 is not aware, that sub-folder on folder 1 was moved, that's why the permission errors occurs)

6. PC 2: Windows Explorer does not reflect the new situation: sub-folder on folder 1 is still there, sub-folder is not existing on folder 2 (but the WEB shows, that the move operation was successful).
7. Restarting the NC agent does not improve the situation on PC 2.
8. Upgrade to NC AGent 3.6.6 on PC 1 & PC 2. Reboot both. After that, problem seems to be solved.
