### ISSUE TITLE
[Feature]: Optimal layout of notifications and action buttons

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/desktop#5275]
### ⚠️ Before submitting, please verify the following: ⚠️

- [ ] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The layout of the notifications, specifically the chat notifications is not optimal. It's using a lot of space. The buttons are not aligned to each other.  And the buttons are generally very big compared to the rest of the UI and the text. 

See screenshot:

![layout](https://user-images.githubusercontent.com/867445/207570624-d8d30fba-9370-4033-bf06-22e45bffc3ca.png)

Would it be possible to put the three action buttons (reply) (view) (dismiss) in one row, at the right side of the windows?

### Steps to reproduce

Receive several chat notifications and look at the tray windows

### Expected behavior

A cleaner UI with more content visible and less huge buttons. 

### Which files are affected by this bug

no files 

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS Ventura

### Package

Appimage

### Nextcloud Server version

25.0.2

### Nextcloud Desktop Client version

3.6.50

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
none
```

### Additional info

none

**Comment by karlitschek** [comment]
@jancborchardt @nimishavijay @claucambra @tobiasKaminsky @matthieugallien

**Comment by karlitschek** [comment]
Thanks @claucambra Native buttons are an interesting direction. But we should cleanup the UI to make a buttons more consistent and to use less space. With native UI elements or not.

**Comment by claucambra** [comment]
> Thanks @claucambra Native buttons are an interesting direction. But we should cleanup the UI to make a buttons more consistent and to use less space. With native UI elements or not.

Agreed, I think we have two options here that can help condense things while not breaking them further:

- Reduce vertical size of primary action button
- Only show on activity item hover as an overlay

@jancborchardt @nimishavijay I am sure you have some better ones too :)

**Comment by nimishavijay** [comment]
Great points @claucambra!
- If the height of the primary action button is 44px, it can be reduced to 32px (I'm not sure about reducing it further for accessibility reasons)
- There is also some extra margin inside the button on the right of the "Reply" text which can be removed
- The background of the dismiss button can be removed 

This would already improve it greatly :)

I was also checking out how it could look with some more rearranging:

![image](https://user-images.githubusercontent.com/52440189/208107448-f4545a27-e3cb-4f1e-b50e-e8dd27e27d7d.png)

This requires more effort and would need some more discussion but as a starting point:
- The primary button is moved to the right and is an icon-only button
- All buttons are icon-only with a 16x16px icon and a 32x32px button clickable area
- The buttons are aligned in such a way that the icon is top-aligned with the text
- For Talk notifications, the message displayed is shortened to `[Sender name] on Talk`

This mockup has only chat notifications so it would be different for files, calls, etc. What do you think? cc @jancborchardt for feedback when he is back :)

**Comment by claucambra** [comment]
> I was also checking out how it could look with some more rearranging:
> 
> ![image](https://user-images.githubusercontent.com/52440189/208107448-f4545a27-e3cb-4f1e-b50e-e8dd27e27d7d.png)
> 
> This requires more effort and would need some more discussion but as a starting point:
> 
> * The primary button is moved to the right and is an icon-only button
> * All buttons are icon-only with a 16x16px icon and a 32x32px button clickable area
> * The buttons are aligned in such a way that the icon is top-aligned with the text
> * For Talk notifications, the message displayed is shortened to `[Sender name] on Talk`
> 
> This mockup has only chat notifications so it would be different for files, calls, etc. What do you think? cc @jancborchardt for feedback when he is back :)

This mockup looks really nice and much more space-efficient. I think the dismiss button in particular is a huge improvement.

 But I have some trouble seeing how we can translate it into a real-life activity item because the primary button icon is not provided by the activity data at all, and we have to manually set it for specific activity types in the client. Meaning for a lot of apps the primary button will have no icon at all -- so I don't see how we could lay this out in the top-right small button, at least not until the server API provides icons to go along with actions. 

Also, what about the secondary actions? Where would those go? If we have to put them at the bottom of the activity then the space savings are kind of nullified

Lastly, the share icon -- the dismiss icon and the share icon on file activities are pretty much the same, would we also make the share icon a small button on the top-right?

**Comment by jancborchardt** [comment]
Awesome work @nimishavijay! This looks so cool. :) Only have detail points:
- It would be good to show the reply button always (also on Marija’s message in this case)
- The "on Talk" is not needed I’d say?
- I’d say it would be nice to bold the sender name, just like we do for your own name in the heading and for the "Syncing"/"All synced" state

**Comment by tobiasKaminsky** [comment]
Do we really want to have specific layouts for different notifications?
Right now we have a "one fits all" solution.

Not judging, I am really just asking if we should do it. 
If so, we then also need specific mockups for notifications with 1,2 or even more actions.
(and those actions have names, where we do not know/control how long those are…)

**Comment by jancborchardt** [comment]
@claucambra 

> not until the server API provides icons to go along with actions.

Yep, then we need to adjust the notification API so that is possible. @PVince81 @nickvergessen 


> Also, what about the secondary actions? Where would those go? If we have to put them at the bottom of the activity then the space savings are kind of nullified

If there are more than 2 actions, anything except the primary action can go into a 3-dot menu, on the spot where the "x" dismiss is now.
But more obvious actions like "View chat" can just be handled by clicking the entry itself.

> Lastly, the share icon -- the dismiss icon and the share icon on file activities are pretty much the same, would we also make the share icon a small button on the top-right?

Yes, we can make it uniform in layout like that. This also answers @tobiasKaminsky’s question, right?

**Comment by tobiasKaminsky** [comment]
I would be more comfortable if we have a mockup for some/all different types.
Then we can also use this to check/adopt it on Android/iOS.

**Comment by nickvergessen** [comment]
> Yep, then we need to adjust the notification API so that is possible.

Would of course be possible, but only going forward. Actions without icons would still need to be supported for 3years, which means until ~2026

**Comment by jancborchardt** [comment]
One consideration @AndyScherzinger and I had discussing this is that looking at the design of other native notifications @claucambra posted at https://github.com/nextcloud/desktop/issues/5275#issuecomment-1351061362 is that all the action buttons are text-only – not icon-only (except dismiss).

This is generally more understandable and more accessible, so maybe it makes more sense to go in that direction? In the Talk example:
- Dismiss would still be an x
- "View chat" would be the action when you click on the entry itself
- "Reply" would be the only actual action. Could be a button on the bottom right, same line as timestamp.

So this is @nimishavijay’s mockup slightly adjusted based on that. Uses same reduced vertical space, but text button and adjusted timestamp position:
![image](https://user-images.githubusercontent.com/925062/209829051-88f34a11-c50b-47cc-bea0-9a26afd22445.png)

**Comment by tobiasKaminsky** [comment]
Create generic layout for all, discuss with @jancborchardt 

Check
- login approval
- talk chat
- general notification
- general: 1,2 or more actions -> how to show them?
- activity item
  - deletion/adding of a file -> maybe mimetype with small +/x instead of giant X

Bug
- remove old notifications: receive message via Talk, answer in web, still see it in notification list

API Documentation: https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md

**Comment by mgallien** [comment]
make sure and check that all accessibility metadata to every notification items

**Comment by mgallien** [comment]
fix overlay icons for dark/light mode

**Comment by mgallien** [comment]
I will check the source of the icons and make sure the border of the icons is the proper one

**Comment by nickvergessen** [comment]
> general: 1,2 or more actions -> how to show them?

Maybe it's time to finally add a fake-testing command that generates notifications with dummy actions

**Comment by tobiasKaminsky** [comment]
> Maybe it's time to finally add a fake-testing command that generates notifications with dummy actions

Awesome idea. Let me give this a try.

**Comment by tobiasKaminsky** [comment]
Draft here: https://github.com/nextcloud/notifications/pull/1431

**Comment by tobiasKaminsky** [comment]
A way better approach is this by Joas: https://github.com/nextcloud/notifications/pull/1432

**Comment by mgallien** [comment]
Current state for a Talk message notification
still work needed

![image](https://user-images.githubusercontent.com/168967/220297686-7376b342-2d25-4797-9bd9-2687f0532e5c.png)

@jancborchardt  @nimishavijay 
could you give it a quick look to see if you have early feedback (please forget about the `Reply` button style, it has got the default Linux style that is just bad) ?

could you also give me info about the reply feature ? should I keep the previous solution with inline reply via extended area at bottom of the notification ?
see
![image](https://user-images.githubusercontent.com/168967/220298605-7a708132-c697-40d5-987f-6b696c8f74cf.png)

a last question, do you already have mockups of the other notification types ?

**Comment by nimishavijay** [comment]
Looks great! My main point was about the button anyway :) If the button will be styled then that's great! Some other small things:
- Is it possible for a shorter date/time? It shows "33 minutes ago" which is quite wide. Instead we can show "33m" for minutes, "2h" for hours, "2d" for days, etc
- If that is not possible, we can decrease the font size of the datetime to match the size of the content text
- There could also be around 2px of space between the text content and the button. It seems quite close now.


For the reply feature, doing it like how it is currently seems like the best option, good call :) 
On clicking "reply" the height of the container will increase and the input field will appear below the text. Also additionally, since the container is increasing in height anyway, for long messages there could be up to 2-3 additional lines of text shown. What do you think? also cc @jancborchardt 
<img src="https://user-images.githubusercontent.com/52440189/220331497-17288e90-2758-494b-a1cd-35167f8dd7e9.png" width=50% height=50%> <img src="https://user-images.githubusercontent.com/52440189/220331592-19d53e3e-713e-48c7-bd8e-178c33bf1bf1.png" width=50% height=50%>

Other solution I tried: replacing the content text with the input field. This preserves the size but it is confusing as the message you are replying to disappears.
<img src="https://user-images.githubusercontent.com/52440189/220331774-8ff1f8a6-84cd-46d1-861b-a598cf4d3cf4.png" width=50% height=50%>

For the other types, the basic layout can be similar:
- [ ] dismiss button on top right corner
- [ ] primary action as a text-only button on bottom right corner 
- [ ] position of any secondary actions should be discussed. Any initial thoughts @jancborchardt ?

I can do mockups for the particular file types with @jancborchardt and post them soon :)

**Comment by jancborchardt** [comment]
Agree with all of @nimishavijay’s comments – additionally:
- [ ] The alignment and sizing is off:
  - [ ] The avatar of the message sender is much bigger than e.g. the avatar of yourself in the heading
  - [ ] This leads to the text not being left-aligned anymore
- [ ] I don’t know if it is because the text of the entry is too big, or the text above is too small. It’s just mismatching, if you compare it to the mockups (and the current state of the tray actually)
- [ ] To clear this up, I would suggest we keep everything in the tray menu at one font size, and only differentiate with bolding (for your own name, "All synced", and headlines like e.g. sender names) or max-contrast (for supplemental info like timestamps or the search input placeholder)

**Comment by nimishavijay** [comment]
Possible layout improvements for other notifications:

<img src="https://user-images.githubusercontent.com/52440189/221355153-2c9d4e53-c879-4f26-a3a9-2230038752dd.png" width=50% height=50%>

- General idea remains the same: small dismiss button on top right, small primary button on bottom right, shortened date time 
- For items with multiple actions: primary action is shown, rest of the actions in a three dot menu on the left of the primary action 
- For notifications that have only one line and no button, the icon/thumbnail size could be reduced to around 36x36px so that the height of the container can also be reduced. 
- In #3665 we discussed having a title, subline, icon, thumbnail, date, location etc consistently standardised for all apps, so I'm guessing it is not possible to fine tune each type of notification yet, but they should all fall into one of these layout categories, right?

what do you think? and cc @jancborchardt for any changes :)

**Comment by jancborchardt** [comment]
Looks great @nimishavijay! Only one edit about the link expiration, for that the filename should also be bold in the first line and the subline short like so:

> **Bookmarks design review.md**
> Share link expired

(Also slight wording adjustment.)

**Comment by jancborchardt** [comment]
@mgallien what’s the current state of this by the way – do you have screenshots to share, and we should talk about what to improve next! :)

**Comment by nickvergessen** [comment]
Just to repeat it again, the clients MUST NOT modify text of notifications/activities provided by other apps (the information what a notification is about might not be fully available at the clients, because the parameters, notification object and app id are not unique identifiers).

If we want to have such a short / different labelling and strings that needs to be extended on the API, therefore properly scheduled with the involved server teams and all apps need enough time to be able to provide that new mode.
