### ISSUE TITLE
NC icon is broken

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/desktop#546]
Hello,

I tried one of the very first e2e-desktop clients and in the Windows-Explorer was installed the Nextcloud-e2e icon / link to the folder.
When installing one of the latest prereleases, the icon was broken and also pointed to a new directory :-/
I am using latest prerelease Version 2.5.0daily (build 20180812).

Regards

**Comment by er-vin** [comment]
Hello,

This is a very old issue sorry about not getting back to you about it earlier. Since it is about, a prerelease of 2.5.0 I will assume you are not affected by this issue anymore (we rolled a few stable release since then).

If it turns out you are still affected, please let us know either by commenting here and reopening (if possible) or by opening a new issue.

Regards.
