### ISSUE TITLE
[Bug]: client (at least macOS client) doesn't sync symbolic links

### ISSUE THREAD

**Issue by avibrazil** [nextcloud/desktop#5509]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I know this is being [discussed in some forum](https://help.nextcloud.com/t/symbolic-link-support/220/45).

Nextcloud must support Unix symbolic links, either storing them as a reference (the correct way of doing this, in my opinion) or de-referencing them (storing a copy of the content they are pointing to). Or let the user chose how to store.

Unix filesystem symbolic links have nothing to do with web links. Please let's not confuse these 2 different concepts in this discussion.

Unix filesystem symbolic links are an incredible practical OS feature.

### Steps to reproduce

On my Mac, inside a folder synced and managed by Nextcloud, I do this:
```
$ touch a
$ ln -s a b
$ mkdir x
$ ln -s x y
```
Create a file named `a` and create a symbolic link named `b` pointing to `a`, all in the same folder.
Create a folder named `x` and create a symbolic link named `y` pointing to `x`, all in the same folder.

File `a` gets synced but file (symbolic link) `b` doesn't. Same for folders `x` and link `y`. I verified by going into the Nextcloud Linux server and checking which files appeared under `/var/lib/nextcloud/data/USER/files/...`

I don't get the symbolic links in the server.

### Expected behavior

Expected behavior is to get the Nextcloud client handling and storing Unix symbolic links as symbolic links.

Then clients on other platforms, such as Windows, will convert the server-side Unix symbolic link into something that makes sense in Windows filesystems, which apparently already supports symbolic links.

When I mount my Nextcloud folder via WebDAV as a regular filesystem (using davfs2), I also expect to correctly see the synced symbolic links.

### Which files are affected by this bug

I have no idea

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura 13.2.1

### Package

Appimage

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mikeperalta1** [comment]
Hope this will be done eventually. It's a big time waster to constantly have to re setup symlinks on every desktop I use, especially in situations where I use many many symlinks to organize things.

**Comment by taminob** [comment]
I think this might be a duplicate of #250. Already posted it over there, but I'd like to work on Linux symlink synching (without dereferencing, so "as-is") which might be identical for MacOS, but I have no experience with MacOS. :)

However, they probably shouldn't be stored as symbolic links on the server-side since that might pose a security risk (or requires additional handling to prevent links to the outside of the user data directory, could also be an option to allow for your WebDAV mounting use case).

**Comment by taminob** [comment]
> @taminob I just did a quick test on my nextcloud instance by creating a symlink to one of my folders directly in my user's data dir ( ln -s /var/www/nextcloud/data/myuser/myfolder /var/www/nextcloud/data/myuser/mylink ) and restarted apache and it does not show up in the web front end...not a conclusive test by any means but it doesn't seem that they are even visible by the web file browser.

You have to enable `'localstorage.allowsymlinks' => false` in your nextcloud server config if you want them to show up. Broken symlinks will be ignored and all other symlinks (to either file or directory) will be simply shown as that file/directory in the front end. (You probably also have to run a `occ files:scan --all` if you create the file manually.)

However, I think this will actually also let the client download the file/directory twice because the server will dereference them and send the file/directory content.

I already did some work for uploading symlinks, I will open a PR soon. Changes on server and client are definitely necessary.

**Comment by joshtrichards** [comment]
Duplicate of #250
