### ISSUE TITLE
[Bug]: ignored files always show state 'sync pending'

### ISSUE THREAD

**Issue by PhilippSchlesinger** [nextcloud/desktop#5524]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

ignored files always show state 'sync pending'

### Steps to reproduce

1. have some files that are ignored from sync per configuration.
![grafik](https://user-images.githubusercontent.com/2735628/224999921-810a0753-446c-4b3f-99c7-cc16383236d4.png)

2. look at some of those files in Windows Explorer:
![grafik](https://user-images.githubusercontent.com/2735628/225000406-a01e256f-945c-4eb9-9de4-e94f7995d2f4.png)

3. the files show 'sync pending' while hovering and in status line. The status icon is also suggesting 'sync pending'.

### Expected behavior

File status and icon should somehow show that this file is exempted from sync.
Icon could be corresponding to the tray window
(
![grafik](https://user-images.githubusercontent.com/2735628/225001778-99c73349-9873-445f-8648-e4a4f9bcc91e.png)
)

### Which files are affected by this bug

all files that are ignored by configuration

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Plinsboorg** [comment]
# **I can confirm the same issue for me.**
## Software versions
I tested it on my personal PC: Windows 11 Home 22H2 build 22621.1413
And on the fresh Windows install in VM: Windows 10 Home 22H2 build 19045.2728
Nextcloud desktop client version 3.8.0
Nextcloud server. Tested on: 26.0.0, 25.0.2, 24.0.9
**This issue shows up on both OS versions, and for each server version from above.** 

## Ignored files and desktop.ini
You can see I added the .xyz file to the ignore list and it became permanently in pending sync state
![ignored files are not synced](https://user-images.githubusercontent.com/42300339/230767190-9d42768b-9af1-4117-bb79-4548b25ec459.png)
This issue also affects the desktop.ini files. Nextcloud ignores them as explained [in this post](https://valinet.ro/2022/04/12/Upload-desktop-ini-when-using-Nextcloud.html) (this post also confirms the issue). When you add a custom icon to the folder Windows creates desktop.ini inside of it. This file receives pending sync status and this status propagates to the folder itself and all folders above it. 
When I remove the .xyz file from the ignore list it's synced just fine:

![ignored files are not synced 2](https://user-images.githubusercontent.com/42300339/230767440-a7b91acd-4eb6-42c7-aa31-27b68583e842.png)

But the issue with desktop.ini is not going anywhere. 

## Test with older version of file explorer
I also tested on the older version of Windows. Windows 10 Enterprise 1607. It had the older version of the file explorer that looks like this:
![ignored files old file explorer](https://user-images.githubusercontent.com/42300339/230767629-789d967c-f320-4c3c-b187-7a15d64788cb.png)
You can see the status icon is displayed close to the folder (not in the separate column). It is not syncing the desktop.ini files but they have a yellow icon instead of the blue (sync pending) icon. And this doesn't propagate to the folder above. You can see the Photos folder has a green icon despite the desctop.ini with a yellow icon inside of it. If you hide hidden files you will not see this in the old style of file explorer. That's why you didn't see this issue earlier.

## Expected behavior 
I would suggest different icon for the expected behavior. 
![image](https://user-images.githubusercontent.com/42300339/230767902-6ba92c00-27f4-4821-b777-cb13b37c2bc8.png)
I would expect the gray icon that is used by Onedrive. It also displays "Excluded from sync" message when you hover the mouse over this icon.

**Comment by Plinsboorg** [comment]
I found out that even on the new versions of Windows the status icons are displayed in the "old way" (near the folder icon) if you don't enable the virtual files support. 
And without virtual files support enabled this issue is not observed.
![image](https://user-images.githubusercontent.com/42300339/233746986-32063a04-3c5a-4233-acfa-2fcb8ea4b98b.png)
Windows 11 Home 22H2
Nextcloud desktop client version 3.8.1
Virtual files support DISABLED

**Comment by nfnfgo** [comment]
Sorry to disturb, but it seems I'm still facing this issue in the latest NextCloud Desktop client.

![showing_pending](https://github.com/user-attachments/assets/6adc3015-3e30-4704-9d7d-c0fd18cad41e)

As the image shows above, some ignored folder shows a "Pending" states.

Below is my ignore config:

Global:

![Image](https://github.com/user-attachments/assets/d73eea79-5b37-4016-a5b2-648a69bbfe23)

Per-folder:

![Image](https://github.com/user-attachments/assets/45c3e3a0-764d-4a1f-8fd0-b9a12bcf2795)

My version info is attached below:

```plaintext
OS: Windows
Edition	Windows 11 Enterprise
Version	24H2
Installed on	‎12/‎7/‎2024
OS build	26100.3775
Experience	Windows Feature Experience Pack 1000.26100.66.0

NextCloud Desktop 3.16.2
```

**Comment by nfnfgo** [comment]
Here is some additional info about my case.

### Only with those ignored files already exists before sync connection created

I found that this issue only affect those **ignored folders/files that already exist before adding a new sync connection**.

For example, before adding a sync folder using NextCloud desktop, I have a folder `/Sync` with structure below:

```
- Sync/
  - .git/
```

If I try to add a connection like: `local:Sync <---> NextCloud/Sync`, then issues occurred.

- The  `/Sync/.git` will be ignored, and NOT uploaded to server. (Expected behavior)
- The `/Sync/.git` will **shows a "Sync pending" state forever** on local machine (Unexpected, should be "Excluded(Not synced)" )

-----

Note that if I try to create another ignored folder like `/Sync/Another/.git` AFTER the creation of sync folder, the state could be shown correctly.

### Renaming could help

Consider the example above, if the `.git` folder already there before link created, there could a wrong sync state display.

However if I try to:

- Rename from `.git` to `.git1` (Or some other name that will not be ignored)
- Change it back to `.git`

This time it will show "Excluded(Not synced)" state correctly.

**Comment by tomdereub** [comment]
I get the same behaviour with .lnk files, about only files that exist before sync connection creation causing a bug : https://github.com/nextcloud/desktop/issues/6419

**Comment by Baptistou** [comment]
This issue is still present with Nextcloud Desktop 4.0.6 on Windows 11.

**Comment by nfnfgo** [comment]
Seems the issue still exists.

This bug is quite annoying, considering the fact that **if a file has been ignored but shows as being in a pending state, all the parent folders will also be shown in a pending state**. This bug will **render the state indicator useless**, since user could not tell if there is something syncing for that folder, or if there's just some files in that folder has been ignored.

I believe this issue should be reopened and fixed as soon as possible.
