### ISSUE TITLE
[Bug]: Linux client is too aggressive in notifying about sync errors

### ISSUE THREAD

**Issue by euclip** [nextcloud/desktop#5633]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I use Gnucash on Linux, and I have the database synced up to nextcloud. Every time I open Gnucash or save the database, Nextcloud triggers a desktop notification telling me that it failed to synchronize files that Gnucash creates. I'm not sure exactly what what Gnucash does with its files to cause the NC client to do this, but in any case when I click the notification to open the NC dialog, everything that needs to be synced has been synced, so it seems to me that the client is perhaps a bit too aggressive when notifying about such sync failures. The notifications can be extremely irritating as well.

I don't know how technically feasible this is, but perhaps when there is a sync failure, a retry would be triggered, say, a few seconds later, and only if that retry fails should the desktop notification be displayed.

### Steps to reproduce

1. Install Gnucash and create its database in your NC synced folder
2. Make some changes in the database in Gnucash and then save
3. Close Gnucash and then reopen it, make some more changes, and then save again

### Expected behavior

No desktop notification is displayed regarding synchronization failures which are resolved nearly immediately.

### Which files are affected by this bug

Gnucash database files

### Operating system

Linux

### Which version of the operating system you are running.

Fedora Workstation 38

### Package

Distro package manager

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

The debug archive contains information that I would prefer to keep private.

**Comment by maples3** [comment]
I also have a similar issue with GnuCash.  In my case, I often get sync conflicts.  I'll save the file, and then a second or two later, Nextcloud will tell me that there's a version conflict, and prompt me to choose between the "server version" and the "local version".  The correct answer is (nearly) always the "local version", because it hasn't actually been changed on the server.

I say "nearly always", because occasionally I'll open the prompt and it will ask me if I want to keep a 0kB local version or a properly-sized server version.  If I choose the local version in that case, I'll lose all of my data since the last successful sync (which may have been a while ago, due to these same sync issues).

The last time I was working in GnuCash, I decided to ignore all the sync errors until I was done.  That turned out to be a mistake.  The client apparently keeps track of multiple version conflicts at a time, and keeps a copy of the file at a time.  There were a half-dozen conflict messages, and I started clicking "local version" for all of them -- then I realized that one of them was a 0kB version.  Fortunately, the server version history somehow had the correct, up-to-date version (what _should_ have been kept when I clicked "keep local version"), and I was able to restore that copy.

**Comment by jospoortvliet** [comment]
There's been quite some bugfixing in this handling of conflicts and such. Does this still happen? If not, I suggest closing the issue... To help keep this clean, I'll take the liberty to close it - please, re-open if still relevant! Thanks!
