### ISSUE TITLE
nextcloud client does not launch on OSX 10.13.1

### ISSUE THREAD

**Issue by opeeters** [nextcloud/desktop#57]
Hi,
it is impossible to get the client to launch on macOS 10.13 High Sierra. I tried both version 2.3.2 and 2.3.3 beta. Same result. Launching the client, e.g. like so:

```
/Applications/nextcloud.app/Contents/MacOS/nextcloud --logfile nextcloud.log
```
produces the attached log output:
[nextcloud.log](https://github.com/nextcloud/client/files/1499528/nextcloud.log)

and dmp (as zip):
[A486DFD3-3F9D-427C-9281-54EB98451F7F.dmp.zip](https://github.com/nextcloud/client/files/1499532/A486DFD3-3F9D-427C-9281-54EB98451F7F.dmp.zip)

**Comment by tflidd** [comment]
There is a report on startup problems with the OC client as well:
https://github.com/owncloud/client/issues/6191

**Comment by mcnesium** [comment]
This is also happening on Mac OSX 10.11 El Capitan using the current stable Nextcloud-2.3.3.84.pkg as well as Nextcloud-2.3.2.1.pkg

**Comment by mcnesium** [comment]
Is this error related?

    $ /Applications/nextcloud.app/Contents/MacOS/nextcloudcmd -u mcnesium -p xxxx Desktop/ https://cloud.domain.de/remote.php/webdav/desktop/
    Illegal instruction: 4

According to [this answer](https://stackoverflow.com/a/14285922/1329744) it means that the application is not able to run on my old OSX 10.11 😞

**Comment by thedogsrag** [comment]
If you are using self signed certificates my above instructions won't help you that much. It queries you to add the certificate and you click yes but then the Chrome backend blocks it. I suspect it is because I need to do something special with the .pem file in the openssl directory. There isn't that much documentation on that so I kind of gave up.

If you are using a normal certificate or no authentication I suspect it will work for you though. 

I ended up downloading the old version of the client from the nextcloud ftp site (2.2.4). Hopefully that helps some people like me get out of gaol.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
