### ISSUE TITLE
[Bug]: root home folder connection with root nextcloud folder gives permission problem

### ISSUE THREAD

**Issue by keunes** [nextcloud/desktop#5950]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When setting up a folder connection in the desktop client with the user's root folder (`/home/username`), permission errors are thrown.

### Steps to reproduce

1. Start setting up new folder connection
2. Enter `/home/username` as the local folder
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/de106cbf-54b2-46df-a5b7-2cd17b2f30b8)
3. Select the Nextcloud root as the remote folder
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/baa57185-fe68-4552-b227-2a4884332c37)
4. Confirm that no remote folders need to be excluded
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/2abeba47-1bde-4868-aea5-420115fb3507)
5. See a lot of sync error, about a new one every second
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/2bcae894-58f0-4643-97a3-a431995d0008)

### Expected behavior

Start synchronisation of all folders in the home folder (i.e. Documents, Images, etc).

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 23.04

### Package

Official SNAP package

### Nextcloud Server version

26.0.0

### Nextcloud Desktop Client version

Versie 3.9.0 (Ubuntu)  ubuntu-core-6.2.0-26-generic

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Not sure if 'Official snap package' refers to the following: https://snapcraft.io/nextcloud-desktop-client. But that's what I installed.

I verified that the snap has the permission to access the files:
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/43f1bba9-3315-4d7b-95ac-9ebe95992e6b)

I didn't include the debug archive because the server URL is all over the place, while I want to keep it private. Happy to provide relevant info from it, if necessary.

**Comment by m038** [comment]
I am also suffering from this bug. I am able to reproduce the bug with the steps described above. I think this is a Snap specific issue, due to the way access to hidden files on home directories are managed by Snaps.

After researching the topic of accessing data in the home-directory I've found [this article](https://snapcraft.io/docs/home-interface). From that page the following becomes clear:

> The home [interface](https://snapcraft.io/docs/interface-management) allows access to **non-hidden files** owned by the user in the user’s home ($HOME) directory where a user normally stores their personal files and documents.

Purely adding a connection to the `:home`-interface for Snaps will no suffice for the use case that creates this bug. Based on [this](https://askubuntu.com/questions/1238211/how-to-make-snaps-access-hidden-files-and-folders-in-home) and [this](https://forum.snapcraft.io/t/the-personal-files-interface/9357) it seems that additional permissions are needed. Namely connection to the `:personal-files`-interface.

```
> sudo snap connect nextcloud-desktop-client:personal-files
error: snap "nextcloud-desktop-client" has no plug named "personal-files"
```

When trying to connect this interface, it is not allowed, as the interface needs to be defined in the Snap before it can be connected.


**Bug details**
Nextcloud version: 3.10.1
Nextcloud Desktop version: 27.1.4

**Expected behavior**
Synchronization happens via Nextcloud Snap Desktop Client

**Actual behavior**
Error indicating lack of write access in `/home/$USER`. Nextcloud Desktop Client writes `.sync_*` files in the synchronization directory to keep track.

**Home directory sync setup**
![image](https://github.com/nextcloud/desktop/assets/164319/09c746d9-e1d5-47e0-9fb6-44878f6f5e0e)

**Errors reported by snap**
![image](https://github.com/nextcloud/desktop/assets/164319/13da3d5c-b56d-4041-976d-c5ffeaa3a52c)

**Snap connections for nextcloud-desktop-client**
```
> sudo snap connections nextcloud-desktop-client                                                                         1 ✘ 
Interface                 Plug                                               Slot                            Notes
browser-support           nextcloud-desktop-client:browser-support           :browser-support                -
content[gnome-42-2204]    nextcloud-desktop-client:gnome-42-2204             gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]     nextcloud-desktop-client:gtk-3-themes              gtk-common-themes:gtk-3-themes  -
content[icon-themes]      nextcloud-desktop-client:icon-themes               gtk-common-themes:icon-themes   -
content[sound-themes]     nextcloud-desktop-client:sound-themes              gtk-common-themes:sound-themes  -
desktop                   nextcloud-desktop-client:desktop                   :desktop                        -
desktop-legacy            nextcloud-desktop-client:desktop-legacy            :desktop-legacy                 -
gsettings                 nextcloud-desktop-client:gsettings                 :gsettings                      -
home                      nextcloud-desktop-client:home                      :home                           -
mount-observe             nextcloud-desktop-client:mount-observe             -                               -
network                   nextcloud-desktop-client:network                   :network                        -
network-bind              nextcloud-desktop-client:network-bind              :network-bind                   -
network-manager-observe   nextcloud-desktop-client:network-manager-observe   -                               -
opengl                    nextcloud-desktop-client:opengl                    :opengl                         -
password-manager-service  nextcloud-desktop-client:password-manager-service  -                               -
removable-media           nextcloud-desktop-client:removable-media           -                               -
unity7                    nextcloud-desktop-client:unity7                    :unity7                         -
wayland                   nextcloud-desktop-client:wayland                   :wayland                        -
x11                       nextcloud-desktop-client:x11                       :x11                            -
```

**Comment by joshtrichards** [comment]
You'll have to take this up with the maintainers of the snap you're using: https://github.com/glasen/snap-nextcloud-desktop-client/issues

This looks potentially relevant:

https://github.com/glasen/snap-nextcloud-desktop-client/issues/14
