### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HumanG33k** [nextcloud/desktop#5951]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Data leak on notification. 

I currently not need wanted to see some notifications on certain destktop device. 
I just need to sync files. 
In my current production/company env notification of others things can be see as same as a security issue. 

### Steps to reproduce

1. connect the desktop app
2. wait 
3. see calendar or whatever not current sync files notifications.

### Expected behavior

A least a full désactivation of notification by device or better a fine grain configure notification  by device.

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

Parrot

### Package

Distro package manager

### Nextcloud Server version

24.0.12

### Nextcloud Desktop Client version

3.1.1-2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by thgoebel** [comment]
I don't know about Parrot and which desktop environment you use. But on KDE Plasma you can configure Notifications for each application under "System Settings -> Notifications -> Application-specific settings -> Nextcloud". There you can enable/disable notifications.

Actually, I would expect enabling/disabling notifications to be an OS feature, not an app feature. That's how iOS and KDE do it. Android goes one step further with Notification Channels where you have very fine-grained control and can enable/disable different types of notifications.

P.S.: Nextcloud 24 is [end-of-life](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) since April 2023, you might want to upgrade to 27 :)

**Comment by jospoortvliet** [comment]
Yes, please configure this on your desktop - or on the server. You can configure this here:

<yourserver>/settings/user/notifications

The client sends the server notifications, that's not a bug, that's a feature ;-)
