### ISSUE TITLE
Click for details not working in Linux Appimage and macOS

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/desktop#610]
Downloaded the latest Beta version of the Appimage. Everything went well, it remembered my settings etc, so all good. But then came a message stating "There are unresolved conflicts. Click for details" just beneath the Sync ribbon which tells you what files are being checked. The mouse pointer changes like with a URL when I hover over it, but clicking on it seems to do nothing. It doesn't open a list or anything.

Where is it supposed to take me?

**Comment by augustseptember** [comment]
Same here with RC1. It also prevents to mark a folder as e2e encrypted, saying **Please wait for the folder to sync before trying to encrypt it.**

**Comment by jlfranklin** [comment]
Same here with the macOS version, 2.5.0daily.  (Built from Git revision 371001 on Nov 12 2018, 01:03:46 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017)

**Comment by er-vin** [comment]
Hello,

This is a very old issue sorry about not getting back to you about it earlier. Since it is about, a prerelease of 2.5.0 I will assume you are not affected by this issue anymore (we rolled a few stable release since then).

If it turns out you are still affected, please let us know either by commenting here and reopening (if possible) or by opening a new issue.

Regards.
