### ISSUE TITLE
[Bug]: WebDav TooManyRequests

### ISSUE THREAD

**Issue by wangtiankun123** [nextcloud/desktop#6202]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello, 
  while we were using WebDav as "normal" way to work, however, we were trying to online editing through WebDav, it does not show any online users or pop up a windows to remind us someone is using etc., which leads us some of the information are gone. (we are using MS Word, WPS, OnlyOffice,etc, i dont know if that is  the matter or no).
However, through our logs, there are so many Errors occur, picture are below. we were wondering if  there is any insights or suggestions. 
![1699336907446](https://github.com/nextcloud/desktop/assets/58538425/3ba0c998-37d9-4140-8876-1b4efece34a2)

![image](https://github.com/nextcloud/desktop/assets/58538425/60a672b6-332f-48b1-89b1-da101f46cdcd)

### Steps to reproduce

N/A

### Expected behavior

online editing through webdav, (if thats feature need to be pay, plz let me know)

### Which files are affected by this bug

word files

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.5

### Nextcloud Desktop Client version

3.9.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by marcotrevisan** [comment]
I'd try to find possible configuration limits in your current LDAP/AD server connection pool.
The exception arises during the authentication/authorization processing.
If you're using an external WebDAV client (i.e. NOT the Nextcloud client), in my experience you're also better off setting up an Application password for your client and use that password instead of the original one (repeat this step for everyone is using that webDav client). 
In a non-LDAP environment that would dramatially help. I'm not using LDAP in my setup but I guess it would help even more in that scenario.
You are putting much stuff in a single ticket. I tried to reply to what seems to me the most important issue outlined.

**Comment by wangtiankun123** [comment]
thank you for your explanation,really appreciate. i'll try and send feedback ASAP. BTW, as the another things I mentioned, is that possible for "WebDav users" co-editing?

**Comment by marcotrevisan** [comment]
In a typical WebDAV file system scenario the file workflow is like "lock -> edit -> save -> unlock", similarly to what happens in a SMB mounted filesystem. There's no concurrent co-working.

If you need to co-work on the same Office file (.docx, .xlsx, .pptx) concurrently, as far as I know you need to add Nextcloud Office (or Onlyoffice, ...possibly there are some other apps that do the same) to your current instance.
In that way you'll be able to edit the files online and co-work on them (i.e. seeing the other user's cursor and so on).
I'm not aware of any current integration with MS Office allowing the same thing using Office in the user's client system.

I ultimately went for Nextcloud Office app along with a "companion" Collabora Code server instance.

If on the other hand you need to co-work on rich text online, Nextcloud Collectives is fit for that and by far the fastest way to reach that goal. Just install the app and you're ready to go.

Please be aware that I'm only a user trying to help the NC community, I'm not a NC developer / team member,  so take my info as it is, just my experience on working with NC. It may be partial and in some cases wrong.

**Comment by joshtrichards** [comment]
Hi @wangtiankun123 - Sorry you're run into some challenges. This doesn't seem to be a matter involving the Nextcloud Desktop client though. This also appears to be a configuration matter rather than a bug. This channel is for reporting bugs in the Desktop client, not for general troubleshooting or configuration assistance. 

However: The `TooManyRequests` is a configuration issue likely related to Bruce force protection. Typically happens if  you have a client connection with an invalid password *or* your `trusted_proxies` settings are wrong. Please review the relevant documentation:

- https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html
- https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html

The rest was covered by @marcotrevisan. 

Any follow-ups mentioned should be taken to the Nextcloud Help Forum - https://help.nextcloud.com.
