### ISSUE TITLE
[Bug]: Sync issue - no info on the problem, clicking the error redirects to the dashboard

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/desktop#6272]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
<img width="1043" alt="2023-12-08 13_49_11-Nextcloud-Einstellungen" src="https://github.com/nextcloud/desktop/assets/1315170/9fec31a1-0deb-4661-9aa6-cbfc6550e67f">

clicking on it leads you to
<img width="440" alt="2023-12-08 13_48_29-Nextcloud" src="https://github.com/nextcloud/desktop/assets/1315170/4355e357-39d7-4f73-b35f-7a7ccb95dddc">

clicking on that leads you to 
https://cloud.nextcloud.com/apps/dashboard/

there is enough local disk space
<img width="176" alt="2023-12-08 13_56_08-Dieser PC" src="https://github.com/nextcloud/desktop/assets/1315170/d26a6522-09d4-40ba-a9b0-031a7cfb9e7f">

The the failure of creating a folder might not be related to insufficient storage

### Steps to reproduce

1. Run Desktop Win11 with VFS for c.nc.c

### Expected behavior

* Provide more information on why the folder could not be created
* when clicking the notification / activity I would expect to be directed to the file/folder in question (which exists on the server)

### Which files are affected by this bug

sensitive info

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 Pro latest patch level

### Package

Other

### Nextcloud Server version

28.0.0 RC3

### Nextcloud Desktop Client version

3.10.81 (3.11.0 RC1)

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by allexzander** [comment]
Not sure if this is exactly the root cause, but here is what I did to come up with https://github.com/nextcloud/desktop/pull/6285

- Create an empty (0 bytes) file (probably not required, can be any size) and upload it to the server
- Have desktop client VFS mode enabled on Windows, and sync that file so it appears as a placeholder on the disk
- Exit the desktop client
- Remove the file from the server and create a folder with exactly the same name and put any file into it
- Run the desktop client and observe how it is unable to download a file with "Couldn't create placeholder info" error

@mgallien what do you think?
