### ISSUE TITLE
[Bug]: Root folder gets synced although everything but one subfolder unchecked during setup

### ISSUE THREAD

**Issue by mamama1** [nextcloud/desktop#6801]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The title says it all. Windows client syncs the root folder to the local PC, although during setup, root folder (all folders) has been unticked and only one subfolder has been selected for syncing. The intended folder gets synced fine as well, but i don't want the files from the root folder.

### Steps to reproduce

Install Nextcloud client, select to choose what to sync, unselect all, select only one subfolder

### Expected behavior

Only the selected subfolder should be synced

### Which files are affected by this bug

not needed

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

28.0.6

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
this is on purpose
every parent folder of a selected folder will be synced

**Comment by davidv92** [comment]
Hello @mgallien ,

I would like to understand why syncing parent folders of a selected folder is the default behavior in the Nextcloud desktop client. if I wanted to sync the parent folder, I would simply select it. The current rule that forces the parent folder to sync when selecting a subfolder seems unnecessary, especially since it only happens during the setup process.

Once the setup is complete, if I choose to add a folder for syncing afterward, everything works as expected: only the selected folder is synced, and not the parent folder. This inconsistency in behavior between the initial setup and post-setup folder selection is confusing.

This is particularly confusing for new users. The setup is the first interaction they have with the application, and this behavior can be very misleading. Novice users may not understand why the parent folder is being synced, and they may struggle to find a workaround.

Could you explain the rationale behind this design choice? If there's an existing explanation available, I'd appreciate it if you could point me to it.

**Comment by lejvin** [comment]
@davidv92 and @mamama1 

Hi!
Did you find an explanation for the behavior? 
What workaround did you end up using?
