### ISSUE TITLE
Launch on System Startup does not work with Flathub Flatpack

### ISSUE THREAD

**Issue by skewty** [nextcloud/desktop#688]
The Launch on System Startup option does not work on the Flatpack.

Can the code detect if it is running as Flatpack and adjust the Exec= line in the .desktop created?

**Comment by joshtrichards** [comment]
Since the Flatpak isn't managed by this repository I'm going to close this out in favor of tracking whatever needs to happen, if anything, about this here: flathub/com.nextcloud.desktopclient.nextcloud#18

Chances are the work will be driven from there rather than here, even if there end up being some coordinated changes or something.
