### ISSUE TITLE
Allow Nextcloud to act like Virtual Drive

### ISSUE THREAD

**Issue by TypicalZedF** [nextcloud/desktop#7127]
The ability to have Nextcloud act as a virtual drive would be great! Similar to google drive!
![image](https://github.com/user-attachments/assets/ee5b05a0-ca00-4d2f-a55e-abe2bfa53d2a)
A larger reason for this is due to how Nextcloud works: When you sync a file over it likes to display itself as its own thing inside of Explorer's navigation pane. This gets cluttered very quickly when you start syncing files over... Having this would basically eliminate that and allow a different way to interact with Nextcloud.

**Comment by roberix** [comment]
Hi. 

Fully support for this request from my side but I have not a lot of hope that this is going to happen. I requested that feature through enterprise channels and received a negative feedback. 

Regards

rob

**Comment by chowluca** [comment]
Hallo 
I have been using NC since version 18 and have been deployng virtual files and folder sycn ever since.
I know this has been touched before by other users and rejected but I do believe this is a potentially critical feature which would radically change the work environemtn for many users. Below is my user case hoping my context may help NC developers to re-evaluate this feature.

- We are a design office and use CAD programs like Autodesk Autocad / Revit / Bricscad / Rhino / Archicad.
- all these programs rely on External References (Xrefs) for managing 2D and 3D drawing data, ie designers divide drawings and design parts in separate files and assemble them toghether in a main file for a complete enviroment. This allows for smaller lighter files instead of a single large one, while different users can work on "partial files" (MEP, structure, Architecture, interior) without incurring in file locks, while providing other specialists constantly reloaded to the most up to date state.
- These files are generally "mapped" using local server absolute and relative paths (X:/SERVERNAME/PROJECTNAME/Filename.xxx). This is the structure of these programs which were born in the LAN server era.

With NC virtual files there are several problems:
- files are often conflicted because files locks on CAD files do not work
- Nextcloud drive can be installed on computers (in house or remote) and save files in different drives (C:/ for some laptops whiel D:/ or E:/ on another workstation) resulting in broken links.
- different paths make the createion of shared libraries and standards impossible: on server we wimply share a folder.

Last but not least, in the CAD market this is one of the key aspects that vendors use to LOCK clients in their specific enviroments. Autodesk will sell their cloud platform BIM 360 (and others as their own...) which means again data sovereignity is not only hard but impossible.

With virtual drives, we can have the same setup as a local server, but on our private cloud. That would "free" the AEC industry from the monopoly of proprietary cloud servers.... This is my personal opinion.

I welcome any point of view on the same and I hope this message helps NC guys in re-evaluating this issue.

Thanks In advance for any feedback.

regards 

Luca
