### ISSUE TITLE
[Bug]: Client app (3.14.3) on Mac OS (15.1.1) only starts once, after reboot it won't start

### ISSUE THREAD

**Issue by aschubert** [nextcloud/desktop#7557]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After installing Nextcloud client app on Mac OS X, the app could be started, after a reboot, it crashes immediatly with a "program could not be opened" (german screenshot see here: [https://help.nextcloud.com/t/macos-client-wont-launch-after-reboot/136662](https://help.nextcloud.com/t/macos-client-wont-launch-after-reboot/136662)). Looks a lot like this issue: [https://github.com/nextcloud/desktop/issues/4906](https://github.com/nextcloud/desktop/issues/4906) except for:

- I did everything described in #4906, aka wipe everything and try a reinstall, did not help
- I have an Intel Based Mac, not ARM

### Steps to reproduce

1. Install Nextcloud client app
2. Start app, works fine
3. Reboot Mac
4. Client could not start again, except you reinstall it

### Expected behavior

Client should be able to start again.

### Which files are affected by this bug

/Applications/nextcloud.app/Contents/MacOS/nextcloud

### Operating system

macOS

### Which version of the operating system you are running.

Sequoia 15.1.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

30.0.2

### Nextcloud Desktop Client version

3.14.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [x] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

Unfortunately, I'm not able to produce much of debugging or logging information. When I try to start the nextcloud client on the terminal, it says immediatly "killed".
As I have deleted all of Nextcloud client, I would assume, it's only a client problem, because before the reboot, I would have been able to create a new connection/configuration, which I didn't. After the reboot it won't start (and I don't see any connection to my selfhosted server).

**Comment by fabwal** [comment]
I have exactly the same problem. 
After fresh install it works again.
Maybe related to this is that updates which are triggered by the client are also not working. Installer runs but is not able to finish the update due to "Program "nextcloud" cannot be started" bug.

Maybe some access rights are not set correctly? I have "Full access to hard disk" in Mac Preferences which should be enough I guess. Also I think this started with Sequoia?

**Comment by d3en89** [comment]
I posted the post as an option for a temporary solution to this problem.
[https://help.nextcloud.com/t/desktop-app-not-starting-on-mac-after-update-to-sequoia/213103](url)

**Comment by lopezio** [comment]
Hi there, I just experienced the exaclt same issue on a client's MacBook Air (M1) with 3.16.1 (the version without virtual files) on macOS Sonoma. 
The hint from https://github.com/nextcloud/desktop/issues/4906#issuecomment-1486356649 (deleting every folder and file somehow referencing Nextcloud both in ~/Library and /Library, plus the application in /Applications, issuing `sudo pkgutil --forget com.nextcloud.desktopclient`  and then reinstalling and reconfiguring the client) seemed to solve the issue across reboots. 

Before, I had tried to remove some of the files selectively (such as ~/Library/Caches/Nextcloud and other supposedly ephemeral files), but it did not help. Weird issue. Possibly somehow involving Qt, but not necessarily. I suppose it's difficult to reproduce because it most probably does not happen on a fresh install.
