### ISSUE TITLE
usage percentage misplacement in main window

### ISSUE THREAD

**Issue by pascalbrax** [nextcloud/desktop#79]
The size of storage used against defined quota is confusing as showing GB and % together, wrongly.

Example belows shows **"20GB%"** instead of **"20GB (9.8%)"** on client inteface.

Not sure if related to Italian locale.

![mouse over shows correct data usage](https://i.imgur.com/KkPOKKf.png)

Client version 2.3.2 build 1.
Built from Git revision [820899](https://github.com/owncloud/client/commit/820899d07102b990b19e8b02121221e41f7fbf06).

**Comment by dreua** [comment]
In english it's "6,2 MB of 1 GB in use" and the percentage is shown in the tooltip similar to the screenshot.

So I think we just have to remove the surplus %-sign in the Italian translation.

I guess you have a visual representation of the percentage in the blue/white bar so its fine to have it only in the tooltip in favor of less visible text, which is a good idea in my opinion.

(In case you noticed the comma as a decimal: That's fine, my system is configured to use English language but German formats for dates and numbers.)

**Comment by dreua** [comment]
I found the typo:
https://github.com/nextcloud/client/blob/18b456ea2c316358896b5fcf4bf1ae35954ba21b/translations/client_it.ts#L337-L338

I think this has to be fixed in Transifex. I was able to find and propose a change in Transifex for *own*cloud (it's the same issue there) but I couldn't locate the string in Transifex for *next*cloud.

I think this should be handled by someone who is familiar with Transifex and the related processes.

**Comment by juliushaertl** [comment]
Changes from transifex should be synced when we pull in changes from upstream.

@rullzer Not sure if we should we have our own transifex setup for the client? I guess there is sadly no easy way to merge changes from upstream translations and our own translations.

**Comment by rullzer** [comment]
Transifex is setup for thsi repo now. So please fix it in https://www.transifex.com/nextcloud/nextcloud/client-desktop/ if it is still an issue THNX
