### ISSUE TITLE
What is the current Client Manual?

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#839]
What is the current Nextcloud Client Manual in the public domain?

One would expect the **availability of a documentation** for both the **2.3** and the **2.5** NC Client.

Apparently, there are two URLs available which seek to provide either the 2.3 or the 2.5 Client Manual. However, both seem to be just copies of the same source and may be misleading.

1. https://docs.nextcloud.com/desktop/2.3/introduction.html
1. https://docs.nextcloud.com/desktop/2.5/introduction.html

Unfortunately, the a.m. web-pages provide identical content as:
> Improvements and New Features
> The **2.4.0** release of the Nextcloud desktop sync client has many new features and improvements.
> [...]
> Last updated on **Nov 15, 2018**.

Furthermore, the details of certain (if not all) pages seem to be outdated, e.g.
1. https://docs.nextcloud.com/desktop/2.3/conflicts.html
1. https://docs.nextcloud.com/desktop/2.5/conflicts.html

I would call this situation rather unfortunate. Please provide an updated documentation and differentiate between NC Client versions as applicable.

**Comment by TP75** [comment]
lazy or no QM ?

devs love code but docs nether ever

:-1:

**Comment by TP75** [comment]
![Bildschirmfoto 2019-11-08 um 19 03 45](https://user-images.githubusercontent.com/31193257/68499879-a6626580-025a-11ea-80f6-1ece189b9521.png)

Funny idea of a so-called update of documentation.

+1 - there is an active link for 2.6 now

-100 - same issue as above, apparently 2.3 -> 2.5 -> 2.6 copy & paste nonsense or worse

q.e.d.    unfortunately

**QM ???**

**Comment by claell** [comment]
Reading from your first post, you basically were confused, since the manuals contained similar to equal and outdated content. However, during the issue that changed and now you basically want enhancement in the documentation. That however is not reflected in the issue description and title.

So for now, I added the help wanted label as it best reflects the title and description.

I'd appreciate if you could either update the title and description to reflect the request for better documentation or that you open a new issue for that.

**Comment by mgallien** [comment]
We have made adjustments to the way documentation is generated to ensure we have matching versions in it and usually update it when needed (see new features section).
I do not believe keeping this issue open will help in any way.
