### ISSUE TITLE
Renaming folders with lots of files takes a long time

### ISSUE THREAD

**Issue by rcdailey** [nextcloud/desktop#845]
Version: Version 2.5.0daily (build 20181110)
OS: Windows 10

When I simply rename a top-level directory, it starts to individually process all the files inside of it:

![image](https://user-images.githubusercontent.com/1768054/48653044-4bd85580-e9c8-11e8-930c-c6f3ce3287a5.png)

When I rename directories in other sync services, it's usually instant with no processing of directory contents. Why is a simple rename taking so long? Can this be optimized to be as fast as, say Insync for Google Drive?

**Comment by hlprasu** [comment]
I see the exact same problem with version 2.5.1git on Linux (KDE Neon - 18.04 base). 

To add some more details: When I rename a folder, it seems that it is creating a new folder on Nextcloud server with updated name and moving all existing files from old named folder into the new folder folder. Why should it do that instead of simply renaming the top-level folder?

**Comment by mrpew** [comment]
This is still a thing. Just renamed a couple of folders on the client. After a couple of hiccups, the client is now *downloading* the renamed folders. A simple "rename" caused 8gig of files that were _present_ on the client to be downloaded again.

**Comment by mgallien** [comment]
Can you still reproduce this issue ?
Can we close it if it is fixed ?
