### ISSUE TITLE
Remove .htaccess from ignored file list

### ISSUE THREAD

**Issue by nanonettr** [nextcloud/desktop#85]
.htaccess should be synced when enabling Synchronize hidden files.

Reference : https://github.com/owncloud/client/issues/5701

**Comment by Square252** [comment]
That could override nextclouds server configuration and possibly break the file folder. Very bad idea. You could rename this file to DOT.htaccess and rename it when uploading the files to the productive webserver if its not too much PITA... But if there are more than one htaccess file this can be annoying, i unterstand.

**Comment by adriansuter** [comment]
OwnCloud made that step. Check https://github.com/owncloud/client/issues/6144

Maybe it would be nice to allow an administrator to activate/deactivate the `.htaccess` file from the ignore list. For example if the data-directory lies outside of the web-accessible folder.

**Comment by superDuperCyberTechno** [comment]
I use Nextcloud extensively to synchronize web projects across machines (usually containing ,htaccess files), so this is a pretty significant annoyance especially when you pair it with git and git constantly thinks I deleted the .htaccess file every time I'm not using the machine I originally created the project on...

A simple solution would be to simply prepend a string to the ignored file prior to upload, removing the string again on download...? Maybe even hiding the string from the web interface making it completely seamless for the end user.

**Comment by ludgart** [comment]
Hello,

for all people they need to allow the **.htaccess** file.

**Follow this steps:**
1. Download the owncloud client
2. Edit following files on your nextcloud server
2.1. https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/Files/Filesystem.php#L643
2.2. https://github.com/owncloud/core/blob/c9f5fce1777a96a8e2f09ea54fbcbed90cd1925f/apps/files/lib/Capabilities.php#L61
3. Done :)

Be careful your data folder should not hosted on your web server. Move it to e.x /home
You can change the data folder path in the config/config.php

Have fun.

**Comment by Terrox** [comment]
So is there  a real solution for this yet which will survive an update? I develop websites and .htaccess is a part of that. I want to use Nextcloud to store and sync my dev work but I can't feel comfortable with unexpected file deleting going on and I don't want to be constantly on alert for missing data.

**Comment by despens** [comment]
I think administrators should have the power to edit the file ignore list via the web interface, given they know what they are doing. Which could include:
- not using apache web server
- using apache but locating the data directory outside of the web server's root

**Comment by rafleo** [comment]
+1

Nextcloud could also rename the file for security reasons (e.g. .htaccess-SAFE) but display and download it as .htaccess in clients and the web interface.

Manually renaming a file before uploading it is a massive pain if you're a web dev with lots of sites to sync, plus Windows won't easily allow renaming the files back to .htaccess (as the files lack a proper filename).

**Comment by Terrox** [comment]
So that means we can't do web dev work or copy web dev data through nextcloud?

**Comment by richardfleming** [comment]
I used to use dropbox for webdev before I clued into git.  Git makes it so much better to track versions of files, role back, experiment with new code and all other stuff without having to keep separate copies of everything.

Yes, you can use Nextcloud for webdev work, but it's really not the right tool.  Nextcloud is used for my docs, and pictures, and that sort of sundry... Git is used for all webdev source code.  (BitBucket and GitLab offer free private repositories).

Rich

**Comment by rafleo** [comment]
While Git or SVN is a better tool for backing up web work, yes, I believe we're missing the point here. There are always arguments to be made for both sides (e.g. wanting to share a private link to a web project without the users having to register anywhere) and reasons behind why someone uses a specific tool and not another one.

**The point** is: we want and **expect Nextcloud to sync files, and in this case, it doesn't** - for no good reason.  I say "no good reason" because owncloud has a solution to this and there's multiple ways to solve it.

And while we as developers understand why Nextcloud ignores .htaccess files in the first place, novice users might not - and that's a problem. Especially, if you remove .htaccess from the ignored file list.

**Comment by caillou** [comment]
This issue seems to relate to the following server issue: https://github.com/nextcloud/server/issues/13831

**Comment by epma01** [comment]
I don't know in old versions, but working ok with:
Nextcloud Client: 2.5.1. -> Enabled "Synchronize hidden files"
Nextcloud Server: 15.0.7.0.  -> Added to server file /config/config.php next line:
   'blacklisted_files' => array(),

**Comment by SamSirry** [comment]
Please see my suggestion for a better solution here:
https://github.com/nextcloud/server/issues/13831#issuecomment-899420286

**Comment by joshtrichards** [comment]
`.htaccess` was removed from the client's built-in ignore list prior to this issue being opened here:

https://github.com/nextcloud/desktop/commit/4697f0274f282cafd28cbad07066efb397dbf21b

It's actually the same change mentioned in the referenced https://github.com/owncloud/client/issues/5701

If you can't upload `.htaccess` files it's due to the server-side blacklist mentioned elsewhere in this issue. Feel free to adjust it at your discussion (it's in the Server docs if you need more details).

Closing this out.

**Comment by C0rn3j** [comment]
One can simply empty the default blacklist array in `config.php` to let the client sync the files:

```php
'blacklisted_files' => array(),
```

**Comment by SamSirry** [comment]
> empty the default blacklist array

The problem lies in how the webserver interacts with and handles the special file `.htaccess`.
If this file is allowed to be controlled by the user it can create serious security backdoors to the whole server.

Your suggestion should absolutely not be attempted on a production system, unless the webserver settings are changed so that it doesn't treat `.htaccess` as a special file.

**Comment by C0rn3j** [comment]
Absolutely correct, *IF* you use Apache, which I do not.

Forgot to put that disclaimer there though, thanks for the catch.

**Comment by Terrox** [comment]
Isn't it only a problem when the data directory is within the web root? So only needs to be blocked in that situation?
