### ISSUE TITLE
Desktop Client New Connection Wizard Freezes/glitches

### ISSUE THREAD

**Issue by pemuelle79** [nextcloud/desktop#888]
### Expected behaviour
The Assistant continues with the next step, and does not freeze.

### Actual behaviour
After entry of the server address in the first screen of the Assistant and after pressing "next" the application seems to freeze and shows a strange white border around the window. 
The wheel to the right of the entry field also does not spin. 
However the window can still be closed by clicking the top right close button
After clicking: 
![image](https://user-images.githubusercontent.com/45310390/48968390-480f8900-efef-11e8-95a3-5793f63454f3.png)
The server address is valid and everything is working if using the old 2.3.3.1cllient ( was not installed before).

Entering a wrong address also  does not expose this behaviour ( expected error message appears)

### Steps to reproduce
1. Open new Connection Assistant , either via the Client Application or by popping up after first start
2. Enter a valid Server Address 
3. Presss next
--> Freeze + white border appears ( see Screenshot

### Client configuration
Client version: 2.5.0 (release)

Operating system: Windows 10  (1709)

OS language: German

Installation path of client:
C:\Program Files (x86) (default)

### Server configuration

Operating system: nextcloudplus (14.0.4)

Nextcloud version:14.0.4

### Logs

1. Client Log
[OCC::FolderMan::setupFoldersMigration 	Setup folders from  "C:/Users/pm/AppData/Roaming/Nextcloud/folders" (migration)
[OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use NO proxy
[OCC::ownCloudGui::slotOpenSettingsDialog 	No configured folders yet, starting setup wizard
[unknown 	Could not parse stylesheet of object 0x207e46df360
[OCC::WebViewPage::WebViewPage 	Time for a webview!
[unknown 	Could not parse stylesheet of object 0x207e46df360
[unknown 	Could not parse stylesheet of object 0x207e46df360
[OCC::SocketApi::slotNewConnection 	New connection QLocalSocket(0x207ea3513f0)
[OCC::OCUpdater::backgroundCheckForUpdate 	Checking for available update
[OCC::AccessManager::createRequest 	2 "" "https://updates.nextcloud.org/client/?version=2.5.0.20181112&platform=win32&oem=Nextcloud&versionsuffix=v2.5.0" has X-Request-ID "815cce0d-3ad8-4708-99a9-da21d71cc706"
[OCC::NSISUpdater::versionInfoArrived 	Client is on latest version!
[OCC::AccessManager::createRequest 	2 "" "https://*edited*/status.php" has X-Request-ID "eb9a9904-50f9-4b7c-9015-35b891c55cd2"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://*edited*" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"","version":"14.0.4.2","versionstring":"14.0.4"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x207ea33d070)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://*edited*/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://*edited*/remote.php/webdav/" has X-Request-ID "2c47bc30-44d5-4c97-8d02-cb3d3ed2e030"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://*edited*" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://*edited*/remote.php/webdav/" has X-Request-ID "53c23f3a-fa86-417e-89ab-663aefefd494"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://*edited*" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://*edited*/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://*edited*/index.php/login/flow"

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):
-- no entries

**Comment by pjao** [comment]
Same issue also with daily build, tested with "Nextcloud-2.5.0.61573-daily-20181125"

**Comment by research-it** [comment]
Same here (do we want +1 posts? I am sure many people suffer from this).

Clicking and dragging from various locations on the (seemingly frozen) screen uncovered some sort of "overlay image" showing the following::

![image](https://user-images.githubusercontent.com/45562695/49374466-b942f080-f701-11e8-9604-6d5b956aea23.png)

![image](https://user-images.githubusercontent.com/45562695/49374496-ceb81a80-f701-11e8-9870-5ac2565ac61c.png)

Possibly this helps pinpointing the technical root-cause and helps towards a (quick)fix!

Thanks for this amazing peace of FOSS!

---

### Client configuration

Client version: `2.5.0` (release)

Operating system: `Windows 10 Enterprise`

OS language: `English`

Installation path of client: `C:\Program Files (x86)` (default)

### Server configuration

Operating system: `Debian 9.x`
Nextcloud version: `14.0.4`

**Comment by natrius** [comment]
# Configuration

**Server**
Operating system: `Raspbian somewhat`
Nextcloud version: `14.0.4`

**Client **
Operating system: `KDE neon (aka Ubuntu)`
Client version: `2.5.0`

Same computer, dualboot, Windows is working, Linux is not working. Entering the server adress, something about certs, i do accept and then a white screen. 
Could it because the server is in the same network? For that reason i use the local IP and not the normal URL i normally use. 

I think it worked with the old OS-Installation where it was 2.3.0 before and i upgraded to 2.5.0. This is now a complete fresh installation (OS and Nextcloud)

**Comment by natrius** [comment]
@camilsan
Maybe want to add the label Linux too? Is more information needed? Its annoying because i'm dualbooting with linux as my main working space and its working with Windows 10 and not working with Ubuntu :/

**Comment by 6i6i** [comment]
I got the same on Windows 10. Tried various versions (Nextcloud-2.5.1, Nextcloud-2.5.1.61659-daily-20181211, Nextcloud-2.5.0.0-Debug-20180622). I can login and use it with the android client and also via Web. It is also possible to use it with latest owncloud client (2.51).
It is also possible to use it with the latest nextcloud client in a KubuntuVM on the same device on the same network. So it should not be a network problem (local address,..).

I think its a Problem with "qtwebengineprocess" because a process of it starts when I try to login and does not go away until I kill it (even if I quit or kill nextcloud client completely).

**Comment by darren-harrison** [comment]
I did have to kill off qtwebengineprocess a few times.
One thing I found was that the next screen was there, and if I clicked in the right place I could get it to go back to the previous step, but I couldn't fumble my way to the next step.
Eventually, I downloaded build 2.3.2 and was able to install the client and sync (link below). 
I tried installing 2.5.1 over 2.3.2, however, it wouldn't use the same settings so needed to be set up again (even though uninstalling 2.5.1 and reinstalling 2.3.2 didn't require setup again).
https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.2.1-setup.exe

This was on Windows 10.

Darren.

**Comment by AlNotSteve** [comment]
Have the same issue here.  Only way I've found around it is to install 2.3.2.
I tried upgrading again after that, but same issue again.  Stuck on 2.3.2 for no

**Comment by brtptrs** [comment]
These versions seem to solve the problems we were having behind our proxy:
2.6 RC1 on Windows 10
2.7.0.20190909-daily on Ubuntu 19.04
Thank you for the updates.

**Comment by FunnyAnimal** [comment]
After entering the server (in my case https://<user_name>.ocloud.de ), the next screen stays blank (except for a thin blue line at the top).

Clicking with the right mouse button gives a menu. When I click on 'View page source' this leads to a website, which is in my case https://<user_name>.ocloud.de/index.php/login/flow . That shows an error message:
![Nextcloud 2 5 connection wizard page source](https://user-images.githubusercontent.com/31759302/66380830-6fc5d080-e9b8-11e9-91b6-da651c0d8183.png)

So, the blank login screen is caused by the provider not understanding the new way in which the recent version (>= 2.5.0) NextCloud clients try to authenticate.

The only solution is to stay with version 2.3.3.1 ???

Can we have the old client authentication back?
