### ISSUE TITLE
Part of GUI not accessible on low resolution screen

### ISSUE THREAD

**Issue by ykgmfq** [nextcloud/desktop#91]
Version: 2.3.3
Host: Fedora 27 GNOME
Display: 768 pixels vertically

The main window is too tall, cutting off the buttons at the buttom. It cannot be vertically resized to make it smaller either.

![bildschirmfoto von 2017-12-14 11-44-21](https://user-images.githubusercontent.com/16083673/33989173-cf65f81e-e0c6-11e7-8d2d-d12485326411.png)

I can provide more screenshots if desired.

**Comment by Mickael-Martin** [comment]
Same issue for me. I cant add precision if you want.

**Comment by Mickael-Martin** [comment]
No, not actually. I search.

**Comment by rullzer** [comment]
@jpnurmi could I ask you to have a look at this one as well?

**Comment by rschr** [comment]
For what it's worth, I'm currently testing the Linux client from [http://ppa.launchpad.net/nextcloud-devs/client-beta/ubuntu](http://ppa.launchpad.net/nextcloud-devs/client-beta/ubuntu) which gets updated very frequently. The current version identifies itself as "2.5.0git" (the current apt package version is 2.5.0-20181106-10111), and the issue seems to be fixed there.

**Comment by jpnurmi** [comment]
I can take a look later. :)
