### ISSUE TITLE
Very small font and icon size on hidpi monitor 

### ISSUE THREAD

**Issue by scroom** [nextcloud/desktop#914]
### Expected behaviour
I've got a new Laptop with a HiDPI-screen, on which I've installed Ubuntu 18.10 and the newest Nextcloud-client (2.5.0). I've expected that the nextcloud client is using the same font size and size of my desktop environment, but it doesn't.

### Actual behaviour
Font size and icon size for folders are extremely small, which makes it hard to read everything.

### Steps to reproduce
1. Install the Nextcloud client on a machine whith HiDPI-Screen (Ubuntu 18.10 with Gnome, non Wayland)

### Client configuration
Client version: Version 2.5.0git.

Operating system: Ubuntu 18.10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): ?

Client package (From Nextcloud or distro) (Linux only): Nextcloud

**Comment by aleho** [comment]
I just stumbled upon this issues, can confirm here.

Suspect its a problem of QT not playing nice with a GNOME environment (or the other way round, those two never played nice together out of the box in my 15+ years of Linux desktop usage).

Solution (for me): Set QT_SCALE_FACTOR. I'm doing it in my .profile, you could also do it system-wide in /etc.
```
export QT_SCALE_FACTOR=1
```

Nextcloud now looks the way its intended to.

**Comment by select** [comment]
Try adding `X-GNOME-Autostart-Delay=5` to `~/.config/autostart/Nextcloud.desktop` so gnome has time to load the scaling factor. This worked for me. I got the solution from https://github.com/nextcloud/desktop/issues/205

**Comment by AlexeyGusev** [comment]
I have the same issue with nextcloud client that runs on `manjaro 20.02`. It's even trickier in that sense that without having `QT_SCALING_FACTOR` set, «Settings» window looks good, properly scaled, whilst «Open main dialog» opens minuscule window that has so tiny font that it is hardly readable. Setting `QT_SCALING_FACTOR=2` fixes the main screen, but makes settings window monstrously big. Logwindow (`nextcloud -l`) looks good without `QT_SCALING_FACTOR`, so it seems to be a problem of main window only.

```
Nextcloud version 3.0.3git
Git revision 78da725ac38e1508e5800d02fd1700a4e43b1088
Using Qt 5.15.2, built against Qt 5.15.1
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1h  22 Sep 2020'
Running on Manjaro Linux, x86_64
```

**Comment by ataraxus** [comment]
Can Confirm this issue on Ubuntu 20.04.1 LTS nextcloud client version: Version 3.1.1

**Comment by jospoortvliet** [comment]
Here's a screenshot of this issue on my 4K monitor:

![Screenshot_20210504_091633](https://user-images.githubusercontent.com/551757/116971572-0ef89a00-acba-11eb-8a7a-2f60ed9234a7.png)

Desktop client 3.2.1 from openSUSE Tumbleweed packages on Linux 5.12, KDE Plasma 5.21.4, KDE Framework 5.81.0.

I have not set a custom scaling, but apps (as you can see) scale nicely - I guess they auto-detect the needed scaling. Previously, I had configured a custom 125% or 150% scaling in the SystemSettings and the desktop client would properly adapt to that, showing up bigger and more readable. I guess DPI detection is not working somehow. 

If I run `QT_SCALE_FACTOR=1.5 nextcloud` I get this:
![Screenshot_20210504_092753](https://user-images.githubusercontent.com/551757/116972466-559ac400-acbb-11eb-9075-9a0fecc0927b.png)
This makes the menu look good, but the normal window a bit too big.

Perhaps the issue is just that the menu is too small compared to the normal window and we should just increase all sizes in the menu by 20% or so?

**Comment by FlexW** [comment]
@jospoortvliet The fonts of the main dialog are to small and need fixing, but they should not be that small. The menu should appear bigger. It's too small in your screenshot. I did tests on GNOME 40 and sway and the main dialog scales properly for me, if I scale for example to 200%. Just some guessing from me, but maybe your desktop environment does some scaling behind the back of the apps or did you choose a big font? I just think that because in the first picture the icons look really small. When scaling is activated, the should appear bigger. I guess you use X11?

By the way, hidpi detection was deactivated in the desktop client on Linux in the past. We activated it with this pull request https://github.com/nextcloud/desktop/pull/3025 for 3.2.0. I followed this guide from Qt when doing this https://doc.qt.io/qt-5/highdpi.html.

**Comment by droid001** [comment]
Can confirm this is still the issue with Ubuntu 21.04, nextcloud-desktop  3.1.1. WIth `export QT_SCALE_FACTOR=1` set the settings window looks normal while the main window is minuscule.

**Comment by mgallien** [comment]
> Can confirm this is still the issue with Ubuntu 21.04, nextcloud-desktop 3.1.1. WIth `export QT_SCALE_FACTOR=1` set in ~/.profile the settings window looks normal while the main window is minuscule.

but like @FlexW  said, this has been changed in the latest feature release and a test with it would make sense
we are aware that the 3.1 series could use some improvements

**Comment by megahertz** [comment]
Unfortunately, the problem is still not solved. Tiny main window and normal settings window.  Arch & KDE & X11, nextcloud-client 3.2.3-1

**Comment by droid001** [comment]
The main window appears normal now on a my Dell 13" XPS with screen scaling set to 200% and adding `QT_AUTO_SCREEN_SCALE_FACTOR=1` to ~/.profile. Followed the [link](https://doc.qt.io/qt-5/highdpi.html) provided by @FlexW .

**Comment by mgallien** [comment]
> The main window appears normal now on a my Dell 13" XPS with screen scaling set to 200% and adding `QT_AUTO_SCREEN_SCALE_FACTOR=1` to ~/.profile. Followed the [link](https://doc.qt.io/qt-5/highdpi.html) provided by @FlexW .

My KDE Plasma desktop (when running with X11) is using the following variables:
 * QT_AUTO_SCREEN_SCALE_FACTOR=0
 * QT_SCREEN_SCALE_FACTORS = eDP=2;HDMI-A-0=2;

I tested with the Appimage and could not find anything not good. Could you try that ?

I am sorry the way Qt configure itself is very confusing and have changed a lot between versions.

**Comment by megahertz** [comment]
@mgallien Thank you, that works for me
`env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS='DVI-D-0=1;DP-4=2' nextcloud`

**Comment by mgallien** [comment]
> @mgallien Thank you, that works for me
> `env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS='DVI-D-0=1;DP-4=2' nextcloud`
> 
> The only issue with that, when nextcloud opens Dolphin, it inherits scaled settings, so it's too large. But it's very rare case.

Thanks not sure we can do something on our end (maybe apart from updating the documentation).

**Comment by claell** [comment]
I think this is still relevant, so reopening.

**Comment by mgallien** [comment]
there is no longer a bug
the fact is that depending on the Qt versions, you can end up easily misconfiguring the scaling feature within Qt and will get badly scaled tray dialog.
this is not a bug in itself because if you fix the configuration as seen in comment https://github.com/nextcloud/desktop/issues/914#issuecomment-873715895 then it is working
