### ISSUE TITLE
e2ee - from App Store

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/desktop#972]
From iOS App Store review (translate from german language.) :

The app works by itself works fine. However, end-to-end encryption still causes a lot of problems:

1. Encrypted folders with spaces in names can not be decrypted on Mac or Windows.

2. Subfolders of encrypted folders are encrypted in the iOS app. This works on the Mac and not yet on Windows (automatic).

3. Files can be stored in encrypted folders with subfolders and can not be opened on other iOS devices. I can not test Mac and Windows (see 1).

Great approach, but in the field of encryption there are massive problems. Unfortunately, it is not clear to the layman which problems are related to the server and which to the clients. So unfortunately not productive.

**Comment by GoetheG** [comment]
I have the same problem here. That is why we withdraw the idea of using the end-to-end-encryption for now because we are not sure whether this thing works or not. As a non-coder I never understand the problems I have. The manual and the instructions on the net do not help at all. So it's hard for me to understand what's going on. I start thinking more often whether Nextcloud is the right solution for us. It's becoming more complicated and the error messages are not a good indicator for problems for non-coders. Hope this will change soon. I do love Nextcloud though.
