### ISSUE TITLE
New apps menu appears after a delay

### ISSUE THREAD

**Issue by Aranad** [nextcloud/desktop#979]
Great work on the new [Apps menu](/pull/195)! There's just one tiny, but very annoying, problem though which is that it gets added to the menu a short time after the menu is opened. This means that you often click on the wrong item because all the items below "Apps" move down just before you click something. Having the "Apps" item already in place after the menu opens but greyed out would be a simple way resolve this.

**Comment by folknor** [comment]
This problem is much worse than you'd think, because if you have the system tray at the bottom of the screen:
1. Right click the icon
1. Menu opens such that the Quit item is parallel to the bottom edge of the screen
1. "Apps" item pops into existence
1. "Quit" is pushed below the screen edgew

This is on a MATE desktop, and it's enfuriating.

**Comment by camilasan** [comment]
The system tray menu was completely re-done. Please try the latest 3.1.2 desktop client.
